### ISSUE TITLE
Error  Building Windows

### ISSUE THREAD

**Issue by allessandrojs** [Baseflow/flutter-geolocator#1001]
Error 
Building Windows

CMake Error at flutter/ephemeral/.plugin_symlinks/geolocator_windows/windows/CMakeLists.txt:33 (message):
  Failed to install nuget package Microsoft.Windows.CppWinRT.2.0.210806.1

**Comment by mvanbeusekom** [comment]
Hi @allessandrojs,

Please have a look at [this](https://github.com/Baseflow/flutter-geolocator/issues/963#issuecomment-1024413875) issue which describes a similar problem. Final solution was to update Visual Studio, restart Windows and run `flutter clean` and `flutter pub get`.
