### ISSUE TITLE
linux Support

### ISSUE THREAD

**Issue by chaudharyjatin115** [Baseflow/flutter-geolocator#1008]
as flutter linux is quiet stable is there any plan to support linux ?

**Comment by mvanbeusekom** [comment]
There is no concrete plan at the moment. To my knowledge the biggest problem with Linux support is that is doesn't have a standard library (similar to Windows or macOS) that provides access to location information.

My Linux experience is very limited and I am not confident on which (third party) lib would be best to include. Feedback or pull requests are welcome.

**Comment by pablojimpas** [comment]
> There is no concrete plan at the moment. To my knowledge the biggest problem with Linux support is that is doesn't have a standard library (similar to Windows or macOS) that provides access to location information.
> 
> My Linux experience is very limited and I am not confident on which (third party) lib would be best to include. Feedback or pull requests are welcome.

I left a comment https://github.com/Baseflow/flutter-geolocator/issues/241#issuecomment-1060681624 on a previous issue providing some insight on a possible approach to implement this.

I can't work on this right now but maybe someone from Canonical (@jpnurmi, @Feichtmeier) is willing to contribute here or can point to someone with both Linux & Dart expertise to implement this.

**Comment by jpnurmi** [comment]
Sounds like a fun task! A geoclue client for Dart would be a good place to start.

**Comment by jpnurmi** [comment]
FYI, I started working on a GeoClue client: https://github.com/jpnurmi/geoclue.dart

**Comment by pablojimpas** [comment]
> FYI, I started working on a GeoClue client: https://github.com/jpnurmi/geoclue.dart

Wow that was fast! I'm willing to help although right now I'm not running a Linux distro with dbus nor geoclue, maybe I can test those edge cases.

**Comment by chaudharyjatin115** [comment]
hey i could help you test that if yall want im currently using debian 11

**Comment by jpnurmi** [comment]
I haven't looked at flutter-geolocator, but you can try to run the geoclue.dart example if you want: https://github.com/jpnurmi/geoclue.dart

**Comment by chaudharyjatin115** [comment]
hey thanks i would try it

**Comment by jpnurmi** [comment]
https://github.com/jpnurmi/flutter-geolocator/tree/linux/geolocator_linux

**Comment by chaudharyjatin115** [comment]
thank you so much for this

**Comment by mvanbeusekom** [comment]
I agree, I will re-open the issue.
