### ISSUE TITLE
AndroidSettings intervalDuration it doesn't seem to accept values ​​less than 5 seconds

### ISSUE THREAD

**Issue by dener4321** [Baseflow/flutter-geolocator#1014]
I was doing tests with AndroidSettings and I noticed that when I set the intervalDuration value to less than 5 seconds, for example 1 second, the interval is still 5 seconds. But setting the interval to any value above 5 seconds seems to work fine.

### Reproduction steps

```
final locationSettings = AndroidSettings(
        accuracy: LocationAccuracy.best,
        distanceFilter: 0,
        intervalDuration: const Duration(seconds: 1),
      );

 Geolocator.getPositionStream(locationSettings: locationSettings)
.listen(value => print('Position update ' + value.timestamp!.toString()));
```
### Configuration
**Version:** 8.2.0

**Platform:**

- [x] 🤖 Android

**Comment by florissmit1** [comment]
Thanks for reporting your issue @dener4321. I can't reproduce your issue and it seems to work fine for me. Can you confirm if your issue still exists? And if so, can you specify which device you're testing on and which version of Flutter you're using (post your `flutter doctor -v`).

**Comment by dominikstrdev** [comment]
Have someone solved this problem? I'm facing it also

**Comment by dkozenkov** [comment]
I have exactly the same problem as in the title of this problem.

### Reproduction steps
```
final locationSettings = AndroidSettings(
        accuracy: LocationAccuracy.best,
        distanceFilter: 0,
        intervalDuration: const Duration(seconds: 1),
      );

 Geolocator.getPositionStream(locationSettings: locationSettings)
.listen(value => print('Position update ' + value.timestamp!.toString()));

```
### Configuration
Version: 13.0.1
Platform: Android

flutter doctor
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.19045.5073], locale ru-RU)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.5)
[√] Android Studio (version 2024.2)
[√] IntelliJ IDEA Community Edition (version 2024.2)
[√] VS Code (version 1.95.1)
[√] Connected device (4 available)
[√] Network resources
