### ISSUE TITLE
No support on Terminals without Google Play Services

### ISSUE THREAD

**Issue by eric-geek1232** [Baseflow/flutter-geolocator#1021]
## HI, I hope everybody is good!

Im working on point of sale terminal, this terminal doesn't have google play services(GApps), the android is very basic, this plugin sometimes works and sometimes not until the log message appears: com.example.app requires google play services or google play, but it's missing

**Comment by KingSering** [comment]
I/flutter (32689):  permission = LocationPermission.whileInUse 
W/GooglePlayServicesUtil(32689): Google Play Store is missing.
E/GoogleApiAvailability(32689): Google Play services is invalid. Cannot recover.

**Comment by amenk** [comment]
Maybe the branch by @zverik is helpful? https://github.com/Zverik/flutter-geolocator/tree/floss

**Comment by Zverik** [comment]
Or try adding `forceLocationManager: true` to location settings, as written in the documentation.

**Comment by JeroenWeener** [comment]
Hi @eric-geek1232, thanks for reaching out!

As @Zverik mentioned, providing `forceLocationManager: true` to `AndroidSettings` should solve your problem.

I will close this issue now. We can reopen it if the proposed solution does not work for you.
