### ISSUE TITLE
geolocator getPositionStream stops listening to position updates after a while of mobile screen off and device idle

### ISSUE THREAD

**Issue by Yakoota** [Baseflow/flutter-geolocator#1023]
### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
Closing this issue due to lack of information.

I would gladly re-open the issue when required information is supplied (the platforms the issue occurs on, is background support enabled, reproduction steps, configuration send with the `getPositionStream` method, etc...).

**Comment by MohammedHannoush** [comment]
I've added all info

**Comment by johnray016** [comment]
@MohammedHannoush  did you find any solution to this?

**Comment by JulianBissekkou** [comment]
Please consider reopening this issue.
@mvanbeusekom

**Comment by FlawLessx** [comment]
i still had this problem, after some times when the app paused by system, location update not sent anymore, i think getPositionStream not properly freground service
