### ISSUE TITLE
huawei problem

### ISSUE THREAD

**Issue by zakarya0** [Baseflow/flutter-geolocator#1026]
getCurrentLocation function is not retrieving latlng data on huawei phones.

**Comment by liu731** [comment]
+1

**Comment by liu731** [comment]
Try this, it worked for me
`Position position = await Geolocator.getCurrentPosition(forceAndroidLocationManager: true);`

**Comment by florissmit1** [comment]
Hey @zakarya0. Thanks for reporting your issue,  can you be a bit more specific about your issue? Share your `flutter doctor -v`, a code example, name it. Then I can try reproducing your issue (or not).
