### ISSUE TITLE
Enable location service dynamically

### ISSUE THREAD

**Issue by cedvdb** [Baseflow/flutter-geolocator#1034]
## 🏗 Enhancement Proposal

In google maps if the location service is disabled it is possible to enable it without going into the location settings, you just press ok on the dialog. The idea here is to enable the same thing for the platforms that supports it

**Comment by Mandax78** [comment]
Yeah that's a good idea !

**Comment by LostInDarkMath** [comment]
I would like this feature too :)

**Comment by Galti** [comment]
I see location package has this feature. It surprised me that geolocator doesn't have this feature yet.

**Comment by florissmit1** [comment]
Hey @cedvdb, thanks for sharing your enhancement request. I'm not sure if this feature will fit in the current `geolocator` plugin. I will discuss your request with the main author of the plugin and will give you an update soon.

**Comment by jglatre** [comment]
> I see location package has this feature. It surprised me that geolocator doesn't have this feature yet.

Nothing prevents you from using both packages together, so my workaround is something like this:

```
bool enabled = await Geolocator.isLocationServiceEnabled();
if (!enabled) {
  enabled = await Location().requestService();
}
```

**Comment by Galti** [comment]
> > I see location package has this feature. It surprised me that geolocator doesn't have this feature yet.
> 
> Nothing prevents you from using both packages together, so my workaround is something like this:
> 
> ```
> bool enabled = await Geolocator.isLocationServiceEnabled();
> if (!enabled) {
>   enabled = await Location().requestService();
> }
> ```

@jglatre thank you for your comment.
Agree that nothing prevents from doing this but it is not a good practice to have many dependencies.
Best UX for location services is to prompt the user to switch on location services by just clicking yes(or something like that)
Geolocator uses location services and, in my opinion, most of the geolocator user's would like to use this functionality.

**Comment by glennfordd** [comment]
Calling `getCurrentPosition` actually shows the Android prompt to turn on your location. Tapping OK will then enable your location. I haven't tested this on iOS though

**Comment by jglatre** [comment]
> Calling `getCurrentPosition` actually shows the Android prompt to turn on your location. Tapping OK will then enable your location. I haven't tested this on iOS though

Thank you @glennfordd, it works. Although still not ideal, it's better than my previous workaround (as pointed out by @Galti). I've ended up with this, which smells somewhat hacky compared with its Location package equivalent:

```
bool enabled = await Geolocator.isLocationServiceEnabled();
if (!enabled) {
  try {
    await Geolocator.getCurrentPosition();
    enabled = true;
  } catch (e) {
    _log.warning('User rejected location service');
  }
}
```

**Comment by florissmit1** [comment]
As mentioned by @glennfordd, the feature is already available using just the `getCurrentPosition` method and skipping handling permissions. A workaround like @jglatre is mentioning is correct and working, but checking whether is location service is enabled is not needed. When using the `getCurrentPosition` method on Android while the location service is disabled, the prompt will appear, making checking for Location Service availability unnecessary. 

On iOS, handling permissions **is** necessary, but a prompt will appear as you would expect.

For now I will close this issue, since I think a small code change will make this feature work (in the case of using Android).

**Comment by tolotrasamuel** [comment]
what happens when we call getCurrentPosition on Android and user denies the turn on location prompt ? Do we get an exception ?
