### ISSUE TITLE
getLastKnownPosition returns null even if location previously queried before

### ISSUE THREAD

**Issue by burekas7** [Baseflow/flutter-geolocator#1037]
Hi,

This is an old issue I found and I still have this problem.

Original issue: https://github.com/Baseflow/flutter-geolocator/issues/285

This is a comment I found that relates to the issue:
`This is on purpose since disabling the location services will clear the location cache. So having logic to enable the service will not help since the cache will still be empty and you will still receive null. More information can be found here: https://developer.android.com/training/location/retrieve-current#last-known`

So my question is what is the purpose of 'getLastKnownPosition' if it actually doesn't show the last location if location service is disabled?
(Tested on Andorid, geolocator: ^8.2.0)

Thanks.

**Comment by mvanbeusekom** [comment]
The purpose is to quickly acquire an initial location (considering location services are enabled). Fetching a fresh location might take some time and in most applications a quick fetch of the last known location improves the user experience.
