### ISSUE TITLE
MissingPluginException(No implementation found for method checkPermission on channel flutter.baseflow.com/geolocator)

### ISSUE THREAD

**Issue by patildarshan66** [Baseflow/flutter-geolocator#1038]
MissingPluginException(No implementation found for method checkPermission on channel flutter.baseflow.com/geolocator)

getting this issue in the production build
<img width="1399" alt="Screenshot 2022-04-21 at 6 45 31 PM" src="https://user-images.githubusercontent.com/51800177/164465974-59c0e927-e4c9-45d3-99fa-577b7fd82e7d.png">

**Comment by iamabhishek229313** [comment]
I too got this in production release.

**Comment by patildarshan66** [comment]
@mvanbeusekom look into this

**Comment by PollexLee** [comment]
I got it too.

I dropped the version of geolocato_android to 3.1.5 and it was OK.

**Comment by mvanbeusekom** [comment]
That is a bit strange. Do you add platform specific dependencies? 

All you would need in general is to depend on the `geolocator` package and it will pull in the necessary platform packages. This should also prevent versioning problems.

**Comment by ysur67** [comment]
> I dropped the version of geolocato_android to 3.1.5 and it was OK.

Solved the problem for me. Thanks!

**Comment by patildarshan66** [comment]
> geolocato_android

I am not using a native plugin, I used the flutter package geolocator: ^8.2.0

**Comment by ManukumarSB** [comment]
Any solutions @patildarshan66

**Comment by mvanbeusekom** [comment]
Doing more detailed research we found out the this exception occurs when calling the `getCurrentPosition` from a background task (either the `Workmanager` or a separate `Isolate`). 

This reason this is happening is two fold:

1. We refactored the code to comply to the latest architectural concepts for Flutter plugins (fully federated architecture) where platform specific packages (geolocator_android, geolocator_apple, etc..) are responsible for maintaining their own communication layer between Dart and the native platform.
2. When running a background task there is no Flutter engine and therefore platform specific plugins are not registered with the native platform.

> Note: it is good to realize that the main (a.k.a. app-facing) geolocator package internally depends on the platform specific packages. So even if the app only depends on the geolocator package, internally a dependency is created on the geolocator_android, geolocator_apple, etc... packages. To verify the exact versions used check the contents of the `pubspec.lock` file.

On pre-Flutter 2.11, the workaround for this is to manually register the native platform implementations:

```dart
//callback function
void callbackDispatcher() {
  Workmanager().executeTask((task, inputData) async {
   if (defaultTargetPlatform == TargetPlatform.android) {
     GeolocatorAndroid.registerWith();
   } else if (defaultTargetPlatform == TargetPlatform.iOS || defaultTargetPlatform == TargetPlatform.macOS) {
     GeolocatorApple.registerWith();
   } else if (defaultTargetPlatform == TargetPlatform.linux) {
     GeolocatorLinux.registerWith();
   }

   await LocationService.getCurrentLocation();
    print("Native called background task-1: $task");

    return Future.value(true);
  });
}
```

Alternatively if you are running Flutter 2.11+, you can use the new `DartPluginRegistrant.ensureInitialized()` method to ensure all packages are registered correctly:

```dart
//callback function
void callbackDispatcher() {
  Workmanager().executeTask((task, inputData) async {
   DartPluginRegistrant.ensureInitialized();

   await LocationService.getCurrentLocation();
    print("Native called background task-1: $task");

    return Future.value(true);
  });
}
```

More information can be found [here](https://github.com/Baseflow/flutter-geolocator/issues/1041#issuecomment-1125862107) and [here](https://github.com/flutter/flutter/issues/98473#issuecomment-1060952450).

**Comment by eerbee** [comment]
> I dropped the version of geolocato_android to 3.1.5 and it was OK.

this solved my issue, just check on your pobspec.lock then change the version

**Comment by mvanbeusekom** [comment]
> > I dropped the version of geolocato_android to 3.1.5 and it was OK.
> 
> this solved my issue, just check on your pobspec.lock then change the version

This is not the best solution, please check out the [comment](https://github.com/Baseflow/flutter-geolocator/issues/1038#issuecomment-1165491595) above and ensure you register the platform specific implementations. Going forward this will be the stable solution and new versions will rely on this.

Of course if you are fine using an outdated version and pin versions in your pubspec.yaml, feel free to do so. However I strongly suggest refraining from doing so and follow instructions in the mentioned comment.

**Comment by eerbee** [comment]
> This is not the best solution, please check out the [comment](https://github.com/Baseflow/flutter-geolocator/issues/1038#issuecomment-1165491595) above and ensure you register the platform specific implementations. Going forward this will be the stable solution and new versions will rely on this.
> 
> Of course if you are fine using an outdated version and pin versions in your pubspec.yaml, feel free to do so. However I strongly suggest refraining from doing so and follow instructions in the mentioned comment.

for your info, for my problem ... i didnt put any geolocator process on background or isolated task. 
but yeah thank you for your suggestion

**Comment by namanx19** [comment]
Check these lines of codes if they are present in your code or not. Adding them will resolve your issue:

1. android/app/src/main/AndroidManifest.xml
```
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
```

2. ios/runner/info.plist
    ```
<key>NSLocationWhenInUseUsageDescription</key>
    <string>This app needs access to location when open.</string>
    <key>NSLocationAlwaysUsageDescription</key>
    <string>This app needs access to location when in the background.</string>
```

3. In your getLocation() add these 2 lines:
```
    await Geolocator.checkPermission();
    await Geolocator.requestPermission();
```

After doing all these steps do a Hot Restart or Stop all and Run again.
