### ISSUE TITLE
Geolocator not working correctly on Android

### ISSUE THREAD

**Issue by umitbicici** [Baseflow/flutter-geolocator#1042]
### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

Geolocator working correctly on IOS System but not working correctly on Android System

**Comment by mvanbeusekom** [comment]
Closing issue due to lack of information. Please describe clearly:

1. Which problem you are facing. 
2. What are your expectations.
3. Provide sample code.
4. Provide version information.
