### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getCurrentPosition on channel flutter.baseflow.com/geolocator)

### ISSUE THREAD

**Issue by Saikiran24** [Baseflow/flutter-geolocator#1043]
Getting this issue when running on Android

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getCurrentPosition on channel flutter.baseflow.com/geolocator)

**Comment by mvanbeusekom** [comment]
Duplicate of issues #745 and #930, please have a look there. This error is usually an issue with the development environment or pub.dev cache.
