### ISSUE TITLE
[ANDROID]`GeolocatorPlatform.requestPermission()` returns `deniedForever` when dismissing the dialog

### ISSUE THREAD

**Issue by DominicOrga** [Baseflow/flutter-geolocator#1044]
## 🐛 Bug Report

When dismissing the permission dialog by pressing on the background, `GeolocatorPlatform.requestPermission()` erroneously returns `deniedForever`. However, when you fetch the location permission via `GeolocatorPlatform.checkPermission()`, this returns `denied` which is the correct location permission.

### Expected behavior

Dismissing the `GeolocatorPlatform.requestPermission` should return the current location permission instead of `deniedForever`.

### Reproduction steps

Step 1: Show the request permission dialog
Step 2: Dismiss the dialog by tapping on the background (This returns a location permission)
Step 3: Fetch the location permission

By comparing the location permissions obtained from Step 2 and Step 3, we get two different results.

### Configuration

**Version:** 8.2.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by florissmit1** [comment]
@DominicOrga Thanks for reporting your issue. I am able to reproduce the issue, and I think it indeed is incorrect behaviour. I will take a look into it and will give you a heads up when the changes are published.

**Comment by huzaifansari54** [comment]
hello sir can i work on this issue ?

**Comment by TimHoogstrate** [comment]
Hi @DominicOrga 

Unfortunately the Android SDK doesn't support this. This is explained into more detail in [this comment](https://github.com/Baseflow/flutter-geolocator/issues/1087#issuecomment-1163479678) for issue #1087. 

Also have a look at our [Wiki](https://github.com/Baseflow/flutter-geolocator/wiki/Breaking-changes-in-7.0.0) page.
