### ISSUE TITLE
Unable to get user location on android 13

### ISSUE THREAD

**Issue by abhihasabe** [Baseflow/flutter-geolocator#1046]
We are unable to locate, the location on android 13 (all devices), It working properly on below 13.

**Comment by JeroenWeener** [comment]
Hi @abhihasabe, thank you for filing this issue!

During triaging, I encountered similar issues. To clean up, I am going to close this issue in favor of #1188, which is a duplicate. You can keep track of progress on this issue there. If you can, please provide us with extra information regarding the issue there. To effectively tackle the issue, we require at least minimal reproducible code (or a confirmation that the example app exhibits mentioned behavior).
