### ISSUE TITLE
iOS Background location update stop working after 15 minutes

### ISSUE THREAD

**Issue by SimonTellier** [Baseflow/flutter-geolocator#1047]
Hi !
i'm working to create an iOS app to track user location when user launch the app.
Geolocator works very well ! My app track user location when he move but when user stop moving since 15 minutes my app is killed by iOS. 
Do you have a tip for keep alive my app and continue to track him ? 

Regards

Simon

**Comment by florissmit1** [comment]
Hey @SimonTellier, thanks for reporting your issue. When your application is killed on iOS, does the console report any errors/issues? If so, can you share some code with me? Also, provide me the device you're using and your `flutter doctor -v`. On iOS, it can occur that the app is killed while trying to fetch a `Location` update in the background, while your app does not have the permission to fetch `Location Updates` in the background.
