### ISSUE TITLE
Need to manually define a Position variable, can't find documentation on the format?

### ISSUE THREAD

**Issue by jmote** [Baseflow/flutter-geolocator#1054]
Hello!

I'm trying to manually define a Position variable before using geolocator to redefine it later. But I have no idea what the format of the variable is, and I can't find documentation on it either.

If I were to do:

`Position _currentPosition = X;`

where X is the manually defined lat/long, what is the format necessary?

**Comment by weihenglim** [comment]
You can use the `fromMap` function like so:
`Position _currentPosition = Position.fromMap({'latitude': 37.4, 'longitude': -122.0});`

**Comment by mvanbeusekom** [comment]
Hi @jmote,

The example shown by @weihenglim is correct, you can use the `fromMap` method to create a new position if you want to. Alternatively (and that would be my recommendation) you could create your own `Position` class on which you have full control and create a special constructor that accepts the Geolocator's `Position` class to construct it self.

Something a long the lines of:

```dart
class MyPosition {
  MyPosition(this.latitude, this.longitude);
  
  MyPosition.fromPosition(Position position) 
    : this.latitude = position.latitude, 
      this.longitude = position.longitude;
 
  final double latitude;
  final double longitude;
}
```

Now you can use the `MyPosition` class in the rest of your application which makes the coupling between your code and the geolocator a bit more loosely (which is a good thing).

If you are looking for the definition of the `Position` class, you can find it here: https://github.com/Baseflow/flutter-geolocator/blob/9ff1f1b7712fc7c2b210d21408884258689cb389/geolocator_platform_interface/lib/src/models/position.dart

I am going to close this issue now, however feel free to leave a comment if you have additional questions.
