### ISSUE TITLE
didChangeAppLifecycleState will infinite looping when calling function contains requestPermission

### ISSUE THREAD

**Issue by sed1ka** [Baseflow/flutter-geolocator#1056]
## 🐛 Bug Report

so I use didChangeApplifeCycleState to refresh a page if user goes to settings to change location permission using `openAppSettings()`.
whereas I need didChangeApplifeCycle so that the page is refreshed because there is a condition case if the location permission is denied or denied forever, and I open the settings using `openAppSettings()` and allow location permission access. The application will not restart automatically.

after debugging, didChangeApplifeCycle will be an infinite loop if there is a `requestPermission()` function. didChangeApplifeCycle will only run normally when I don't use `requestPermisson()` at all. And this only happens in Android, working fine in iOS

Device test: Xiaomi Redmi 9T

**Version:** 8.2.0

**Platform:** 
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @sed1ka,

Can you provide a small reproduction sample that demonstrates this behavior? We have had similar people mentioning this problem but we don't have enough information to reproduce the issue.

**Comment by sed1ka** [comment]
simple code example

Note: I just tested this issue on Xiaomi Redmi 9T (android), Samsung Note 20 (Android) and simulator (iOS)
the bug happens on Android devices both Xiaomi and Samsung

Maybe this code will cause an error for you because I disabled the null-safety on my flutter


```
import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';
import 'package:permission_handler/permission_handler.dart';

class GeolocatorSimpleExample extends StatefulWidget {
  const GeolocatorSimpleExample({Key key}) : super(key: key);

  @override
  State<GeolocatorSimpleExample> createState() => _GeolocatorSimpleExampleState();
}

class _GeolocatorSimpleExampleState extends State<GeolocatorSimpleExample> with WidgetsBindingObserver {
  final GeolocatorPlatform geo = GeolocatorPlatform.instance;
  LocationPermission permission;

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    // TODO: implement dispose
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  Future<void> didChangeAppLifecycleState(AppLifecycleState state) async {
   // this will be loop after back from openAppSettings()
   // and when calling requestPermission();
    print('#didChangeApplifeCycleState $state');
    if (state == AppLifecycleState.resumed) {
      print('#didChangeApplifeCycleState state is resume');
      permission = await geo.requestPermission();
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: <Widget>[

            GestureDetector(
              onTap: (){
                openAppSettings();
              },
              child: Text('Click to Open Settings'),
            )
          ],
        ),
      ),
    );
  }
}
```

**Comment by mvanbeusekom** [comment]
Thank you for providing the code sample, I think I see the problem here.

Requesting permissions on Android requires triggering a new intent. This means the App is send to the background so the Android OS can handle the permission request. When the OS has handled the permission it will resume the App and thus triggers the `didChangeAppLifecycleState` callback.

What happens in the code example is that it will again request permissions, sending the app to the background, etc... causing the infinite loop.

To break the loop the best thing to do would be to keep track if the permission request has been handled already after te resume. Maybe something like this:

```dart
import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';
import 'package:permission_handler/permission_handler.dart';

class GeolocatorSimpleExample extends StatefulWidget {
  const GeolocatorSimpleExample({Key key}) : super(key: key);

  @override
  State<GeolocatorSimpleExample> createState() => _GeolocatorSimpleExampleState();
}

class _GeolocatorSimpleExampleState extends State<GeolocatorSimpleExample> with WidgetsBindingObserver {
  final GeolocatorPlatform geo = GeolocatorPlatform.instance;
  bool _shouldRequestPermission = false;
  LocationPermission permission;

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    // TODO: implement dispose
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  Future<void> didChangeAppLifecycleState(AppLifecycleState state) async {
   // this will be loop after back from openAppSettings()
   // and when calling requestPermission();
    print('#didChangeApplifeCycleState $state');
    if (state == AppLifecycleState.resumed) {
      print('#didChangeApplifeCycleState state is resume');
      if (_shouldRequestPermission) {
        _shouldRequestPermission = false;
        permission = await geo.requestPermission();
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: <Widget>[

            GestureDetector(
              onTap: (){
                _shouldRequestPermission = true;
                openAppSettings();
              },
              child: Text('Click to Open Settings'),
            )
          ],
        ),
      ),
    );
  }
}
```

**Comment by Mamasodikov** [comment]
For better control, use like this (calls every time when switched between foreground and background):

` void _onDetached() => print('detached');

  void _onResumed() {
    if (_shouldRequestPermission) {
      permissionWall();
      _shouldRequestPermission = false;
    }
  }

  void _onInactive() => print('inactive');

  void _onHidden() => print('hidden');

  void _onPaused() => _shouldRequestPermission = true;`
