### ISSUE TITLE
MethodChannelGeolocator.getCurrentPosition Error.

### ISSUE THREAD

**Issue by Yukika0216** [Baseflow/flutter-geolocator#1063]
> E/flutter ( 6641): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getCurrentPosition on channel flutter.baseflow.com/geolocator)
E/flutter ( 6641): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
E/flutter ( 6641): <asynchronous suspension>
E/flutter ( 6641): #1      MethodChannelGeolocator.getCurrentPosition (package:geolocator_platform_interface/src/implementations/method_channel_geolocator.dart:122:27)
E/flutter ( 6641): <asynchronous suspension>

 [√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19044.1706], locale ko-KR)
    • Flutter version 2.10.5 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (5 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.14)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32428.217
    • Windows 10 SDK version 10.0.19041.0
    X The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.67.2)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554    • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows          • windows-x64    • Microsoft Windows [Version 10.0.19044.1706]
    • Edge (web)                   • edge             • web-javascript • Microsoft Edge 101.0.1210.47

[√] HTTP Host Availability
    • All required HTTP hosts are available

I already add these to AndroidManifest.xml 

```
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
```
And this too.

```
android.useAndroidX=true
android.enableJetifier=true
```

I can get getCurrentPosition at Foreground, but I can't get getCurrentPosition at Background and Terminated.
Obviously I can get at Background and Terminated a few weeks ago, Suddenly the function didn't work for me.
I do 'flutter clean' and 'flutter pub get' so many times. 

I wonder what makes this happen...
If there are more information you need, plz tell me. 
Thx. Have a nice day.

### Configuration

**Version:** 
- geolocator: ^8.2.1

**Platform:** 
- Android

**Comment by mvanbeusekom** [comment]
Hi @Yukika0216,

Due to a change in architecture on the Android implementation (introduced with version 3.1.6) some unexpected behavior showed up. Please have a look at this [comment](https://github.com/Baseflow/flutter-geolocator/issues/1041#issuecomment-1125862107) in issue #1041. This describes the solution for this problem when calling from the background or isolate.

**Comment by Yukika0216** [comment]
thanks. I'll check it.

**Comment by Yukika0216** [comment]
> Hi @Yukika0216,
> 
> Due to a change in architecture on the Android implementation (introduced with version 3.1.6) some unexpected behavior showed up. Please have a look at this [comment](https://github.com/Baseflow/flutter-geolocator/issues/1041#issuecomment-1125862107) in issue #1041. This describes the solution for this problem when calling from the background or isolate.

thanks for your help.
but I wonder where do I add `GeolocatorAndroid.registerWith()` ...
I use getCurrentLocation at main.dart with FCM notification...

**Comment by mvanbeusekom** [comment]
Hi @Yukika0216,

I am not familiar with FCM notification, however I imagine you'd have to register some kind of callback method or delegate that is called when a notification arrives, this would be the place to call `GeolocationAndroid.registerWith()`.
