### ISSUE TITLE
Geolocation not working in workManager when app run in the background

### ISSUE THREAD

**Issue by anhTuan0712** [Baseflow/flutter-geolocator#1065]
## 🐛 Bug Report

source code: 
![image](https://user-images.githubusercontent.com/75367671/170815566-9264d362-9e7e-43e7-9f33-f5aa47a61ad0.png)

When the app runs in the foreground works fine (may return location).

But when the app runs in the background (both simulation and real device) the location is not returned, see the following output: enter image description here
![image](https://user-images.githubusercontent.com/75367671/170815592-97ad767b-e219-4678-8024-7f346ad01bed.png)
please show me how to fix this problem. any help is appreciated!
### Configuration

**Version: 
workmanager: ^0.5.0
geolocator: ^8.2.0
**Platform:** 

- [Note 8 ] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @anhTuan0712, 

When trying to call `getCurrentPosition()` from the background make sure to register the platform implementations. Something like this on Flutter 2.11+:

```dart
void callbackDispatcher() {
  Workmanager().executeTask(task, inputData) async {
    DartPluginRegistrant.ensureInitialized();
    
    // TODO: Put the rest off the code here...
  }
}
```

or if you are on older Flutter version use:

```dart
void callbackDispatcher() {
  Workmanager().executeTask(task, inputData) async {
    if (defaultTargetPlatform == TargetPlatform.android) {
      GeolocatorAndroid.registerWith();
    } else if (defaultTargetPlatform == TargetPlatform.iOS) {
      GeolocatorApple.registerWith();
    }
    
    // TODO: Put the rest off the code here...
  }
}
```

A more detailed explanation can be found in this [comment](https://github.com/Baseflow/flutter-geolocator/issues/1041#issuecomment-1125862107). 

Pro tip: when reporting an issue please include the code and error messages as plain text instead of a screenshot. This will make it a lot easier for us to help out. The screenshots are often difficult to read and we need to rewrite code if we want to test code samples instead of being able to simply copy/ paste code.

**Comment by anhTuan0712** [comment]
Hi @mvanbeusekom, thanks for your answer.
I am still facing this problem
**This is my latest source code **
void callbackDispatcher() {
  Workmanager().executeTask((task, inputData) async {
    switch (task) {
      case simplePeriodicTask:
        counter++;
        final myName = inputData!['myName']!;
        final pathFile = inputData['pathFile']!;
        DartPluginRegistrant.ensureInitialized();
        await Geolocator.getCurrentPosition(forceAndroidLocationManager: false, desiredAccuracy: LocationAccuracy.bestForNavigation, timeLimit: const Duration(seconds: 20))
            .then((Position position) async {
          locationCurrent.latitude = position.latitude;
          locationCurrent.logitude = position.longitude;
          debugPrint(ResString.getData("tag") + "updateLocationInBackground1 => my location current   -  CURRENT POS -  [${locationCurrent.latitude},${locationCurrent.logitude}]");
          await hiveSql.getIntance()!.init(path: pathFile);
          double latitude = 0.0;
          double longitude = 0.0;
          try {
            latitude = hiveSql.getIntance()!.getLocationLatitude();
            longitude = hiveSql.getIntance()!.getLocationLongitude();
          } catch (e) {
            debugPrint(ResString.getData("tag") + "updateLocationInBackground exception: get data -  $e");
          }

          debugPrint(ResString.getData("tag") + "updateLocationInBackground1 => my location Old   -  CURRENT POS -  [$latitude,$longitude]");
          if ((latitude - locationCurrent.latitude).abs() > 0.0004 || (longitude - locationCurrent.logitude).abs() > 0.0004)
          {
            try {
              debugPrint(ResString.getData("tag") + "updateLocationInBackground_currentPosition.latitude: ${locationCurrent.latitude}");
              debugPrint(ResString.getData("tag") + "updateLocationInBackground_currentPosition.longitude: ${locationCurrent.logitude}");
              locationOld = locationCurrent;
              hiveSql.getIntance()!.setLocation(locationCurrent.latitude, locationCurrent.logitude);
              await Firebase.initializeApp(); //remove
              FireBaseData.getInstance()!.setLocation(position.latitude, position.longitude, myName: myName);
            } catch (ee) {
              return Future.error("Try catch (Firebase)-> $ee");
            }
          } else {
            return Future.error("location complete but data is still stale");
          }
        }).catchError((e) async {
          debugPrint(ResString.getData("tag") + "updateLocationInBackground exception: -  $e");
          return Future.error("Try catch (Geolocation)-> $e");
        });

        debugPrint(ResString.getData("tag") + "simplePeriodicTask was executed -- endl ");
        break;

      case Workmanager.iOSBackgroundTask:
        debugPrint(ResString.getData("tag") + "You can access other plugins in the background, for example Directory.getTemporaryDirectory():");
        break;
    }

    return Future.value(true);
  });
}
**When I test with a virtual machine (Android 10)**
Received Exception error: **TimeoutException after 0:00:20.000000: Future not completed**
![image](https://user-images.githubusercontent.com/75367671/171821509-d1de30cb-b5ab-4412-b105-558b81d83289.png)
**Permissions I gave to Android**
![image](https://user-images.githubusercontent.com/75367671/171821755-37d4d5c1-cb82-460a-b983-dccda35e7533.png)
But when I run on real device [Galaxy Note 8]
There are still some times when it executes successfully (no TimeoutException errors)
![image](https://user-images.githubusercontent.com/75367671/171822624-5010893f-f7b9-4188-ab92-80a571a0674b.png)

**Comment by mvanbeusekom** [comment]
Hi @anhTuan0712,

Do I understand correctly that this error mainly occurs on the emulator? This might be very possible as the emulator is known for its problems simulating location updates. 

When testing with location services you should always rely on a real phone.

**Comment by anhTuan0712** [comment]
Hi @mvanbeusekom 
No, it happens on my real device as well.
Real devices I tried and got this error:
1.  Samsung Galaxy Note 8 - Android 9
2.  Oppo F1 S - Android 5.1
3.  Samsung galaxy A31 - Android 10
Particularly for Samsung Galaxy Note 8 - the error only occurs randomly (70% of error occurs)

**Comment by anhTuan0712** [comment]
I give you more information
![Untitled](https://user-images.githubusercontent.com/75367671/172080490-989b1f2a-92e7-40b9-93a5-0abce69ca827.png)

**Comment by anhTuan0712** [comment]
Hi @mvanbeusekom,
are you still there?
Was the information I provided useful to you?

**Comment by mvanbeusekom** [comment]
Yes I am still here, but my time is limited.

I am not sure what is causing this problem. It is possible that it just takes too long to acquire the position and that is causing the timeouts. Another possibility might be that Android is limiting access to the location services when your app is in the background. 

Did you request the `locationAlways` permissions? 

It would be very helpful if you can make a small example application that reproduces the problem. That way I can also have a look and see if I experience similar problems.

**Comment by pilojanmobile** [comment]
still same issue 

workmanager: ^0.5.0
geolocator: ^9.0.2

**Comment by lahirunc** [comment]
Same issue persist

workmanager: ^0.5.0
geolocator: ^9.0.2

Anyone has a solution for this?

**Comment by vasanthbalaji88** [comment]
@mvanbeusekom 

Tried your suggestions with DartPluginRegistrant.ensureInitialized() in Android , but im not getting any location when workmanager gets started , i have posted the verbose below , please check it. could you please help on this issue.

**geolocator: ^9.0.2
workmanager: ^0.5.1**


**main.dart**

```
import 'package:flutter/material.dart';
import './utils/fetch_location_callback.dart';
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Workmanager().initialize(callbackDispatcher, isInDebugMode: true);
  
  runApp(child: MyApp());
}
class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
 
  @override
  void initState() {
    super.initState();
}

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),

      home: const HomePage(),
     );
  }
}
```

***fetch_location_callback.dart***
```
@pragma('vm:entry-point')
void callbackDispatcher() {
  WidgetsFlutterBinding.ensureInitialized();
  Workmanager().executeTask((task, inputData) async {
     print('Date Time :$task : ${DateTime.now()} ');
     DartPluginRegistrant.ensureInitialized();
     getLocation();
      return Future.value(true);
  });
}

void getLocation() async {
 
  print('getLocation');
  Position? position;
  await Geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.high)
      .then((value) {
    position = value;
    String latitude = position!.latitude.toString();
    String longitude = position!.longitude.toString();
   
    print('Latitude $latitude  Longitude $longitude');
  
  });
 
}

```
Please find the verbose below

Launching lib/main.dart on M2101K6P in debug mode...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
D/FlutterGeolocator(16934): Attaching Geolocator to activity
D/FlutterGeolocator(16934): Creating service.
D/FlutterGeolocator(16934): Binding to location service.
D/FlutterGeolocator(16934): Geolocator foreground service connected
D/FlutterGeolocator(16934): Initializing Geolocator services
D/FlutterGeolocator(16934): Flutter engine connected. Connected engine count 1
Connecting to VM Service at ws://127.0.0.1:50519/L_pvUUb9-G4=/ws

D/DecorView[](16934): onWindowFocusChanged hasWindowFocus false
D/AppScoutStateMachine(16934): 16934-ScoutStateMachinecreated
I/OpenGLRenderer(16934): Davey! duration=27318ms; Flags=1, FrameTimelineVsyncId=19515238, IntendedVsync=1267242679508903, Vsync=1267242679508903, InputEventId=0, HandleInputStart=1267242680412198, AnimationStart=1267242680415427, PerformTraversalsStart=1267242680416625, DrawStart=1267242680932771, FrameDeadline=1267242712842235, FrameInterval=1267242680392719, FrameStartTime=16666666, SyncQueued=1267242681907458, SyncStart=1267242682027146, IssueDrawCommandsStart=1267242682797510, SwapBuffers=1267242703385635, FrameCompleted=1267269998281719, DequeueBufferDuration=3139791, QueueBufferDuration=1240468, GpuCompleted=1267269998281719, SwapBuffersCompleted=1267242705080792, DisplayPresentTime=0,
D/DecorView[](16934): onWindowFocusChanged hasWindowFocus true
D/DecorView[](16934): onWindowFocusChanged hasWindowFocus false
D/DecorView[](16934): onWindowFocusChanged hasWindowFocus true
I/flutter (16934): Date Time :fetchingLocation : 2022-12-13 10:37:20.410298
**I/flutter (16934): **getLocation****
D/FlutterGeolocator(16934): Flutter engine disconnected. Connected engine count 1
**D/FlutterGeolocator(16934): Disposing Geolocator services
E/FlutterGeolocator(16934): Geolocator position updates stopped**
E/FlutterGeolocator(16934): There is still another flutter engine connected, not stopping location service
I/WM-WorkerWrapper(16934): Worker result SUCCESS for Work [ id=96edd7dd-0643-43b8-a455-604a7c787a8d, tags={ be.tramckrijte.workmanager.BackgroundWorker } ]
W/FlutterJNI(16934): Tried to send a platform message response, but FlutterJNI was detached from native C++. Could not send. Response ID: 3
E/BLASTBufferQueue(16934): [ViewRootImpl[MainActivity]#2](f:0,a:2) Applying pending transactions on dtor 1
D/DecorView[](16934): onWindowFocusChanged hasWindowFocus false

**Comment by gotnull** [comment]
The Workmanager documentation references the following to be added in the AppDelegate:

    ```
WorkmanagerPlugin.setPluginRegistrantCallback { registry in
      // Registry in this case is the FlutterEngine that is created in Workmanager's
      // performFetchWithCompletionHandler or BGAppRefreshTask.
      // This will make other plugins available during a background operation.
      GeneratedPluginRegistrant.register(with: registry)
    }
```
I guess this allows other plugins available during a background operation. Not sure if this means you no longer need to do the following: ```DartPluginRegistrant.ensureInitialized();```

**Comment by Leekogram** [comment]
Please has anyone been able to resolve this issue ?

**Comment by root4417** [comment]
D/DeviceInfoPlugin(21930): Use TaskQueues.
D/FlutterGeolocator(21930): Geolocator foreground service connected
D/FlutterGeolocator(21930): Initializing Geolocator services
D/FlutterGeolocator(21930): Flutter engine connected. Connected engine count 2
W/FlutterJNI(21930): FlutterJNI.loadLibrary called more than once
W/FlutterJNI(21930): FlutterJNI.prefetchDefaultFontManager called more than once
I/ResourceExtractor(21930): Found extracted resources res_timestamp-22-1695666334496
W/FlutterJNI(21930): FlutterJNI.init called more than once
I/flutter (21930): task: backgroundUploadTask
I/flutter (21930): inputData: {backgroundTask: one off}
I/flutter (21930): Scheduled task executed!
D/FileSaver(21930): Detached From Engine
D/FlutterGeolocator(21930): Flutter engine disconnected. Connected engine count 1
I/WM-WorkerWrapper(21930): Worker result SUCCESS for Work [ id=1bde30c5-d04c-4439-9f8f-992acc70d7ea, tags={ be.tramckrijte.workmanager.BackgroundWorker } ]
D/FlutterGeolocator(21930): Disposing Geolocator services
E/FlutterGeolocator(21930): Geolocator position updates stopped
E/FlutterGeolocator(21930): There is still another flutter engine connected, not stopping location service

**Comment by Raajmathankumardys** [comment]
is this issue resolved?if it is please give the full code

**Comment by Domestositos** [comment]
Faced the same problem. To solve it, you need to make sure that the application always has access to the location, not only when it is running.

**Comment by MSF01** [comment]
so have you fixed this issue? @Domestositos

**Comment by sachin96Boy** [comment]
Same issue persist

workmanager: ^0.5.2
geolocator: ^10.1.0

No errors, it just disposes geolocator

Anyone has a solution for this?

**Comment by parapsychic** [comment]
For anyone looking for this @mvanbeusekom was right. I got it working on android with the following setup:
```
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
```

  geolocator: ^12.0.0
  workmanager: ^0.5.2

```dart
@pragma('vm:entry-point')
void callbackDispatcher() {
  Workmanager().executeTask(task, inputData) async {
    DartPluginRegistrant.ensureInitialized();
    
    // TODO: Put the rest off the code here...
  }
}
```

Most important of all: **Set location permission to ALWAYS**.
I have only tested on Android (15). I am not sure about iOS.
