### ISSUE TITLE
Support wearOS(samsung galaxy watch) and watchOS(apple watch)?

### ISSUE THREAD

**Issue by DDS-VangTA** [Baseflow/flutter-geolocator#1066]
### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @DDS-VangTA,

Can you please be more specific? Are there any special APIs that should be used? Maybe include links to the documentation?

**Comment by DDS-VangTA** [comment]
@mvanbeusekom Please update this plugin to support: get location, last known location, and location updates on smartwatch (apple watch, wearOS).

**Comment by mvanbeusekom** [comment]
Duplicate of #785
