### ISSUE TITLE
Information request about GPS geolocator plugin

### ISSUE THREAD

**Issue by willemvanleeuwen** [Baseflow/flutter-geolocator#1073]
While searching through various GPS Flutter plugins, we also found this package which is even a Flutter Favorite! 

Currently we are using another GPS plugin, which is giving us unwanted results on iOS devices. Our application is used to track cars during driving events and show 'dialogs' at certain locations. For us it is important that the GPS is the exact location and not some correlated 'snap-to-road' result.

Currently we experience unwanted 'snap-to-road' GPS signals on iOS devices, and before migrating to your package, we are curious if this 'issue' is known at your end.

Below we have an example of our current problem; the two devices were in the exact same car and drove the exact same route. However; on iOS the signal ''snapped' to the main road, instead of the smaller parallel road where the vehicle was actually driving. The 'accuracy' of the signal deteriorates at that moment (wider line), and on iOS the dialog did not trigger because of this. On Androids this is not an issue... If we look into Apple Maps; we can see that the small road does not exists, so apparently, iOS combines the GPS signal with their Maps... However we don't want this :-) We have various examples/cases like this.

![gps issue](https://user-images.githubusercontent.com/11671067/172329184-7b30675f-3c38-42a5-9315-017e924f9b8c.png)

Does anyone know if this 'issue' is present in the Geolocator package or maybe worse, that this is a Flutter issue in general?

**Comment by mvanbeusekom** [comment]
Hi @willemvanleeuwen,

Thank you for reaching out. Let me start by saying that I can only speak for the geolocator plugin, as I am not familiar with the implementation of the background_locator plugin.

The way the geolocator plugin is implemented is to simply wraps around the native [CLLocationManager](https://developer.apple.com/documentation/corelocation/cllocationmanager?language=objc) SDK on iOS. That would be the same (and only) SDK available when you would like to receive location updates on an iOS device. The geolocator plugin forwards the results provided by the CLLocationManager SDK to the Dart / Flutter and does not do any other logic (for example snapping to roads).

The geolocator offers several accuracy levels:

```dart

/// Represent the possible location accuracy values.
enum LocationAccuracy {
  /// Location is accurate within a distance of 3000m on iOS and 500m on Android
  lowest,

  /// Location is accurate within a distance of 1000m on iOS and 500m on Android
  low,

  /// Location is accurate within a distance of 100m on iOS and between 100m and
  /// 500m on Android
  medium,

  /// Location is accurate within a distance of 10m on iOS and between 0m and
  /// 100m on Android
  high,

  /// Location is accurate within a distance of ~0m on iOS and between 0m and
  /// 100m on Android
  best,

  /// Location accuracy is optimized for navigation on iOS and matches the
  /// [LocationAccuracy.best] on Android
  bestForNavigation,

  /// Location accuracy is reduced for iOS 14+ devices, matches the
  /// [LocationAccuracy.lowest] on iOS 13 and below and all other platforms.
  reduced,
}
```

These accuracy settings map 1 to 1 to the iOS `CLAccuracy` enum which controls the level of detail iOS will use to provide GPS updates. The official documentation can be found [here](https://developer.apple.com/documentation/corelocation/kcllocationaccuracybestfornavigation?language=objc).

I honestly can't promise the geolocator will solve this issue. However I am convinced this would not be a Flutter issue but an issue with iOS it self (as Flutter and the geolocator don't do anything else then wrap the official CLLocationManager SDK). I do notice however that you only mentioned the `high` and `best` accuracy modes in the background_location plugin where we also over the additional `bestForNavigation` option.

Maybe an easy way to find out if this is an iOS issue is to run the same road with Apple Maps tracking your location and see if it will report the position correctly (off road in this case, as Apple Maps isn't aware this road exists).  However in my personal experience the location reports on Apple (I am a iPhone 12 mini user and do a lot of off road cycling) is very accurate.

I hope this will answer your question, please feel free to ask follow up questions.

**Comment by willemvanleeuwen** [comment]
We have done some trials with this plugin; unfortunately (as you hinted already) the results are the same;

Below is the track of an Android phone with you geolocator plugin:
![image](https://user-images.githubusercontent.com/11671067/183625724-f6e0a442-cbce-49e7-8f7e-e11806b5373d.png)

And below is the track of an iPhone in the exact same car:
![image](https://user-images.githubusercontent.com/11671067/183625826-c70b4b75-0f5c-46e3-a1a7-77b39bdfd2a2.png)

Please note that the small road at the side is not present in Apple Maps; which is probably causing this issue.

**Comment by willemvanleeuwen** [comment]
We have better results with the gps library from transistorsoft
