### ISSUE TITLE
location.isMocked on iOS 15+

### ISSUE THREAD

**Issue by venzeo** [Baseflow/flutter-geolocator#1079]
Right now the location's [isMocked property returns always false on iOS](https://pub.dev/documentation/geolocator_platform_interface/latest/geolocator_platform_interface/Position/isMocked.html)

Fortunately iOS 15+ already provides this info in [sourceInformation](https://developer.apple.com/documentation/corelocation/cllocation/3861803-sourceinformation).

Would you be able to implement it please?

**Comment by mvanbeusekom** [comment]
This feature is added in version 2.2.0 of the geolocator_apple package and should be available on pub.dev. 

If you'd run `flutter pub upgrade` the package should automatically be updated as a dependency of the geolocator app facing package.

For official changelogs have a look at: https://pub.dev/packages/geolocator_apple/changelog.
