### ISSUE TITLE
Android: the build fails with compileSdkVersion 33

### ISSUE THREAD

**Issue by arielt** [Baseflow/flutter-geolocator#1084]
## 🐛 Bug Report

I have to bump compileSdkVersion to 33 because of dependencies on other packages. Compilation fails:

/dev/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_android-3.2.1/android/src/main/java/com/baseflow/geolocator/GeolocatorLocationService.java:134: warning: [deprecation] stopForeground(boolean) in Service has been deprecated
      stopForeground(true);
      ^
error: warnings found and -Werror specified
/dev/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_android-3.2.1/android/src/main/java/com/baseflow/geolocator/permission/PermissionUtils.java:27: warning: [deprecation] getPackageInfo(String,int) in PackageManager has been deprecated
              .getPackageInfo(context.getPackageName(), PackageManager.GET_PERMISSIONS);
              ^
1 error
2 warnings

FAILURE: Build failed with an exception.

### Expected behavior

Compilation succeeds.

### Reproduction steps

add compileSdkVersion 33 to build.gradle, try to build

### Configuration

**Version:** 8.2.1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mohamedYearex** [comment]
it doesn't work for me!

**Comment by verhneudinec** [comment]
Same problem

**Comment by divyanshu2345** [comment]
same problem. Did anyone find the solution?

**Comment by martin-braun** [comment]
@mvanbeusekom I maintain a Flutter package that I try to keep compatible with the latest Flutter 2 version (2.10.5), because Flutter 3 introduces too many breaking changes at the moment. It would've been great if you could've fixed this issue without breaking Flutter 2 compatibility.

**Comment by mvanbeusekom** [comment]
> @mvanbeusekom I maintain a Flutter package that I try to keep compatible with the latest Flutter 2 version (2.10.5), because Flutter 3 introduces too many breaking changes at the moment. It would've been great if you could've fixed this issue without breaking Flutter 2 compatibility.

I don't see how these changes are breaking compatibility with Flutter 2. The only changes made are upgrading the JAVA `compileSdkVersion` and some changes in the JAVA code working around the deprecated API since the release in Android API 33. This is completely unrelated to Flutter and should work perfectly fine in Flutter 2 (as long as you make sure you update the `compileSdkVersion` in your `android/app/build.gradle` file and set it to 33 as documented in the README and release notes.

**Comment by mvanbeusekom** [comment]
Hi @martin-braun,

Since the different packages part of the geolocator plugin used different Dart SDK and Flutter versions I decided to create a PR (see #1102) and straighten things out. 

The result is that the geolocator will depend on Dart SDK 2.15.0 and Flutter version 2.8.0 going forward (at least until it's time to upgrade to a higher Flutter version).

This should solve your problem as the error indicates you are not compiling against Dart SDK 2.17.0 (which comes with Flutter 3.0.0, but can also be installed separately).

**Comment by niaz25610** [comment]
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\audio_service-0.18.4\android\src\main\java\com\ryanheise\audioservice\AudioService.java:312: warning: [deprecation] stopForeground(boolean) in Service has been deprecated
        stopForeground(!config.androidResumeOnClick);
        ^
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\audio_service-0.18.4\android\src\main\java\com\ryanheise\audioservice\AudioService.java:586: warning: [deprecation] stopForeground(boolean) in Service has been deprecated
        stopForeground(false);
        ^
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\audio_service-0.18.4\android\src\main\java\com\ryanheise\audioservice\AudioService.java:795: warning: [deprecation] get(String) in BaseBundle has been deprecated
            final KeyEvent event = (KeyEvent)mediaButtonEvent.getExtras().get(Intent.EXTRA_KEY_EVENT);
                                                                         ^
error: warnings found and -Werror specified
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\audio_service-0.18.4\android\src\main\java\com\ryanheise\audioservice\AudioServicePlugin.java:1142: warning: [deprecation] get(String) in BaseBundle has been deprecated
            Object value = bundle.get(key);
                                 ^
1 error
4 warnings

FAILURE: Build failed with an exception.

**Comment by mgoldp** [comment]
Hi, I have the seame issue when I updated my project to the Flutter V3.7.

**Comment by elmar001** [comment]
The issue is reproducable with geolocator 8.2.1. Flutter version 2.10.5
Updating geolocator version to 9.0.0 fixes the issue without any further changes necessary.

**Comment by xeeshansami** [comment]
> it doesn't work for me!

how to resolve this issue bro please tell me

**Comment by yogithesymbian** [comment]
> same problem. Did anyone find the solution? Well, i find a solution if we just reduce the size of andorid sdk version 33 to 32 and implement old version of geolocator then there is no problem

well how if when run debug its say must upgrade into 33 , after fix this , i got a new error for geo location Zzzz
