### ISSUE TITLE
Crash on iOS 14.6

### ISSUE THREAD

**Issue by Wackymax** [Baseflow/flutter-geolocator#1091]
## 🐛 Bug Report

I have a user whose app randomly crashes when location sharing is enabled, but when location is denied the application starts up fine.

### Expected behavior

Application should startup up even when location permissions are set to allowed.

### Reproduction steps

Not sure, I only have the crash logs.

### Configuration

**Version:**
geolocator: 9.0.0

** Trace **

```
Fatal Exception: NSInvalidArgumentException
-[CLLocation sourceInformation]: unrecognized selector sent to instance 0x282ec5060


Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x129754 __exceptionPreprocess
1  libobjc.A.dylib                0x287a8 objc_exception_throw
2  CoreFoundation                 0x2cc3c -[NSOrderedSet initWithSet:copyItems:]
3  CoreFoundation                 0x12c2ac ___forwarding___
4  CoreFoundation                 0x12e5b0 _CF_forwarding_prep_0
5  geolocator_apple               0x8218 (Missing UUID 720753cd252738f1be0ac8f3f52507b7)
6  geolocator_apple               0x75a4 (Missing UUID 720753cd252738f1be0ac8f3f52507b7)
7  geolocator_apple               0x7024 (Missing UUID 720753cd252738f1be0ac8f3f52507b7)
8  Flutter                        0x55a33c (Missing UUID 1aed3005d544309887cd044022e3ec31)
9  Flutter                        0x424e8 (Missing UUID 1aed3005d544309887cd044022e3ec31)
10 libdispatch.dylib              0x2a84 _dispatch_call_block_and_release
11 libdispatch.dylib              0x481c _dispatch_client_callout
12 libdispatch.dylib              0x12c70 _dispatch_main_queue_callback_4CF
13 CoreFoundation                 0xa3398 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
14 CoreFoundation                 0x9d270 __CFRunLoopRun
15 CoreFoundation                 0x9c360 CFRunLoopRunSpecific
16 GraphicsServices               0x3734 GSEventRunModal
17 UIKitCore                      0xbca584 -[UIApplication _run]
18 UIKitCore                      0xbcfdf4 UIApplicationMain
19 Runner                         0x6b0c main + 5 (AppDelegate.swift:5)
20 libdyld.dylib                  0x1cf8 start
```

**Comment by AmanMasipeddi** [comment]
I am also getting this error.

**Comment by JianrongHui** [comment]
> ## 🐛 Bug Report
> I have a user whose app randomly crashes when location sharing is enabled, but when location is denied the application starts up fine.
> 
> ### Expected behavior
> Application should startup up even when location permissions are set to allowed.
> 
> ### Reproduction steps
> Not sure, I only have the crash logs.
> 
> ### Configuration
> **Version:** geolocator: 9.0.0
> 
> ** Trace **
> 
> ```
> Fatal Exception: NSInvalidArgumentException
> -[CLLocation sourceInformation]: unrecognized selector sent to instance 0x282ec5060
> 
> 
> Fatal Exception: NSInvalidArgumentException
> 0  CoreFoundation                 0x129754 __exceptionPreprocess
> 1  libobjc.A.dylib                0x287a8 objc_exception_throw
> 2  CoreFoundation                 0x2cc3c -[NSOrderedSet initWithSet:copyItems:]
> 3  CoreFoundation                 0x12c2ac ___forwarding___
> 4  CoreFoundation                 0x12e5b0 _CF_forwarding_prep_0
> 5  geolocator_apple               0x8218 (Missing UUID 720753cd252738f1be0ac8f3f52507b7)
> 6  geolocator_apple               0x75a4 (Missing UUID 720753cd252738f1be0ac8f3f52507b7)
> 7  geolocator_apple               0x7024 (Missing UUID 720753cd252738f1be0ac8f3f52507b7)
> 8  Flutter                        0x55a33c (Missing UUID 1aed3005d544309887cd044022e3ec31)
> 9  Flutter                        0x424e8 (Missing UUID 1aed3005d544309887cd044022e3ec31)
> 10 libdispatch.dylib              0x2a84 _dispatch_call_block_and_release
> 11 libdispatch.dylib              0x481c _dispatch_client_callout
> 12 libdispatch.dylib              0x12c70 _dispatch_main_queue_callback_4CF
> 13 CoreFoundation                 0xa3398 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
> 14 CoreFoundation                 0x9d270 __CFRunLoopRun
> 15 CoreFoundation                 0x9c360 CFRunLoopRunSpecific
> 16 GraphicsServices               0x3734 GSEventRunModal
> 17 UIKitCore                      0xbca584 -[UIApplication _run]
> 18 UIKitCore                      0xbcfdf4 UIApplicationMain
> 19 Runner                         0x6b0c main + 5 (AppDelegate.swift:5)
> 20 libdyld.dylib                  0x1cf8 start
> ```

The minimum supported iOS version of this API（[CLLocation sourceInformation]） is iOS15

**Comment by Wackymax** [comment]
Was a cocoa pod configuration issue on my side

**Comment by Abdelilahskali** [comment]
Hell all to resole this problem you can add  Background modes => Location update in Signing & Capabilities
![Screen Shot 2022-09-23 at 16 55 52](https://user-images.githubusercontent.com/6975959/192002745-0df21d84-7b08-4e23-b15e-8c05f0a96f09.png)
