### ISSUE TITLE
Can't catch PermissionDeniedException

### ISSUE THREAD

**Issue by dpedrinha** [Baseflow/flutter-geolocator#1094]
I'm trying to catch the PermissionDeniedException to `openAppSettings` if the user denies twice but I just can't catch it.

Here's my code:
```
          print('2');
          try {
            Geolocator.requestPermission();
          } on PermissionDeniedException catch (e) {
            print('3');
          }
```

The following code doesn't work either:
```
          Geolocator.requestPermission().catchError((e) async {
            print('3');
          });
```

It just doesn't work. It never catches it. In this code, '3' is never printed to the console. It's like `Geolocator.requestPermission()` is not being called even though '2' is being printed on the console.

I've tried using the generic `Exception` type and had the same result.

How can I know if I can't `requestPermission()` anymore and `openAppSettings` instead?

**Comment by mvanbeusekom** [comment]
Hi @dpedrinha,

The method `requestPermission` is not throwing a `PermissionDeniedException` but returns the permission the user selected. Even when permission has been denied earlier, the `requestPermission` will not throw an exception. Internally it will simply check the current permissions and if it is `deniedForever` it will not show a dialog and immediately return the current permission.

So you'd probably want to do something like this:

```dart
final LocationPermission permission = await Geolocator.requestPermission();

if (permission == LocationPermission.deniedForever) {
  // Offer the user the option to open App settings...
}
```

Or even better, the recommended approach is as follows:

```dart
bool serviceEnabled;
LocationPermission permission;

// Test if location services are enabled.
serviceEnabled = await Geolocator.isLocationServiceEnabled();
if (!serviceEnabled) {
  // Location services are not enabled don't continue
  // accessing the position and request users of the 
  // App to enable the location services.
  return;
}

permission = await Geolocator.checkPermission();
if (permission == LocationPermission.denied) {
  permission = await Geolocator.requestPermission();
  if (permission == LocationPermission.deniedForever) {
    // Permissions are denied forever, handle appropriately. 
    return;
  } 

  if (permission == LocationPermission.denied) {
    // Permissions are denied, next time you could try
    // requesting permissions again (this is also where
    // Android's shouldShowRequestPermissionRationale 
    // returned true. According to Android guidelines
    // your App should show an explanatory UI now.
    return;
  }
}

// When we reach here, permissions are granted and we can
// continue accessing the position of the device.
_position = await Geolocator.getCurrentPosition();
```

More detailed reasoning for this approach can be found on the [Wiki page](https://github.com/Baseflow/flutter-geolocator/wiki/Breaking-changes-in-7.0.0#android-permission-update).

**Comment by dpedrinha** [comment]
Oh right, now I got it.

I was using the recommended approach and I've read the wiki page, but then I was on a different flow on my app and I guess I got stuck trying to catch this error ever since I got it on the console. I was really tired. But now it all makes sence.

Thank you very much.
