### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method getCurrentPosition on channel flutter.baseflow.com/geolocator) 

### ISSUE THREAD

**Issue by dukenebur** [Baseflow/flutter-geolocator#1096]
## 🐛 Bug Report

Hi, hope you are doing well.

I am having this error:

Unhandled Exception: MissingPluginException(No implementation found for method getCurrentPosition on channel flutter.baseflow.com/geolocator) 

Dart SDK version is 2.13.1
geolocator: 8.0.5

Could you help me?

Kind Regards

**Comment by ricardoboss** [comment]
I'm having the same issue on web, but only in production builds. When debugging, it works fine.

**Comment by dehypnosis** [comment]
In my case it was due to `https://pub.dev/packages/permission_handler` library which throw same error message with above one when access to `Permission.locationWhenInUse.status` on web platform.
