### ISSUE TITLE
Geolocator.getCurrentPosition do not update position

### ISSUE THREAD

**Issue by jeanantoine** [Baseflow/flutter-geolocator#1099]
Hello,
I want to update the position with button tap (see code below)  but when I tap the button the position is not updated, it gets updated only when I switch to google Maps and go back to my app.
how can I get my app to update withou switching to google Maps ?

on Samsung S21 

```
Geolocator.getCurrentPosition(
            desiredAccuracy: LocationAccuracy.bestForNavigation,
            forceAndroidLocationManager: true)
        .then((Position position) {
      setState(() {
        _currentPosition = position;
        positions =
            "$positions\nLAT: ${_currentPosition?.latitude}, LNG: ${_currentPosition?.longitude}";
      });
    }).catchError((e) {
      print("$e");
    });
```

permissions in AndroidManifest.xml:
 ```
<uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
    <uses-permission android:name="android.hardware.location.gps" />
```

**Comment by jeanantoine** [comment]
this works for me:

```
final GeolocatorPlatform geolocatorAndroid = GeolocatorPlatform.instance;
final position = await geolocatorAndroid.getCurrentPosition(
        locationSettings: const LocationSettings(accuracy: LocationAccuracy.best));
```

**Comment by moustafamosalam** [comment]
Hello,
I have the same problem, can you just tell me how did you solve it please? @jeanantoine

**Comment by jeanantoine** [comment]
Hello,
I have solved this like described above, have you tried it ?:
`final GeolocatorPlatform geolocatorAndroid = GeolocatorPlatform.instance;
final position = await geolocatorAndroid.getCurrentPosition(
        locationSettings: const LocationSettings(accuracy: LocationAccuracy.best));`
 
permissions in AndroidManifest.xml:       
`<uses-permission android:name="android.permission.INTERNET" />
   <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
   <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
   <uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
   <uses-permission android:name="android.hardware.location.gps" />`

**Comment by moustafamosalam** [comment]
yes and unfortunately it didn't work :(

**Comment by prabavgts** [comment]
I also faced this problem, do you have any solution?
