### ISSUE TITLE
Spelling Mistake in the README on pub.dev

### ISSUE THREAD

**Issue by mdoroff** [Baseflow/flutter-geolocator#1110]
## 🐛 Bug Report

Under the Android instructions the following line is present:

_note that the geolocator plugin doesn't support receiving an processing location updates while running in the background_

I think that we mean to say, "doesn't support receiving **and** processing location update..." instead of using the word **an**.

Please see screenshot for more details.

<img width="834" alt="2022-07-27_12-53-22" src="https://user-images.githubusercontent.com/104392620/181339470-fc0b5fa4-f21e-4cec-8773-7fa473eeb98c.png">

**Comment by florissmit1** [comment]
Hey @mdoroff, thanks for reporting your issue. I guess you're right. You can make a PR yourself or I will do it for you, please let me know!

**Comment by mdoroff** [comment]
I see that the documentation was updated, but cannot find the associated PR.

Closing! Thank you.
