### ISSUE TITLE
Flutter build failing

### ISSUE THREAD

**Issue by TechInjectIndia** [Baseflow/flutter-geolocator#1118]
## 🐛 Bug Report

Cannot create flutter build after updating every thing in pubspec.

Error: 
> Task :geolocator_android:compileDebugJavaWithJavac FAILED
/Users/sumeet/.pub-cache/hosted/pub.dartlang.org/geolocator_android-4.0.2/android/src/main/java/com/baseflow/geolocator/location/BackgroundNotification.java:71: error: cannot find symbol
            notificationManager.createNotificationChannel(channel);

Flutter doctor:
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.1 21C52 darwin-x64, locale en-IN)
    • Flutter version 3.0.5 at /Users/sumeet/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (4 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/sumeet/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/sumeet/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[!] Android Studio
    • Android Studio at /Users/sumeet/Downloads/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.57.1)
    • VS Code at /Users/sumeet/tools/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[!] Connected device
    ! No devices available

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

publock:
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  async:
    dependency: transitive
    description:
      name: async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.8.2"
  boolean_selector:
    dependency: transitive
    description:
      name: boolean_selector
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  characters:
    dependency: transitive
    description:
      name: characters
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  charcode:
    dependency: transitive
    description:
      name: charcode
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.1"
  clock:
    dependency: transitive
    description:
      name: clock
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  cloud_firestore:
    dependency: "direct main"
    description:
      name: cloud_firestore
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.4.3"
  cloud_firestore_platform_interface:
    dependency: transitive
    description:
      name: cloud_firestore_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.7.0"
  cloud_firestore_web:
    dependency: transitive
    description:
      name: cloud_firestore_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.8.3"
  collection:
    dependency: transitive
    description:
      name: collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.16.0"
  crypto:
    dependency: transitive
    description:
      name: crypto
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.2"
  cupertino_icons:
    dependency: "direct main"
    description:
      name: cupertino_icons
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.5"
  fake_async:
    dependency: transitive
    description:
      name: fake_async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.0"
  ffi:
    dependency: transitive
    description:
      name: ffi
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
  file:
    dependency: transitive
    description:
      name: file
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.1.2"
  firebase_auth:
    dependency: "direct main"
    description:
      name: firebase_auth
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.6.2"
  firebase_auth_platform_interface:
    dependency: transitive
    description:
      name: firebase_auth_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.5.2"
  firebase_auth_web:
    dependency: transitive
    description:
      name: firebase_auth_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.2.2"
  firebase_core:
    dependency: "direct main"
    description:
      name: firebase_core
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.20.0"
  firebase_core_platform_interface:
    dependency: transitive
    description:
      name: firebase_core_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.5.0"
  firebase_core_web:
    dependency: transitive
    description:
      name: firebase_core_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.7.1"
  firebase_crashlytics:
    dependency: "direct main"
    description:
      name: firebase_crashlytics
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.8.6"
  firebase_crashlytics_platform_interface:
    dependency: transitive
    description:
      name: firebase_crashlytics_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.2.12"
  firebase_messaging:
    dependency: "direct main"
    description:
      name: firebase_messaging
      url: "https://pub.dartlang.org"
    source: hosted
    version: "12.0.1"
  firebase_messaging_platform_interface:
    dependency: transitive
    description:
      name: firebase_messaging_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.1.0"
  firebase_messaging_web:
    dependency: transitive
    description:
      name: firebase_messaging_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.0"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_google_places_hoc081098:
    dependency: "direct main"
    description:
      name: flutter_google_places_hoc081098
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  flutter_lints:
    dependency: transitive
    description:
      name: flutter_lints
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.4"
  flutter_plugin_android_lifecycle:
    dependency: transitive
    description:
      name: flutter_plugin_android_lifecycle
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.7"
  flutter_spinkit:
    dependency: "direct main"
    description:
      name: flutter_spinkit
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.1.0"
  flutter_test:
    dependency: "direct dev"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_web_plugins:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.0"
  geocoder2:
    dependency: "direct main"
    description:
      name: geocoder2
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.0"
  geocoding:
    dependency: "direct main"
    description:
      name: geocoding
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.4"
  geocoding_platform_interface:
    dependency: transitive
    description:
      name: geocoding_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
  geoflutterfire:
    dependency: "direct main"
    description:
      name: geoflutterfire
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.3"
  geolocator:
    dependency: "direct main"
    description:
      name: geolocator
      url: "https://pub.dartlang.org"
    source: hosted
    version: "9.0.1"
  geolocator_android:
    dependency: transitive
    description:
      name: geolocator_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.0.2"
  geolocator_apple:
    dependency: transitive
    description:
      name: geolocator_apple
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.1"
  geolocator_platform_interface:
    dependency: transitive
    description:
      name: geolocator_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.0.6"
  geolocator_web:
    dependency: transitive
    description:
      name: geolocator_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.6"
  geolocator_windows:
    dependency: transitive
    description:
      name: geolocator_windows
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.1"
  get_it:
    dependency: "direct main"
    description:
      name: get_it
      url: "https://pub.dartlang.org"
    source: hosted
    version: "7.2.0"
  google_api_headers:
    dependency: transitive
    description:
      name: google_api_headers
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.0"
  google_maps_flutter:
    dependency: "direct main"
    description:
      name: google_maps_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.10"
  google_maps_flutter_platform_interface:
    dependency: transitive
    description:
      name: google_maps_flutter_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.1"
  google_maps_webservice:
    dependency: "direct main"
    description:
      name: google_maps_webservice
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.0.20-nullsafety.5"
  http:
    dependency: "direct main"
    description:
      name: http
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.13.5"
  http_parser:
    dependency: transitive
    description:
      name: http_parser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.0.1"
  intl:
    dependency: transitive
    description:
      name: intl
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.17.0"
  js:
    dependency: transitive
    description:
      name: js
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.4"
  json_annotation:
    dependency: transitive
    description:
      name: json_annotation
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.6.0"
  lints:
    dependency: transitive
    description:
      name: lints
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1"
  listenable_stream:
    dependency: transitive
    description:
      name: listenable_stream
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  location:
    dependency: "direct main"
    description:
      name: location
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.4.0"
  location_platform_interface:
    dependency: transitive
    description:
      name: location_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.3.0"
  location_web:
    dependency: transitive
    description:
      name: location_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.1"
  matcher:
    dependency: transitive
    description:
      name: matcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.11"
  material_color_utilities:
    dependency: transitive
    description:
      name: material_color_utilities
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.4"
  meta:
    dependency: transitive
    description:
      name: meta
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.7.0"
  modal_bottom_sheet:
    dependency: "direct main"
    description:
      name: modal_bottom_sheet
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  nested:
    dependency: transitive
    description:
      name: nested
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
  package_info_plus:
    dependency: transitive
    description:
      name: package_info_plus
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.4.3"
  package_info_plus_linux:
    dependency: transitive
    description:
      name: package_info_plus_linux
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.5"
  package_info_plus_macos:
    dependency: transitive
    description:
      name: package_info_plus_macos
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.0"
  package_info_plus_platform_interface:
    dependency: transitive
    description:
      name: package_info_plus_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2"
  package_info_plus_web:
    dependency: transitive
    description:
      name: package_info_plus_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.5"
  package_info_plus_windows:
    dependency: transitive
    description:
      name: package_info_plus_windows
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  path:
    dependency: transitive
    description:
      name: path
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.8.1"
  path_provider_linux:
    dependency: transitive
    description:
      name: path_provider_linux
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.7"
  path_provider_platform_interface:
    dependency: transitive
    description:
      name: path_provider_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.4"
  path_provider_windows:
    dependency: transitive
    description:
      name: path_provider_windows
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.1"
  percent_indicator:
    dependency: "direct main"
    description:
      name: percent_indicator
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.2.2"
  platform:
    dependency: transitive
    description:
      name: platform
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.0"
  plugin_platform_interface:
    dependency: transitive
    description:
      name: plugin_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.2"
  process:
    dependency: transitive
    description:
      name: process
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.2.4"
  provider:
    dependency: "direct main"
    description:
      name: provider
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.0.3"
  rxdart:
    dependency: "direct main"
    description:
      name: rxdart
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.27.5"
  rxdart_ext:
    dependency: transitive
    description:
      name: rxdart_ext
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.5"
  shared_preferences:
    dependency: "direct main"
    description:
      name: shared_preferences
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.15"
  shared_preferences_android:
    dependency: transitive
    description:
      name: shared_preferences_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.12"
  shared_preferences_ios:
    dependency: transitive
    description:
      name: shared_preferences_ios
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.1"
  shared_preferences_linux:
    dependency: transitive
    description:
      name: shared_preferences_linux
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.1"
  shared_preferences_macos:
    dependency: transitive
    description:
      name: shared_preferences_macos
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.4"
  shared_preferences_platform_interface:
    dependency: transitive
    description:
      name: shared_preferences_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  shared_preferences_web:
    dependency: transitive
    description:
      name: shared_preferences_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.4"
  shared_preferences_windows:
    dependency: transitive
    description:
      name: shared_preferences_windows
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.1"
  sky_engine:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.99"
  source_span:
    dependency: transitive
    description:
      name: source_span
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.8.2"
  stack_trace:
    dependency: transitive
    description:
      name: stack_trace
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.10.0"
  stream_channel:
    dependency: transitive
    description:
      name: stream_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  stream_transform:
    dependency: transitive
    description:
      name: stream_transform
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  test_api:
    dependency: transitive
    description:
      name: test_api
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.9"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.1"
  url_launcher:
    dependency: "direct main"
    description:
      name: url_launcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.1.5"
  url_launcher_android:
    dependency: transitive
    description:
      name: url_launcher_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.0.17"
  url_launcher_ios:
    dependency: transitive
    description:
      name: url_launcher_ios
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.0.17"
  url_launcher_linux:
    dependency: transitive
    description:
      name: url_launcher_linux
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.1"
  url_launcher_macos:
    dependency: transitive
    description:
      name: url_launcher_macos
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.1"
  url_launcher_platform_interface:
    dependency: transitive
    description:
      name: url_launcher_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  url_launcher_web:
    dependency: transitive
    description:
      name: url_launcher_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.12"
  url_launcher_windows:
    dependency: transitive
    description:
      name: url_launcher_windows
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.1"
  uuid:
    dependency: "direct main"
    description:
      name: uuid
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.6"
  vector_math:
    dependency: transitive
    description:
      name: vector_math
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.2"
  win32:
    dependency: transitive
    description:
      name: win32
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.7.0"
  xdg_directories:
    dependency: transitive
    description:
      name: xdg_directories
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.0+1"
sdks:
  dart: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"
  
   flutter pub deps
Dart SDK 2.17.6
Flutter SDK 3.0.5
txapita 1.0.0+1
|-- cloud_firestore 3.4.3
|   |-- cloud_firestore_platform_interface 5.7.0
|   |   |-- collection...
|   |   |-- firebase_core...
|   |   |-- flutter...
|   |   |-- meta...
|   |   '-- plugin_platform_interface 2.1.2
|   |       '-- meta...
|   |-- cloud_firestore_web 2.8.3
|   |   |-- cloud_firestore_platform_interface...
|   |   |-- collection...
|   |   |-- firebase_core...
|   |   |-- firebase_core_web...
|   |   |-- flutter...
|   |   |-- flutter_web_plugins 0.0.0
|   |   |   |-- characters...
|   |   |   |-- collection...
|   |   |   |-- flutter...
|   |   |   |-- js...
|   |   |   |-- material_color_utilities...
|   |   |   |-- meta...
|   |   |   '-- vector_math...
|   |   '-- js 0.6.4
|   |-- collection...
|   |-- firebase_core...
|   |-- firebase_core_platform_interface 4.5.0
|   |   |-- collection...
|   |   |-- flutter...
|   |   |-- flutter_test...
|   |   |-- meta...
|   |   '-- plugin_platform_interface...
|   |-- flutter...
|   '-- meta...
|-- cupertino_icons 1.0.5
|-- firebase_auth 3.6.2
|   |-- firebase_auth_platform_interface 6.5.2
|   |   |-- collection...
|   |   |-- firebase_core...
|   |   |-- flutter...
|   |   |-- meta...
|   |   '-- plugin_platform_interface...
|   |-- firebase_auth_web 4.2.2
|   |   |-- firebase_auth_platform_interface...
|   |   |-- firebase_core...
|   |   |-- firebase_core_web...
|   |   |-- flutter...
|   |   |-- flutter_web_plugins...
|   |   |-- http_parser...
|   |   |-- intl 0.17.0
|   |   |   |-- clock...
|   |   |   '-- path...
|   |   |-- js...
|   |   '-- meta...
|   |-- firebase_core...
|   |-- firebase_core_platform_interface...
|   |-- flutter...
|   '-- meta...
|-- firebase_core 1.20.0
|   |-- firebase_core_platform_interface...
|   |-- firebase_core_web 1.7.1
|   |   |-- firebase_core_platform_interface...
|   |   |-- flutter...
|   |   |-- flutter_web_plugins...
|   |   |-- js...
|   |   '-- meta...
|   |-- flutter...
|   '-- meta...
|-- firebase_crashlytics 2.8.6
|   |-- firebase_core...
|   |-- firebase_core_platform_interface...
|   |-- firebase_crashlytics_platform_interface 3.2.12
|   |   |-- collection...
|   |   |-- firebase_core...
|   |   |-- flutter...
|   |   |-- meta...
|   |   '-- plugin_platform_interface...
|   |-- flutter...
|   '-- stack_trace 1.10.0
|       '-- path...
|-- firebase_messaging 12.0.1
|   |-- firebase_core...
|   |-- firebase_core_platform_interface...
|   |-- firebase_messaging_platform_interface 4.1.0
|   |   |-- firebase_core...
|   |   |-- flutter...
|   |   |-- meta...
|   |   '-- plugin_platform_interface...
|   |-- firebase_messaging_web 3.1.0
|   |   |-- firebase_core...
|   |   |-- firebase_core_web...
|   |   |-- firebase_messaging_platform_interface...
|   |   |-- flutter...
|   |   |-- flutter_web_plugins...
|   |   |-- js...
|   |   '-- meta...
|   |-- flutter...
|   '-- meta...
|-- flutter 0.0.0
|   |-- characters 1.2.0
|   |-- collection 1.16.0
|   |-- material_color_utilities 0.1.4
|   |-- meta 1.7.0
|   |-- sky_engine 0.0.99
|   '-- vector_math 2.1.2
|-- flutter_google_places_hoc081098 1.1.0
|   |-- collection...
|   |-- flutter...
|   |-- google_api_headers 1.3.0
|   |   |-- flutter...
|   |   '-- package_info_plus 1.4.3
|   |       |-- flutter...
|   |       |-- package_info_plus_linux 1.0.5
|   |       |   |-- flutter...
|   |       |   |-- package_info_plus_platform_interface...
|   |       |   '-- path...
|   |       |-- package_info_plus_macos 1.3.0
|   |       |   '-- flutter...
|   |       |-- package_info_plus_platform_interface 1.0.2
|   |       |   |-- flutter...
|   |       |   |-- meta...
|   |       |   '-- plugin_platform_interface...
|   |       |-- package_info_plus_web 1.0.5
|   |       |   |-- flutter...
|   |       |   |-- flutter_web_plugins...
|   |       |   |-- http...
|   |       |   |-- meta...
|   |       |   '-- package_info_plus_platform_interface...
|   |       '-- package_info_plus_windows 2.0.0
|   |           |-- ffi...
|   |           |-- flutter...
|   |           |-- package_info_plus_platform_interface...
|   |           '-- win32...
|   |-- google_maps_webservice...
|   |-- http...
|   |-- listenable_stream 1.1.0
|   |   |-- flutter...
|   |   '-- rxdart...
|   |-- rxdart...
|   '-- rxdart_ext 0.2.5
|       |-- meta...
|       |-- path...
|       |-- rxdart...
|       '-- stack_trace...
|-- flutter_spinkit 5.1.0
|   '-- flutter...
|-- flutter_test 0.0.0
|   |-- async...
|   |-- boolean_selector 2.1.0
|   |   |-- source_span...
|   |   '-- string_scanner...
|   |-- characters...
|   |-- charcode 1.3.1
|   |-- clock 1.1.0
|   |-- collection...
|   |-- fake_async 1.3.0
|   |   |-- clock...
|   |   '-- collection...
|   |-- flutter...
|   |-- matcher 0.12.11
|   |   '-- stack_trace...
|   |-- material_color_utilities...
|   |-- meta...
|   |-- path...
|   |-- source_span 1.8.2
|   |   |-- collection...
|   |   |-- path...
|   |   '-- term_glyph...
|   |-- stack_trace...
|   |-- stream_channel 2.1.0
|   |   '-- async...
|   |-- string_scanner 1.1.0
|   |   |-- charcode...
|   |   '-- source_span...
|   |-- term_glyph 1.2.0
|   |-- test_api 0.4.9
|   |   |-- async...
|   |   |-- boolean_selector...
|   |   |-- collection...
|   |   |-- matcher...
|   |   |-- meta...
|   |   |-- source_span...
|   |   |-- stack_trace...
|   |   |-- stream_channel...
|   |   |-- string_scanner...
|   |   '-- term_glyph...
|   '-- vector_math...
|-- geocoder2 1.3.0
|   |-- flutter...
|   '-- http...
|-- geocoding 2.0.4
|   |-- flutter...
|   '-- geocoding_platform_interface 2.0.1
|       |-- flutter...
|       |-- meta...
|       '-- plugin_platform_interface...
|-- geoflutterfire 3.0.3
|   |-- cloud_firestore...
|   |-- flutter...
|   |-- flutter_lints 1.0.4
|   |   '-- lints 1.0.1
|   '-- rxdart...
|-- geolocator 9.0.1
|   |-- flutter...
|   |-- geolocator_android 4.0.2
|   |   |-- flutter...
|   |   '-- geolocator_platform_interface...
|   |-- geolocator_apple 2.2.1
|   |   |-- flutter...
|   |   '-- geolocator_platform_interface...
|   |-- geolocator_platform_interface 4.0.6
|   |   |-- flutter...
|   |   |-- meta...
|   |   |-- plugin_platform_interface...
|   |   '-- vector_math...
|   |-- geolocator_web 2.1.6
|   |   |-- flutter...
|   |   |-- flutter_web_plugins...
|   |   '-- geolocator_platform_interface...
|   '-- geolocator_windows 0.1.1
|       |-- flutter...
|       '-- geolocator_platform_interface...
|-- get_it 7.2.0
|   |-- async...
|   '-- collection...
|-- google_maps_flutter 2.1.10
|   |-- flutter...
|   |-- flutter_plugin_android_lifecycle 2.0.7
|   |   '-- flutter...
|   '-- google_maps_flutter_platform_interface 2.2.1
|       |-- collection...
|       |-- flutter...
|       |-- plugin_platform_interface...
|       '-- stream_transform 2.0.0
|-- google_maps_webservice 0.0.20-nullsafety.5
|   |-- http...
|   |-- json_annotation 4.6.0
|   |   '-- meta...
|   '-- meta...
|-- http 0.13.5
|   |-- async 2.8.2
|   |   |-- collection...
|   |   '-- meta...
|   |-- http_parser 4.0.1
|   |   |-- collection...
|   |   |-- source_span...
|   |   |-- string_scanner...
|   |   '-- typed_data 1.3.1
|   |       '-- collection...
|   |-- meta...
|   '-- path 1.8.1
|-- location 4.4.0
|   |-- flutter...
|   |-- location_platform_interface 2.3.0
|   |   |-- flutter...
|   |   |-- meta...
|   |   '-- plugin_platform_interface...
|   '-- location_web 3.1.1
|       |-- flutter...
|       |-- flutter_web_plugins...
|       |-- http_parser...
|       |-- js...
|       |-- location_platform_interface...
|       '-- meta...
|-- modal_bottom_sheet 2.1.0
|   '-- flutter...
|-- percent_indicator 4.2.2
|   '-- flutter...
|-- provider 6.0.3
|   |-- collection...
|   |-- flutter...
|   '-- nested 1.0.0
|       '-- flutter...
|-- rxdart 0.27.5
|-- shared_preferences 2.0.15
|   |-- flutter...
|   |-- shared_preferences_android 2.0.12
|   |   |-- flutter...
|   |   '-- shared_preferences_platform_interface...
|   |-- shared_preferences_ios 2.1.1
|   |   |-- flutter...
|   |   '-- shared_preferences_platform_interface...
|   |-- shared_preferences_linux 2.1.1
|   |   |-- file 6.1.2
|   |   |   |-- meta...
|   |   |   '-- path...
|   |   |-- flutter...
|   |   |-- path...
|   |   |-- path_provider_linux 2.1.7
|   |   |   |-- ffi 2.0.1
|   |   |   |-- flutter...
|   |   |   |-- path...
|   |   |   |-- path_provider_platform_interface...
|   |   |   '-- xdg_directories 0.2.0+1
|   |   |       |-- meta...
|   |   |       |-- path...
|   |   |       '-- process 4.2.4
|   |   |           |-- file...
|   |   |           |-- path...
|   |   |           '-- platform...
|   |   |-- path_provider_platform_interface 2.0.4
|   |   |   |-- flutter...
|   |   |   |-- platform 3.1.0
|   |   |   '-- plugin_platform_interface...
|   |   '-- shared_preferences_platform_interface...
|   |-- shared_preferences_macos 2.0.4
|   |   |-- flutter...
|   |   '-- shared_preferences_platform_interface...
|   |-- shared_preferences_platform_interface 2.0.0
|   |   '-- flutter...
|   |-- shared_preferences_web 2.0.4
|   |   |-- flutter...
|   |   |-- flutter_web_plugins...
|   |   '-- shared_preferences_platform_interface...
|   '-- shared_preferences_windows 2.1.1
|       |-- file...
|       |-- flutter...
|       |-- path...
|       |-- path_provider_platform_interface...
|       |-- path_provider_windows 2.1.1
|       |   |-- ffi...
|       |   |-- flutter...
|       |   |-- path...
|       |   |-- path_provider_platform_interface...
|       |   '-- win32 2.7.0
|       |       '-- ffi...
|       '-- shared_preferences_platform_interface...
|-- url_launcher 6.1.5
|   |-- flutter...
|   |-- url_launcher_android 6.0.17
|   |   |-- flutter...
|   |   '-- url_launcher_platform_interface...
|   |-- url_launcher_ios 6.0.17
|   |   |-- flutter...
|   |   '-- url_launcher_platform_interface...
|   |-- url_launcher_linux 3.0.1
|   |   |-- flutter...
|   |   '-- url_launcher_platform_interface...
|   |-- url_launcher_macos 3.0.1
|   |   |-- flutter...
|   |   '-- url_launcher_platform_interface...
|   |-- url_launcher_platform_interface 2.1.0
|   |   |-- flutter...
|   |   '-- plugin_platform_interface...
|   |-- url_launcher_web 2.0.12
|   |   |-- flutter...
|   |   |-- flutter_web_plugins...
|   |   '-- url_launcher_platform_interface...
|   '-- url_launcher_windows 3.0.1
|       |-- flutter...
|       '-- url_launcher_platform_interface...
'-- uuid 3.0.6
    '-- crypto 3.0.2
        '-- typed_data...

Pubspec:
<img width="471" alt="Screenshot 2022-08-09 at 6 18 27 PM" src="https://user-images.githubusercontent.com/55683378/183650828-ffed8275-d254-463d-a364-52339f6fd292.png">

Build.gradle Android:
<img width="783" alt="Screenshot 2022-08-09 at 6 11 24 PM" src="https://user-images.githubusercontent.com/55683378/183649476-a83175c5-3c1b-41d7-93bb-5701db96336d.png">

Build.gradle :
<img width="623" alt="Screenshot 2022-08-09 at 6 11 58 PM" src="https://user-images.githubusercontent.com/55683378/183649622-0c24750f-ebfd-445a-82d6-68d34fd5d9cd.png">

**Comment by Wackymax** [comment]
This should be resolved with the latest release.

**Comment by TimHoogstrate** [comment]
Dear @TechInjectIndia,
Can you confirm that this is working? It looks like it has been fixed.
