### ISSUE TITLE
9.0.1 deprecation in android build with sdk 33 

### ISSUE THREAD

**Issue by heshesh2010** [Baseflow/flutter-geolocator#1124]
> Task :geolocator_android:compileDebugJavaWithJavac FAILED
/Users/hesham/.pub-cache/hosted/pub.dartlang.org/geolocator_android-4.0.2/android/src/main/java/com/baseflow/geolocator/location/FusedLocationClient.java:199: warning: [deprecation] LocationRequest() in LocationRequest has been deprecated
    LocationRequest locationRequest = new LocationRequest();
                                      ^
/Users/hesham/.pub-cache/hosted/pub.dartlang.org/geolocator_android-4.0.2/android/src/main/java/com/baseflow/geolocator/location/FusedLocationClient.java:222: warning: [deprecation] PRIORITY_NO_POWER in LocationRequest has been deprecated
        return LocationRequest.PRIORITY_NO_POWER;
                              ^
/Users/hesham/.pub-cache/hosted/pub.dartlang.org/geolocator_android-4.0.2/android/src/main/java/com/baseflow/geolocator/location/FusedLocationClient.java:224: warning: [deprecation] PRIORITY_LOW_POWER in LocationRequest has been deprecated
        return LocationRequest.PRIORITY_LOW_POWER;
                              ^
/Users/hesham/.pub-cache/hosted/pub.dartlang.org/geolocator_android-4.0.2/android/src/main/java/com/baseflow/geolocator/location/FusedLocationClient.java:226: warning: [deprecation] PRIORITY_BALANCED_POWER_ACCURACY in LocationRequest has been deprecated
        return LocationRequest.PRIORITY_BALANCED_POWER_ACCURACY;
                              ^
/Users/hesham/.pub-cache/hosted/pub.dartlang.org/geolocator_android-4.0.2/android/src/main/java/com/baseflow/geolocator/location/FusedLocationClient.java:228: warning: [deprecation] PRIORITY_HIGH_ACCURACY in LocationRequest has been deprecated
        return LocationRequest.PRIORITY_HIGH_ACCURACY;
                              ^
error: warnings found and -Werror specified
1 error
5 warnings

warnings found and -Werror specified

**Comment by xellDart** [comment]
Same error

**Comment by stephancj** [comment]
I got the same error. The only solution I found is downgrading compileSdk to 32, which is not suitable for my project since are starting to user Android 13

**Comment by Wackymax** [comment]
The issue is most likely because of the "-Werror" flag that is specified in the build.gradle for the Android plugin. I am not sure if you can override this?

**Comment by mvanbeusekom** [comment]
Version 4.1.1 of the `geolocator_android` package has just been released removing the `-Werror` from the package `build.gradle` file which should no longer enforce this instruction onto app developers. 

In the meantime we will also work on another update to fix the actual deprecation warning and make sure the root cause of this problem is also fixed.
