### ISSUE TITLE
GetCurrentPosition doesn't return a location on PDA android devices

### ISSUE THREAD

**Issue by ebrahimmansur** [Baseflow/flutter-geolocator#1125]
## 🐛 Bug Report

the get current position doesn't return a location 
I tried to test it by placing a try catch and a  break point when calling  [  Geolocator.getCurrentPosition()] but never got a return value or a expectation thrown.

package version -> ^9.0.0

android device -> 
https://www.senter-e.com/pda/5-7inch-pda/pda-android.html
android api 28

**Comment by benyameenashraf** [comment]
I'm facing the same issue on android using geolocator 9.0.1

**Comment by JeroenWeener** [comment]
Hi @ebrahimmansur, @benyameenashraf!

We just fixed an issue on Android today that involves the `LocationManager`. I am assuming your device does not have access to the Google Play Services, which means it needs to use this manager. Can you upgrade to the latest version of the geolocator plugin (10.0.1) and run `dart pub upgrade`? You should see `geolocator_android` with version `4.2.3` in your `pubspec.lock` file.

Please let me know if this resolves your issue.
