### ISSUE TITLE
Locale Identifier Not Working

### ISSUE THREAD

**Issue by alfredoptarigan** [Baseflow/flutter-geolocator#1126]
## 🐛 Bug Report

Locale identifier id_ID not working but sometime working. I don't know it's bug or not. But i'm pretty sure that my configuration are correctly.

![image](https://user-images.githubusercontent.com/62396803/186869586-ac3fd5f1-99aa-4c97-8544-c4965de100b9.png)

**Comment by mvanbeusekom** [comment]
Hi @alfredoptarigan,

I am assuming you want to use the locale for Indonesia. In Java (Android) the correct identifier for Indonesia is `in_ID` as Java still implements the older ISO 639 standard and never updated to ISO 3166.

P.S. this is not an issue for the Geolocator but the [Geocoding](https://github.com/baseflow/flutter-geocoding) plugin.
