### ISSUE TITLE
No implementation found for method isLocationServiceEnabled on channel flutter.baseflow.com/geolocator

### ISSUE THREAD

**Issue by Marco410** [Baseflow/flutter-geolocator#1129]
## 🐛 Bug Report

MissingPluginException (MissingPluginException(No implementation found for method isLocationServiceEnabled on channel flutter.baseflow.com/geolocator))

### Expected behavior
I only need if the user activate their GPS

### Reproduction steps
It´s when i try to access to this function
final isEnable = await Geolocator.isLocationServiceEnabled();

### Configuration
Here is my flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.4 21F79 darwin-arm, locale en-MX)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.71.1)
[✓] Connected device (3 available)

• No issues found!

**Version:** 8.0.5

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by Igormikheev** [comment]
same issue

**Comment by Shen-Zen** [comment]
same

**Comment by DmitrySikorsky** [comment]
I can confirm that it doesn't work on macOS Monterey.

**Comment by DmitrySikorsky** [comment]
Hm, but if I manually add 'geolocator_apple' package to pubspec.yaml, I can call `Geolocator.isLocationServiceEnabled()` and even `Geolocator.requestPermission()` on macOS.

**Comment by DmitrySikorsky** [comment]
So, I allowed location, checked in the privacy and security settings that the app has location permissions, also the `await Geolocator.checkPermission()` returns 'always', but when I call the `await Geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.high)` I receive 'user denied permissions to access the device's location' exception on macOS.

**Comment by limonadev** [comment]
This is also happening on Flutter web, release mode
