### ISSUE TITLE
Location stream if the app is kill

### ISSUE THREAD

**Issue by michaelnabil230** [Baseflow/flutter-geolocator#1134]
## 🚀 Feature Requests

We need some modifications to the package to support this feature because it is definitely useful for some people.

### Platforms affected (mark all that apply)

- [x] :iphone: iOS
- [x] :robot: Android

**Comment by michaelnabil230** [comment]
In Apple's system, there is a action called 'startMonitoring' and it works when the user moves every 500 meters only, and I think so is for Apple's privacy policy.

**Comment by michaelnabil230** [comment]
In the Android system, it supports this thing easily, but we need someone who is capable in that to add it to the hood without raising anything.

**Comment by michaelnabil230** [comment]
I'm not a swift programmer but I've been a bit researched and I've decided to write this simple code to fetch the current site if the app is permanently locked from the background.

I send a request on API mocking so I can check whether it works or not and I see that it is working well.

But sometimes when you install the application for the first time, you are not asked to take the site in the background, I think this is related to the code and there is a solution if we search well.

Can see my result in my repo on GitHub (https://github.com/michaelnabil230/background-location)

**Comment by michaelnabil230** [comment]
When you lock the simulator and run, you will see that message to allow the application to run in the background and send your location.
<img width="405" alt="Screen Shot 2022-10-18 at 6 08 05 PM" src="https://user-images.githubusercontent.com/46572405/196484623-10ce9f54-011a-4b23-9be9-0834830ef20a.png">

**Comment by michaelnabil230** [comment]
When you change it to always allow, everything will work well

**Comment by TimHoogstrate** [comment]
Dear @michaelnabil230 ,

It seems that this issue has been resolved. Therefore I close this issue. Feel free to reopen the issue if you have some additional information.

Kind regards,
