### ISSUE TITLE
Unable to get latitude and longitude

### ISSUE THREAD

**Issue by wahyu-handayani** [Baseflow/flutter-geolocator#1135]
Hi I am using ios simulator 15.5 and running this code:
```
Position posisiNow = await Geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.high);
```
when I try to print ```posisiNow.latitude```, I always get ```NoSuchMethodError: The getter 'latitude' was called on null.``` while... when I print: ```print(posisiNow)``` I get ```Latitude: 37.33233141, Longitude: -122.0312186```. That's only happen in ios simulator, when I try it in android it works fine. I have tried to get latitude and longitude by using ```_geolocatorPlatform.getPositionStream()``` and get the same result.. I get null when printing```posisiNow.latitude``` but getting ```Latitude: 37.33233141, Longitude: -122.0312186``` when only print ```posisiNow```

**Revised for:**
I get null when printing```posisiNow.latitude``` but getting ```Latitude: 37.33233141, Longitude: -122.0312186``` when only print ```posisiNow```

**into:**
I get ```NoSuchMethodError: The getter 'latitude' was called on null.``` when printing```posisiNow.latitude``` but getting ```Latitude: 37.33233141, Longitude: -122.0312186``` when only print ```posisiNow```

**Comment by mvanbeusekom** [comment]
Hi @wahyu-handayani,

I have tested this using the geolocator example app on iOS 15.5 simulator and cannot reproduce this error. I have also been over the code base of the plugin but came to the conclusion the returned position cannot be `null` (if so you should see a whole bunch of `ArgumentError`s). This code is working perfectly fine for me:

```dart
  Future<void> _getCurrentPosition() async {
    final hasPermission = await _handlePermission();

    if (!hasPermission) {
      return;
    }

    final position = await _geolocatorPlatform.getCurrentPosition();
    print(
      'Latitude: ${position.latitude}, Longitude: ${position.longitude}',
    );
  }
```

Based on the description this feels like a small mistake in the code used to call the geolocator plugin. Could you provide a more detailed code sample? This might help finding the problem, the one line provided doesn't give a lot of context to help locate the problem. In addition the output of `flutter doctor -v` might also help.

**Comment by wahyu-handayani** [comment]
@mvanbeusekom Hi I think I make a mistake for my question and revise it just now. For additional at some time my app often crash and get sudden close, I have been checking my info.plist and have been adding this configuration:
```
<key>NSLocationWhenInUseUsageDescription</key>
<string>This app needs access to location when open.</string>
<key>NSLocationAlwaysUsageDescription</key>
<string>This app needs access to location when in the background.</string>
<key>EnableBackgroundLocationUpdates</key>
<true/>
```
I believe that there is something wrong with my ios configuration and this case is the same case like
https://stackoverflow.com/questions/64962353/flutter-app-crashes-when-requesting-location-on-ios

**Comment by mvanbeusekom** [comment]
Can you provide a small example application demonstrating the same behaviour? As mentioned the problem doesn't occur using the example application making it really difficult to help out. Please also include the output of the `flutter doctor -v` command.

**Comment by wahyu-handayani** [comment]
@mvanbeusekom Hi, I am so sorry to take very long time to reply, I will upload it today

**Comment by wahyu-handayani** [comment]
https://user-images.githubusercontent.com/55479207/192185751-008d11ef-def4-4f17-a0fe-c86da63e7eb1.mov

Hi @mvanbeusekom this is short capture while the app is forced to close after I open the maps page

**Comment by wahyu-handayani** [comment]
Here is ```flutter doctor -v```
```
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.5.1 21G83 darwin-x64, locale
    en-ID)
    • Flutter version 3.3.1 on channel stable at /Users/mine/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (3 weeks ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mine/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = /Users/mine/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • iPhone 13 Pro Max (mobile) • 7CA6DFCF-80DA-44AB-979B-05B7889C1BCA • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
