### ISSUE TITLE
`Geolocator.checkPermission()` returns `denied` status both for `denied` and `deniedForever` on Android devices

### ISSUE THREAD

**Issue by mathrocco** [Baseflow/flutter-geolocator#1137]
### Expected behavior

When user permanently denied location permission, `Geolocator.checkPermission()` method should return `LocationPermission.deniedForever` status instead of `LocationPermission.denied`.

This works as expected for iOS devices.

### Reproduction steps

1. Runs `Geolocator.requestPermission()` on Android app
2. Permanently deny location permission
3. Runs `Geolocator.checkPermission()`
4. It returns `denied` status

### Configuration

**Version:** 9.0.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @mathrocco,

Unfortunately the Android SDK doesn't support this. This is explained into more detail in [this comment](https://github.com/Baseflow/flutter-geolocator/issues/1087#issuecomment-1163479678) for issue #1087. 

Also have a look at our [Wiki](https://github.com/Baseflow/flutter-geolocator/wiki/Breaking-changes-in-7.0.0) page.

**Comment by mathrocco** [comment]
@mvanbeusekom thanks for the quick reply, I wan't able to find the linked issue.
