### ISSUE TITLE
Revoking permission while listening to stream

### ISSUE THREAD

**Issue by i-dentify** [Baseflow/flutter-geolocator#1144]
Hi!

I wonder what happens, if my app starts listening to the position stream and then the user retracts the permission from app settings.

To be more concrete:

1. My app asks the user for permission to access location services
2. User allows this
3. My app starts listening to the position stream
4. User switches to the device app settings and revokes the permission there

Is there any chance to listen to such an event? I'd like to react on such an event to let my app ask for permission again.

**Comment by YannickMaljaars** [comment]
Hi @i-dentify,

I believe this would not be possible, since android kills all app processes if you revoke a permission while the app is running. This means the app will restart and therefore it will not be possible to listen for such an event.

**Comment by i-dentify** [comment]
Hi @YannickMaljaars 

thanks for explanation. At least this explains, why I constantly loose connection to the emulator in such a case. For iOS emulator this indeed is not the case - the app kept on running there but then threw exceptions.

**Comment by JeroenWeener** [comment]
Hi @i-dentify!

I am closing this issue, as it seems that your question was answered by @YannickMaljaars.
