### ISSUE TITLE
Incorrect speed in Android using getPositionStream 

### ISSUE THREAD

**Issue by dark-chocolate** [Baseflow/flutter-geolocator#1146]
## 🐛 Bug Report

The `Position.speed` returns some random speed even when the device is not moving. When I did the native implementation myself, I found that the `LocationListener.onLocationChanged` method actually reports 0.0 speed but geolocator doesn't. 

### Expected behavior
The `Position.speed` should return `0.0` when the device isn't moving. 

### Reproduction steps
1. Install the app. 
2. Grant location permission 
3. Turn on location (GPS)
4. Put the below code in `initState` 

```dart
Geolocator.getPositionStream(locationSettings: AndroidSettings(intervalDuration: Duration(seconds: 1))).listen((position) {
  print(position.speed);
});
```

The console will print speeds like: 

```
I/flutter (16652): 0.46334308385849
I/flutter (16652): 0.2126198261976242
I/flutter (16652): 0.17610421776771545
I/flutter (16652): 0.158951073884964
I/flutter (16652): 0.11525963991880417
I/flutter (16652): 0.06874571740627289
I/flutter (16652): 0.033980026841163635
I/flutter (16652): 0.019662072882056236
I/flutter (16652): 0.011276562698185444
I/flutter (16652): 0.004466619808226824
```

I can understand that even when the device is not moving there can be some minor location updates, so I tested it myself natively using 

```
LocationManager.requestLocationUpdates(LocationManager.GPS_PROVIDER, 0, 0, locationListener);
```

and it does show me a speed of `0.0` which is the correct behavior. 

### Configuration

Tested on Samsung Galaxy S20+ (running Android 12)

**Version:** 9.0.2

**Platform:** 
- [ ] :iPhone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @dark-chocolate,

Thanks for taking the time and submitting this issue and apologies for the late reply. 

To see if I could reproduce the behaviour I cloned the example [Android application](https://github.com/android/codelab-while-in-use-location) provided by Google showcasing how to access location information and modified is slightly to output the location and speed to the log. 

To be precise, these are the changes I made to the "complete" module:

1. In the `MainActivity.kt` I inserted to following  at line 286:
```kotlin
Log.d("GEO_ANDROID", output)
```
2. Also in `MainActivity.kt` I replace line 302 to following to include the speed:
```kotlin
logResultsToScreen("Foreground location: ${location.toText()} (speed: ${location.speed})")
```
3. In file `ForegroundOnlyLocationService.kt` I have updated the settings when creating the `LocationRequest` instance so updates will be send more frequent:
- Replace line 97 with: `interval = TimeUnit.SECONDS.toMillis(0)`
- Replace line 101 with: `fastestInterval = TimeUnit.SECONDS.toMillis(0)`

After these changes I ran the "complete" module on my stationary Pixel 7a device with the following output:

```
Foreground location: (52.5664504, 5.6436581) (speed: 0.04597577)
Foreground location: (52.5664464, 5.643675) (speed: 0.003850141)
Foreground location: (52.5664216, 5.6437561) (speed: 0.8001415)
Foreground location: (52.5664538, 5.6436637) (speed: 0.007609423)
Foreground location: (52.5664533, 5.6436627) (speed: 0.0030399787)
Foreground location: (52.566406, 5.6437149) (speed: 0.875059)
Foreground location: (52.5664522, 5.6436608) (speed: 0.00466736)
Foreground location: (52.5664514, 5.6436622) (speed: 0.0041651744)
Foreground location: (52.5664514, 5.6436622) (speed: 0.0)
Foreground location: (52.5664501, 5.6436632) (speed: 6.443236E-4)
```

As you might notice the speed in these cases are also almost never exactly 0.0 even though the phone is not moving at all. And this makes sense as the GPS coordinates are slightly different (GPS is simply not dead accurate), therefore calculating speed (distance / time) will most always be a positive value.

Maybe I am missing something, could you provide the native Android sample application you used to test? Hopefully I can compare notes and explain the deviation in result.
