### ISSUE TITLE
Android if location is off, it shows a popup for the user to turn on, and on yes, I'm not getting positions, only works if location already enabled

### ISSUE THREAD

**Issue by paulosousadias** [Baseflow/flutter-geolocator#1149]
## 🐛 Bug Report

First of all thanks for this library.

On Android, if location is disable, the lib asks for permission and Android asks for the user to connect the location.

After that no location is able to be read.

If the app gets restarted, with the location activated on the phone, all works as expected. Even if I turn location off and on on the phone, location info gets in to the application.

### Expected behavior

If the app starts with location enabled or not on the phone, we should get positions when locations gets enabled.

### Reproduction steps

```dart
import 'package:geolocator/geolocator.dart' as geo;
...
final _locationSettings = const geo.LocationSettings(
    accuracy: geo.LocationAccuracy.best,
    distanceFilter: 0,
  );

Future<StreamSubscription<geo.Position>> addPositionListener(
      void Function(geo.Position) onData,
      {Function? onError,
      void Function()? onDone,
      bool? cancelOnError}) async {
    await _checkAndAskLocationPermission().catchError((e) {
      print(e);
    });
    return geo.Geolocator.getPositionStream(locationSettings: _locationSettings)
        .listen(
      onData,
      onError: onError ?? (e) {},
      onDone: onDone,
      cancelOnError: cancelOnError,
    );
  }

Future<geo.LocationPermission?> _checkAndAskLocationPermission() async {
    bool serviceEnabled;
    geo.LocationPermission? permission;

    permission = await geo.Geolocator.checkPermission();
    if (permission == geo.LocationPermission.denied) {
      permission = await geo.Geolocator.requestPermission();
      if (permission == geo.LocationPermission.denied) {
        return Future.error('Location permissions are denied');
      }
    }

    if (permission == geo.LocationPermission.deniedForever) {
      // Permissions are denied forever, handle appropriately.
      return Future.error(
          'Location permissions are permanently denied, we cannot request permissions.');
    }

    return permission;
  }

...

  Future<void> _initialize() async {
    _statusPositionListener = await addStatusPositionListener((s) async {
      switch (s) {
        case geo.ServiceStatus.enabled:
          await checkAndAskLocationPermission();
          break;
        case geo.ServiceStatus.disabled:
          // TODO: Handle this case.
          break;
      }
    });
  }

```

The entry point is the ```addPositionListener```. No extra code to handle geolocator.

This worked on v7.7.1 (without the ```_checkAndAskLocationPermission``` code that the lib took care previously).

Is there something I'm doing wrong?

### Configuration

I've tested on the Android emulator and a POCO X3 Pro, both with Android 12.

**Version:** 9.0.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by paulosousadias** [comment]
Another info. I tested with your example and it works for the v7.7.1, but from v8 forward has the same behavior.

If Location is already enabled, all works as expected. If is disable, the stream does not gives positions, but the get current position works.

**Comment by han-tm** [comment]
> 

Same problem. Were you able to solve this problem?

**Comment by paulosousadias** [comment]
Nope. I'm using V7.7.1

**Comment by JeroenWeener** [comment]
Hi @paulosousadias, @han-tm!

I'm investigating the issue you reported but cannot seem to reproduce it. As the provided code did not compile I have tested on the example application, as you did in your later comment.

Currently there is a bug in the example application, where the location permission is not requested when starting the position stream. To that end, you can add the following code:

```dart
void _toggleListening() async {
  final hasPermission = await _handlePermission();

  if (!hasPermission) {
    return;
  }

  ...
}
```

Below you'll find a video recording of my findings. I'd be happy to receive additional information to continue the investigation.

- Are you experiencing this on the latest version of the plugin (10.0.1) too?
- Which Android versions are you testing on?
- Which devices are you using?
- Are you testing on an emulator?

https://github.com/Baseflow/flutter-geolocator/assets/9049645/438bd6b2-b07a-40a7-90cd-5939e4c0f235

**Comment by paulosousadias** [comment]
Hi @JeroenWeener ,
  Thanks for the reply back.
  I stayed fixed on the v7.7.1. I'm using Android 11, but also found the bug on 10. The test was done on a device and not on emulator.
  I will need a bit of time to be able to test with your suggestion (work related will be away until end of the month).

  I will get back to you on my testing.

**Comment by JeroenWeener** [comment]
Hi @paulosousadias, were you able to look into the issue?

**Comment by JeroenWeener** [comment]
Thanks for the response @paulosousadias. I'll put this on our backlog for further investigation.

**Comment by prabavgts** [comment]
I am also facing this problem. Do you have any solution?

**Comment by paulosousadias** [comment]
@prabavgts At the moment no, I'm using last version of the v7 at the moment.
