### ISSUE TITLE
[CoreLocation]  This method can cause UI unresponsiveness if invoked on the main thread

### ISSUE THREAD

**Issue by Tom3652** [Baseflow/flutter-geolocator#1151]
## 🐛 Bug Report

I am seeing this "warning" in my logs : 

```
[CoreLocation] This method can cause UI unresponsiveness if invoked on the main thread. Instead, consider waiting for the `-locationManagerDidChangeAuthorization:` callback and checking `authorizationStatus` first.
```

### Expected behavior

I would like my app to not experience any "UI unresponsiveness" if it's possible to avoid it.

### Reproduction steps

Run the sample app on an iOS 16 device. 

**Version:** 9.0.2

**Platform:** 
- [ ] :iphone: iOS

**Comment by dev-juju** [comment]
Same issue here!

**Comment by sparshba** [comment]
SAME HERE

**Comment by KingUgochukwu** [comment]
SAME HERE. Also experiencing the UI unresponsiveness on IOS 16

**Comment by abdalmonem** [comment]
@JulianBissekkou
is there any thing we can do to skip this issue ? , we had to lunch an app next week.

**Comment by mvpires** [comment]
My app was rejected yesterday because the screen went unresponsive and while it wasn't possible to reproduce the error, this warning showed up. I need to fix this ASAP to release an important update.

**Comment by JulianBissekkou** [comment]
I did a quick fix and the warning is not present anymore.
See: https://github.com/Baseflow/flutter-geolocator/pull/1218

You guys can do some testing and let me know if its works.

**Comment by SamerOrfali22** [comment]
the issue still happening

**Comment by flutterwithfaiz** [comment]
Same here on 29 April 2023.

**Comment by yourElchi** [comment]
Hello Everybody, I just solved UI problem with the code below. Still got error but at least UI works with the last known location.

  Future<Position?> getUserUpdatedLocationFuture() async {
    try {
      Position? userPosition = await Geolocator.getCurrentPosition(
        desiredAccuracy: LocationAccuracy.best,
        timeLimit: const Duration(seconds: 3),
      );
      return userPosition;
    } catch (e) {
      return await Geolocator.getLastKnownPosition();
    }
  }

**Comment by arnabonetraker** [comment]
Same here. Even though I am not running into any UI unresponsiveness, but it is logging in console.
```
[CoreLocation] This method can cause UI unresponsiveness if invoked on the main thread. Instead, consider waiting for the `-locationManagerDidChangeAuthorization:` callback and checking `authorizationStatus` first.
[CoreLocation] This method can cause UI unresponsiveness if invoked on the main thread. Instead, consider waiting for the `-locationManagerDidChangeAuthorization:` callback and checking `authorizationStatus` first.

**Comment by angelschnider** [comment]
> @arnabonetraker @angelschnider see my reply , maybe helps [#1128 (comment)](https://github.com/Baseflow/flutter-geolocator/issues/1128#issuecomment-1571438199)

:-( unfortunately that's not changing my issue, but that give me an another point of view for searching a fix. Thanks! :-)

**Comment by fatihmerickoc** [comment]
SO ANY UPDATES???

**Comment by mvanbeusekom** [comment]
@fatihmerickoc, June 5th we released a solution. Shouting in all caps is not the way to get our sympathie.

**Comment by RedHappyLlama** [comment]
@mvanbeusekom, thanks for the update to geolocator_apple that fixed this. However I'm "sort of" still being impacted by this. I'm new to coding and flutter so probably missing something obvious. Any help would be greatly appreciated. 

My app is dependent on `flutter_map_location_marker: ^7.0.2` which is dependent on `geolocator: ^9.0.2` which I believe is dependent on `geolocator_apple: ^2.1.1+1` (which doesn't have the fix). 

I've tried adding `geolocator_apple: ^2.2.7` to my `dependency_overrides`, in the hope this would override the dependency within flutter_map_location_marker. However this doesn't seem to have an effect. 

I believe I could create a fork of `flutter_map_location_marker: ^7.0.2` to fix this. However I'm just wondering if there is any other solution? Other than waiting for a new version of geolocator to contain `geolocator_apple: ^2.2.7` and then wait for an update to flutter_map_location_marker? Many thanks!

**Comment by mvanbeusekom** [comment]
Hi @RedHappyLlama, 

It should be possible to run the `flutter pub upgrade` command.

This will update all minor and patch versions of packages that have a dependency with the `^` (caret) constraint. This includes dependencies of dependencies.

More details on package versions and constraints can be found here: https://dart.dev/tools/pub/dependencies#version-constraints

Hope this helps.

**Comment by RedHappyLlama** [comment]
@mvanbeusekom, thanks! I've given it a go but still get the issue. I'll raise an issue on flutter_map_location_marker to see if it's an issue with their package.
