### ISSUE TITLE
Use `ServiceStatus` enumeration from `permission_handler_platform_interface`

### ISSUE THREAD

**Issue by bambinoua** [Baseflow/flutter-geolocator#1154]
In my app I use both packages `flutter_geolocator` and `permission_handler`. Both packages reference on their own _platform interfaces_. Both interfaces contains `ServiceStatus` enumerations but they are different.

**geolocator_platform_interface**
```dart
/// Describes the current state of the location service on the native platform.
enum ServiceStatus {
  /// Indicates that the location service on the native platform is disabled.
  disabled,

  /// Indicates that the location service on the native platform is enabled.
  enabled,
}
```
**permission_handler_platform_interface**
```dart
/// Defines the different states a service can be in.
enum ServiceStatus {
  /// The service for the permission is disabled.
  disabled,

  /// The service for the permission is enabled.
  enabled,

  /// The permission does not have an associated service on the current
  /// platform.
  notApplicable,
}
```

Is is possible to use in package `flutter_geolocator` the `ServiceStatus` enumeration from `permission_handler_platform_interface`? Otherwise it is a bit confusing what `ServiceStatus` should be used.

**Comment by JeroenWeener** [comment]
Hi @bambinoua! Thank you for filling in the issue template.

Both plugins make use of their own implementation of `ServiceStatus`, as we do not want cross dependencies between the two plugins.

Could you provide me with a code example of what you are trying to achieve and where having two types of `ServiceStatus`es gets confusing? We assume classes would not reference both. Note that you can get location permissions from `geolocator`, not needing `permission_handler`.
