### ISSUE TITLE
Geolocator.getCurrentPosition not working with huwawei and vivo

### ISSUE THREAD

**Issue by ahmedNagar123** [Baseflow/flutter-geolocator#1156]
Geolocator.getCurrentPosition not working with huwawei and vivo nothing Position returned

**Comment by Igormikheev** [comment]
same issue

**Comment by wsxc451** [comment]
我也是,三星手机,在浏览器定位可以,但是在flutter,flutter_inappwebview中,无法获取位置

**Comment by JeroenWeener** [comment]
Hi @ahmedNagar123, thank you for reporting this issue!

You mention the plugin not returning a current position for Huawei and Vivo phones. Can you tell us which exact phones (brand/type) are experiencing this issue?

**Comment by ahmedNagar123** [comment]
> Hi @ahmedNagar123, thank you for reporting this issue!
> 
> You mention the plugin not returning a current position for Huawei and Vivo phones. Can you tell us which exact phones (brand/type) are experiencing this issue?

Hi @JeroenWeener  thank you for responding
Phones that do not have Google Play Services

**Comment by JeroenWeener** [comment]
Hi @ahmedNagar123,

we recently pushed some changes for Android that remedy issues related to receiving no location updates when using the `LocationManager`, which is what phones without Google Play Services are using. Could you confirm that this issue has been resolved on the newest version of geolocator (10.0.1)?

**Comment by asadfareed777** [comment]
@JeroenWeener Facing same issue on vivo y33s android 13 with google play services in version 10.0.1

**Comment by JeroenWeener** [comment]
Hi @asadfareed777. If the device has Google Play Services this is likely a different issue. Could you open a [new issue](https://github.com/Baseflow/flutter-geolocator/issues/new/choose)?

A common cause for these types of issues is that the plugin is configured to run with an accuracy of `low`. In these cases, only drive-by location updates will be emitted; the plugin will not attempt to fetch locations itself.

**Comment by howe-Guo** [comment]
@JeroenWeener
