### ISSUE TITLE
`Geolocator.getCurrentPosition()` is not working on Web as stablished on docs

### ISSUE THREAD

**Issue by Retr0sec7** [Baseflow/flutter-geolocator#1164]
I'm trying get the current position of the client when the app is running on a web browser. The issues are:

* `checkGeolocationPermissionStatus()` is failing on web, returning an error with the following message: `UnsupportedError (Unsupported operation: Platform._operatingSystem): "Platform._operatingSystem"`. This causes the application to throw (or not doing anything at all, it just breaks out of the current flow) instead of returning `LocationPermission.denied` as docs suggests.
* `getCurrentPosition()` is having the same behavior described on the past bullet, but could not mange to get the any error message.

I'm wondering if someone has a working example of this working on Web platform. Could this be a bug? Thanks for the help.

Code I'm using: 

```
Future<String> getCountryCode() async {
    Geolocator geo = Geolocator();
    if (!kIsWeb) {
     //Mobile...
      var status = await geo.checkGeolocationPermissionStatus();
      if (status.value == 2) {
        Position position = await Geolocator()
            .getCurrentPosition(desiredAccuracy: LocationAccuracy.high);
        final coordinates = Coordinates(position.latitude, position.longitude);
        var addresses =
            await Geocoder.local.findAddressesFromCoordinates(coordinates);
        var first = addresses.first;
        return first.countryCode; // this will return country code
      } else {
        return 'CR';
      }
    } else {
    //Web...
      Position position =
          await geo.getCurrentPosition(desiredAccuracy: LocationAccuracy.high); // <- Application throws here
      // var status = await geo.checkGeolocationPermissionStatus(); <-It also throws when asking for the permissions
      final coordinates = Coordinates(position.latitude, position.longitude);
      var addresses =
          await Geocoder.local.findAddressesFromCoordinates(coordinates);
      var first = addresses.first;
      return first.countryCode;
    }
  }
```

**Comment by bmonson** [comment]
We are also having an issue with version 9.0.2 where the positionFuture in getCurrentPosition seems to never resolve in this line of code:
https://github.com/Baseflow/flutter-geolocator/blob/08c1f285b0ed44fa0cd580e9ff9697df9407b31c/geolocator_android/lib/src/geolocator_android.dart#L121

**Comment by Retr0sec7** [comment]
@bmonson that file seems to be related to the android handler for geolocator. Is it happening on Android/Mobile devices as well? For me it's working on mobile (tested on Android, not iOS), the portion of code I provided after the `//Mobile...` comment works fine.

**Comment by F7085** [comment]
i'm also having the same issue as @Retr0sec7 , for me it works on mobile/android but in web it breaks when calling  `Geolocator.getCurrentPosition()`

**Comment by mvanbeusekom** [comment]
@Retr0sec7, the method `checkGeolocationPermissionStatus()` is not a method supported by the current versions of the geolocator package. This method was removed in version 6.0.0 of the Geolocator plugin. If you are still using this I recommend updating to the latest version (9.0.2). Since web support is only added in version 6.2.0 of the geolocator plugin this would explain the errors you receive.

Please add some additional information to your question:
1. The version of the geolocator plugin used.
2. Provide the output of the `flutter doctor -v` command.

**Comment by adnan-haider007** [comment]
@F7085, have you found a solution for this? I am also facing this issue on web Flutter when trying to fetch the location.
