### ISSUE TITLE
Window demo crash in Win7

### ISSUE THREAD

**Issue by nikohpng** [Baseflow/flutter-geolocator#1168]
### Expected behavior

Window demo crash in Win7

### Reproduction steps

I make a debug pacakge to run it

**Version:** 9.0.2

**Platform:** 
- [ ] 🪟 : Windows

**Comment by TimHoogstrate** [comment]
Closing issue due to lack of reproducible steps. Feel free to reopen with additional information. Thank you for your understanding.
