### ISSUE TITLE
Permission request does not appear on Safari

### ISSUE THREAD

**Issue by dangabdolfo** [Baseflow/flutter-geolocator#1170]
## 🐛 Bug Report

When I call `Geolocator.requestPermission()`, on IOS in PWA mode, the system permission dialog does not appear.
Have you an idea or a workaround?

Thanks for your help.

### Expected behavior
When I call `Geolocator.requestPermission()`, I should show the system permission dialog.
### Reproduction steps
To reproduce this bug, you must:
- A web server in HTTPS ('secure contexts' is mandatory)
- Build geolocator-web exemple and put it on your sever
- Generate PWA from Safari
- Test to get your location.

### Configuration
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 13.0 22A380 darwin-arm, locale
    fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.73.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```
**Version:** 9.0.2

**Platform:** 
- [ ] :iphone: iOS
- [X] :web: iOS
- [ ] :robot: Android

**Comment by TimHoogstrate** [comment]
@dangabdolfo,

To be sure, the permission has not already been accepted earlier? I think you can check this in the settings of safari.

Kind regards,
