### ISSUE TITLE
Geolocator.getPositionStream takes too long 

### ISSUE THREAD

**Issue by laura-rodriguez8** [Baseflow/flutter-geolocator#1174]
## 💬 Questions and Help

Hi!
I'm currently working on a project when I need a UAV to follow the location of my phone. The plugin has been very helpful, how ever I'm getting data of latitude and longitude in intervals of 4 seconds using  `Geolocator.getPositionStream` to constantly update the data  , is it possible to get the geolocation points with intervals of 10 milliseconds?

I am testing on my phone Android Samsung A30S

Hope you can understand me since english isn't my first language

Thanks in advance

**Comment by richCode-Ama** [comment]
am facing the same issue I want to take the data in 33milliseconds

**Comment by JeroenWeener** [comment]
Hi @laura-rodriguez8!

I have dived into your question and I believe this should be possible on Android, by providing an instance of `AndroidSettings` specifying `intervalDuration`, to `Geolocator.getPositionStream()`.

Example:

```dart
Geolocator.getPositionStream(
  locationSettings: AndroidSettings(
    intervalDuration: Duration(milliseconds: 10),
  ),
);
```

This only works for Android. The plugin does not support this behavior for iOS. If your use case also applies to iOS, feel free to open a new issue for a feature request. That way we can track interest in support for such functionality.
