### ISSUE TITLE
[Enhancement proposal] Activating location service on Android Geolocator 9.0.2

### ISSUE THREAD

**Issue by cnkygmr** [Baseflow/flutter-geolocator#1175]
`bool isLocationServiceEnabled  = await Geolocator.isLocationServiceEnabled();`

When you use this code, the popup that should appear in order to activate the location on android does not appear.

`Position position = await Geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.high);`

When this code runs, the popup that needs to be opened asks for permission to open

When you call the isLocationServiceEnabled function, a popup should appear asking android to enable location access.

**Comment by yamaroni** [comment]
Feel the same way and finally, i use another plugin to get ask permission popup showing on screen.
Here the plugin : [Permission Handler](https://pub.dev/packages/permission_handler)

**Comment by cnkygmr** [comment]
> 

Yes it makes sense but I can use it now with the getCurrentPosition function. When this function runs, it asks for that permission, if it doesn't, an error pops up.

**Comment by JeroenWeener** [comment]
Hi @cnkygmr, after consulting with the team, we decided that for now, we will not implement this feature in the `geolocator` plugin. For maintenance purposes, we would like to keep the Android and iOS behavior similar. According to Google, it is best practice is to ask to enable location services the moment you need it, as opposed to asking for it up-front. This is why the plugin behaves this way.

If you are keen on enabling the location services up-front, you could call `getCurrentPosition()` and ignore the result. Note: this will only work on Android.
