### ISSUE TITLE
geolocation does not work in workmanger

### ISSUE THREAD

**Issue by vignesh235** [Baseflow/flutter-geolocator#1176]
geolocation does not work in workmanger
![image](https://user-images.githubusercontent.com/95606753/204083682-4125c9c7-5b7d-4975-ba5b-caa02f300b95.png)

**Comment by TimHoogstrate** [comment]
Dear @vignesh235,

Thanks for submitting this issue. could you please inform us how we could reproduce this issue? Could you also add some details like the output of `flutter doctor -v?

Kind regards,
