### ISSUE TITLE
Loads forever on some devices

### ISSUE THREAD

**Issue by simplenotezy** [Baseflow/flutter-geolocator#1179]
## 🐛 Bug Report

We have several android users who is experiencing it loads forever when trying to fetch the location.

It does not happen on all android versions, and not on iOS at all.

### Expected behavior
Should not load forever (also LocationAccuracy.lowest should work on all android versions, but it seems like it doesnt)

### Reproduction steps
```dart
    final position = await Geolocator.getCurrentPosition(
      // On android .lowest does not work for some reason. Use LocationAccuracy.best instead, or it will load forever.
      desiredAccuracy: Platform.isAndroid ? LocationAccuracy.best : LocationAccuracy.lowest,
      timeLimit: Duration(seconds: 20),
    );
```

### Configuration

**Version:** 9.0.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by simplenotezy** [comment]
Possibly related: https://github.com/Baseflow/flutter-geolocator/issues/949

**Comment by simplenotezy** [comment]
OnePlus 9pro
Android version 13

Apparently it worked to clear Storage and Cache from the app, and then trying again. Very strange issue.

**Comment by TimHoogstrate** [comment]
@simplenotezy,

Do you have the output of `flutter doctor -v`
