### ISSUE TITLE
Geolocator.getServiceStatusStream().listen not working when android device location is on at the first time

### ISSUE THREAD

**Issue by EdwinKomala85** [Baseflow/flutter-geolocator#1180]
Hi,

Can anybody help me why the service status stream listening not working when the device location already ON at the first time. It does work if the location is off and then enabled manually afterward.
Here is my snippet code:

```dart
@override
void initState()  {
  handlePermission();
  getLocationContinuous();
  super.initState();
}

void getLocationContinuous() async {
  serviceStatusSubscription ??= Geolocator.getServiceStatusStream().listen(
    (ServiceStatus status) {
      if (status == ServiceStatus.enabled) {
        PositionSubscription ??= Geolocator.getPositionStream(
          locationSettings: const LocationSettings(
            distanceFilter: 0, 
            accuracy: LocationAccuracy.bestForNavigation
          )
        ).listen((Position? position){
          print(position == null ? 'Unknown' : '${position.latitude.toString()}, ${position.longitude.toString()}');
          setState(() {
          });
        });
      } else { //Location disabled
        if (PositionSubscription != null) {
          PositionSubscription!.cancel();
          PositionSubscription = null;
        }
      }
    }
  );
}  
```

For the info, I'm using Geolocator plugin 9.0.2.

Please advise.

Thank you.

Regards,

Edwin Newbie of Flutter

**Comment by Fitem** [comment]
I had the same problem. （The example also exists.）

**Comment by JoHassan** [comment]
Have you managed to solve it? I Have the same issue

**Comment by edwinkomalaICI** [comment]
Hi Jo,

For some reason, I changed into OSM and the OSM is much simpler than using geolocator function.

Regards,

Edwin

**Comment by robbiwu** [comment]
Seems to happen only on some android phones. I made a static call to _determinePosition as shown in the pub as an extension of initState() which seems to have fixed the issue for me at least.

**Comment by JeroenWeener** [comment]
Hi @EdwinKomala85, thank you for taking the time to submit your issue!

I am happy to hear that you already found a workaround in using OSM.
If you or someone else (@robbiwu?) wants to help in getting this issue in geolocator resolved, we'd love to receive a minimal code sample that showcases the issue.

For example, you can create a new flutter project, add the geolocator dependency, modify `main.dart` minimally so it showcases the issue, and then send the contents of `main.dart` as a response to this issue.

Thank you again for the feedback and have a nice weekend!

**Comment by abdullaalimobileshop** [comment]
same issue

**Comment by amal-stack** [comment]
This is actually the expected behaviour and has been explained in a previous issue:
https://github.com/Baseflow/flutter-geolocator/issues/1095#issuecomment-1169889577

The `Geolocator.getServiceStatusStream()` stream does not send a stream event for the current location service status when initially listened to. It only raises events when the service status changes. 

However, it is possible to create a new custom stream that first raises an event regarding the current location service status by obtaining it by calling `Geolocator.isLocationServiceEnabled()` and then delegates to `Geolocator.getServiceStatusStream()` for further events. Dart allows doing this easily using an `async*` generator function. `yield*` is used to delegate raising future events to `Geolocator.getServiceStatusStream`:
```dart
 Stream<ServiceStatus> getServiceStatusStreamWithCurrentStatus() async* {
    yield await Geolocator.isLocationServiceEnabled()
      .then((value) => value ? ServiceStatus.enabled : ServiceStatus.disabled);

    yield* Geolocator.getServiceStatusStream();
  }
```

**Comment by famasf1** [comment]
> This is actually the expected behaviour and has been explained in a previous issue: [#1095 (comment)](https://github.com/Baseflow/flutter-geolocator/issues/1095#issuecomment-1169889577)
> 
> The `Geolocator.getServiceStatusStream()` stream does not send a stream event for the current location service status when initially listened to. It only raises events when the service status changes.
> 
> However, it is possible to create a new custom stream that first raises an event regarding the current location service status by obtaining it by calling `Geolocator.isLocationServiceEnabled()` and then delegates to `Geolocator.getServiceStatusStream()` for further events. Dart allows doing this easily using an `async*` generator function. `yield*` is used to delegate raising future events to `Geolocator.getServiceStatusStream`:
> 
> ```dart
>  Stream<ServiceStatus> getServiceStatusStreamWithCurrentStatus() async* {
>     yield await Geolocator.isLocationServiceEnabled()
>       .then((value) => value ? ServiceStatus.enabled : ServiceStatus.disabled);
> 
>     yield* Geolocator.getServiceStatusStream();
>   }
> ```

This took me months to debug. Had to put it on hold several times because all the other stream like Wi-Fi and Bluetooth doesn't behave the same way. even using RxDart didn't solved it for me. Thank you so much for this!
