### ISSUE TITLE
How to close runtime permission dialog programmatically?

### ISSUE THREAD

**Issue by shahpasandar** [Baseflow/flutter-geolocator#1182]
## 💬 Questions and Help

I want to close runtime permission dialog  with deny as selected option when user sends the app to background.  How can I handle this? Thanks in advance.

**Comment by mvanbeusekom** [comment]
Hi @shahpasandar, 

Unfortunately you cannot. Non of the supported platforms (iOS, Android and Windows) support an API to interact with the permission dialog (which is completely managed by the underlying operating system).
