### ISSUE TITLE
We are unable to locate the location on android 13 (all devices), It is working properly on versions below 13.

### ISSUE THREAD

**Issue by mikiyasET** [Baseflow/flutter-geolocator#1188]
**Platform:** 
- [ ] :robot: Android

**Comment by Kampfotter** [comment]
Any update @mikiyasET did you solved the issue ?

**Comment by JeroenWeener** [comment]
Hi @mikiyasET, thank you for taking the time to file this issue!

In order for us to effectively tackle this issue, we need some additional information.

Are you experiencing this behavior in the example app as well? If not, please show us a minimal reproduction of your code.
Additionally, could you provide me with the output of `flutter doctor -v`?
