### ISSUE TITLE
minSdkVersion set to 23 causes exception

### ISSUE THREAD

**Issue by JohnWelchDT** [Baseflow/flutter-geolocator#1189]
## 🐛 Bug Report

If I set the minSdkVersion to 23 for my project, I get a the following error when compiling for Android: 

> E/AndroidRuntime(21732): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.SettingsClient, but class was expected (declaration of 'com.google.android.gms.location.SettingsClient' appears in /data/app/~~VaSsYpHacYF9CNgw5Qul1w==/com.example.app-U2GvP8Pg6RvdzrXqq1nO2w==/base.apk!classes6.dex)
E/AndroidRuntime(21732): 	at com.baseflow.geolocator.location.FusedLocationClient.startPositionUpdates(FusedLocationClient.java:206)
E/AndroidRuntime(21732): 	at com.baseflow.geolocator.location.GeolocationManager.startPositionUpdates(GeolocationManager.java:55)
E/AndroidRuntime(21732): 	at com.baseflow.geolocator.StreamHandlerImpl.onListen(StreamHandlerImpl.java:137)
E/AndroidRuntime(21732): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:218)
E/AndroidRuntime(21732): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:197)
E/AndroidRuntime(21732): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime(21732): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/AndroidRuntime(21732): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime(21732): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(21732): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(21732): 	at android.os.Looper.loop(Looper.java:250)
E/AndroidRuntime(21732): 	at android.app.ActivityThread.main(ActivityThread.java:7868)
E/AndroidRuntime(21732): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21732): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(21732): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

After some review this may be due to using an older version of com.google.android.gms:play-services-location

**Version:** 9.0.2

**Platform:** 
- [ ] :robot: Android

**Comment by JohnWelchDT** [comment]
I was able to resolve this issue by adding the following to my app/build.gradle

```
android {
...
configurations.all {
        resolutionStrategy.force 'com.google.android.gms:play-services-location:20.0.0'
    }
}
```

**Comment by justsaagar** [comment]
I have tried giving Soln. But still getting crashes in my application.


```
W/munity.coop.ap(17312): Attempt to remove non-JNI local reference, dumping thread
E/AndroidRuntime(17312): FATAL EXCEPTION: main
E/AndroidRuntime(17312): Process: community.coop.app, PID: 17312
E/AndroidRuntime(17312): java.lang.IncompatibleClassChangeError: Found class com.google.android.gms.location.SettingsClient, but interface was expected (declaration of 'com.google.android.gms.location.SettingsClient' appears in /data/app/~~JtFmo4CxTWnaj-1yq9bJzA==/community.coop.app-aclA7YNqr9cQB21qFS44wg==/base.apk!classes6.dex)
E/AndroidRuntime(17312): 	at com.baseflow.geolocator.location.FusedLocationClient.startPositionUpdates(FusedLocationClient.java:208)
E/AndroidRuntime(17312): 	at com.baseflow.geolocator.location.GeolocationManager.startPositionUpdates(GeolocationManager.java:55)
E/AndroidRuntime(17312): 	at com.baseflow.geolocator.MethodCallHandlerImpl.onGetCurrentPosition(MethodCallHandlerImpl.java:222)
E/AndroidRuntime(17312): 	at com.baseflow.geolocator.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:74)
E/AndroidRuntime(17312): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/AndroidRuntime(17312): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime(17312): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:322)
E/AndroidRuntime(17312): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime(17312): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(17312): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(17312): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(17312): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(17312): 	at android.app.ActivityThread.main(ActivityThread.java:7870)
E/AndroidRuntime(17312): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17312): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(17312): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
I/Process (17312): Sending signal. PID: 17312 SIG: 9
```
