### ISSUE TITLE
[Bug] Geolocator Android 13 API 33 precise location does not work

### ISSUE THREAD

**Issue by Kampfotter** [Baseflow/flutter-geolocator#1192]
## 🐛 Bug Report

With the newest Android Version 13 (API 33) the location accuracy does not work anymore. The user just get the pop up for approximate location. I tested it with Android 12 API 32 and it still work. You get two windows where the user can choose between aproximate and precise location.
### Reproduction steps
1. call Geolocator.RequestPermission()

### Configuration
Android Manifest
ACCESS_FINE_LOCATION
ACCESS_COARSE_LOCATIOn

**Version:** 9.0.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by Kampfotter** [comment]
I cannot exclude that it is due to my own configuration. But please confirm me if it works the plugin for API 33 or not.
Thank you very much.

**Comment by rizaldywirawan** [comment]
Our mobile dev experience the samething, if we downgrade the OS version, it works

**Comment by DevMayur** [comment]
Do we have any update on android 13 issues ?

**Comment by daviddagan** [comment]
im getting  he location service on the device is disabled in android 13

**Comment by Kingtous** [comment]
same here, it's really a project blocker.

**Comment by Kampfotter** [comment]
still having the issue..

**Comment by Kingtous** [comment]
> same here, it's really a project blocker.

Maybe `getLastKnownPosition` can be a fallback.
```dart
 Future<Position?> getCurrentLocation({LocationAccuracy? accuracy}) async {
    try {
      var pos = await Geolocator.getCurrentPosition(
          forceAndroidLocationManager: true,
          timeLimit: const Duration(seconds: 5),
          desiredAccuracy: accuracy ?? LocationAccuracy.best);
      return pos;
    } catch (e) {
      debugPrint("$e");
      return Geolocator.getLastKnownPosition(forceAndroidLocationManager: true);
    }
  }
```

**Comment by Kampfotter** [comment]
I will try later the thing is my customer needs a really precise location because the action he wan'ts to do is only allowed in some areas. But still thank you !

**Comment by TimHoogstrate** [comment]
Dear @Kampfotter,

Personally I cannot reproduce this issue, can you send me a little more information on how you are testing this. Like e.g. some minimal reproducible code and your configuration settings. An output of `flutter doctor -v` would also help a lot. Furthermore, can you also confirm that it is working in the example app?

**Comment by jpunie** [comment]
It seems an permission and SDK version issue on android: https://stackoverflow.com/questions/70793162/android-12-not-showing-correct-permissions-request-screen

adding tools:remove="android:maxSdkVersion" fixed the issue for me. The user will now get the correct dialog with options to opt out of precise location, previously this was not an option.

**Comment by AntolKun** [comment]
just use <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" android:maxSdkVersion="34"/>, and you'll be fine, tested on INFINIX X663B and Pixel 7 API 34 emulator
