### ISSUE TITLE
[IOS 16.2][XCODE 14.2] Geolocator.getCurrentPosition() No work

### ISSUE THREAD

**Issue by Jartz** [Baseflow/flutter-geolocator#1194]
## 🐛 Bug Report

When i use method `Geolocator.getCurrentPosition();` the app closes and shows a black screen. no crashed

https://user-images.githubusercontent.com/19338050/212491548-216138db-5167-4330-8133-ffc192efa057.mp4

### Expected behavior

- Don't close the app

### Reproduction steps
- iOS 16.2
- Xcode 14.2
- use method `Geolocator.getCurrentPosition();` 

### Configuration

**Version:** 9.0.2

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by abdalmonem** [comment]
we facing the same issue , i hope this issue get fixed , we waiting for it to lunch our app :(

**Comment by luvishq** [comment]
any updates on this ?

**Comment by Jartz** [comment]
@abdalmonem @luvishq, I solved the problem, delete the iOS folder. I created it again
`flutter create -i swift . `

<img width="633" alt="Screenshot 2023-02-06 at 7 48 15 AM" src="https://user-images.githubusercontent.com/19338050/216975419-e175a1a8-d82a-4dc5-abd1-3f5b0c756a5f.png">

**Comment by abdalmonem** [comment]
@Jartz thank you sooo much , i tried and its work, you saved me.

**Comment by benneca** [comment]
The recreation of the ios folder leads to a whole host of other issues, do we know what exactly is causing the issue so I can address that specifically? More of a scalpel approach and less grenade so to speak
