### ISSUE TITLE
Android build error Wrong Constant

### ISSUE THREAD

**Issue by amrud** [Baseflow/flutter-geolocator#1199]
## 🐛 Bug Report

Android gradle build error with message - 

```
 C:\flutter\.pub-cache\hosted\pub.dartlang.org\geolocator_android-4.1.4\android\src\main\java\com\baseflow\geolocator\GeolocatorLocationService.java:159: Error: Must be one of: Service.STOP_FOREGROUND_LEGACY, Service.STOP_FOREGROUND_REMOVE, Service.STOP_FOREGROUND_DETACH [WrongConstant]
          stopForeground(ONGOING_NOTIFICATION_ID);

 Explanation for issues of type "WrongConstant":
     Ensures that when parameter in a method only allows a specific set of
     constants, calls obey those rules.
```

### Expected behavior
Should be able to build in android

### Reproduction steps
cd to android
run .\gradlew build

### Configuration

**Version:** 9.0.2

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android

**Comment by SLAYEEERRR** [comment]
i did it but still got this error

**Comment by mvanbeusekom** [comment]
Hi @amrud, 

Thank you for bringing this issue to our attention. I have released a new version of the `geolocator_android` package. If you depend on the `geolocator` package simply run `flutter pub upgrade` to automatically update to the latest version.

**Comment by amrud** [comment]
Alright. Thank you 👍🏻
