### ISSUE TITLE
bearingBetween behavior

### ISSUE THREAD

**Issue by ctnadovich** [Baseflow/flutter-geolocator#1208]
What are the units returned by Geolocator.bearingBetween? Radians? Degrees? Grads? Is the result guaranteed to be within some range? (0 to 360, -180 to 180, -pi to pi)?  This doesn't seem to be documented anywhere.

**Comment by TimHoogstrate** [comment]
Dear @ctnadovich,

If I look into the calculations and the tests it seems that the the output of the degrees(atan2(y, x)) expression will be in the range from -180 degrees to +180 degrees. I'll note this as an enhancement for the documentation. 

`    test('the West to the East bearing should be 90', () async {
      const startLatitude = 0.0;
      const startLongitude = 180.0;
      const endLatitude = 0.0;
      const endLongitude = -180.0;
      final geolocatorPlatform = ExtendsGeolocatorPlatform();

      final bearing = geolocatorPlatform.bearingBetween(
        startLatitude,
        startLongitude,
        endLatitude,
        endLongitude,
      );

      expect(bearing, 90.0);
    });

    test('the East to the West bearing should be -90', () async {
      const startLatitude = 0.0;
      const startLongitude = -180.0;
      const endLatitude = 0.0;
      const endLongitude = 180.0;
      final geolocatorPlatform = ExtendsGeolocatorPlatform();

      final bearing = geolocatorPlatform.bearingBetween(
        startLatitude,
        startLongitude,
        endLatitude,
        endLongitude,
      );

      expect(bearing, -90.0);
    });
  });
}`
