### ISSUE TITLE
Not getting coords without internet [ Geolocator.getCurrentLocator() ]

### ISSUE THREAD

**Issue by chirag-chopra** [Baseflow/flutter-geolocator#1211]
## 🐛 Bug Report

> Geolocator.getCurrentLocation()

Not returning data without internet.

### Expected behavior
As coords are not dependent on internet connection. So, plugin should return coords. 

### Reproduction steps
Just try to call the below code without internet 
> Geolocator.getCurrentLocation()

### Configuration

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.0, on macOS 12.6 21G115 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the
        Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.72.2)
[✓] VS Code (version 1.72.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

**Version:** 1.x
geolocator: ^9.0.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by TheauLep** [comment]
Same problem here ... Did you find a solution ?

**Comment by SunlightBro** [comment]
Same issue here, these are some devices where I was able to reproduce
```
• EDA71 G (mobile)  • 21113B1FCB         • android-arm64  • Android 8.1.0 (API 27)
• SM G930F (mobile) • 988674424b56494e49 • android-arm64  • Android 8.0.0 (API 26)
• SM G955F (mobile) • ce021712daadea0f02 • android-arm64  • Android 9 (API 28)
```

**Comment by AliEasy** [comment]
The problem still persists
Any update on this?!

**Comment by benoit-rolandeau-act** [comment]
Same here, with the permissions:

```
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
```

And the LocationSettings:

```
LocationSettings(
    accuracy: LocationAccuracy.best,
    timeLimit: Duration(seconds: 10),
 )
```

But it's working with `LocationAccuracy.high`. Is there because, `best` needs the connectivity to return a better position?

**Comment by JeroenWeener** [comment]
Hi everyone!

This might have been caused by a bug in the Android implementation, where we filtered out locations based off their accuracy. Could you confirm that this issue has been resolved?

You would need to pull in the latest version of the `geolocator` (10.0.1) and run `dart pub upgrade`. Please check your `pubspec.lock` file to see if it mentions `geolocator_android` version `4.2.3`.
