### ISSUE TITLE
java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient'

### ISSUE THREAD

**Issue by halhwadi** [Baseflow/flutter-geolocator#1214]
## 🐛 Bug Report

I have upgraded flutter to 3.7.0 and use geolocator: ^9.0.2 , android studio  (version 2022.1)

**issue behaviour:**
App keeps crashing/closing once its lunched  

**Error msg:**
E/AndroidRuntime(24725): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~7kJb1UB3ROFjA15MqSt5-A==/org.bikum-Rh6OUdna6OycDn5yFflSqw==/base.apk)

**### Configuration**

**flutter doctor:**

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.0, on Microsoft Windows [Version 10.0.22621.1105], locale en-AE)
[√] Windows Version (Installed version of Windows is version 10 or higher)
Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)
[√] Android Studio (version 2022.1)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!

Android/build.gradle:
```
buildscript {
    ext.kotlin_version = '1.6.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}


allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}


```

App/build.gradle:
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
//    compileSdkVersion flutter.compileSdkVersion
    compileSdkVersion 33

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "org.bikum"
        minSdkVersion flutter.minSdkVersion
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "com.google.android.gms:play-services-location:21.0.1"
}

```

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by christocracy** [comment]
See #1202

**Comment by SukumarRaja** [comment]
Thank you,
I faced this problem solve to more than 5 five days...
In my project on live, I am scared.
Thanks lot

**Comment by carlosvpinto** [comment]
cual es la solucion?

**Comment by halhwadi** [comment]
@carlosvpinto solution for my case is above there in my previous comment

**Comment by correiarangel** [comment]
Thanks @christocracy, @halhwadi solution worked beautifully ;] 

maven {
           url 'https://google.bintray.com/exoplayer/'
       }
       //** add this line
       configurations.all {
           resolutionStrategy {
               force "com.google.android.gms:play-services-location:21.0.1"
           }

**Comment by rehanmir30** [comment]
Not working for me. Got even more errors. Now even app is not building

**Comment by AdmiJW** [comment]
Thank you! In my case, I wanted to use `flutter_activity_recognition` and `geolocator` package in my flutter app. `flutter_activity_recognition` worked fine alone, but as soon as I install `geolocator`, application startup results in error. Applying changes to the `build.gradle` worked like a charm!

**Comment by shreyashindisk** [comment]
> Thank you @christocracy
> 
> i got it solved after adding the followings lines to allprojects:
> 
> ```
> maven {
>            url 'https://google.bintray.com/exoplayer/'
>        }
>        //** add this line
>        configurations.all {
>            resolutionStrategy {
>                force "com.google.android.gms:play-services-location:21.0.1"
>            }
> ```
> 
> android\build.gradle:
> 
> ```
> buildscript {
>     ext.kotlin_version = '1.6.10'
>     repositories {
>         google()
>         mavenCentral()
>     }
> 
> 
>     dependencies {
>         classpath 'com.android.tools.build:gradle:4.1.0'
>         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
>     }
> }
> 
> 
> allprojects {
>     repositories {
>         google()
>         mavenCentral()
>         maven {
>             url 'https://google.bintray.com/exoplayer/'
>         }
>         //** add this line
>         configurations.all {
>             resolutionStrategy {
>                 force "com.google.android.gms:play-services-location:21.0.1"
>             }
>         }
>     }
> }
> 
> rootProject.buildDir = '../build'
> subprojects {
>     project.buildDir = "${rootProject.buildDir}/${project.name}"
> }
> subprojects {
>     project.evaluationDependsOn(':app')
> }
> 
> task clean(type: Delete) {
>     delete rootProject.buildDir
> }
> ```

in my case 20.0.0 worked

**Comment by ghifariakbar01** [comment]
not working. Flutter (Channel stable, 3.7.10,). packages used

#* Background service
 flutter_background_geolocation: ^4.11.1
 workmanager: ^0.5.1

  #* Maps
  geofence_service: ^4.0.0

**Comment by bhumit822** [comment]
worked for me

+ multiDexEnabled true
+ implementation 'com.google.android.gms:play-services-location:21.0.1'
