### ISSUE TITLE
Review requirements

### ISSUE THREAD

**Issue by mazhengshui** [Baseflow/flutter-geolocator#1215]
## 💬 Questions and Help

For questions or help we recommend checking:

Now the app can only obtain the location permission after the approval of the privacy agreement, but the current sdk is to obtain the location permission directly.

Can you provide a way to delay the acquisition of location permissions?

**Comment by TimHoogstrate** [comment]
Dear @mazhengshui, I don't understand your question. What privacy agreement are you writing about. Is it your "own" privacy agreement? Feel free to update this question when needed.

Kind regards,
