### ISSUE TITLE
isMocked is always false according to the documentation

### ISSUE THREAD

**Issue by vanlooverenkoen** [Baseflow/flutter-geolocator#1216]
## 🐛 Bug Report
This is the documentation
```
  /// Will be true on Android (starting from API lvl 18) when the location came
  /// from the mocked provider.
  ///
  /// On iOS this value will always be false.
  final bool isMocked;
```

But https://github.com/Baseflow/flutter-geolocator/issues/1079 added support for isMocked in iOS 15

### Configuration

**Version:** 9.0.2

**Platform:** 
- [X] :iphone: iOS
- [ ] :robot: Android

**Comment by TimHoogstrate** [comment]
Dear @vanlooverenkoen,

Your suggestion seems to be correct. I'll label this as an enhancement. Thanks!

**Comment by TimHoogstrate** [comment]
Is resolved by [1370](https://github.com/Baseflow/flutter-geolocator/pull/1370)
