### ISSUE TITLE
Unable to build apk for Android with Flutter version 3.7.0

### ISSUE THREAD

**Issue by vikramsinghrajpoot** [Baseflow/flutter-geolocator#1219]
## 🐛 Bug Report

Getting error while creating build for android
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':geolocator_android:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

### Configuration
Pacakge and flutter version
  geolocator: ^9.0.2
 **Version:** 3.7.0 flutter

**Platform:** 
- [ ] :robot: Android

**Comment by mgoldp** [comment]
Hi! I have a similar issue, I updated my flutter project to v3.7.

And when running it on android emulator I get the same failure when building:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':geolocator_android:compileDebugJavaWithJavac'.

There're some deprecations in the code:

warning: [deprecation] stopForeground(boolean) in Service has been deprecated
      stopForeground(true);
      ^

warning: [deprecation] getPackageInfo(String,int) in PackageManager has been deprecated
              .getPackageInfo(context.getPackageName(), PackageManager.GET_PERMISSIONS);
              ^
1 error
2 warnings

I'm currently using geolocator ^8.2.1, couldn't update to the last version, but as I see it on de documentation it's from the las 5 months. Should be updated to the last Flutter version.

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.5, on Microsoft Windows [Versi¢n 10.0.19044.2604], locale es-CL)
[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1) 
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.0)        
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.75.1)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.

**Comment by jb3rndt** [comment]
Maybe Related issue: https://github.com/Baseflow/flutter-geolocator/issues/795
Try out one of those solutions: https://github.com/Baseflow/flutter-geolocator/issues/795#issuecomment-888179840
https://github.com/Baseflow/flutter-geolocator/issues/795#issuecomment-1671218143

**Comment by mvanbeusekom** [comment]
Thanks for pointing this issue out @jb3rndt, this has been solved in version 4.2.1 of the geolocator_android package. Please run `flutter pub upgrade` to download the latest version.

**Comment by jb3rndt** [comment]
I just had the issue with 4.2.1 and 4.2.2. After downgrading to 4.2.0 it disappeared.
<details>
  <summary>Logs:</summary>
[        ] /Users/jberndt/.pub-cache/hosted/pub.dev/geolocator_android-4.2.1/android/src/main/java/com/baseflow/geolocator/location/FusedLocationClient.java:91: error: cannot find
symbol
[   +1 ms]     LocationRequest.Builder builder = new LocationRequest.Builder(0);
[        ]                    ^
[        ]   symbol:   class Builder
[        ]   location: class LocationRequest
[        ] /Users/jberndt/.pub-cache/hosted/pub.dev/geolocator_android-4.2.1/android/src/main/java/com/baseflow/geolocator/location/FusedLocationClient.java:91: error: cannot find
symbol
[        ]     LocationRequest.Builder builder = new LocationRequest.Builder(0);
[        ]                                                          ^
[        ]   symbol:   class Builder
[        ]   location: class LocationRequest
[        ] 2 errors
[        ] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':geolocator_android:compileDebugJavaWithJavac'.
[        ] > Compilation failed; see the compiler error output for details.
[        ] * Try:
[        ] > Run with --debug option to get more log output.
[        ] > Run with --scan to get full insights.
</details>

Am I doing something wrong?

**Comment by mvanbeusekom** [comment]
@jb3rndt, this seems a different error. In this case the compiler is complaining about not being able to find the `LocationRequest.Builder` class which has been introduced in Android API 31 and is replacing the deprecated `LocationRequest.create` method since Android API 33. 

This could be related to the Android licenses you haven't accepted (according to the `flutter doctor -v` output you supplied). Can you try running `flutter doctor --android-licenses` and accepting the licenses and try again? If this doesn't work please create a new issue and I would be happy to help and dive into this.

**Comment by jb3rndt** [comment]
It had nothing to do with the licenses, but I found some other reasons. I'll open a new issue. Thank you :)

**Comment by DineshIT** [comment]
If you 

> I just had the issue with 4.2.1 and 4.2.2. After downgrading to 4.2.0 it disappeared.
> 
> Logs:
> Am I doing something wrong?
> 
> flutter doctor -v

If you downgrade the geolocator_android version to 4.2.0, then the map loading would get stuck in the application, you might get rid of the build issues.
