### ISSUE TITLE
Get Position when app enter Deep Idle (doze Mode)

### ISSUE THREAD

**Issue by johnray016** [Baseflow/flutter-geolocator#1221]
how to get devlce location when the app enters Doze Mode?

have have `Timer` used and gets location of the user for a certain interval.
But when I tried to test it in Doze Mode using `adb shell dumpsys deviceidle force-idle` the app stops in getting the location of the user.

I am new to flutter and not have a deep knowledge in Android App Development.

**Comment by anst270125** [comment]
I have the same question. In my case, I use flutter_background_service to create a foreground service, in which I getCurrentPosition each 5 seconds. After the device was left idle for a longer time, I start getting the same position over and over again, until I wake the device up. Strangely, the altitude keeps updating in this timeframe. I have disabled every setting regarding battery optimization for the app. Is there any solution for this?

**Comment by Shreemanarjun** [comment]
You can just check docs : [https://developer.android.com/about/versions/oreo/background-location-limits]()

**Comment by TimHoogstrate** [comment]
Dear @johnray016 or @anst270125,

Can you share some minimal reproducible code + perhaps some detailed steps to reproduce and your manifest file? Futhermore, the output of `flutter doctor -v` would also help a lot. We are unable to answer your question when I don't have additional information.

Kind regards,
