### ISSUE TITLE
Exception in Position.toJson() on NaN values

### ISSUE THREAD

**Issue by swipetwenty** [Baseflow/flutter-geolocator#1222]
## 🐛 Bug Report

The [Position](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator_platform_interface/lib/src/models/position.dart) class has an issue in the toJson method when there is a NaN double.  The NaN double can be seen on Windows targets for position attributes heading and speed. When calling the toJson on an object that was received from the locator service, an exception occurs.

### Expected behavior
ToJson will not exception and create a valid string for the NaN values

### Reproduction steps
Start Listener, and on first message received from service, position includes NaNs, perform the toJson().

### Configuration
Using Windows PC target that hardware does not support heading or speed.  Possibly this is all windows per #1067 

**Version:** 8.2.2

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [X] Windows

**Comment by TimHoogstrate** [comment]
Dear @swipetwenty,

Do you have the output of `flutter doctor -v`, some minimal reproducible code and possibly the output of the crashlog?

**Comment by swipetwenty** [comment]
@TimHoogstrate 

I tried recreating an exception, but failed to do so.  I started with the example code as shown on pub.dev, used v8.2.1.  Cleaned up the example code's warnings, and changed the position.toString() in _toggleListening() to position.toJson().toString()

Ran and started the location tracking within the windows application.

I still see heading and speed as NaN.  While I recorded using v8.2.2, I cannot seem to find this version on pub.dev or github, so not sure what I was doing back then.  I checked with v9.0.0 as well, and saw same result.  No exception but continued to see NaN values for speed and heading.

I think my report is basically reporting the same as https://github.com/Baseflow/flutter-geolocator/issues/1067.  Where NaN has to be checked before doing anything with the json string due to some windows devices are not reporting those values.   I am simply using windows PC for this test.   

Are the NaN values expected behavior and up to the user to handle them?

### Output of flutter doctor -v
$ flutter doctor -v
[√] Flutter (Channel stable, 3.10.3, on Microsoft Windows [Version 10.0.19045.3208], locale en-US)
    • Flutter version 3.10.3 on channel stable at [hidden]
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f92f44110e (9 weeks ago), 2023-06-01 18:17:33 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at [hidden]
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = [hidden]
    • Java binary at: [hidden]
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at [hidden]

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.3)
    • Visual Studio at [hidden]
    • Visual Studio Community 2022 version 17.3.32825.248
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.3)
    • Android Studio at [hidden]
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code, 64-bit edition (version 1.73.1)
    • VS Code at [hidden]
    • Flutter extension version 3.60.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.3208]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 115.0.5790.110
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 115.0.1901.183

[√] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by mvanbeusekom** [comment]
Start from geolocator_windows version 0.2.0 (geolocator, version 10.0.0) the `altitude`, `heading` and `speed` values will be returned as `0` when these values are not available. This should be in sync with the other supported platforms.
