### ISSUE TITLE
Getting error when running example "No file or variants found for asset: packages/baseflow_plugin_template/logo.png"

### ISSUE THREAD

**Issue by brand17** [Baseflow/flutter-geolocator#1224]
## 🐛 Bug Report

When I run example - I am getting "No file or variants found for asset: packages/baseflow_plugin_template/logo.png"
### Expected behavior
Example running without errors
### Reproduction steps
1) Clone repository
2) Open folder "geolocator/example" in VSCode (with Flutter extention)
3) Run "lib/main.dart"
### Configuration

**Version:** 9.0.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by brand17** [comment]
I created the folders `packages/baseflow_plugin_template` in `example` folder and copied two `.png` files there from `baseflow_plugin_template` package. And it works now

**Comment by muziyuqi** [comment]
> and in my case, pubspec.yaml should be edit with add  " - packages/baseflow_plugin_template/" to assets, like:👇🏻
flutter:
  assets:
    - packages/baseflow_plugin_template/

**Comment by JeroenWeener** [comment]
Closing this issue, as it was fixed as part of #1264.
