### ISSUE TITLE
[Warning] Uses or overrides a deprecated API on Android.

### ISSUE THREAD

**Issue by vqthanh1412489** [Baseflow/flutter-geolocator#1231]
## 🐛 Bug Report

`/.pub-cache/hosted/pub.dartlang.org/geocoding_android-2.1.0/android/src/main/java/com/baseflow/geocoding/Geocoding.java uses or overrides a deprecated API.`

### Expected behavior
This warning does not show

### Reproduction steps
Run the project as usual and you can see this warning.

### Configuration

**Version:**
^9.0.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by al-fahad-bd** [comment]
Same issue occurred when using (geocoding: ^2.1.0)

**Comment by JeroenWeener** [comment]
This issue seems to be related to `geocoding`, not `geolocator`. You can file an issue here: https://github.com/Baseflow/flutter-geocoding/issues/new/choose
