### ISSUE TITLE
getPositionStream does not work proper in Android 12 compare to other Android versions

### ISSUE THREAD

**Issue by RupeshKalkani** [Baseflow/flutter-geolocator#1232]
## 🐛 getPositionStream does not work proper in Android 12 compare to other Android versions

I got the new coordinates using getPositionStream and I stored them in a list. Then I displayed the list in the map.

You can see the attachment screenshot, I have drawn the poly line in 2 different versions of android mobile. But the result was different. 
First Screenshot = Android 11 (Samsung M30S).
Second Screenshot = Android 12 (Samsung F23),

Currently I am using geolocator: ^9.0.2.
Do I need to do some configuration for Android 12?

Android 11 (Samsung M30S)
![Screenshot_20230318-162808](https://user-images.githubusercontent.com/77331571/226102172-001c5aa0-8b67-40d6-9015-8f2eebb7bdca.jpg)

Android 12 (Samsung F23)
![Screenshot_20230318-162812](https://user-images.githubusercontent.com/77331571/226102198-a73726d7-39a8-45a8-b620-3ddc0fb576a5.jpg)

### Configuration

(geolocator: ^9.0.2.)

**Platform:** 
- [ ] :robot: Android 12

**Comment by TimHoogstrate** [comment]
Dear @RupeshKalkani,

It depends a bit on what you are expecting. Can you send us the settings that you are currently using? The locations will be determined based on the settings in combination with thinks like GPS and Wifi connections. I see that one devices shows the location icon, the other one has a 4g connection. This already can be a big difference. 

Kind regards,

Tim
