### ISSUE TITLE
doesn't allow null

### ISSUE THREAD

**Issue by SupremePPC** [Baseflow/flutter-geolocator#1235]
### Expected behaviour
Ask for permission to access GEO location and GPS
../../.pub-cache/hosted/pub.dev/geolocator_apple-2.2.5/lib/src/geolocator_apple.dart:53:30: Error: A non-null value must be returned since the return type 'LocationPermission' doesn't allow null.
 - 'LocationPermission' is from 'package:geolocator_platform_interface/src/enums/location_permission.dart' ('../../.pub-cache/hosted/pub.dev/geolocator_platform_interface-4.0.7/lib/src/enums/location_permission.dart').
  Future<LocationPermission> requestPermission() async {
  
### Reproduction steps
build fails with the following error:

### Configuration

**Version:** latest

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by JeroenWeener** [comment]
Hi @SupremePPC, thank you for taking the time to file this issue!

Your issue report states that this behavior is relevant for both Android and iOS. However, the error you provide seems to be iOS specific. Could you confirm on which platforms you are experiencing this behavior?

Could you provide example code that showcases the use case in which you encounter this error? You can easily create an example by creating a new flutter project and tweaking `main.dart`. Sending the contents of `main.dart` here, or linking a repo, helps others in looking into this issue.
