### ISSUE TITLE
Configuration for linux / snapcraft

### ISSUE THREAD

**Issue by moneytoo** [Baseflow/flutter-geolocator#1236]
The `geolocator_linux` plugin seems to be working fine for me on the latest Ubuntu 22.04.2 LTS. When packed in a [snap](https://docs.flutter.dev/deployment/linux#overview-of-snapcraft), geolocator works as well. However, when limiting the access to resources by switching from `confinement: devmode` to `confinement: strict`, geolocator no longer works. Adding the [`location-observe`](https://snapcraft.io/docs/location-observe-interface) interface doesn't help. Any guidance specific to this plugin on how to resolve this?

**Comment by mvanbeusekom** [comment]
Hi @moneytoo, 

Thank you for raising this issue, my Linux experience is extremely limited so I am tagging some community members who worked on the Linux implementation in the hope they can provide some guidance. 

@jpnurmi, @pablojimpas, is this something you can and are willing to look into?
