### ISSUE TITLE
 Windows / Desktop getCurrentPosition without Network Causes Crash 

### ISSUE THREAD

**Issue by AndreLuizNogueira** [Baseflow/flutter-geolocator#1240]
### Expected behavior

on  Windows / Desktop getCurrentPosition without Network Causes Crash

### Reproduction steps

On Windows, Turn off all Network Connections and Then Try :

```
      final position = await Geolocator.getCurrentPosition(
        desiredAccuracy: LocationAccuracy.high,
      );
```

It will Crash the App. Try-Catch Didn't Help

### Configuration

**Version:** 9.0.2

**Platform:** 
Windows

**Comment by TimHoogstrate** [comment]
Dear @AndreLuizNogueira,

Can you explain something outbox your environment (windows version and possibly device gps chip) and paste the output of `flutter doctor -v` below this issue? And do you have the output of the crashlog? Because it is unclear to me how I can reproduce this issue.

**Comment by AndreLuizNogueira** [comment]
> Dear @AndreLuizNogueira,
> 
> Can you explain something outbox your environment (windows version and possibly device gps chip) and paste the output of `flutter doctor -v` below this issue? And do you have the output of the crashlog? Because it is unclear to me how I can reproduce this issue.

**Comment by AndreLuizNogueira** [comment]
> Dear @AndreLuizNogueira,
> 
> Can you explain something outbox your environment (windows version and possibly device gps chip) and paste the output of `flutter doctor -v` below this issue? And do you have the output of the crashlog? Because it is unclear to me how I can reproduce this issue.

Sorry for The Delay.  the problem still ocurs. Here in my github I pushed a sample app that get location on click. if you run this on windows, with network off it will crash.

I know it can't get the location without internet, but it should'nt crash my app.

https://github.com/AndreLuizNogueira/flutter_application_1

**Comment by milindgoel15** [comment]
It also crashes if the location service is off altogether in the windows settings:
![image](https://github.com/Baseflow/flutter-geolocator/assets/45682747/64d92d06-587f-489a-8472-c32d645e7a6a)

Unless this is on, then the getCurrentPosition works.
