### ISSUE TITLE
Make Permissions optional (especially NSLocationAlwaysAndWhenInUseUsageDescription)

### ISSUE THREAD

**Issue by Aulig** [Baseflow/flutter-geolocator#1241]
## 🏗 Enhancement Proposal

If your app only needs access to the location while the app is in use, the app should only specify NSLocationWhenInUseUsageDescription in Info.plist, otherwise you could get problems with the app reviewers (you may not request permissions you don't need/use).

If you do that though, you will get this e-mail from Apple every time you upload a build: 

ITMS-90683: Missing purpose string in Info.plist - Your app’s code references one or more APIs that access sensitive user data, or the app has one or more entitlements that permit such access. The Info.plist file for the “Runner.app” bundle should contain a **NSLocationAlwaysAndWhenInUseUsageDescription** key with a user-facing purpose string explaining clearly and completely why your app needs the data. If you’re using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. For details, visit: https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources. 

My proposed solution: Offer compiling out each permission, for example like it's done in [the permission_handler package](https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/README.md) (see iOS section where certain permissions can be disabled using the Podfile). The [audio_session plugin ](https://github.com/ryanheise/audio_session#ios-setup) does something like that too.

### Pitch

Getting the e-mail from Apple is quite confusing at first (until you realize you can ignore it). I could imagine Apple not ignoring it in the future though, at which point a solution has to be found.
Apart from that, it's always annoying if you're uploading an app to a customer's developer account and they get the email that the app has issues.

### Platforms affected
- :iphone: iOS

**Comment by themumy10** [comment]
This is urgent

**Comment by H7mosh** [comment]
How Did You Solve It Please . I'm Facing The Same Issue in My App

**Comment by ondanplatform** [comment]
any update?

**Comment by Aulig** [comment]
> This is urgent

> any update?

Please upvote the original issue instead of posting these comments that alert everyone watching the issue. When there is news, you will see it here.

**Comment by Aulig** [comment]
Just saw that this has been fixed now: #1403 
Thanks @781flyingdutchman :)
