### ISSUE TITLE
web app not getting past loading screen even after building it using null safety.

### ISSUE THREAD

**Issue by 3Nitinkaushik** [Baseflow/flutter-geolocator#1242]
## 🐛 Bug Report

I have built a weather app using geolocator it works fine on emulator and physical device but does not get past loading screen while running it on web, i have tried to deploy it on github after building web without null safety but still it does not work. you can check my code here: https://github.com/3Nitinkaushik/weatherapp

### Configuration

**Version:** 1.x

**Platform:** 
-[]:web
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by TheGlorySaint** [comment]
Using macOS 13.3 and xCode 14.3. Before the Update of macOS i haven't had the issue, since updated I have the issue.

@mvanbeusekom

**Comment by TimHoogstrate** [comment]
Dear @TheGlorySaint or @3Nitinkaushik,

Are you still experiencing this issue? To be able to reproduce this issue can you past the output of `Flutter doctor -v` to this issue?

Kind regards,

**Comment by TheGlorySaint** [comment]
@TimHoogstrate Still experience the issue.

[✓] Flutter (Channel stable, 3.10.5, on macOS 13.5 22G74 darwin-arm64, locale de-DE)
    • Flutter version 3.10.5 on channel stable at /opt/homebrew/Caskroom/flutter/3.10.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (7 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/dqss/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.5 22G74 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by 3Nitinkaushik** [comment]
> Dear @TheGlorySaint or @3Nitinkaushik,
> 
> Are you still experiencing this issue? To be able to reproduce this issue can you past the output of `Flutter doctor -v` to this issue?
> 
> Kind regards,

no, the issue is resolved now
