### ISSUE TITLE
App takes longer time to launch after allowing location permission on Android 12 and above.

### ISSUE THREAD

**Issue by rahulbhuwan** [Baseflow/flutter-geolocator#1243]
## 🐛 Bug Report

After granting location permission whenever launching the app it is taking longer time to launch on Android 12 and above. When removed location permission from app info after that it's launching smoothly as it should. And agian if i grant location permission launch time increases again like before.

### Expected behavior
Launch should happens smoothly as it should eventhough location permission granted.

### Reproduction steps
Just allow location permission after that close the app and launch again App launch will take longer time to launch.

### Configuration

**Version:** 
geolocator 9.0.2
Android 12 or above

**Platform:** 
- [x] :robot: Android

**Comment by Maringmei** [comment]
same problem

**Comment by ThomasLilley** [comment]
Yeah also experiencing this behaviour on android 12+ fine on other versions of android and iOS

**Comment by rahulbhuwan** [comment]
@ThomasLilley using workaround it's working as it should?

**Comment by ThomasLilley** [comment]
@rahulbhuwan mostly yes, it still sometimes takes a long time, but retrying seems to work. But a proper fix would be preferable

**Comment by rahulbhuwan** [comment]
@ThomasLilley @Maringmei  You guys found any solution for this?

**Comment by bluespada** [comment]
> edAccu

I have same issue too, in debug mode it's running so very well
but when i try build to apk or run by `--release` arguments whenever i allow location permission the next app launch it's give error.

i have a release log may it's not helping too much, but i hope it can helped.

`
D/FlutterGeolocator(24933): Creating service.
D/FlutterGeolocator(24933): Binding to location service.
I/flutter (24933): AppModule started!
D/FlutterGeolocator(24933): Flutter engine connected. Connected engine count 1
F/crash_dump64(24991): crash_dump.cpp:485] failed to attach to thread 809: Permission denied
F/crash_dump64(24994): crash_dump.cpp:485] failed to attach to thread 952: Permission denied
I/flutter (24933): Permission: While In Use
`

**Comment by bluespada** [comment]
> @ThomasLilley @Maringmei You guys found any solution for this?

hey do you find any solution ?

**Comment by rahulbhuwan** [comment]
@andreisas06 Hello, I am just using this GeolocatorPlatform geoLocatorPlatform = GeolocatorPlatform.instance;
    final position = await geoLocatorPlatform.getCurrentPosition(); to fetch current location inside a async method. This is working fine. Actually while requesting location permission if I deny or allo coarse location then app is working fine as expected but if i allow fine location then whenever I am launching the app it takes around 10 sec to launch. In logcat it seems its taking long to connect with location service .  Logcat seeing this error while launching.
 E  [LocationManager] Location request A96384B6(Listener) gps interval=5000ms (min=5000ms) from com.google.android.gms.persistent[WorkSource app package id] (10235_FINE_fg_false_foreground).

**Comment by rahulbhuwan** [comment]
@andreisas06 And I want add more when i launch the app following steps i see : 
D/FlutterGeolocator(19169): Attaching Geolocator to activity
D/FlutterGeolocator(19169): Creating service.
D/FlutterGeolocator(19169): Binding to location service.
D/FlutterGeolocator(19169): Geolocator foreground service connected
D/FlutterGeolocator(19169): Initializing Geolocator services
D/FlutterGeolocator(19169): Flutter engine connected. Connected engine count 1

On this line execution pauses for sometime like 5 to 10 secs and then start executing again.

**Comment by ThomasLilley** [comment]
> @andreisas06 And I want add more when i launch the app following steps i see : D/FlutterGeolocator(19169): Attaching Geolocator to activity D/FlutterGeolocator(19169): Creating service. D/FlutterGeolocator(19169): Binding to location service. D/FlutterGeolocator(19169): Geolocator foreground service connected D/FlutterGeolocator(19169): Initializing Geolocator services D/FlutterGeolocator(19169): Flutter engine connected. Connected engine count 1
> 
> On this line execution pauses for sometime like 5 to 10 secs and then start executing again.

Yes this is what’s happening to me too. The app completely halts on launch for 10 seconds or sometimes up to 40 seconds and then starts executing again, no errors from flutter but I can see the same info in logcat

**Comment by FrancescoPenengo** [comment]
Hi everybody, I found a temporary solution by downgrading to version 8.2.1.

**Comment by Dr-Usman** [comment]
@FrancescoPenengo Thanks for the workaround and it works correctly..

**Comment by rahulbhuwan** [comment]
@FrancescoPenengo This work around did not work for me, This started giving some other error. May be because mine flutter, android and depending plugins are up to date.

**Comment by andreisas06** [comment]
@rahulbhuwan could you please provide me with your AndroidManifest file and the output from `flutter doctor`? It would be very helpful if you can provide a minimal code sample, that gives you the same result as now. `GeolocatorPlatform geoLocatorPlatform = GeolocatorPlatform.instance;
final position = await geoLocatorPlatform.getCurrentPosition();` is missing the surrounding context, which could prove to be important and help solve the issue faster. Also, is this a device specific issue, or did you encounter this problem on other Android devices as well?

**Comment by mvanbeusekom** [comment]
Adding to @andreisas06's question for more information, can someone confirm this is related to using the Geolocator in combination with running the background services? From some of the logs provided it seems an additional Flutter engine is created. This happens when background services are turned on and might be the cause of the delay.

Code snippets or even better a sample application would help us a lot understanding and tackling this issue.

**Comment by rahulbhuwan** [comment]
@andreisas06 This issue I am facing on android devices after upgrading flutter and every plugins. I am just fetching current position that also not in root screens, it's inside screen . After integrading flutter geolocator I am requesting checking location permission and if it is not there so requesting the same. If i approve coarse location app is workin as expected ( when i close app and launch again from application launcher it's launching smoothly) but if i approve fine locaion then I am getting location smootyhly but if i close the app and launch again then it stuck on launch screen for sometimes like 5 to 10 secs and then it navigate to desired page. I am using geolator version geolocator 9.0.2. 

Flutter doctor output - 
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.4 22F66 darwin-arm64, locale
    en-IN)
    • Flutter version 3.10.2 on channel stable 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (4 weeks ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (3 available)
    • SM G780F (mobile) • adb-RZ8R11NY6ZD-GCvMyI._adb-tls-connect._tcp. •
      android-arm64  • Android 13 (API 33)
    • macOS (desktop)   • macos                                         •
      darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)      • chrome                                        •
      web-javascript • Google Chrome 114.0.5735.133

[✓] Network resources
    • All expected network resources are available.

• No issues found!


Manifest file I have put permisson for location access. Below is manifest : 

 <uses-feature
        android:name="android.hardware.camera"
        android:required="false" />

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    
    <uses-permission android:name="com.google.android.gms.permission.ACTIVITY_RECOGNITION" />
    
    <uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.VIBRATE"/>
    <uses-permission android:name="android.permission.USE_BIOMETRIC"/>


    <queries>
        
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="https" />
        </intent>
        
        <intent>
            <action android:name="android.intent.action.DIAL" />
            <data android:scheme="tel" />
        </intent>
        
        <intent>
            <action android:name="android.intent.action.SEND" />
            <data android:mimeType="*/*" />
        </intent>
    </queries>
    <application
        android:allowBackup="false"
        android:fullBackupContent="false"
        android:icon="@mipmap/ic_launcher"
        android:label="${variant}"
        android:largeHeap="true"
        android:requestLegacyExternalStorage="true">

        <activity
            android:name=".MainActivity"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:launchMode="singleTop"
            android:screenOrientation="portrait"
            android:networkSecurityConfig="@xml/network_security_config"
            android:theme="@style/LaunchTheme"
            android:windowSoftInputMode="adjustResize"
            android:exported="true">
            <meta-data
                android:name="io.flutter.embedding.android.NormalTheme"
                android:resource="@style/NormalTheme"
                />

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

      

        <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver"
            android:exported="false">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
                <action android:name="android.intent.action.MY_PACKAGE_REPLACED"/>
            </intent-filter>
        </receiver>

        <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver" />
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="@string/default_notification_channel_id" />

        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />

    </application>

Still I am not sure why this is happening with fine location access permission. For getting current location I am using below code in a method.

_fetchLocation() async {
    GeolocatorPlatform geoLocatorPlatform = GeolocatorPlatform.instance;
    final Position? position = await geoLocatorPlatform.getCurrentPosition();
    if (position != null) {
     // Showing to UI
    }
  }

@mvanbeusekom I am not using any background service here. But a WorkManager to upload Image but that get triggered when user capture images and that WorkManager is not periodi it's one shot.

**Comment by mvanbeusekom** [comment]
@rahulbhuwan,

Can you provide the complete code flow that results in the calling of `_fetchLocation` method? The method it self looks fine, however we suspect the location is requested (and awaited) during the start up of the application causing the App to hang until the location is acquired.

However without the complete code it is really hard to assist and help locate the error. Alternatively it would help if you could provide a small example application reproducing the behaviour. As mentioned earlier, the example application part of the geolocator plugin source code does not show this behaviour.

**Comment by hrajwade96** [comment]
> > @andreisas06 And I want add more when i launch the app following steps i see : D/FlutterGeolocator(19169): Attaching Geolocator to activity D/FlutterGeolocator(19169): Creating service. D/FlutterGeolocator(19169): Binding to location service. D/FlutterGeolocator(19169): Geolocator foreground service connected D/FlutterGeolocator(19169): Initializing Geolocator services D/FlutterGeolocator(19169): Flutter engine connected. Connected engine count 1
> > On this line execution pauses for sometime like 5 to 10 secs and then start executing again.
> 
> Yes this is what’s happening to me too. The app completely halts on launch for 10 seconds or sometimes up to 40 seconds and then starts executing again, no errors from flutter but I can see the same info in logcat

I am also facing this issue, 
Is there a way to see this using systrace or in dev tools?

**Comment by AnggaSP** [comment]
We've bisected and found that https://github.com/Baseflow/flutter-geolocator/commit/b214430ad635cf802fdae84f2c96a49d861c05cf is the caused for the long startup after granting permission.

I'm not sure if its because of how this plugin starts up but reverting it fixed the issue for us.

**Comment by hanifmhd** [comment]
> b214430

same issue with me, don't set background service, just get current position when click button

**Comment by hanifmhd** [comment]
> 



> @andreisas06 This issue I am facing on android devices after upgrading flutter and every plugins. I am just fetching current position that also not in root screens, it's inside screen . After integrading flutter geolocator I am requesting checking location permission and if it is not there so requesting the same. If i approve coarse location app is workin as expected ( when i close app and launch again from application launcher it's launching smoothly) but if i approve fine locaion then I am getting location smootyhly but if i close the app and launch again then it stuck on launch screen for sometimes like 5 to 10 secs and then it navigate to desired page. I am using geolator version geolocator 9.0.2.
> 
> ```
> Flutter doctor output - 
> [✓] Flutter (Channel stable, 3.10.2, on macOS 13.4 22F66 darwin-arm64, locale
>     en-IN)
>     • Flutter version 3.10.2 on channel stable 
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 9cd3d0d9ff (4 weeks ago), 2023-05-23 20:57:28 -0700
>     • Engine revision 90fa3ae28f
>     • Dart version 3.0.2
>     • DevTools version 2.23.1
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
>     • Platform android-33, build-tools 33.0.0
>     • Java binary at: /Applications/Android
>       Studio.app/Contents/jbr/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build
>       17.0.6+0-17.0.6b802.4-9586694)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Build 14E300c
>     • CocoaPods version 1.11.2
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2022.2)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build
>       17.0.6+0-17.0.6b802.4-9586694)
> 
> [✓] VS Code (version 1.79.2)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.66.0
> 
> [✓] Connected device (3 available)
>     • SM G780F (mobile) • adb-RZ8R11NY6ZD-GCvMyI._adb-tls-connect._tcp. •
>       android-arm64  • Android 13 (API 33)
>     • macOS (desktop)   • macos                                         •
>       darwin-arm64   • macOS 13.4 22F66 darwin-arm64
>     • Chrome (web)      • chrome                                        •
>       web-javascript • Google Chrome 114.0.5735.133
> 
> [✓] Network resources
>     • All expected network resources are available.
> 
> • No issues found!
> ```
> 
> Manifest file I have put permisson for location access. Below is manifest :
> 
> ```
>  <uses-feature
>         android:name="android.hardware.camera"
>         android:required="false" />
> 
>     <uses-permission android:name="android.permission.INTERNET" />
>     <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
>     <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
>     <uses-permission android:name="android.permission.CAMERA" />
>     <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
>     <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
>     
>     <uses-permission android:name="com.google.android.gms.permission.ACTIVITY_RECOGNITION" />
>     
>     <uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" />
>     <uses-permission android:name="android.permission.WAKE_LOCK" />
>     <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
>     <uses-permission android:name="android.permission.VIBRATE"/>
>     <uses-permission android:name="android.permission.USE_BIOMETRIC"/>
> 
> 
>     <queries>
>         
>         <intent>
>             <action android:name="android.intent.action.VIEW" />
>             <data android:scheme="https" />
>         </intent>
>         
>         <intent>
>             <action android:name="android.intent.action.DIAL" />
>             <data android:scheme="tel" />
>         </intent>
>         
>         <intent>
>             <action android:name="android.intent.action.SEND" />
>             <data android:mimeType="*/*" />
>         </intent>
>     </queries>
>     <application
>         android:allowBackup="false"
>         android:fullBackupContent="false"
>         android:icon="@mipmap/ic_launcher"
>         android:label="${variant}"
>         android:largeHeap="true"
>         android:requestLegacyExternalStorage="true">
> 
>         <activity
>             android:name=".MainActivity"
>             android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
>             android:hardwareAccelerated="true"
>             android:launchMode="singleTop"
>             android:screenOrientation="portrait"
>             android:networkSecurityConfig="@xml/network_security_config"
>             android:theme="@style/LaunchTheme"
>             android:windowSoftInputMode="adjustResize"
>             android:exported="true">
>             <meta-data
>                 android:name="io.flutter.embedding.android.NormalTheme"
>                 android:resource="@style/NormalTheme"
>                 />
> 
>             <intent-filter>
>                 <action android:name="android.intent.action.MAIN" />
> 
>                 <category android:name="android.intent.category.LAUNCHER" />
>             </intent-filter>
>         </activity>
> 
>       
> 
>         <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver"
>             android:exported="false">
>             <intent-filter>
>                 <action android:name="android.intent.action.BOOT_COMPLETED"/>
>                 <action android:name="android.intent.action.MY_PACKAGE_REPLACED"/>
>             </intent-filter>
>         </receiver>
> 
>         <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver" />
>         <meta-data
>             android:name="com.google.firebase.messaging.default_notification_channel_id"
>             android:value="@string/default_notification_channel_id" />
> 
>         <meta-data
>             android:name="flutterEmbedding"
>             android:value="2" />
> 
>     </application>
> ```
> 
> Still I am not sure why this is happening with fine location access permission. For getting current location I am using below code in a method.
> 
> ```dart
> _fetchLocation() async {
>     GeolocatorPlatform geoLocatorPlatform = GeolocatorPlatform.instance;
>     final Position? position = await geoLocatorPlatform.getCurrentPosition();
>     if (position != null) {
>      // Showing to UI
>     }
>   }
> ```
> 
> @mvanbeusekom I am not using any background service here. But a WorkManager to upload Image but that get triggered when user capture images and that WorkManager is not periodi it's one shot.

same issue with me, don't set background service, just get current position when click button

**Comment by kahfikud** [comment]
> We've bisected and found that [b214430](https://github.com/Baseflow/flutter-geolocator/commit/b214430ad635cf802fdae84f2c96a49d861c05cf) is the caused for the long startup after granting permission.
> 
> I'm not sure if its because of how this plugin starts up but reverting it fixed the issue for us.

may i ask which version of geolocator that you use? i'm currently got the same problem and reverting the geolocator android to 4.1.4 didn't fix this

**Comment by rymesaint** [comment]
i'm having this issue too on version 10.0.1

**Comment by taufiqridha** [comment]
So i'm having this issue too. 
After some debug this issue came from another library safe_device. I'm using this to detect mock locations and it seems to make the issues come in. Remove safe_device the issues disappear.

**Comment by fhgomeshelp** [comment]
I´m also facing this, currently using 10.0.0

**Comment by amanInfograins** [comment]
> Hi everybody, I found a temporary solution by downgrading to version 8.2.1.

IT IS WORKING FINE . IT IS THE PERFECT SOLUTION FOR THIS ISSUE

**Comment by vargascarlitos** [comment]
Same problem here, i downgrade the version package for 8.2.1 :(

**Comment by urbanjagodic** [comment]
It looks like the change from 4.4.0 to 5.0.0 was the dependency upgrade 
![image](https://github.com/Baseflow/flutter-geolocator/assets/34213584/1f7b8a0e-d189-4fca-9fda-0a3d55a4ebbe)

of `google play services location` dependency to 21.+ version which according to this issue's comment is the source of slow app startup latency: https://github.com/Baseflow/flutter-geolocator/issues/1243#issuecomment-1772328273

The real fix for this package should be lowering this dependency and not removing other packagesas a workaround from user's codebase which are essential to app's core functionality.

**Comment by ernestomar** [comment]
i'm having this issue too on version 10.0.1

**Comment by PabloCir** [comment]
> So i'm having this issue too. After some debug this issue came from another library safe_device. I'm using this to detect mock locations and it seems to make the issues come in. Remove safe_device the issues disappear.

yeap, safe_device plugin was the problem... deleting this works fine!

**Comment by picmanadhul** [comment]
> ## 🐛 Bug Report
> After granting location permission whenever launching the app it is taking longer time to launch on Android 12 and above. When removed location permission from app info after that it's launching smoothly as it should. And agian if i grant location permission launch time increases again like before.
> 
> ### Expected behavior
> Launch should happens smoothly as it should eventhough location permission granted.
> 
> ### Reproduction steps
> Just allow location permission after that close the app and launch again App launch will take longer time to launch.
> 
> ### Configuration
> **Version:** geolocator 9.0.2 Android 12 or above
> 
> **Platform:**
> 
> * [x]  🤖 Android

did it get reolved

**Comment by lukeirvin** [comment]
I'm experiencing the same issue. I'm running the latest Android Studio & Flutter version.

**Comment by lukeirvin** [comment]
> @lukeirvin If you are using safe_device plugin then remove and try. Issue should be fix as mine got resolved by doing that.

Thanks for the reply @rahulbhuwan. I did have this package (though I wasn't using it). I removed that & some other unused packages but still stuck.

**Comment by rrrrray** [comment]
> @lukeirvin If you are using safe_device plugin then remove and try. Issue should be fix as mine got resolved by doing that.

@rahulbhuwan  -- Thanks for this tip! I was going crazy trying to figure out why startup was taking 30+ seconds after granting location permissions and removing safe_device fixed it. I *never* would have suspected that package was causing it and wasn't using it anyway.

**Comment by joshuamoreno1** [comment]
> @lukeirvin If you are using safe_device plugin then remove and try. Issue should be fix as mine got resolved by doing that.

God has a reserved place for you in Heaven. Thanks a lot!!!!

**Comment by dbard** [comment]
@lukeirvin THANK YOU!  I don't want to think about how long it might have taken to figure that out.

**Comment by YashSherla** [comment]
Hello @lukeirvin i'm getting same issue flutter_version:3.27.1 name: boxxapp_partner
description: An application for multivendor ecommerce restaurant.
publish_to: 'none'
version: 2.0.0+8

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.0.5
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^17.2.2
  path_provider: ^2.1.4
  url_strategy: ^0.3.0
  shimmer_animation: ^2.2.1
  image_picker: ^1.1.2
  http: ^1.2.2
  pin_code_fields: ^8.0.1
  url_launcher: ^6.3.0
  vibration: ^2.0.0
  audioplayers: ^6.1.0
  flutter_switch: ^0.3.2
  flutter_typeahead: ^4.3.7
  phone_numbers_parser: ^9.0.0
  country_code_picker: ^3.0.0
  flutter_html: ^3.0.0-alpha.6
#  bluetooth_thermal_printer: ^0.0.6
  photo_view: ^0.15.0
  # image_compression_flutter: ^1.0.4
  win32: ^5.2.0
  google_maps_flutter: ^2.9.0
  cached_network_image: ^3.4.1
  print_bluetooth_thermal: ^1.1.1
  flutter_esc_pos_utils: ^1.0.1
#  esc_pos_utils: ^1.1.0
  screenshot: ^3.0.0
  http_parser: ^4.1.0
  path: ^1.9.0
  intl: ^0.19.0
  image: ^4.2.0
  dotted_border: ^2.1.0
  carousel_slider: ^5.0.0
  just_the_tooltip: ^0.0.12
  flutter_inappwebview: ^6.0.0
  permission_handler: ^11.3.1
  flutter_svg: ^2.0.10+1
  card_swiper: ^3.0.1
  universal_html: ^2.0.8
  file_picker: ^8.1.2
  video_player: ^2.9.1
  chewie: ^1.8.4
  fluttertoast: ^8.2.8
  flutter_launcher_icons: ^0.13.1
  appinio_social_share: ^0.3.2
  # contacts_service: ^0.6.3
  app_links: ^6.3.3
  firebase_analytics: ^11.4.1
  flutter_widget_from_html_core: ^0.15.2

dependency_overrides:
  collection: ^1.19.0
  web: ^1.0.0
  geolocator: ^7.4.0  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/notification.mp3

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logo2.png"
  min_sdk_android: 21
