### ISSUE TITLE
Windows app crashes when Wi-Fi off or "no internet connection"

### ISSUE THREAD

**Issue by Ali-Fadaei** [Baseflow/flutter-geolocator#1247]
## 🐛 Bug Report

when Geolocator.getCurrentPosition  called in windows which Wi-Fi is off, after few seconds app is crash!!!
also, sometimes this crash happens when Wi-Fi is on but no internet connection on it!
this issue makes GeoLocator fully unstable for release.

**Version:** 9.0.2

**Platform:** 
- [x] 🪟 11

**Comment by TimHoogstrate** [comment]
Dear @Ali-Fadaei or @DKAC,

Can you past the output of `flutter doctor -v` some minimal reproducible code and steps to reproduce to this issue? The it helps a lot to investigate this issue.

**Comment by DKAC** [comment]
I will provide a minimum code example as soon as I am back from vacation (in 2 weeks). Thanks for looking into it...

**Comment by DKAC** [comment]
Sorry, I couldn't provide more info yet. I hope to be able to do it later this week...

**Comment by mvanbeusekom** [comment]
Hi @DKAC, @Ali-Fadaei,

After doing some research this seems to be a known issue in WinRT (see also https://stackoverflow.com/a/35838740/5167831). Thanks to @jherkel, we have an improved version which will catch the error and return it to the Flutter side so you can handle it in your application.

Running `flutter pub upgrade` should help you out.

**Comment by DKAC** [comment]
Hi @mvanbeusekom, I just upgraded and tested the fix. Works like a charm! Thank you very much!!!
