### ISSUE TITLE
Altitude accuracy

### ISSUE THREAD

**Issue by mbn18** [Baseflow/flutter-geolocator#1248]
While migrating from a different library to this one, I noticed that the `Position` class is missing **altitude accuracy**.
I think that in some scenarios this value might be useful.
Same goes from **bearing accuracy**.

**Comment by JeroenWeener** [comment]
Hi @mbn18, thank you for bringing this to our attention.

We just released a new version of the plugin (10.1.0) that exposes these fields if the underlying APIs supports it. They are fully supported on Android, iOS and macOS. On web and Windows only the altitude accuracy is available, and on Linux neither is available.
