### ISSUE TITLE
Build of example app fails

### ISSUE THREAD

**Issue by christianfl** [Baseflow/flutter-geolocator#1249]
## 🐛 Bug Report

Building the linux example app failed with error:

```
ERROR: No file or variants found for asset: packages/baseflow_plugin_template/logo.png.
ERROR: Target release_bundle_linux-arm64_assets failed: Exception: Failed to bundle asset files
``` 

### Expected behavior

App built successfully.

### Reproduction steps

1. Clone repo: `git clone https://github.com/Baseflow/flutter-geolocator.git`.
2. Go to linux example app: `cd flutter-geolocator/geolocator_linux/example`.
3. Compile: `flutter build linux --release`.

### Configuration

**Version:** 0.1.2 (Current upstream e60daab16c5568ee46ff3c8851b16167c3e412e9)

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [X] linux

---

Possible fix. Change the `pubspec.yaml` from:

```
  assets:
    - res/images/baseflow_logo_def_light-02.png
    - res/images/poweredByBaseflowLogoLight@3x.png
    - packages/baseflow_plugin_template/logo.png
    - packages/baseflow_plugin_template/poweredByBaseflow.png
```

to:

```
  assets:
    - res/images/baseflow_logo_def_light-02.png
    - res/images/poweredByBaseflowLogoLight@3x.png
    - packages/baseflow_plugin_template/assets/logo.png
    - packages/baseflow_plugin_template/assets/poweredByBaseflow.png
```

`/assets` is missing two times here.

**Comment by JeroenWeener** [comment]
Closing this issue, as it was fixed as part of #1264.
