### ISSUE TITLE
Geolocator getPositionStream is not working 

### ISSUE THREAD

**Issue by isshort** [Baseflow/flutter-geolocator#1253]
## 🐛 Bug Report

When attempting to use the getPositionStream function,I am unable to obtain a consistent stream of location updates.

I have checked that all necessary permissions have been granted, and have tested the function on multiple devices with the same result. I have also tried to update to the latest version of the geolocator package, but the issue persists.

As this function is critical to the functionality of my project, I would appreciate any assistance you can provide in resolving this issue as soon as possible.

Thank you for your attention to this matter. I look forward to hearing back from you soon.

Best regards,
**Version:** 9.0.2

**Platform:** 
- [x] :iphone: iOS 
- [x] :robot: Android
 ### Android

![Screenshot_1683541918](https://user-images.githubusercontent.com/37234355/236802369-1a0993f8-d72a-44fe-8fd2-73101a05c669.png)
### IOS

![Simulator Screenshot - iPhone 14 Pro Max - 2023-05-08 at 16 30 15](https://user-images.githubusercontent.com/37234355/236802377-5194c455-ef43-4463-b2ed-d788d3991b3f.png)

**Comment by andreisas06** [comment]
Hello @isshort , thank you for submitting the issue. To better understand the problem you're facing, could you please provide a code sample related to the issue? This would greatly help in diagnosing the problem and providing an appropriate solution faster.
