### ISSUE TITLE
Problem With geolocator_android

### ISSUE THREAD

**Issue by Prefect001** [Baseflow/flutter-geolocator#1255]
I am building a flutter application that uses geolocation.

When I run the app on my android device I get the following error.

\AppData\Local\Pub\Cache\hosted\[pub.dev](http://pub.dev/)\geolocator_android-2.1.0\android\src\main\java\com\baseflow\geolocator\permission\PermissionUtils.java:28: error: cannot find symbol
                context.getUserId()
                       ^
  symbol:   method getUserId()
  location: variable context of type Context
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':geolocator_android:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

I have no errors on the code for the app. My pubspec.yaml file has the following packages
 geolocator: ^7.7.1
  geolocator_android: ^2.0.0

I have been stuck on this problem for days now. Help will be much appreciated. Thanks in advance.

**Comment by flodaniel** [comment]
Can you try updating your geolocator dependency? Also you do not need to declare the `geolocator_android` in your pubspec.yml. 

Reference for latest version, installation instruction and usage are always on pub.dev: https://pub.dev/packages/geolocator
