### ISSUE TITLE
What's going on with this plugin?

### ISSUE THREAD

**Issue by bartekpacia** [Baseflow/flutter-geolocator#1257]
Thank you for your open-source, volunteer work for the community. I highly appreciate it - huge kudos.

That said, the issues are piling up, the last commit was 8th months ago. What's happening?

If you don't have the resources to maintain it, please consider donating it to [fluttercommunity](https://github.com/fluttercommunity). Alternatively, you can start looking for volunteer maintainers to help with it.

**Comment by bartekpacia** [comment]
The other very popular geolocation plugin – [package:location](https://pub.dev/packages/location) – is also basically unmaintained.

And both are _Flutter Favorite_s.

**Comment by keeganskeate** [comment]
@bartekpacia you're always welcome to address issues yourself or even [sponsor Baseflow](https://github.com/sponsors/Baseflow) to expedite their work. It's a free world and I don't see why Baseflow needs to explain why they may haven't released an update in a while, give away their hard-worked-for repository, or even look for volunteer maintainers. I'm super thankful for every line of open-source code and think we should treat open-source contributors with utmost respect.

**Comment by bartekpacia** [comment]
> I'm super thankful for every line of open-source code and think we should treat open-source contributors with utmost respect.

Of course. I couldn't agree more.

I was just worried that they stopped maintaining these packages for whatever, completely legit, reason. And it'd be quite bad for the whole community given how popular they are. Flutter evolves quite fast and a package that's been out for a few months without an update is a yellow, if not red, flag to many developers.

I see they merged some PRs today - super nice.

**Comment by thecodemonk** [comment]
> @bartekpacia you're always welcome to address issues yourself or even [sponsor Baseflow](https://github.com/sponsors/Baseflow) to expedite their work. It's a free world and I don't see why Baseflow needs to explain why they may haven't released an update in a while, give away their hard-worked-for repository, or even look for volunteer maintainers. I'm super thankful for every line of open-source code and think we should treat open-source contributors with utmost respect.

I also agree with this, however, this becomes a huge problem for a lot of developers when a project becomes super popular, which causes other developers to not create their own plugins, because who would use it? Then the popular plugin gets so outdated that it does not work on the latest versions of Flutter/Dart/Gradle/etc. Now thousands of developers are left in the dark and cannot update their own projects because of this. Their work is highly appreciated, absolutely, but they must do the right thing and hand the project over to someone else once they can no longer maintain it, especially when it becomes hugely popular.

**Comment by TimHoogstrate** [comment]
This is a discussion rather than an issue. Therefore I close this issue. We appreciate any feedback and free to reopen it when you have any additional information. We invite you all to proactively maintain this code and pickup any issues that you feel comfortable working on.
