### ISSUE TITLE
PlatformException: Invalid notification (no valid small icon)

### ISSUE THREAD

**Issue by MichaelTamm** [Baseflow/flutter-geolocator#1258]
## 🐛 Bug Report

We noticed the following error in our Sentry:
`PlatformException: PlatformException(error, Invalid notification (no valid small icon): Notification(channel=geolocator_channel_01 shortcut=null contentView=null vibrate=null sound=null defaults=0x0 flags=0x0 color=0x00000000 vis=PRIVATE), null, null)` on Android 13 devices.

**Version:** 9.0.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by flodaniel** [comment]
What are you `AndroidSettings`?

Here are mine: 
```dart
gl.AndroidSettings(
        accuracy: gl.LocationAccuracy.best,
        distanceFilter: 2,
        foregroundNotificationConfig: const gl.ForegroundNotificationConfig(
          notificationText: 'We are recording your commute',
          notificationTitle: 'Running in Background',
          enableWakeLock: true,
          notificationIcon: gl.AndroidResource(name: 'notification_icon'),
        ),
      )
```
and the `notification_icon` is stored in `android/app/src/main/res/drawable/notification_icon.xml`

Make sure to provide at least the code that is causing the issue for you, when filing a bug  :)

**Comment by mvanbeusekom** [comment]
Without additional information, we are unfortunately not sure how to
resolve this issue. We are therefore reluctantly going to close this
bug for now.

If you find this problem please file a new issue with the same description,
what happens, logs and the output of 'flutter doctor -v'. All system setups
can be slightly different so it's always better to open new issues and reference
the related ones.

Thanks for your contribution.
