### ISSUE TITLE
Can't turn off location updates

### ISSUE THREAD

**Issue by evansherry** [Baseflow/flutter-geolocator#1259]
## 🐛 Bug Report

**Version:** 4.1.7

**Platform:** 
- [ ] :robot: Android

I think the plugin needs a function to stop positioning, in android plugin, in some cases, we need to stop positioning manually. 

For example, startPositionUpdates has not returned a result for a long time, or the positioning has timed out. At this time, we cannot close the positioning, which causes the positioning to be permanent and consumes power.

**Comment by evansherry** [comment]
Hi @mvanbeusekom 

If there is a scene where the position does not return, the getCurrentPosition method cannot be used to cancel the position. This is a great risk, so I think it is necessary to provide a method to cancel the position.

The use of getCurrentPosition is a positioning, the use of getPositionStream is continuous positioning.

Although you can use getPositionStream to achieve a single positioning and then cancel it, getCurrentPosition loses its meaning.
This is my opinion.

**Comment by laiiihz** [comment]
Hi i'm facing the same issue, you could temporarily using `getPositionStream().listen()` as mvanbeusekom said. by the way, the `getCurrentPosition ` method seems not call the `stopPositionUpdates` when timeout.

**Comment by evansherry** [comment]
Yes, getPositionStream can solve this situation.
After using getCurrentPosition to time out, a TimeoutException will be thrown, because this event is only triggered in flutter, it will not stop positioning.

**Comment by mvanbeusekom** [comment]
Hi @evansherry, 

Thank you for clarifying, I didn't realise this was regarding the `getCurrentPosition` method. I have some idea's to resolve this issue. At the very least there are ways to catch the timeout exception internally and make sure the `stopPositionUpdates` method is called natively. 

I will reopen the issue and send updates on progress here.

**Comment by JeroenWeener** [comment]
Hi @evansherry! We published the fix to your issue. If you run `flutter pub upgrade` in your project, the fix should be pulled in automatically.

Don't hesitate to reach out to us if you encounter any problems!

**Comment by evansherry** [comment]
OK, thanks
