### ISSUE TITLE
Problem with Android Emulator, location cannot be determined

### ISSUE THREAD

**Issue by Kerve-Software** [Baseflow/flutter-geolocator#1260]
Location on android emulator cannot be determined. I've switched various emulator but the same issue persists.

Device: Nexus 5X Android API 30, Android version 11
Device: Pixel 4XL Android API 30, Android version 11

**Comment by storm265** [comment]
Please let us see your code.

**Comment by Kerve-Software** [comment]
I have triple checked and done that but still the same problem.
The same code gets the job done on ios emulator but somehow android isn't responding

I've also tested it on iPhone 14 Pro Max and iPhone 14 plus

**Comment by storm265** [comment]
I have same error buy usually only on tablets. But in my case I tried this:
`Geolocator.getPositionStream(locationSettings: _locationSettings);`

`// comment this code
    foregroundNotificationConfig: ForegroundNotificationConfig(
      notificationText: "App name",
      notificationTitle: LocaleKeys.getting_location.tr(),
      enableWakeLock: true,
    ),`

**Comment by andreisas06** [comment]
Hello @Kerve-Software, thank you for submitting the issue. To enhance our understanding of the problem you're encountering, it would be greatly appreciated if you could share a relevant code sample. This will greatly assist us in diagnosing the issue accurately and offering a suitable solution and/or an explanation.

**Comment by mvanbeusekom** [comment]
Hi @Kerve-Software, 

The Android emulator is know for not playing nice with the location services. Often it will suddenly start working when you open Google Maps. 

Also have a look at the instructions mentioned in this issue: https://github.com/Baseflow/flutter-geolocator/issues/1082#issuecomment-1160457180. This is how I always ensure the emulator starts emitting location updates.

I will go ahead and close this issue for now. Feel free to leave a comment with more details if the issue persists and I would be happy to re-open it.

**Comment by ethicnology** [comment]
> I had the same error. But in my case I tried this: Worked only for `Geolocator.getPositionStream()`
> 
> ```
> // gets position using stream;
> Geolocator.getPositionStream(locationSettings: _locationSettings);
> ```
> 
> ```
>  final _locationSettings = AndroidSettings(
>     accuracy: LocationAccuracy.high,
>     distanceFilter: 100,
> 
>     foregroundNotificationConfig: ForegroundNotificationConfig(
>       notificationText: "App name",
>       notificationTitle: "getting_location" ,
>       enableWakeLock: true,
>     ),
>   );
> ```
> 
> To solve problem I commented this code and did hot restart:
> 
> ```
>    // foregroundNotificationConfig: ForegroundNotificationConfig(
>     //   notificationText: "App name",
>     //   notificationTitle: 'getting_location',
>     //   enableWakeLock: true,
>     // ),
> ```
> 
> When your app is loaded after hot restart you may see dialog for google location permission, allow this permission, then uncomment this code above and do again hot restart. In my case it worked, even after I reinstalled my app, I get location without any problems.

turning `enableWakeLock` to `false` worked for me
