### ISSUE TITLE
Get position every 10 seconds

### ISSUE THREAD

**Issue by aitor-gomila** [Baseflow/flutter-geolocator#1262]
Hi. I need to get the position of the phone every 10 seconds in order to save battery. Is it worth it to set up a timer, etc. or should I just use the Stream and get it as soon as possible? Does it work this way (e.g. every frame)?

**Comment by mvanbeusekom** [comment]
Hi @aitor-gomila, 

Unfortunately the iOS SDK doesn't natively support location updates based on a time interval. It is possible to setup constraints based on the desired accuracy or desired distance. To configure these settings supply an instance of the `AppleSettings` class to the `getPositionUpdates` method.

On Android it is possible to configure a time interval which is exposed through the `AndroidSettings` class. 

The following code sample shows how to provide a time interval for Android and a distance filter for Apple (iOS, macOS):

```dart
LocationSettings locationSettings;

if (defaultTargetPlatform == TargetPlatform.android) {
  locationSettings = AndroidSettings(
    intervalDuration: const Duration(seconds: 10),
  );
} else if (defaultTargetPlatform == TargetPlatform.iOS) {
  locationSettings = AppleSettings(
    distanceFilter = 100, // Distance is set in meters.
  );
} else {
  locationSettings = const LocationSettings();
}

final Stream<Position> positionStream = await Geolocator.getPositionStream(locationSettings: locationSettings);
```

Alternatively you could implement your own algorithm to pause and resume the stream based on a timer, however this will not guarantee a location update every x interval.

I will close this issue for now, feel free to leave a comment with additional questions or feedback.

**Comment by aitor-gomila** [comment]
Hi, thanks for your answer! In this case, I think just setting up a timer will be easier.
