### ISSUE TITLE
geolocator_apple > 2.2.2 does not work in background ?

### ISSUE THREAD

**Issue by ChristopheLyonnaz** [Baseflow/flutter-geolocator#1270]
## 💬 Questions and Help

Hello,
I have a flutter application using geolocator 9.0.2 on iOS.
My application is designed to run continuously for a long time in order to report user position, although the application is in background (smartphone in sleep mode or application not on the front).
Using geolocator_apple 2.2.2,everything is OK, but using 2.2.5 or 2.2.6, I get an error message : 

```
LOCATION UPDATE FAILURE:Error reason: (null)Error description: The operation couldn’t be completed. (kCLErrorDomain error 1.)
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: The operation couldn’t be completed. (kCLErrorDomain error 1.)
#0      GeolocatorApple.getPositionStream.<anonymous closure> (package:geolocator_apple/src/geolocator_apple.dart:188:9)
#1      Stream.handleError.<anonymous closure> (dart:async/stream.dart:929:16)
#2      _HandleErrorStream._handleError (dart:async/stream_pipe.dart:269:17)
#3      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
#4      _RootZone.runBinaryGuarded (dart:async/zone.dart:1605:10)
#5      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358:15)
#6      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:376:7)
#7      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)

```

And my application is no longer collecting the location.

I've checked all permissions are active (Location: While Using the App, and Background : location capability is set).
Any idea why I keep having this issue ?

Thank you for your help
Regards,
Christophe.

**Comment by Dev-Paccore** [comment]
+1

**Comment by TimHoogstrate** [comment]
Does it stop collecting the location data immediately or after some time, and can you inform me about how long it takes before you run into this issue?

It would be helpful if you could provide the output of 'flutter doctor -v' and clear, step-by-step instructions to reproduce the issue in the comment section. This will assist us in better understanding and addressing the problem.

**Comment by mvanbeusekom** [comment]
Hi @ChristopheLyonnaz,

Thank you for providing the additional details, we will start looking into this. If you do manage to create a real testing application that would still help out a lot.

**Comment by TimHoogstrate** [comment]
Hi @ChristopheLyonnaz,

Can you please confirm the following: Do you have allowBackgroundLocationUpdates set to true in your locationSettings? e.g. like below (see example app): 

geolocatorApple.getPositionStream(
          locationSettings: AppleSettings(
        accuracy: LocationAccuracy.best,
        distanceFilter: 10,
        activityType: ActivityType.other,
        // Only set showBackgroundLocationIndicator and
        // allowBackgroundLocationUpdates to true if our app will be started up
        // in the background.
        showBackgroundLocationIndicator: false,
        **allowBackgroundLocationUpdates: true,**
      ));

And: 

  /// For this setting to work Info.plist should contain the following keys:
  /// - UIBackgroundModes and the value should contain "location"
  /// - NSLocationAlwaysUsageDescription

Waiting for your reply,

Tim

**Comment by ChristopheLyonnaz** [comment]
Hi @TimHoogstrate ,

Great news, this option totally fixes my issue. I am so sorry not being able to see it earlier.
Thank you for your valuable help.

Christophe.

**Comment by ChristopheLyonnaz** [comment]
Hi Chantha,

This issue was raised quite a long time ago.
Since this, I slighty changed my code. The following simplified code is what I implemented on iOS :

```
  void requestLocationUpdates() async {
    LocationSettings locationSettings;

    serviceEnabled = await Geolocator.isLocationServiceEnabled();
    permission = await Geolocator.checkPermission();

      locationSettings = AppleSettings(
        accuracy: LocationAccuracy.high,
        activityType: ActivityType.airborne,
        distanceFilter: 50,
        pauseLocationUpdatesAutomatically: true,
        // Only set to true if our app will be started up in the background.
        showBackgroundLocationIndicator: true,
        allowBackgroundLocationUpdates: true,
      );

    positionStream = Geolocator.getPositionStream(locationSettings: locationSettings) // 2 mètres entre 2 positions
        .listen((Position position) {
      _position = position;
}
```

**Comment by Chantha123** [comment]
> Hi Chantha,
> 
> This issue was raised quite a long time ago. Since this, I slighty changed my code. The following simplified code is what I implemented on iOS :
> 
> ```
>   void requestLocationUpdates() async {
>     LocationSettings locationSettings;
> 
>     serviceEnabled = await Geolocator.isLocationServiceEnabled();
>     permission = await Geolocator.checkPermission();
> 
>       locationSettings = AppleSettings(
>         accuracy: LocationAccuracy.high,
>         activityType: ActivityType.airborne,
>         distanceFilter: 50,
>         pauseLocationUpdatesAutomatically: true,
>         // Only set to true if our app will be started up in the background.
>         showBackgroundLocationIndicator: true,
>         allowBackgroundLocationUpdates: true,
>       );
> 
>     positionStream = Geolocator.getPositionStream(locationSettings: locationSettings) // 2 mètres entre 2 positions
>         .listen((Position position) {
>       _position = position;
> }
> ```

Yes Thanks brother. I already apply this but it doesn't work . I still got error : 
Unhandled Exception: The operation couldn’t be completed. (kCLErrorDomain error 1.)
#0      GeolocatorApple.getPositionStream.<anonymous closure> (package:geolocator_apple/src/geolocator_apple.dart:188:9)
#1      Stream.handleError.<anonymous closure> (dart:async/stream.dart:923:16)
#2      _HandleErrorStream._handleError (dart:async/stream_pipe.dart:269:17)
#3      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
#4      _RootZone.runBinaryGuarded (dart:async/zone.dart:1606:10)
#5      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358:15)
#6      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:376:7)
#7      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
#8      _ForwardingStreamSubscription._addError (dart:async/stream_pipe.dart:128:11)
#9      _ForwardingStream._handleError (dart:async/stream_pipe.dart:95:10)
#10     _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
#11     _RootZone.runBinaryGuarded (dart:async/zone.dart:1606:10)
#12     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358:15)
#13     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:376:7)
#14     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
#15     _SyncBroadcastStreamController._sendError.<anonymous closure> (dart:async/broadcast_stream_controller.dart:392:20)
#16     _BroadcastStreamController._forEachListener (dart:async/broadcast_stream_controller.dart:322:15)
#17     _SyncBroadcastStreamController._sendError (dart:async/broadcast_stream_controller.dart:391:5)
#18     _AsBroadcastStreamController.addError (dart:async/broadcast_stream_controller.dart:486:5)
#19     _RootZone.runBinaryGuarded (dart:async/zone.dart:1606:10)
#20     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358:15)
#21     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:376:7)
#22     _DelayedError.perform (dart:async/stream_impl.dart:526:14)
#23     _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
#24     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
#25     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)

**Comment by ChristopheLyonnaz** [comment]
Just to be sure, now I've migrated to the following content in pubspec.yaml:
```
  sdk: '>=3.1.0 <4.0.0' # Dart SDK release
  geolocator: ^10.0.1, which leads to geolocator_apple-2.3.2.

```
At the time I fixed workaround the issue, I had:
```
  sdk: ">=2.7.0 <3.0.0"

  geolocator: ^9.0.2                 

dependency_overrides:
  geolocator_apple: 2.2.2                

```

And obviously, I have the following in my Info.plist:

```
	<key>NSLocationAlwaysUsageDescription</key>
	<string>This app needs access to location xxxx.</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>This app needs access to location xxxx.</string>
	<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>This app needs access to location xxxx.</string>

```
