### ISSUE TITLE
Custom Android notification icon color

### ISSUE THREAD

**Issue by cohenadair** [Baseflow/flutter-geolocator#1277]
## 🚀 Feature Requests

Right now, only the notification title, message, and icon can be customized. It would be great if we could also customize the icon's (background) color, instead of being forced to use the system's default.

### Contextualize the feature
The framework creates the Android `NotificationBuilder`, but doesn't expose many of the available methods to Flutter.

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by ttoffalori** [comment]
Any updates on this? Would need the same.

**Comment by DabPb** [comment]
Is there any update for notification icon?

**Comment by JeroenWeener** [comment]
Hi all!

Wanted to let you know that this is available on the newest version of `geolocator_android`. To pull in the changes, run `flutter pub upgrade`. You can check if you are using the newest version by verifying that the version of `geolocator_android` is at least 4.4.0 in the `pubspec.lock` file.
