### ISSUE TITLE
[Bug]: App launch delay in Android

### ISSUE THREAD

**Issue by hrajwade96** [Baseflow/flutter-geolocator#1283]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Steps to reproduce

Add geolocator and measure app launch

### Expected results

App launch should not be impacted 

### Actual results

App launch is getting impacted,
In initial few seconds there is a delay due to this plugin. 
Its initialization is happening at the very beginning of the app before my code execution. 
This initialization is not appearing in dev tools timeline, however I am able to see it in the logs. 
As you can see below there is a 2s gap. 
(not attaching my code as this is happening before code execution). 

### Code sample

<details><summary>Code sample</summary>

```dart
2023-06-23 06:23:14.919 5636-5768 flutter com.myapp I The Dart VM service is listening on http://127.0.0.1:41833/Msm1hBCuSzY=/ 
2023-06-23 06:23:15.229 5636-5636 FlutterGeolocator com.myapp D Creating service. 
2023-06-23 06:23:15.229 5636-5636 FlutterGeolocator  D Binding to location service. 
2023-06-23 06:23:15.241 5636-5636 FlutterGeolocator  D Flutter engine connected. Connected engine count 1 
2023-06-23 06:23:17.523 5636-5751 flutter  I inside main 
2023-06-23 06:23:17.584 5636-5751 flutter I start--> name: Platform description:plugins} 1687481597584


```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

9.0.2

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by mvanbeusekom** [comment]
This seems to be a duplicate of issue #1243. Closing this and will keep track of progress in issue #1243. 

A code sample reproducing the behaviour would still be very much appreciated as we are unable to reproduce the issue in the example application.
