### ISSUE TITLE
Changing location interval or accuracy without restarting the listener

### ISSUE THREAD

**Issue by pamafe1976** [Baseflow/flutter-geolocator#1287]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geolocator/blob/main/geolocator/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Your question

Hi,

I'm trying to achieve something that should be possible with this plugin, but I'm not finding the way.

My app needs to get the user location at regular intervals (lets say 5 seconds), even when it goes to the background.

To keep the stream alive, even when in background, I tried two ways:

- Using geolocator foregroundNotificationConfig
- Using flutter_foreground_task package

And they both worked fine! The stream listener receives location updates even with the app on background.

HOWEVER...
I need my app to be more battery efficient, so I would like to set a different location interval when the app goes to the background.
But the only way to change the interval is to cancel the stream and start it again with different settings, and if I try to cancel and restart the stream while the app is on the background, it does not start sending locations until the app goes to the foreground again.

It is a big limitation, so I imagine I must be doing something wrong.
Also, I tested with another package (flutter location package) and I could change the interval while the app was on background (so its not an android limitation); but the location package is buggy and not well mantained, so I would rather continue using Geolocator if possible.

**EDIT:** The problem described only happens in Android 12+, It works as expected on lower versions.

Thanks for reading my long explanation.
Any help is highly appreciated.

Regards

### Version

9.0.2

**Comment by pamafe1976** [comment]
> Hi @pamafe1976, thank you for reaching out with your question!
> 
> It is certainly an interesting idea to allow the listener to be updated instead of creating a new one, or to allow a new listener to be created and used from a background service.
> 
> You mention that your goal is to make your app more energy efficient. Reading through the Android docs, it seems that starting with Android 8.0 (API 26), the location polling frequency automatically gets limited to a few calls per hour when in the background. A link to the documentation is here: https://developer.android.com/about/versions/oreo/background-location-limits.
> 
> I am wondering if this suits your needs already. Or are you experiencing different behavior?

Hi @JeroenWeener,

I could, after several different attempts make it work as I intended.
My idea was that when the user is actively using the app (app in the foreground), the location is retrieved every 3 seconds with high accuracy; when the user switches to other app, or turns off the screen, the app becomes paused or iddle and the foreground service keeps the location polling alive, but lowers the interval to about 20 seconds.
There is a third situation, when the user opens the app but is not in the reference zone (out of the map) that the interval is even higher and the requested accuracy low.

I could not solve this with the geolocator itself, since each time you have to change settings, it restarts its own foreground service, and in Android 12+ this is not allowed while in background. So when the user switches app, or turns off screen, the app goes to the background, the listener is recreated and it is not started again until the app is on foreground again.

I managed to solve it by putting the geolocator position stream listener inside a flutter_foreground_task. This foreground task is never stopped, and the  getPositionStream is called without ForegroundNotificationConfig, so it does not create any service.
When the app is minimized, I just call a routine inside the ForegroundTask that cancels the stream and starts a new one, and this starts sending positions immediately.

The downside is that with this approach the geolocator stream is inside the TaskHandler of the ForegroundService created using flutter_foreground_task, so I have to send each new position to the app using a port.

Regards

**Comment by pamafe1976** [comment]
Hi @JeroenWeener,

Can you please specify what additional information do you require about this issue?

Regards

**Comment by mvanbeusekom** [comment]
Hi @pamafe1976,

Unfortunately updating the location filter settings is not supported by the native Android SDK. Which means the only way to accomplish this would be to stop the existing stream and start listening to a new stream with the updated settings. 

Of course we could do this internally in the Geolocator's implementations, however this might result into unwanted behaviour for other customers. Therefore we think it is best to allow developers to stop and start the stream themselves and have full control.

To detect if the flutter app is moved to the background, you can override the `didChangeAppLifecycleState` (see [documentation](https://api.flutter.dev/flutter/widgets/WidgetsBindingObserver/didChangeAppLifecycleState.html)) method and use it to restart the location stream with the appropriate configuration.

Hope this helps, I will go ahead and close this issue for now. Please leave a comment if I misunderstood the problem and I would be happy to look into it again.

**Comment by pamafe1976** [comment]
Hi @mvanbeusekom,
As I mentioned in my previous post, that approach works ok if you restart the geolocator stream from a foreground service created using a package such as flutter_foreground_task, but now if you use geolocator own foreground service.
Regards
