### ISSUE TITLE
[Bug]: not getting current location position in offline mode for first time, i faced this issue in one-plus device

### ISSUE THREAD

**Issue by darshanavala** [Baseflow/flutter-geolocator#1288]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Steps to reproduce

run the application in offline mode and get the current position 

it is throw this error continually :

E/GED     (27929): ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
E/GED     (27929): ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
E/GED     (27929): ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
E/GED     (27929): ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
E/GED     (27929): ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
E/GED     (27929): ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2

when calling getCurrentPosition() function

final position = await Geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.high,);

not getting any result it is stuck here.

### Expected results

i want the mobile's current position latitude and longitude without internet connection after installing application

### Actual results

throw this line of code continually in console:

E/GED     (27929): ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
E/GED     (27929): ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
E/GED     (27929): ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
E/GED     (27929): ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
E/GED     (27929): ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
E/GED     (27929): ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2

### Code sample

<details><summary>Code sample</summary>

```dart
  Future<void> getCurrentPosition() async {
final position = await Geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.high,);
 debugPrint('lat long ${position.latitude} ${position.longitude}');
}
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

geolocator: ^9.0.2

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.12, on macOS 12.6 21G115 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

```

</details>

**Comment by TimHoogstrate** [comment]
Dear @darshanavala,

Be careful when testing this indoors. it might be hard to find your position in a building. Could you also check if the correct permissions are requested and if the correct settings are used. You can try to test if it works if you run the example app.

Kind regards

**Comment by mvanbeusekom** [comment]
@darshanavala,

On which devices are you experiencing this issue? This seems to be related to some Oppo devices and not particularly to accessing location information.

It would be helpful if you could provide the full output of the `flutter doctor -v` (including the `-v` switch) in this issue.
