### ISSUE TITLE
[Bug]: Geolocator fails to build for windows.

### ISSUE THREAD

**Issue by milindgoel15** [Baseflow/flutter-geolocator#1299]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [X] Windows

### Steps to reproduce

1. Create a fresh flutter project
2. Run on windows
3. It compiles and runs fine
4. Close the app
5. Add geolocator
6. Run the app again
7. Build fails

### Expected results

Flutter builds for windows without issue even after adding geolocator

### Actual results

The build fails with nuget error message:
<details><summary>Logs</summary>

```console
@Milind ➜ geowin flutter run -d windows
Resolving dependencies...
  collection 1.17.1 (1.18.0 available)
  matcher 0.12.15 (0.12.16 available)
  material_color_utilities 0.2.0 (0.8.0 available)
  source_span 1.9.1 (1.10.0 available)
  stack_trace 1.11.0 (1.11.1 available)
  stream_channel 2.1.1 (2.1.2 available)
  test_api 0.5.1 (0.6.1 available)
Got dependencies!
Launching lib\main.dart on Windows in debug mode...
Argument cannot be null or empty
Parameter name: primarySources
CMake Error at flutter/ephemeral/.plugin_symlinks/geolocator_windows/windows/CMakeLists.txt:33 (message):
  Failed to install nuget package Microsoft.Windows.CppWinRT.2.0.210806.1


Building Windows application...                                  1,136ms
Exception: Unable to generate build files
```

</details>

### Code sample

<details><summary>Code sample</summary>

a very minimal reproducible repo for geolocator issue. There's no change in any file except the pubspec file. Follow the steps to reproduce above to reproduce
https://github.com/milindgoel15/geowin

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

![image](https://github.com/Baseflow/flutter-geolocator/assets/45682747/153a3255-e36f-49b7-ad26-d4070c1c7321)

</details>

### Version

9.0.2

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
@Milind ➜ geowin git(main) flutter doctor -v
[✓] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.22621.1992], locale en-IN)
    • Flutter version 3.10.6 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (3 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\Lenovo\AppData\Local\Android\Sdk
    • Platform android-33-ext4, build-tools 33.0.1
    • ANDROID_SDK_ROOT = C:\Users\Lenovo\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.6.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33712.159
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[✓] VS Code, 64-bit edition (version 1.80.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.66.0

[✓] Connected device (1 available)
    • Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version 10.0.22621.1992]

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by milindgoel15** [comment]
Since the other two issues(#1115 and #1001) were closed, I created another issue just for more detailed information or to provide more detailed information if necessary/when asked. The last asked information on #1115 is written [here](https://github.com/Baseflow/flutter-geolocator/issues/1115#issuecomment-1660012739)

**Comment by aletandil** [comment]
Hi, same problem here. 

geolocator:
    dependency: "direct main"
    description:
      name: geolocator
      sha256: "5c23f3613f50586c0bbb2b8f970240ae66b3bd992088cf60dd5ee2e6f7dde3a8"
      url: "https://pub.dev"
    source: hosted
    version: "9.0.2"
  geolocator_android:
    dependency: transitive
    description:
      name: geolocator_android
      sha256: "94c2cf51f4a8387335cc2d1a21cc50897bc93069e05fc09aee29bd353a14f6f5"
      url: "https://pub.dev"
    source: hosted
    version: "4.1.9"
  geolocator_apple:
    dependency: transitive
    description:
      name: geolocator_apple
      sha256: "36527c555f4c425f7d8fa8c7c07d67b78e3ff7590d40448051959e1860c1cfb4"
      url: "https://pub.dev"
    source: hosted
    version: "2.2.7"
  geolocator_platform_interface:
    dependency: transitive
    description:
      name: geolocator_platform_interface
      sha256: af4d69231452f9620718588f41acc4cb58312368716bfff2e92e770b46ce6386
      url: "https://pub.dev"
    source: hosted
    version: "4.0.7"
  geolocator_web:
    dependency: transitive
    description:
      name: geolocator_web
      sha256: f68a122da48fcfff68bbc9846bb0b74ef651afe84a1b1f6ec20939de4d6860e1
      url: "https://pub.dev"
    source: hosted
    version: "2.1.6"
  geolocator_windows:
    dependency: transitive
    description:
      name: geolocator_windows
      sha256: f5911c88e23f48b598dd506c7c19eff0e001645bdc03bb6fecb9f4549208354d
      url: "https://pub.dev"
    source: hosted
    version: "0.1.1"

**Comment by mvanbeusekom** [comment]
Hi @milindgoel15, @aletandil,

This is usually caused by an configuration error regarding NuGet package manager. The geolocator_windows package makes use of NuGet to download the `Microsoft.Windows.CppWinRT` library which contains is used to generate C++ header files to access the Windows native runtime SDK, needed to communicate with the GPS hardware. 

I am not really sure what causes the configuration error, however here are some steps that can be verified:

1. Make sure the default NuGet configuration file exists at the following path `%appdata%\NuGet\NuGet.Config`. If it doesn't exists create it with the following contents:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>
```
2. If the default `NuGet.Config` exists with the appropriate content, verify if you are allowed to connect to the `https://api.nuget.org/v3/index.json` url. Some organisations are configured behind a firewall or proxy blocking access.
3. Make sure [Visual Studio 2022](https://visualstudio.microsoft.com/downloads/) (not Visual Studio Code) is installed correctly with the "Desktop development with C++" workload including all default options.

If this all fails please run `flutter build windows -v`. The `-v` switch will provide verbose information and will give more feedback on why NuGet wasn't able to install the `Microsoft.Windows.CppWinRT` library.

P.S. we have recently released an updated version of the geolocator_windows package where all internal dependencies are updated.

**Comment by gadjetnut** [comment]
Putting NuGet.Config in my project folder solved the problem. I had tried the above solution of putting in %appdata%\NuGet\ directory but it didn't work.
