### ISSUE TITLE
add flutter 3.10.6 support and bump dependencies 

### ISSUE THREAD

**Issue by fisforfaheem** [Baseflow/flutter-geolocator#1303]
### Is there already an issue requesting this feature?

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).

### Please select affected platform(s)

- [X] Android
- [X] iOS
- [ ] Linux
- [ ] macOS
- [X] Web
- [ ] Windows

### Use case

old  dependencies 

### Proposal

 bump dependencies

**Comment by mvanbeusekom** [comment]
@fisforfaheem Can you explain why this is necessary? 

Are you experiencing build issues or other crashes?

**Comment by fisforfaheem** [comment]
Hi,

Thank you for reaching out. I appreciate your inquiry regarding the
necessity of this issue. As of now, we have not encountered any build
issues or crashes that would require immediate attention.
bumping will help it make future proof
Kind regards
