### ISSUE TITLE
[Bug]: requestPermission() not working

### ISSUE THREAD

**Issue by Ahmed-Ismail74** [Baseflow/flutter-geolocator#1309]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Steps to reproduce

Ask user for permissionfrom app and denie it from app
If i set not allow from settings it will work fine

### Expected results

when start app again it should ask user again for permission but it doesn't

### Actual results

It doesn't show permission ask window only, It works if i change permission from settings only

### Code sample

<details><summary>Code sample</summary>

```dart
if (permission == LocationPermission.denied || permission == LocationPermission.deniedForever) {
      print('Location permissions are denied 1');
      permission = await Geolocator.requestPermission();

      if (permission == LocationPermission.whileInUse ||
          permission == LocationPermission.always) {
        Position position = await Geolocator.getCurrentPosition(
            desiredAccuracy: LocationAccuracy.low);
        print('position = $position');
      }
    } else {
      Position position = await Geolocator.getCurrentPosition(
          desiredAccuracy: LocationAccuracy.low);
      print('position = $position');
    }
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

10.0.0 

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.22621.2134], locale ar-EG)
    ! Warning: `dart` on your path resolves to C:\Program Files\Dart\dart-sdk\bin\dart.exe, which is
      not inside your current Flutter SDK checkout at C:\Users\Ahmed\FlutterSDK\flutter. Consider
      adding C:\Users\Ahmed\FlutterSDK\flutter\bin to the front of your path.
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.0)
[!] Android Studio (version 2021.3)
    X Unable to determine bundled Java version.
[√] Android Studio (version 2022.3)
[√] IntelliJ IDEA Community Edition (version 2022.2)
[√] VS Code (version 1.81.1)
[√] Connected device (4 available)
[√] Network resources

```

</details>

**Comment by TimHoogstrate** [comment]
Dear @Ahmed-Ismail74,

After a permission has a status permanentlyDenied,  the user has to change the permission in the settings. The user will not be asked to give permissions via the alert anymore. Can you check with the example app if the flow that you are testing result in the same outcome? Furthermore, check the statuses of the permission after each step in your own app.

Kind regards,
