### ISSUE TITLE
[Question]: Geolocator 9.0.2 unexpected issue since updating to 10.0.0

### ISSUE THREAD

**Issue by logan-oss** [Baseflow/flutter-geolocator#1310]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geolocator/blob/main/geolocator/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Your question

I compile a apk of my app yesterday with geolocator 9.0.2 because everything was fine since now. 
I have a bug when i use this function : 
```dart
Geolocator.getCurrentPosition(
      desiredAccuracy: LocationAccuracy.best,
);
```
The location is loading for an indefinite time.
But the function work when i add _forceAndroidLocationManager: **false**_
And i noticed that my older build (dated 2 months ago)) work perfectly with the version 9.0.2 of geolocator.
Now i update geolocator to 10.0.0 and the issue is solved.
I'm just frustrated because i really don't know what's append. I think the issue is about the compilation.
If you have an answer or a hypothesis, I would like to know it please.

### Version

9.0.2

**Comment by TimHoogstrate** [comment]
Dear @logan-oss,

I am unsure about your problem/question. I read that the issue is resolved bij geolocation 10.0.0. Is that correct? Furthermore it would help a lot if you could add the output of `flutter doctor -v` and possible the manifest file. 

Kind regards,

**Comment by mahyarmirrashed** [comment]
I'm having a similar problem with 10.0.0 running for an indefinite time on a Pixel 6 device I have in an emulator. It just never returns. I'm not sure why.

**Comment by TimHoogstrate** [comment]
Dear @mahyarmirrashed,

Can you create a separate issue? 

Kind regards,
