### ISSUE TITLE
Location retrieving doesn't work without internet or cellular data on Android?

### ISSUE THREAD

**Issue by AmmarMohamed21** [Baseflow/flutter-geolocator#1312]
I am trying to retrieve the location of the device, however I want to access the location using GPS device only without access to internet or cellular data.

The geolocation apis does not work without internet access and gets stuck in the function forever
```
var position = await Geolocator.getCurrentPosition(
      desiredAccuracy: LocationAccuracy.high,
    );
``` 

I also tried using the getPositionStream() but same problem.

It works only if I get the location at least once with internet access then turn it off.

I tested the functionality on multiple Android devices (Xiaomi and Samsung) with multiple different settings (Location Accuracy), (forceAndroidLocationManager) but same problem

Here is the permissions I have
```
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
```

I tried to remove access coarse location as well as mentioned in the package documentation it may take minutes to get the first coarse location but it didn't solve it.

**Comment by TimHoogstrate** [comment]
Dear @AmmarMohamed21,

Can you elaborate a bit on the issue. Can you test if the locations are working in the example app? And are the permissions requested correctly?

Kind regards,

**Comment by AmmarMohamed21** [comment]
@TimHoogstrate Thanks for your reply
Yes I tested now the example app on Samsung Galaxy A13 and Xiaomi Redmi Note 10 Pro.. both can't get the location without internet access, I try to test on conditions that my app users are supposed to have: No SIM Card, and no Internet Connection..
And I wonder if there are some settings I suppose to have on Android for it to work? I turned off Google Location Accuracy to make sure it uses only GPS and I turned off WIFI Scanning and Bluetooth Scanning still the same, I also wonder if Android devices GPS can work without internet access at all?

**Comment by TimHoogstrate** [comment]
If you turn off: `Google Location Accuracy` it will indeed do not retrieve a location... with forceLocationManager on. Can you try to turn it on and see what happens.

**Comment by AmmarMohamed21** [comment]
I tried forceLocationManager on and off both didn't work

**Comment by AmmarMohamed21** [comment]
They are requested properly yes, but did you make sure to not turn on WIFI at all while Location service is open? because when I get the location once or if I had the wifi and location turned on together then turned off wifi it works, but if from the beginning I turned on location while wifi is off it never works

**Comment by AmmarMohamed21** [comment]
I want to sure an update that it worked when I stood in an open area (not inside a building), is this an expected behavior?

**Comment by TimHoogstrate** [comment]
@AmmarMohamed21,

That is indeed what I would expect if you are using GPS.

Kind regards,

**Comment by mvanbeusekom** [comment]
I will go ahead and close this issue as it is indeed expected not to be able to determine a location based solely on GPS if there is no clear view to the sky (satellite).
