### ISSUE TITLE
[Bug]: Error with GeolocatorAndroid.getPositionStream 

### ISSUE THREAD

**Issue by Mohsen3-5** [Baseflow/flutter-geolocator#1313]
- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.

### Steps to reproduce

Hello,

I am writing to report an issue that has been reported on Crashlytics. I've encountered this issue while using the `geolocator` package in my mobile application. The problem seems to appear most frequently on the Alcatel 3X device running Android 9.0 (Pie).

The issue arises when using the `GeolocatorAndroid.getPositionStream` method from the `geolocator` package within my mobile app. I am encountering an error that results in an unhandled exception. The stack trace indicates that the error originates within the `geolocator_android.dart` file at line 200. This error occurs during the processing of the position stream and seems to be related to error handling and stream handling mechanisms.

![Screenshot of a comment on a GitHub issue showing an image,](https://serving.photos.photobox.com/5675343938a59963e93df854575d442f9f34780ecbef6f241fde5993f869e67fed70e026.jpg)

### Full error description
**#0 GeolocatorAndroid.getPositionStream.<anonymous closure> (package:geolocator_android/src/geolocator_android.dart:200)**
_StackTrace: #0 GeolocatorAndroid.getPositionStream.<anonymous closure> (package:geolocator_android/src/geolocator_android.dart:200) #1 Stream.handleError.<anonymous closure> (dart:async/stream.dart:929) #2 _HandleErrorStream._handleError (dart:async/stream_pipe.dart:269) #3 _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157) #4 _rootRunBinary (dart:async/zone.dart:1422) #5 _CustomZone.runBinary (dart:async/zone.dart:1314) #6 _CustomZone.runBinaryGuarded (dart:async/zone.dart:1224) #7 _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358) #8 _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:376) #9 _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280) #10 _ForwardingStreamSubscription._addError (dart:async/stream_pipe.dart:128) #11 _ForwardingStream._handleError (dart:async/stream_pipe.dart:95) #12 _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157) #13 _rootRunBinary (dart:async/zone.dart:1422) #14 _CustomZone.runBinary (dart:async/zone.dart:1314) #15 _CustomZone.runBinaryGuarded (dart:async/zone.dart:1224) #16 _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358) #17 _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:376) #18 _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280) #19 _SyncBroadcastStreamController._sendError.<anonymous closure> (dart:async/broadcast_stream_controller.dart:392) #20 _BroadcastStreamController._forEachListener (dart:async/broadcast_stream_controller.dart:322) #21 _SyncBroadcastStreamController._sendError (dart:async/broadcast_stream_controller.dart:391) #22 _AsBroadcastStreamController.addError (dart:async/broadcast_stream_controller.dart:486) #23 _rootRunBinary (dart:async/zone.dart:1422) #24 _CustomZone.runBinary (dart:async/zone.dart:1314) #25 _CustomZone.runBinaryGuarded (dart:async/zone.dart:1224) #26 _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358) #27 _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:376) #28 _DelayedError.perform (dart:async/stream_impl.dart:526) #29 _PendingEvents.handleNext (dart:async/stream_impl.dart:620) #30 _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591) #31 _rootRun (dart:async/zone.dart:1390) #32 _CustomZone.run (dart:async/zone.dart:1300) #33 _CustomZone.runGuarded (dart:async/zone.dart:1208) #34 _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1248) #35 _rootRun (dart:async/zone.dart:1398) #36 _CustomZone.run (dart:async/zone.dart:1300) #37 _CustomZone.runGuarded (dart:async/zone.dart:1208) #38 _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1248) #39 _microtaskLoop (dart:async/schedule_microtask.dart:40) #40 _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

### Expected results

I expected the `GeolocatorAndroid.getPositionStream` method to provide a stream of position updates without errors, as it does on other devices.

### Actual results

On the Alcatel 3X device running Android 9.0, the method throws an unhandled exception within the `geolocator_android.dart` file at line 200, impacting the functionality of the app's location services.

### Code sample
here where the error occurred
```
 _positionStream = positionStream
        .map<Position>((dynamic element) =>
            Position.fromMap(element.cast<String, dynamic>()))
        .handleError(
      (error) {
        if (error is PlatformException) {
          error = _handlePlatformException(error);
        }
        throw error;
      },
    );

```

### Version

10.0.0

### Flutter Doctor output

<details><summary>Doctor output</summary>

[✓] Flutter (Channel stable, 3.7.12, on macOS 13.4.1 22F82 darwin-arm64, locale en-TR)
    • Flutter version 3.7.12 on channel stable at /Users/mohsen/fvm/versions/3.7.12
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (4 months ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/mohsen/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Users/mohsen/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • Redmi Note 9S (mobile) • 1bcfb876 • android-arm64  • Android 12 (API 31)
    • macOS (desktop)        • macos    • darwin-arm64   • macOS 13.4.1 22F82 darwin-arm64
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 116.0.5845.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

</details>

**Comment by TimHoogstrate** [comment]
Dear @Mohsen3-5,

I think I understand where your issue comes from. I was testing an issue yesterday that might be related to the settings on the device. I think that I'll label this issue as a bug for now and then check if we can resolve the issue later. Can you send me the configurations that you use to call the position stream on Android (something like: 
```
AndroidSettings(
        accuracy: LocationAccuracy.best,
        distanceFilter: 10,
        intervalDuration: const Duration(seconds: 1),
        forceLocationManager: true)
```

**Comment by Mohsen3-5** [comment]
> I think I understand where your issue comes from. I was testing an issue yesterday that might be related to the settings on the device. I think that I'll label this issue as a bug for now and then check if we can resolve the issue later. Can you send me the configurations that you use to call the position stream on Android (something like:

Hello @TimHoogstrate,

Thank you for your prompt response. In my implementation, I utilize **LocationSettings** instead of **AndroidSettings**, as demonstrated below:

```
LocationSettings locationSettings = LocationSettings(
      accuracy: LocationAccuracy.high,
      distanceFilter: detectDistance,
    );
```

Should I consider substituting locationSettings with AndroidSettings when the platform is Android?

**Comment by TimHoogstrate** [comment]
Dear @Mohsen3-5,

I remember testing a similar issue prior to running into your issue, however, that one was related with a developer testing an implementation with forceLocationManager = true and indoor testing. Yours looks different. I cannot reproduce your issue in my environment. There are things we can try like testing the implementation on that actual Alcatel device, or perhaps playing with the phone settings. Is it possible that all crashes are from the same user?

Kind regards,

**Comment by saurabhkumar8112** [comment]
Any updates on this? I could replicate this issue in Debug mode in
1. Samsung Android OS 13
2. Aquos Sharp Android OS 11

Location Service is enabled, all permissions(locationWhenInUse/Always Allow) are given, but I still get a `LocationServiceDisabledException` exception as the author explained

**Comment by Alfre2021** [comment]
I also have a problem on Android 13 on Samsung devices, when I implement the following stream:
Geolocator.getPositionStream().listen((event) {}
It works fine but when I deactivate and reactivate the GPS from the notification bar or quick accesses it no longer updates the coordinates, it is as if the service stopped. But when I deactivate the GPS from settings and then activate it, it works perfectly, the service updates the coordinates. Please, does anyone have a solution or information about this problem?

**Comment by TimHoogstrate** [comment]
@saurabhkumar8112, I cannot find the author saying anything about a `LocationServiceDisabledException`. Can you create another issue? And post the output of `flutter doctor -v` and the stack trace? And some minimal reproducible code. Also check if this is happening in the example app.

Kind regards,
