### ISSUE TITLE
[Bug]: Timeout Exceeded for Retrieving Location on Emulator

### ISSUE THREAD

**Issue by mahyarmirrashed** [Baseflow/flutter-geolocator#1315]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Steps to reproduce

I am following the App Brewery's Flutter tutorial for how to create an application that can retrieve the user's current location and output it. This is the backend code that makes all the magic happen:

```dart
class Location {
  double latitude = 0.0;
  double longitude = 0.0;

  Future<void> getCurrentLocation() async {
    if (!await isLocationServiceEnabled()) {
      return Future.error(
        'Location services are disabled. Please activate them.',
      );
    }

    if (isPermissionGranted(await getLocationPermission())) {
      await fetchAndSetCurrentLocation();
    }
  }

  Future<LocationPermission> getLocationPermission() async {
    LocationPermission locationPermission = await Geolocator.checkPermission();

    if (locationPermission == LocationPermission.unableToDetermine) {
      throw Future.error(
          "Unable to determine if location permissions are enabled.");
    } else if (locationPermission == LocationPermission.denied ||
        locationPermission == LocationPermission.deniedForever) {
      locationPermission = await Geolocator.requestPermission();
    }

    return locationPermission;
  }

  Future<bool> isLocationServiceEnabled() async {
    return await Geolocator.isLocationServiceEnabled();
  }

  bool isPermissionGranted(LocationPermission locationPermission) {
    return locationPermission == LocationPermission.whileInUse ||
        locationPermission == LocationPermission.always;
  }

  Future<void> fetchAndSetCurrentLocation() async {
    Position position = await Geolocator.getCurrentPosition(
        desiredAccuracy: LocationAccuracy.lowest,
        timeLimit: const Duration(seconds: 10));

    latitude = position.latitude;
    longitude = position.longitude;
  }
}
```

The function `awai Geolocator.getCurrentPosition()` never returns. Even when I increase the time limit to 180 seconds, it still fails to return. I am not sure why this is happening. I am running this on a Simulated Device inside Android Studio.

### Expected results

I expect the function to return.

### Actual results

The function should return.

### Code sample

<details><summary>Code sample</summary>

```dart
class Location {
  double latitude = 0.0;
  double longitude = 0.0;

  Future<void> getCurrentLocation() async {
    if (!await isLocationServiceEnabled()) {
      return Future.error(
        'Location services are disabled. Please activate them.',
      );
    }

    if (isPermissionGranted(await getLocationPermission())) {
      await fetchAndSetCurrentLocation();
    }
  }

  Future<LocationPermission> getLocationPermission() async {
    LocationPermission locationPermission = await Geolocator.checkPermission();

    if (locationPermission == LocationPermission.unableToDetermine) {
      throw Future.error(
          "Unable to determine if location permissions are enabled.");
    } else if (locationPermission == LocationPermission.denied ||
        locationPermission == LocationPermission.deniedForever) {
      locationPermission = await Geolocator.requestPermission();
    }

    return locationPermission;
  }

  Future<bool> isLocationServiceEnabled() async {
    return await Geolocator.isLocationServiceEnabled();
  }

  bool isPermissionGranted(LocationPermission locationPermission) {
    return locationPermission == LocationPermission.whileInUse ||
        locationPermission == LocationPermission.always;
  }

  Future<void> fetchAndSetCurrentLocation() async {
    Position position = await Geolocator.getCurrentPosition(
        desiredAccuracy: LocationAccuracy.lowest,
        timeLimit: const Duration(seconds: 10));

    latitude = position.latitude;
    longitude = position.longitude;
  }
}
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

None needed.

</details>

### Version

10.0.0

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.2, on Ubuntu 22.04.3 LTS 6.2.0-26-generic, locale en_CA.UTF-8)
    • Flutter version 3.10.2 on channel stable at /home/mahyar/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (3 months ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/mahyar/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /snap/android-studio/127/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2022.2)
    • Android Studio at /snap/android-studio/126/android-studio
    • Flutter plugin version 74.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2022.3)
    • Android Studio at /snap/android-studio/127/android-studio
    • Flutter plugin version 75.1.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Ubuntu 22.04.3 LTS 6.2.0-26-generic

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by TimHoogstrate** [comment]
Dear @mahyarmirrashed,

Double check if this is working on the example app in the repository. A emulator is not a suitable solution when testing locations. It also depends on the proper permissions and the AndroidSettings.

Kind regards,

**Comment by mahyarmirrashed** [comment]
Hi @TimHoogstrate , where can I find the example application in the repository? Also, I would have thought that the emulator would be a great way to test since I can set the location to wherever I want in the world to test that my application works as expected. Is there perhaps a guide on how to test with an emulator correctly for this repository? Regards,

**Comment by mahyarmirrashed** [comment]
I am pretty sure that my Android Emulator is working correctly. I just set the location to a very precise location and opened up Google Maps. Maps was then able to identify the correct location of where I had set the location. I tried the same thing more than a few times and it would go to the updated location. There was about a 1-second delay. I also gave it the same permissions that I gave my sample application ("While in use").

**Comment by mvanbeusekom** [comment]
Hi @mahyarmirrashed,

I took the liberty to also look into this issue and I noticed that you set the `desiredAccuracy` to `LocationAccuracy.lowest` when making the call to `getCurrentPosition`. 

On Android accuracy settings will translate into a priority on the native SDK. The `LocationAccuracy.lowest` will translate in to `PRIORITY_PASSIVE` which means:

> Ensures that no extra power will be used to derive locations. This enforces that the request will act as a passive listener that will only receive "free" locations calculated on behalf of other clients, and no locations will be calculated on behalf of only this request.

This will explain why your application is not returning a result, since it is configured to not actively request a location from the device but instead wait for some other application to get a location and return that same particular location.

We are aware that this seems a bit counter intuitive, however it is the only way to over a shared API between all the different platforms. 

The mapping is as follows:

| Location accuracy | Android priority | Description |
| --- | --- | --- |
| lowest | PRIORITY_PASSIVE | Ensures that no extra power will be used to derive locations. This enforces that the request will act as a passive listener that will only receive "free" locations calculated on behalf of other clients, and no locations will be calculated on behalf of only this request. |
| low | PRIORITY_LOW_POWER | Requests a tradeoff that favors low power usage at the possible expense of location accuracy. |
| medium | PRIORITY_BALANCED_POWER_ACCURACY | Requests a tradeoff that is balanced between location accuracy and power usage. |
| high+ | PRIORITY_HIGH_ACCURACY | Requests a tradeoff that favors highly accurate locations at the possible expense of additional power usage. |

I think if you would set the `desiredAccuracy` to `LocationAccuracy.medium` (or higher) you should get a correct result back from the Geolocator plugin.

In the meantime we will double check if we can improve our documentation and make sure we mention how accuracy is translated into a priority on Android devices.
