### ISSUE TITLE
[Question]: the popup to ask for permission is not coming in windows desktop app but woks fine in macos desktop app

### ISSUE THREAD

**Issue by harshjaiswal833** [Baseflow/flutter-geolocator#1325]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geolocator/blob/main/geolocator/README.md).

### Please select for which platform(s) you need help

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [X] Windows

### Your question

the popup to ask for permission is not coming in windows desktop app but woks fine in macos desktop app thus it is always denied. kindly fix it or provide some way out.

### Version

0.0.1

**Comment by mvanbeusekom** [comment]
Describes the same behaviour as issue #1100, I will close this issue and keep track of state in #1100. Thanks for reporting.
