### ISSUE TITLE
[Bug]: Location services still on even after pausing or cancelling

### ISSUE THREAD

**Issue by noorbakerally** [Baseflow/flutter-geolocator#1327]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [x] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [X] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Steps to reproduce

1. Create a minimal app that uses geolocator 
2.  Cancel the geolocator positionstream before going in background

### Expected results

We expect that the location services are off when app is in the background

### Actual results

On iOS, even if we cancel the positionstream, the location service is still on, we can still the blue GPS indicator 

### Code sample

<details><summary>Code sample</summary>

**Initializing the position stream**
```dart
locationSettings = AppleSettings(
        accuracy: LocationAccuracy.high,
        distanceFilter: distanceFilter,
        pauseLocationUpdatesAutomatically: true,
      );
positionStream =
        Geolocator.getPositionStream(locationSettings: locationSettings).listen(
                (Position? position) {
              if (position != null) {
                onNewLocation(position);
              }
            });
```

**Pausing the position stream**
In the code below, at the time when pausing the stream, we ensure that the `positionstream` is not null
```dart
void setStatusToPaused(){
      positionStream!.cancel();
  }
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

10.0.1

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel unknown, 3.7.0, on macOS 12.5.1 21G83 darwin-x64, locale
    en-MU)
    ! Flutter version 3.7.0 on channel unknown at /Users/admin/Documents/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an
      official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions
      at https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

</details>

**Comment by noorbakerally** [comment]
I get the above issue on iOS whenever the code below to raise an event on location service change

```
Geolocator.getServiceStatusStream().listen((serviceStatus) {
      if (serviceStatus == geolocatorServices.ServiceStatus.enabled) {
        serviceEnabled = true;
        setPositionStream();
      } else {
        serviceEnabled = false;
        positionStream = null;
      }
      notifyListeners();
    });
```

**Comment by JeroenWeener** [comment]
Hi @noorbakerally, thank you for filing this bug report.

You mention that you pause the stream when the app is backgrounded, but did not provide us with the code that does this. Are you using a plugin to achieve this functionality? I don't think the plugin automatically closes, pauses or cancels the stream when the application is put in the background.

Here is the behavior I experience: when I run the latest version (10.1.0) of the plugin on a physical iOS device running iOS 16, the location services are off when cancelling the stream, but remain active when pausing the stream. This is regardless of whether the app is on the background.

**Comment by noorbakerally** [comment]
@JeroenWeener this is part of the codes:


**The function below is from `WidgetsBindingObserver` in native flutter itself.** 

Future<void> didChangeAppLifecycleState(AppLifecycleState state) async {
    if (state == AppLifecycleState.paused || state == AppLifecycleState.inactive) {
      if (some condition is true){
        LocationService.instance.setStatusToPaused();
      }
...
}

**LocationService.instance.setStatusToPaused is defined below:**

```
  void setStatusToPaused(){
      status = LocationStatus.Paused;
      positionStream!.cancel();
      notifyListeners();
  }
```

**Comment by JeroenWeener** [comment]
Hi @noorbakerally,

I have investigated the issue with the code you have provided. You can find the code for the minimal app I created in this gist: https://gist.github.com/JeroenWeener/2dbbb323c91f3979b3bd18d7d5c7e1e2.

Below you find a video demonstration. As you can see, the stream stops, contrary to your findings. Can you point me to the differences between your setup and mine?

https://github.com/Baseflow/flutter-geolocator/assets/9049645/b0ee7470-ec20-4a2c-8ccc-0c2c4cd3d256
