### ISSUE TITLE
Getting the Last Known Location of a Device

### ISSUE THREAD

**Issue by mustafabaki** [Baseflow/flutter-geolocator#1328]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geolocator/blob/main/geolocator/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [X] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Your question

I am planning to get the user's last known location using your package but I have a few questions that I could not find the answer on the documentation. Does the Android system periodically store the user's locations? If not, under which conditions does it store? This is crucial to my project.  Thanks for your help and for developing this wonderful package!

### Version

10.0.1

**Comment by JeroenWeener** [comment]
Hi @mustafabaki!

For Android we make use of either the `FusedLocationProviderClient` or the `LocationManager`, depending on the settings you provide to the plugin.

---

[`FusedLocationProviderClient` documentation](https://developers.google.com/android/reference/com/google/android/gms/location/FusedLocationProviderClient.html#public-abstract-tasklocation-getlastlocation):
'Returns the most recent historical location currently available. Will return null if no historical location is available. The historical location may be of an arbitrary age, so clients should check how old the location is to see if it suits their purposes.'

---

[`LocationManager` documention](https://developer.android.com/reference/android/location/LocationManager#getLastKnownLocation(java.lang.String)):
'Gets the last known location from the given provider, or null if there is no last known location. The returned location may be quite old in some circumstances, so the age of the location should always be checked.

This will never activate sensors to compute a new location, and will only ever return a cached location.'

---

So `getLastKnownPosition()` will return what you would expect: the last known location. The location that was fetched most recently is stored. These are drive-by fetches. The system will not periodically fetch a location, only store locations that are fetched anyway. For an up-to-date location you can use `getCurrentLocation()`.

**Comment by mustafabaki** [comment]
I really appreciate your answer. I wanted to use `getCurrentLocation()` function as well but I need to get the location of the user even if the app is killed so I am not sure if this library can handle this situation.  Do you think would it work combining `getCurrentLocation()` with Android Alarm Manager if the user gives the location permission always to the application?

**Comment by JeroenWeener** [comment]
We do not officially support background tracking yet. There is an issue concerning this feature where users have provided their approaches: https://github.com/Baseflow/flutter-geolocator/issues/53. The solution you are searching for depends on the exact use case. You could try to run the application in the background by using a different package, and then call `getPositionStream()`, for example.

**Comment by mustafabaki** [comment]
I really appreciate your support 👍
