### ISSUE TITLE
[Question]: deprecation msg

### ISSUE THREAD

**Issue by blondie63** [Baseflow/flutter-geolocator#1341]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geolocator/blob/main/geolocator/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Your question

On my flutter project i'm using last geolocator and builnding apk i've this warning:
Note: /Users/mauro/.pub-cache/hosted/pub.dev/geolocator_android-4.3.0/android/src/main/java/com/baseflow/geolocator/location/LocationManagerClient.java uses or overrides a deprecated API.

Can i fix it ?

### Version

10.1.0

**Comment by feykro** [comment]
I have just upgraded my pubspec.yaml to use version 10.1.0 and I'm also still getting the same deprecation notice.

**Comment by JeroenWeener** [comment]
We released a patch! You can get it by running `flutter pub upgrade`. Please check that your `pubspec.lock` file contains `geolocator_android ... version: "4.3.1"` or higher.
