### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by Espero1995** [Baseflow/flutter-geolocator#1342]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geolocator/blob/main/geolocator/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Your question

I ran some Android phones and found few error:
unable to connect to service: com.google.android.location.internal.GoogleLocationManagerService.START on com.google.android.gms.
The service for com.google.android.gms.common.internal.service.zap is not available: ConnectionResult{statusCode=SERVICE_VERSION_UPDATE_REQUIRED, resolution=null, message=null}

### Version

10.1.0

**Comment by mvanbeusekom** [comment]
Can you provide more details please? Questions I have are:

- On which phones (brand, model, OS version) does this problem occur?
- What is the output of the `flutter doctor -v` command?
- Does this error happen at runtime or compile time?

**Comment by Espero1995** [comment]
I set the properties "forceAndroidLocationManager: true", but I found that some Android phones do not return the latitude and longitude.

**Comment by mvanbeusekom** [comment]
This is possible depending on the `desiredAccuracy` level you have set. Some points you might want to look into:

1. If the `desiredAccuracy` is set to `LocationAccuracy.lowest`, the location services will only return location updates if other apps actively requesting location updates. This is a special setting which reduces the battery usage (more details can be found in the Location accuracy section of the README).
2. If the `desiredAccuracy` is set to `LocationAccuracy.high` or better, the location services will only use the GPS provider to get location fixes. For this to work the device needs to have clear sight to the sky and means this usually doesn't work while inside of a building.

If you want us to help more detailed please provide the earlier requested information. On top of that example code is always very helpful as well.

**Comment by Espero1995** [comment]
I've solved this problem！`static Future<Position?> getCurrentLocation(
      {LocationAccuracy? accuracy}) async {
    try {
      var pos = await Geolocator.getCurrentPosition(
          forceAndroidLocationManager: true,
          timeLimit: const Duration(milliseconds: 500),
          desiredAccuracy: accuracy ?? LocationAccuracy.high);
      console.log("posotion:${pos.toJson()}");
      return pos;
    } catch (e) {
      return Geolocator.getLastKnownPosition(forceAndroidLocationManager: true);
    }
  }`
