### ISSUE TITLE
[Feature Request]: Add LocationPermission.prompt status

### ISSUE THREAD

**Issue by Prn-Ice** [Baseflow/flutter-geolocator#1356]
### Is there already an issue requesting this feature?

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).

### Please select affected platform(s)

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [X] Web
- [ ] Windows

### Use case

On Safari or Firefox, if users don't select the **remember** location permission checkbox, the browser sets the status as `prompt` Currently, the web plugin interprets this as a denial of permission. https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator_web/lib/src/utils.dart#L38

### Proposal

We should add a `prompt` status to  `LocationPermission`.

**Comment by mvanbeusekom** [comment]
Hi @Prn-Ice,

With the current versions of the geolocator plugin we strive to create a common cross-platform interface. Regarding permissions and there states we decided to use the following values which can be applied to all platforms:

- `denied`: This is the default permission state and means the application should request permission. This state is also returned when the user denies permission and the system will allow requesting permissions on a later time (e.g. the use case where Safari and Firefox return the `prompt` state).
- `permanentlyDenied`: This status is returned when the user denied permission and doesn't allow requesting permissions again (e.g. when the user selected the remember location permission checkbox).
- `granted`: The user granted permissions and the application is allowed to access the location services. 

At this time we are not planning to add another status that will only work for one specific platform. Possibly in the future we will refactor the geolocator to allow access to the native APIs next to the cross-platform interface, however that is something for the future.

I hope this answers your question. I will go ahead and close this issue now as `denied` means `prompt` in this case.

**Comment by Prn-Ice** [comment]
> Hi @Prn-Ice,
> 
> With the current versions of the geolocator plugin we strive to create a common cross-platform interface. Regarding permissions and there states we decided to use the following values which can be applied to all platforms:
> 
> * `denied`: This is the default permission state and means the application should request permission. This state is also returned when the user denies permission and the system will allow requesting permissions on a later time (e.g. the use case where Safari and Firefox return the `prompt` state).
> * `permanentlyDenied`: This status is returned when the user denied permission and doesn't allow requesting permissions again (e.g. when the user selected the remember location permission checkbox).
> * `granted`: The user granted permissions and the application is allowed to access the location services.
> 
> At this time we are not planning to add another status that will only work for one specific platform. Possibly in the future we will refactor the geolocator to allow access to the native APIs next to the cross-platform interface, however that is something for the future.
> 
> I hope this answers your question. I will go ahead and close this issue now as `denied` means `prompt` in this case.

Thanks
