### ISSUE TITLE
[Feature Request]:  update to uuid 4.1.0

### ISSUE THREAD

**Issue by ivanzhadnov** [Baseflow/flutter-geolocator#1357]
### Is there already an issue requesting this feature?

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).

### Please select affected platform(s)

- [X] Android
- [X] iOS
- [X] Linux
- [X] macOS
- [X] Web
- [X] Windows

### Use case

Please update uuid package to  uuid 4.1.0

### Proposal

 
<img width="630" alt="изображение" src="https://github.com/Baseflow/flutter-geolocator/assets/44845863/d2606499-372b-4675-ba72-10e66fe6d09d">

**Comment by JeroenWeener** [comment]
Hi @ivanzhadnov!

Could you tell us about the need for updating the package? Why is this necessary in your opinion?

**Comment by ivanzhadnov** [comment]
at my project i also use  syncfusion_flutter_pdfviewer
and i cannot use both of them(

**Comment by mvanbeusekom** [comment]
Hi @ivanzhadnov, 

I have published an update of the geolocator_android package (new version: 4.3.2) which updates the dependency. Running `flutter pub upgrade` should resolve the problem.
