### ISSUE TITLE
Add privacy manifest for Apple

### ISSUE THREAD

**Issue by mvanbeusekom** [Baseflow/flutter-geolocator#1360]
Starting from April 2024 SDKs used by applications that are published to the Apple App Store need to specify a privacy manifest and digital signature.

Apple reached out with the following:

> I lead the Creative Pro Partnership Management team in Apple Worldwide Developer Relations. We manage the relationship with developers who create developer tools, photography, music, 2D/3D design, 3D and gaming pipeline, and production-focused apps and hardware.
>
> As you may know, in June, Apple [announced](https://developer.apple.com/news/?id=av1nevon) new features to help users understand developers’ privacy and data collection and sharing practices. These new features include privacy manifests and signatures, which we encourage all third-party SDKs to adopt to provide transparency to users and help secure the software supply chain. Third-party SDKs that impact user privacy will be expected to include a privacy manifest and signature, and starting in Spring 2024, new and updated apps that include these third-party SDKs will need to include their manifest and signature to submit to the App Store. 
>
> Your SDK geolocator_apple, may have significant impact on the privacy of the users of apps that include it. We’re reaching out to make sure you are aware of this upcoming change, and to provide resources to help. If you have any questions about implementing privacy manifests and/or signatures, you can reach out to me and I’ll do my best to escalate your questions. 
>
> Here are some additional resources that may be helpful: 
> - You can read[ documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files) about creating a privacy manifest file.
> - Our [User Privacy and Data Use page](https://developer.apple.com/app-store/user-privacy-and-data-use/) has details about requirements for developers.
> - You can [watch videos](https://developer.apple.com/videos/privacy-security/) about adopting privacy manifests and signatures for your SDK.

Flutter is tracking this in flutter/flutter#131940

**Comment by stuartmorgan** [comment]
Have you had any communication with Apple about how to describe usage of location information an the SDK level, given that it's the client application that will ultimately use the data?

**Comment by ShuheiSuzuki-07** [comment]
Hello!

What is the status of the response to this matter?
You may need an empty manifest even if you are not collecting anything 😭
https://github.com/flutter/flutter/issues/131940#issuecomment-1881641272

If an empty manifest is ok I may be able to create a PR for you too.

**Comment by yh-luo** [comment]
Apple has indicated an enforcement date of [May 1st](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc) for Privacy Manifests.
> Starting May 1, 2024, apps that don’t describe their use of required reason API in their privacy manifest file aren’t accepted by App Store Connect.

**Comment by mvanbeusekom** [comment]
We have just release version 2.3.7 of the geolocator_apple package which includes the required privacy manifest. More details can be found in PR #1462.
