### ISSUE TITLE
[Question]: [CoreLocation] This method cause UI unresponsiveness if invoked on the main thread. Instead, consider waiting for the '-locationManagerDidChangeAuthorization:' callback and checking 'authorizationStatus' first

### ISSUE THREAD

**Issue by Ellynnn** [Baseflow/flutter-geolocator#1368]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geolocator/blob/main/geolocator/README.md).

### Please select for which platform(s) you need help

- [ ] Android
- [X] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Your question

I kept getting that warning when I'm running in debug mode on IOS but the app is still runnable. However, when I run in release mode, the UI stopped reacting and I'm stuck with a white screen.

When I comment up the `Geolocator.getServiceStatusStream().Listen((status) {})` and run in debug mode, the warning is gone.

Can I know how to solve this problem?

### Version

10.1.0

**Comment by TimHoogstrate** [comment]
Dear @Ellynnn,

Can you elaborate a bit on the issue? Where do see the warning exactly? When do you see a white screen?

Kind regards,

**Comment by Ellynnn** [comment]
@TimHoogstrate the warning prompts in the console

**Comment by natsuk4ze** [comment]
Hi @mvanbeusekom 

I can provide the screenshot. I wish this helps.

<img width="2583" alt="スクリーンショット 2023-12-27 22 09 27" src="https://github.com/Baseflow/flutter-geolocator/assets/50433979/4c5a5f47-6a7c-4cb0-ba24-f51b36a45234">

**Comment by mvanbeusekom** [comment]
Hi @natsuk4ze ,

Thank you for providing this screenshot. That clarifies a lot, I will try to provide an update shortly.

**Comment by mvanbeusekom** [comment]
I have just published version 2.3.3 of the geolocator_apple package which should resolve this problem. Running `flutter pub upgrade` should ensure the latest dependency is downloaded in case it doesn't happen right away.

Thanks to everyone for pointing out the issue.
