### ISSUE TITLE
Geocoding address not working as expected

### ISSUE THREAD

**Issue by dark-chocolate** [Baseflow/flutter-geolocator#137]
## 🐛 Bug Report

The placemark object doesn't show accurate address. 

### Expected behavior
For instance: While using 37.750345, -122.421060 as latitude and longitude, the address shown should be 
`1406 Valencia St, San Francisco, CA 94110, USA`

But placemark object returns 
`3531, 3531, 25th Street, , San Francisco, 94110, United States`

### Reproduction steps
```
List<Placemark> placeMarkAdd = await Geolocator().placemarkFromCoordinates(37.750345, -122.421060);
Placemark placemark = placeMarkAdd[0];
print("address = ${placemark.name}, ${placemark.subThoroughfare}, ${placemark.thoroughfare}, ${placemark.subLocality}, ${placemark.locality}, ${placemark.postalCode}, ${placemark.country}");
```

**Platform:** 
Tested on Samsung Galaxy S8+ running Android 8.0

**Comment by arctouch-felipepessoa** [comment]
Some problem here.
Did you solve it? same device as well

**Comment by dark-chocolate** [comment]
@arctouch-felipepessoa Not yet, kindly upvote the issue to bring more attention from community.

**Comment by mvanbeusekom** [comment]
Since version 6.0.0 the geocoding features are no longer part of the geolocator plugin and moved to their own plugin which can be found [here](https://github.com/baseflow/flutter-geocoding).
