### ISSUE TITLE
[Question]: getPostionStream not working on IOS

### ISSUE THREAD

**Issue by mhmdVoj** [Baseflow/flutter-geolocator#1372]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geolocator/blob/main/geolocator/README.md).

### Please select for which platform(s) you need help

- [ ] Android
- [X] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Your question

Hi,I use getPositionStream for tracking user in my app. and I config package with below code : 
``` if (Platform.isAndroid) {
        locationSettings = geolocator.AndroidSettings(
            accuracy: geolocator.LocationAccuracy.bestForNavigation,
            distanceFilter: 100,
            forceLocationManager: false,
            intervalDuration: const Duration(seconds: 10),
            //(Optional) Set foreground notification config to keep the app alive
            //when going to the background
            foregroundNotificationConfig:
                const geolocator.ForegroundNotificationConfig(
              notificationText: "myApp is Tracking your mileage ",
              notificationTitle: "myApp",
              enableWakeLock: true,
            ));
      } else if (Platform.isIOS) {
        locationSettings = geolocator.AppleSettings(
          accuracy: geolocator.LocationAccuracy.bestForNavigation,
          activityType: geolocator.ActivityType.fitness,
          distanceFilter: 100,
          pauseLocationUpdatesAutomatically: true,
          // Only set to true if our app will be started up in the background.
          showBackgroundLocationIndicator: true,
        );
      } else {
        locationSettings = geolocator.LocationSettings(
          accuracy: geolocator.LocationAccuracy.high,
          distanceFilter: 100,
        );
      }
```
and I tracking position like this  (location permissions are granted (always use): 
```
StreamSubscription<Position> positionStream = Geolocator.getPositionStream(locationSettings: locationSettings).listen(
    (Position? position) {
        print(position == null ? 'Unknown' : '${position.latitude.toString()}, ${position.longitude.toString()}');
    });
```
but in IOS (any version) version when user pause the application or lock the screen stream stop and tracking not working any more until user back in application! 

### Version

9.0.2

**Comment by TimHoogstrate** [comment]
Dear @mhmdVoj,

Did you enable background location tracking for iOS? As mentioned in the README? 



![Image](https://github.com/Baseflow/flutter-geolocator/assets/7558640/89b302d5-6dd2-492a-92ae-94dbbcab7e69)

Kind regards,
