### ISSUE TITLE
[Bug]: Geolocator.getCurrentPosition

### ISSUE THREAD

**Issue by ynmain** [Baseflow/flutter-geolocator#1373]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Steps to reproduce

On Android
When I run Geolocator.getCurrentPosition
It often happens that the response takes about 5 seconds.

It's been happening all of a sudden in the last few days.

Is there any workaround?

geolocator
ver 10.0.0

### Expected results

Does running Geolocator.getCurrentPosition over a short span cause a delay?

### Actual results

On Android
When I run Geolocator.getCurrentPosition
It often happens that the response takes about 5 seconds.

### Code sample

<details><summary>Code sample</summary>

```dart
final currentPosition = await Geolocator.getCurrentPosition();
await ref
    .read(searchConditionStateNotifierProvider.notifier)
    .getSaunasFrom(LatLng(
        currentPosition.latitude, currentPosition.longitude));
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

3.13.0

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.5.2 22G91 darwin-arm64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.74.0)
[✓] Connected device (5 available)
    ! Error: Browsing on the local area network for iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!
```

</details>

**Comment by TimHoogstrate** [comment]
Dear @ynmain,

Can you paste your settings here? If you for example use the GPS for positioning (forceLocationManager = true) it might be very well possible that it takes some time to determine your position. 

Kind regards,

**Comment by yosuke-nakayama** [comment]
Hello

The code is as per the issue

```
final currentPosition = await Geolocator.getCurrentPosition();
await ref
    .read(searchConditionStateNotifierProvider.notifier)
    .getSaunasFrom(LatLng(
        currentPosition.latitude, currentPosition.longitude));
```

Strangely, there are no delays today.

Did you change any settings on that side?

**Comment by ynmain** [comment]
Hello

The code is as per the issue

```
final currentPosition = await Geolocator.getCurrentPosition();
await ref
    .read(searchConditionStateNotifierProvider.notifier)
    .getSaunasFrom(LatLng(
        currentPosition.latitude, currentPosition.longitude));
```

Strangely, there are no delays today.

Did you change any settings on that side?
