### ISSUE TITLE
[Question]: android a811 geolocator exception 

### ISSUE THREAD

**Issue by michael-kim-korea** [Baseflow/flutter-geolocator#1376]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geolocator/blob/main/geolocator/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Your question

It doesn't seem to be supported on this (android a811) device. If anyone has tested it, please respond.
thank you !!

```
serviceEnabled = await Geolocator.isLocationServiceEnabled();
    // final hasPermission = await Permission.locationWhenInUse.serviceStatus.isEnabled;
    if (!serviceEnabled) {
      bool serviceEnabled = await Geolocator.openLocationSettings();
      if (!serviceEnabled) {
      return Future.error('Location services are disabled.');
      }
    }
```

    permission = await Geolocator.checkPermission();
    if (permission == LocationPermission.denied) {
      permission = await Geolocator.requestPermission();
      if (permission == LocationPermission.denied) {
        // Permissions are denied, next time you could try
        // requesting permissions again (this is also where
        // Android's shouldShowRequestPermissionRationale
        // returned true. According to Android guidelines
        // your App should show an explanatory UI now.
        return Future.error('Location permissions are denied');
      }
    }

    if (permission == LocationPermission.deniedForever) {
      // Permissions are denied forever, handle appropriately.
      return Future.error(
          'Location permissions are permanently denied, we cannot request permissions.');
    }

    // When we reach here, permissions are granted and we can
    // continue accessing the position of the device.
    final loc = await Geolocator.getCurrentPosition();

    debugPrint('loc --------> ${loc.toString()} ');

Syncing files to device a811...
W/GooglePlayServicesUtil(22227): com.example.my_test requires the Google Play Store, but it is missing.
I/art     (22227): Rejecting re-init on previously-failed class java.lang.Class<com.baseflow.geolocator.location.NmeaClient$$ExternalSyntheticLambda0>
I/art     (22227): Rejecting re-init on previously-failed class java.lang.Class<com.baseflow.geolocator.location.NmeaClient$$ExternalSyntheticLambda0>
W/GooglePlayServicesUtil(22227): com.example.my_test requires the Google Play Store, but it is missing.
E/flutter (22227): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: The location service on the device is disabled.
E/flutter (22227): #0      GeolocatorAndroid.getCurrentPosition (package:geolocator_android/src/geolocator_android.dart:139:7)
E/flutter (22227): <asynchronous suspension>
E/flutter (22227): #1      _MyHomePageState._incrementCounter (package:my_test/my_geolocator.dart:85:17)
E/flutter (22227): <asynchronous suspension>
E/flutter (22227): 

It doesn't seem to be supported on this (android a811) device. If anyone has tested it, please respond.
thank you !!

### Version

geolocator: ^9.0.2 or geolocator: ^10.1.0

**Comment by TimHoogstrate** [comment]
Dear @michael-kim-korea,

I was able to test the example app on a device without play services. I cannot reproduce your issue. In order to help you please send us the output of `flutter doctor -v`. Can you try if the example app is working properly?

Kind regards,
