### ISSUE TITLE
[Bug]: PermissionRequestInProgressException not being thrown as expected on Android

### ISSUE THREAD

**Issue by dbmessina** [Baseflow/flutter-geolocator#1378]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Steps to reproduce

The following behavior has been observed on Android 13 and 14 emulator in debug mode and on an Android 13 phone in release mode.

1. Display a permission dialog such as for notifications
2. Without dismissing the dialog from step 1, call requestPermission() inside of a try/catch
3. A message is displayed in the console "Can request only one set of permissions at a time" but the PermissionRequestInProgressException is not thrown yet the code does not proceed past requestPermission()... refer to screenshot

![image](https://github.com/Baseflow/flutter-geolocator/assets/96109732/5d3b5724-c81e-41ab-8f5d-3b4841282416)

### Expected results

A PermissionRequestInProgressException should be thrown when requesting permission while another permission dialog is already visible

### Actual results

A PermissionRequestInProgressException is not being thrown when requesting permission while another permission dialog is already visible and the code execution halts despite console messages confirming the issue

### Code sample

<details><summary>Code sample</summary>

```dart
// Initiate some other permission dialog

debugPrint("Checking");
var permission = await Geolocator.checkPermission();

if (permission == LocationPermission.denied) {
  try {
    debugPrint("Requesting");
    await Geolocator.requestPermission();
    debugPrint("Requested");
  } on Exception {
    debugPrint("caught");
  } finally {
    debugPrint("finally");
  }

  debugPrint("permission = $permission");
}
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

10.1.0

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.9, on Microsoft Windows [Version 10.0.19045.3570], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.84.2)
[√] Connected device (4 available)  
[√] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by TimHoogstrate** [comment]
Dear @dbmessina,

Can you please provide us with a complete piece of example code? I cannot reproduce this.

Kind regards,

**Comment by dbmessina** [comment]
@TimHoogstrate I've attached a minimal project exhibiting the same behavior.

[permission_test.zip](https://github.com/Baseflow/flutter-geolocator/files/13349962/permission_test.zip)

**Comment by TimHoogstrate** [comment]
@dbmessina,

My log says that it works :) Is that correct? Although this is an Android 13 emulator.

```
I/flutter ( 1658): Before requestPermission()
W/Parcel  ( 1658): Expecting binder but got null!
I/flutter ( 1658): After requestPermission()
I/flutter ( 1658): After try/catch
```

Kind regards,

**Comment by dbmessina** [comment]
@TimHoogstrate I'm also running an Android 13 emulator. When I run the app, the camera permission dialog pops up first as intended, blocking the location permission dialog. That is expected behavior. My console shows the following:

`I/flutter ( 7361): Before requestPermission()
W/Activity( 7361): Can request only one set of permissions at a time
I/Geolocator( 7361): The grantResults array is empty. This can happen when the user cancels the permission request`

I would expect it to land in the catch block and it doesn't. Your console output is what I would expect if you didn't have another permission dialog blocking the location one. Is this from the second time you ran the app?

**Comment by TimHoogstrate** [comment]
Dear @dbmessina,

I just re-run the project and it seems that I don't see the camera permission dialog. Log is first run: 

I/flutter ( 2132): Before requestPermission()
W/Parcel  ( 2132): Expecting binder but got null!
I/flutter ( 2132): After requestPermission()
I/flutter ( 2132): After try/catch

**Comment by dbmessina** [comment]
@TimHoogstrate The app is very straightforward, I'm not sure why you aren't seeing the camera permission dialog on a first run after install. I could attach a screen recording... would that be helpful?

**Comment by TimHoogstrate** [comment]
Aah now I get it. Now I see the:

```
I/flutter (18818): Before requestPermission()
W/Activity(18818): Can request only one set of permissions at a time
```
This is expected behaviour. You can request location and camera permissions through the permission handler. If you want to request multiple permissions "simultaneously" you can use: 

```
// You can request multiple permissions at once.
Map<Permission, PermissionStatus> statuses = await [
  Permission.location,
  Permission.storage,
].request();
```

Kind regards,

**Comment by dbmessina** [comment]
@TimHoogstrate Okay, I'll switch to that approach if this is working as intended. But it doesn't seem to be since there is an exception for exactly this situation and it's not landing in the catch block, we only get debug console output.
