### ISSUE TITLE
[Question]: Why is the Geolocator plugin sometimes not picking up the approximate location? But it always picks up the location if we switch on the precise location permission?

### ISSUE THREAD

**Issue by AdeeshaP** [Baseflow/flutter-geolocator#1381]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geolocator/blob/main/geolocator/README.md).

### Please select for which platform(s) you need help

- [ ] Android
- [X] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Your question

Flutter app always picks up the location if we switch on the precise location permission. But sometimes it does not picks up the location if we give permission for approximate location only. 

### Version

10.1.0

**Comment by TimHoogstrate** [comment]
Dear @AdeeshaP,

Thanks for filing this issue. It is possible that this happens depending on other location settings that you use. For example, about the disiredAccuracy: [Apple says](https://developer.apple.com/documentation/corelocation/kcllocationaccuracyreduced?language=objc): 
```
The location service does its best to achieve the requested accuracy; however, apps must be prepared to use less accurate data. If your app isn’t authorized to access precise location information (authorizedForPreciseLocation is NO), changes to this property’s value have no effect; the accuracy is always [kCLLocationAccuracyReduced]
```

```
kCLLocationAccuracyReduced

The accuracy of location data is reduced in both space and time using approaches like selecting a nearby point of interest and updating the location at most a few times per hour. The approximate location preserves the user’s country or region, typically preserves the city, and is usually within 1–20 kilometers of the actual location.

If your app is authorized to access location information with full accuracy, you can use this constant to access location data as if the app didn’t have that authorization.
```

This means that It might be possible that is will not be triggered. 0 in this case, = there is no distance filter. For a complete investigation please add the settings that you use. 

Kind regards,
