### ISSUE TITLE
[Question]:  Conflict Between Geolocator Library and mapbox-maps-flutter Library

### ISSUE THREAD

**Issue by shihanjun19** [Baseflow/flutter-geolocator#1386]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geolocator/blob/main/geolocator/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Your question

I encountered a problem while running the project using mapbox-maps-flutter/example/ (https://github.com/mapbox/mapbox-maps-flutter/tree/main/example). After integrating other location libraries, such as geolocator: ^10.1.0, I found that the animated route line page in the mapbox example failed to obtain the correct location during real device debugging. I'm wondering if the inclusion of geolocator causes it to monopolize location acquisition capabilities, thereby rendering location-related functions of other packages ineffective?

**Steps to Reproduce:**
1. Download the mapbox flutter example project.
2. Add either location: ^5.0.3 or geolocator: ^10.1.0 to the project's pubspec.yaml file.
3. Run the project.
4. Notice that mapbox is unable to acquire location data.

**Error Log:**
```
I/Mapbox  (18814): [maps-core]: Using OpenGL render backend
I/Mapbox  (18814): [threading]: MapboxRenderThr priority is now -10
I/Mapbox  (18814): [maps-android\Mbgl-RenderThread]: Native renderer created.
I/Mapbox  (18814): [maps-android\Mbgl-RenderThread]: onSurfaceCreated: Android surface was processed.
I/Mapbox  (18814): [threading]: Worker 1 priority is now 4
I/Mapbox  (18814): [maps-core]: {MapboxRenderThr}[General]: GPU Identifier: Mali-G76
I/Mapbox  (18814): [threading]: ResourceLoaderT priority is now 4
I/Mapbox  (18814): [threading]: TileStoreFileSo priority is now 4
E/flutter (18814): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (18814): #0      PuckPosition.getPuckPosition (package:mapbox_maps_example/utils.dart:92:42)
E/flutter (18814): <asynchronous suspension>
E/flutter (18814): #1      AnimatedRouteState.refreshTrackLocation.<anonymous closure> (package:mapbox_maps_example/animated_route.dart:130:26)
E/flutter (18814): <asynchronous suspension>
```

**Device Information:**
- Phone: HUAWEI P30
- OS: HarmonyOS 3.0.0

### Version

10.1.0

**Comment by TimHoogstrate** [comment]
Dear @shihanjun19,

Does this also happen when you only add location: ^5.0.3 to the project?

Kind regards,
