### ISSUE TITLE
[Regression]: on version 10.1.0 with android getCurrentPosition takes at least 30 seconds to load. I tried ^8.2.0 and it takes only 0.02s

### ISSUE THREAD

**Issue by tomasbutkevicius** [Baseflow/flutter-geolocator#1394]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Old behavior

in ^8.2.0 takes 0.02seconds to getCurrentPosition

### Current behavior

in ^10.1.0 takes 30seconds to getCurrentPosition

### Steps to reproduce

1. use Android, emulator works too
2. call  Geolocator.getCurrentPosition
3. Measure time in any way you like

### Code sample

<details><summary>Code sample</summary>

```dart
  Future<Position> determinePosition() async {
    bool canMockLocation = await SafeDevice.canMockLocation;

    if (canMockLocation && isProduction) {
      return Future.error(MapException('Device not allowed'));
    }

    bool serviceEnabled;
    LocationPermission permission;

    // Test if location services are enabled.
    serviceEnabled = await Geolocator.isLocationServiceEnabled();
    if (!serviceEnabled) {
      // Location services are not enabled don't continue
      // accessing the position and request users of the
      // App to enable the location services.
      return Future.error(MapException('Location services are disabled.'));
    }

    permission = await Geolocator.checkPermission();
    if (permission == LocationPermission.denied) {
      permission = await Geolocator.requestPermission();
      if (permission == LocationPermission.denied) {
        // Permissions are denied, next time you could try
        // requesting permissions again (this is also where
        // Android's shouldShowRequestPermissionRationale
        // returned true. According to Android guidelines
        // your App should show an explanatory UI now.
        return Future.error(MapException('Location permissions are denied'));
      }
    }

    if (permission == LocationPermission.deniedForever) {
      // Permissions are denied forever, handle appropriately.
      return Future.error(MapException('Location permissions are permanently denied, we cannot request permissions.'));
    }

    // When we reach here, permissions are granted and we can
    // continue accessing the position of the device.
    Position? position = await Geolocator.getLastKnownPosition();

    position ??= await Future.any([
      Geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.best),
      Future.delayed(const Duration(seconds: 5), () => null),
    ]);
    position ??= await Geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.best);

    lastKnowPosition = position;
    return position;
  }
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Current version

10.10

### Last version without regression

^8.2.0 but may be other

**Comment by sulaimanpgm** [comment]
I have the same problem.

**Comment by GustavoFigueira** [comment]
Same here, I've tested on two devices:

1 - Moto G54: almost instantly
2 - Realme 8 Pro: takes about 4-5 seconds

**Comment by TimHoogstrate** [comment]
Dear @tomasbutkevicius,

For now I cannot reproduce this. However, I noticed that you added a required location accuracy "best". Could something be interfering with your location determination. Is it also happening if you play a bit with the location settings?

Kind regards,

**Comment by eb-so** [comment]
I'm also on 10.1.0 
My device is Redmi 8 and it hangs forever
I noticed the issue only after I upgraded to flutter 3.16.5
I tried changing the settings from high to medium but still seeing the issue
Note: the issue doesn't appear on my emulator Pixel_3_API_30

**Comment by mvanbeusekom** [comment]
Hello @tomasbutkevicius, @GustavoFigueira , @eb-so,

This problem has been reported before (see #1243) and several developers confirmed the issue being related to the use of the "safe_device" plugin. Could you confirm if this is also the case for you?

**Comment by tomasbutkevicius** [comment]
@mvanbeusekom hello, I can't check right now but I do use safe_device plugin

**Comment by tomasbutkevicius** [comment]
changing the accuracy did nothing

**Comment by eb-so** [comment]
@mvanbeusekom Sorry for the late response but that's true the safe_device plugging was the issue, kind of weird behavior.

Thanks for the help 🙏

**Comment by tomasButkeviciusAdapt** [comment]
Thank you for your attention and work guys! But I am wondering why close the issue if it's not resolved? I would prefer to leave the issue and when you resolve it then you can close because now it would be like ignoring this, would it not? Also keeping this issue open could be a reminder of what needs to be fixed?

**Comment by eb-so** [comment]
@tomasbutkevicius Maybe it's `safe_device` package issue, I'm now using `root_jailbreak_sniffer` with no problems

**Comment by mvanbeusekom** [comment]
@tomasButkeviciusAdapt, I have closed the issue because I strongly suspect the issue is not related to geolocator but as @eb-so also mentions with the `safe_device` plugin.

**Comment by Nhowka** [comment]
I have the same problem without using `safe_device`. Is there any other possible causes?
