### ISSUE TITLE
[Question]: offline mode

### ISSUE THREAD

**Issue by axroromonov** [Baseflow/flutter-geolocator#1400]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geolocator/blob/main/geolocator/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [X] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Your question

Is it possible to get a location through this package even if there is no internet? , my application works without internet , I need to go to the mountainous areas and get the location from there , there is no internet , how much does this package support it ?

### Version

10.1.0

**Comment by TimHoogstrate** [comment]
Dear @axroromonov,

It depends a lot on the settings and platform that you use, however, in general it should be possible to determine a location without internet. The phone then uses GPS, cellphone network or Wifi to determine the location.

Kind regards,

**Comment by asoko2** [comment]
Hi, @TimHoogstrate , i'm having the same issue here, I cannot get the current GPS location if the device is offline. 
I couldn't find the answer anywhere, could you please help me?
