### ISSUE TITLE
[Question]: Position from getPositionStream() has 0 altitude

### ISSUE THREAD

**Issue by Velek** [Baseflow/flutter-geolocator#1412]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geolocator/blob/main/geolocator/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Your question

I have been using geolocator for quite a while, but after I just did a flutter upgrade, and now the altitude I get from listen()ing to getPositionStream() is always returning 0 for the altitude in the closure, even though there are more than 10 or 20 satellites in solution.  The position I'm getting makes sense.
Using the following location settings:
      locationSettings = AndroidSettings(
          useMSLAltitude: true,
          accuracy: LocationAccuracy.bestForNavigation,
          distanceFilter: 0,
          forceLocationManager: true,
          intervalDuration: const Duration(seconds: 0),
          //(Optional) Set foreground notification config to keep the app alive
          //when going to the background
          foregroundNotificationConfig: const ForegroundNotificationConfig(
            notificationText:
                "Marble Navigator will continue to receive your location even when you aren't using it",
            notificationTitle: "Running in Background",
            enableWakeLock: true,
          ));

### Version

10.1.0

**Comment by andreastambazzi** [comment]
i have the same issue

https://github.com/Baseflow/flutter-geolocator/issues/1414

**Comment by ken-salterdiazsolutions** [comment]
This all of a sudden started happening to me.  Altitude, speed and heading are all 0, but I do get lat and lon updated.

**Comment by nilskntl** [comment]
Is this a known issue? I have just switched to geolocator. With the Location package everything worked fine.

**Comment by Wackymax** [comment]
Fixed in https://github.com/Baseflow/flutter-geolocator/pull/1415

**Comment by TimHoogstrate** [comment]
> Fixed in #1415
> 
> Use this to get the fix while we wait for the PR process:
> 
> ```
> dependency_overrides:
>   geolocator_android:
>     git:
>       url: https://github.com/Wackymax/flutter-geolocator.git
>       path: geolocator_android
>       ref: 135277e44e8283bae5473691324405fe360c844e
> ```

The pr is merged, I'll close this issue. Feel free to reopen when needed op open a new issue.
