### ISSUE TITLE
[Bug]: Android 13 getPositionStream fail

### ISSUE THREAD

**Issue by RoxDevvv** [Baseflow/flutter-geolocator#1413]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Steps to reproduce

1- Start the app with Location Service OFF (This setup what trigger the problem in Android 13)
2- Turn ON Location Service
 

### Expected results

getPositionStream should work 

### Actual results

On android 13 getPositionStream not working most of the time 
Also, I test on android 10 it works as I Expected 

### Code sample

<details><summary>Code sample</summary>

```dart
  LocationListener() async {
    if (locationListener != null) return;

    final geo.LocationSettings locationSettings =
        geo.LocationSettings(accuracy: geo.LocationAccuracy.high);
    locationListener =
        geo.Geolocator.getPositionStream(locationSettings: locationSettings)
            .listen((geo.Position? position) {
      print(position == null
          ? 'Unknown'
          : '${position.latitude.toString()}, ${position.longitude.toString()}');
    });
  }
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

10.1.0

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by RoxDevvv** [comment]
i got it , it is not about Android version it is about location hardware taking time before being ready , calling getPositionStream right away after enabling location using dialogue will fail .
the solution is doing delay between location dialogue and getPositionStream

**Comment by mvanbeusekom** [comment]
Hello @RoxDevvv,

Thank you for taking the time an submitting this issue. Reading your comment it is not quite clear to me if your issue is solved or not. Could you please confirm?
