### ISSUE TITLE
[Bug]: Unable to run on Windows : Failed to install nuget package Microsoft.Windows.CppWinRT.2.0.220418.1

### ISSUE THREAD

**Issue by gadjetnut** [Baseflow/flutter-geolocator#1437]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [X] Windows

### Steps to reproduce

1. Open a new 'Hello World' Flutter project in Visual Studio
2. Run the app (F5)  : Works as expected
3. Add "geolocator: ^10.1.0" to pubspec.yaml
4. Run "flutter clean"
5. Run "flutter pub get"
6. Select device to use : "Windows"
7. Run the app (F5)

### Expected results

The Hello World app should build and run on Windows

### Actual results

Launching lib\main.dart on Windows in debug mode...
Argument cannot be null or empty
Parameter name: primarySources
CMake Error at flutter/ephemeral/.plugin_symlinks/geolocator_windows/windows/CMakeLists.txt:34 (message):
  Failed to install nuget package Microsoft.Windows.CppWinRT.2.0.220418.1
2

Exception: Unable to generate build files

### Code sample

<details><summary>Code sample</summary>

```dart
main.dart
import 'package:flutter/material.dart';

void main() async {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: Text('Hello World!'),
        ),
      ),
    );
  }
}

pubspec.yaml
name: temp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  geolocator: 
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

10.1.0

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
PS C:\src\projects\temp> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.9, on Microsoft Windows [Version 10.0.19045.3930], locale en-CA)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.6)
[√] Android Studio (version 2021.3)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by mvanbeusekom** [comment]
Hi @gadjetnut,

This is a common issue and occurs due to misconfiguration of the development environment. Please have a look at this issue #1299 (and specifically this [comment](https://github.com/Baseflow/flutter-geolocator/issues/1299#issuecomment-1673261558) ) for a solution.
