### ISSUE TITLE
[Enhancement proposal]: throw UnsupportedError instead of UnimplementedError.

### ISSUE THREAD

**Issue by tlserver** [Baseflow/flutter-geolocator#1438]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [X] Web
- [ ] Windows

### Proposal

In the documentation for [`getServiceStatusStream()`](https://pub.dev/documentation/geolocator/latest/geolocator/GeolocatorPlatform/getServiceStatusStream.html), it states:

> Throws an [UnimplementedError](https://api.flutter.dev/flutter/dart-core/UnimplementedError-class.html) on the web, as the concept of location services does not exist on the web platform.

According to the Flutter documentation:

> UnimplementedError class
>
> Thrown by operations that have not been implemented yet.
>
> This [Error](https://api.flutter.dev/flutter/dart-core/Error-class.html) is thrown by unfinished code that has not yet implemented all the features it needs.
>
> If the class does not intend to implement the feature, it should throw an [UnsupportedError](https://api.flutter.dev/flutter/dart-core/UnsupportedError-class.html) instead. This error is intended for use during development only.

Given this, I propose that `getServiceStatusStream()` should throw an `UnsupportedError` instead of an `UnimplementedError`.

Additionally, it should be noted that the documentation for [`GeolocatorPlatform.getServiceStatusStream()`](https://pub.dev/documentation/geolocator/latest/geolocator/GeolocatorPlatform/getServiceStatusStream.html) should be synchronized with [`Geolocator.getServiceStatusStream()`](https://pub.dev/documentation/geolocator/latest/geolocator/Geolocator/getServiceStatusStream.html) to maintain consistency.

Related: #849

#### Enhancement
Switching from `UnimplementedError` to `UnsupportedError` in `getServiceStatusStream()` will provide clearer communication in the codebase, indicating that certain features will intentionally not be implemented on web platforms.

#### Benefits for Contributors
- **Clear Direction**: Saves time by indicating which areas of the codebase are not intended for further development.
- **Consistency**: Synchronizing documentation and error handling across related methods simplifies understanding and collaboration.
- **Code Quality**: Aligns with Flutter's best practices, improving the overall project standard.

#### Impact
Adopting this change will:
- Ensure clarity in development intentions.
- Boost contributor efficiency and satisfaction.
- Serve as a best practice example in the open-source community.

**Comment by mvanbeusekom** [comment]
Hi @tlserver,

Thank you for bringing this to our attention. After some internal discussion we agreed with your reasoning and applied the suggested changes. 

We have recently published version 3.0.0 of the geolocator_web plugin which now throws an `UnsupportedError` for the `getServiceStatusStream` method.
