### ISSUE TITLE
How can i dissable log write in my flutter app using  this pluggin? 

### ISSUE THREAD

**Issue by AswathyMGCdac** [Baseflow/flutter-geolocator#1439]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geolocator/blob/main/geolocator/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [X] iOS
- [X] Linux
- [X] macOS
- [X] Web
- [X] Windows

### Your question

During security audit bugg reported as The App logs information. Sensitive information should never be logged

### Version

  geolocator: ^9.0.2

**Comment by TimHoogstrate** [comment]
Dear @AswathyMGCdac,

Can you elaborate a bit on the subject, and can you show us where it logs "sensitive" information? The plugin does not seem to log any sensitive information.

Kind regards,
