### ISSUE TITLE
Please Update docs 

### ISSUE THREAD

**Issue by CristovoXDGM** [Baseflow/flutter-geolocator#1445]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [X] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Proposal

For Android and Ios we need to add the localization permissions to the Manifest and info.plist, so please, update your readme at pub.dev, because this can save us time.

### Pitch

For Android and Ios we need to add the localization permissions to the Manifest and info.plist, so please, update your readme at pub.dev, because this can save us time.

**Comment by mvanbeusekom** [comment]
Hi @CristovoXDGM,

The current README.md (which is displayed on pub.dev) has separate sections on how to configure the geolocator plugin on Android, iOS, macOS, web and Windows under the "Usage" chapter. Possibly this was over looked as they are presented as bullet points that expand when clicked upon. 

These sections describe exactly which permissions need to be specified in which locations, however if you are missing something specific I would be happy to clarify.

Please let me know if this helps.

**Comment by CristovoXDGM** [comment]
Thanks, this solve my problem, btw, make it more visible

**Comment by mvanbeusekom** [comment]
> Thanks, this solve my problem, btw, make it more visible

Unfortunately we don't have a lot of options to specify format on pub.dev.

We are however working on a more detailed documentation site which should offer a more clear workflow.

Thank you for reporting back, I will go ahead and close this issue.
