### ISSUE TITLE
[Bug]: Crashes because of dereferencing undefined (navigator.geolocation)

### ISSUE THREAD

**Issue by jo-so** [Baseflow/flutter-geolocator#1447]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [ ] iOS
- [x] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Steps to reproduce

1. In Firefox open `about:config`
2. Select `geo.enabled` and set it to false
3. Start an app (e.g. https://fluffychat.im/web/) that requests the geo location

### Expected results

The dereference should not happen, the called should be told that it has no permission to access the geolocation

### Actual results

The app crashes due to access of `geolocation` which is `undefined`
```js
k=window.navigator.geolocation
k.toString
k=new A.bdP(new A.bhZ(k),new A.bi6(window.navigator.permissions))
```

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

2.0.6

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by TimHoogstrate** [comment]
Dear @jo-so,

Can you elaborate a bit on the subject. It seems more related to web then to linux. Second, did you work on: (https://fluffychat.im/web/), and how do you know that this should work? 

Kind regards,
