### ISSUE TITLE
[Bug]: LocationSettings timeLimit not work

### ISSUE THREAD

**Issue by gogommd** [Baseflow/flutter-geolocator#1448]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Steps to reproduce

I added the timeLimit to 5 minutes in LocationSettings

### Expected results

The position should be updated in a 5-minute interval

### Actual results

The position update without any interval

### Code sample

<details><summary>Code sample</summary>

```dart
Future<void> uploadLocation() async {
    final LocationSettings otherLocationSettings = LocationSettings(
      timeLimit: Duration(minutes: 10),
      accuracy: LocationAccuracy.high,

    );
    updatePositionStream =
        Geolocator.getPositionStream(locationSettings: otherLocationSettings)
            .listen((Position? position) {
          if (mounted) {
            setState(() {
              if (position == null) {
                updatePositionStream?.cancel();
                print('Unknown');
              } else {
                final CurrentLocationModel location =
                CurrentLocationModel(
                    locationId:
                    Random().nextInt(9999).toString(),
                    latitude: position.latitude,
                    longitude: position.longitude,
                    address: address,
                    date: date,
                    time: time);
                FirestoreRepository()
                    .uploadCurrentAddress(location);
                print(
                    '${position.latitude.toString()}, ${position.longitude.toString()}');
              }
            });
          }
        });
  }
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

11.0.0

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by TimHoogstrate** [comment]
Dear @gogommd,

Thanks for reaching out again :). First, your code suggests a time limit of 10 minutes. Second, can you explain a bit how you are testing this. Can you for example explain something about the device you are testing on? And are you testing this while walking outside? Or in a building? (indoor it might be difficult to determine a location). Can you check if the TimeOutException is called? The TimeOutException should be called when the timeLimit exceeds the given duration (if there is no location update from the system).

```
- `timeLimit`: the maximum amount of time allowed between location updates. When the time limit is passed a `TimeOutException` will be thrown and the stream will be cancelled. By default no limit is configured.
```

Kind regards,

**Comment by gogommd** [comment]
Dear @TimHoogstrate,

Thank you for your question, I use the android studio routes to simulate the movement, is it should use this to test? For my purpose, I want GPS tracking to be updated every 10 minutes.

Best regards,

**Comment by TimHoogstrate** [comment]
Dear @gogommd, 

then you should override the LocationSettings with the AndroidSettings and use the `intervalDuration` property. The timeLimit is more or less a a Timeout value. Also try to test this outside as much as possible for real word data. Emulated testing is not always sufficient when testing geolocation. 

Success,

**Comment by gogommd** [comment]
> Dear @gogommd, 
> 
> then you should override the LocationSettings with the AndroidSettings and use the `intervalDuration` property. The timeLimit is more or less a a Timeout value. Also try to test this outside as much as possible for real word data. Emulated testing is not always sufficient when testing geolocation. 
> 
> Success,

Ok, I will try it. Thank you very much. Now I have a question about geolocator background update feature. Is it only available in the iOS device? Is the android device not supported?

**Comment by TimHoogstrate** [comment]
Dear @gogommd,

Android should also works. In the README is stated that you should add background permission to the manifest. I'll close this issue for now. Feel free to reopen the issue or create a new issue when new information pops-up.

Kind regards,
