### ISSUE TITLE
[Question]: The AndroidSettings's intervalDuration property cannot work and when the app running in the background, the app will be terminated. How can I do?

### ISSUE THREAD

**Issue by gogommd** [Baseflow/flutter-geolocator#1457]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geolocator/blob/main/geolocator/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [X] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Your question

I want GPS tracking to be updated every 5 minutes, but it still updates whenever I set the `intervalDuration`  to 5 minutes and when I make the app in the background, the app will be terminated. Is `Geolocator.getPositionStream()` cannot work in the background? I have read the README. Is it some setting wrong?

```dart
late LocationSettings locationSettings;
StreamSubscription<Position>? updatePositionStream;
 Future<void> uploadLocation() async {
    if (defaultTargetPlatform == TargetPlatform.android) {
      print("isAndroid");
      locationSettings = AndroidSettings(
          accuracy: LocationAccuracy.high,
          distanceFilter: 150,
          forceLocationManager: true,
          intervalDuration: const Duration(minutes: 5),
          foregroundNotificationConfig: const ForegroundNotificationConfig(
              notificationTitle: "The location tracking is running",
              notificationText: "The location tracking is running",
              enableWakeLock: true));
    } else {
      locationSettings = LocationSettings(
        distanceFilter: 150,
        accuracy: LocationAccuracy.high,
      );
    }

    updatePositionStream =
        Geolocator.getPositionStream(locationSettings: locationSettings)
            .listen((Position? position) {
      if (position == null) {
        updatePositionStream?.cancel();
        print('Unknown');
      } else {
        var currentPosition = LatLng(position.latitude, position.longitude);
        getAddress(currentPosition).then((value) {
          final CurrentLocationModel location = CurrentLocationModel(
              locationId: Random().nextInt(9999).toString(),
              latitude: position.latitude,
              longitude: position.longitude,
              address: address,
              date: date,
              time: time);
          FirestoreRepository().uploadCurrentAddress(location);
          print(
              '${position.latitude.toString()}, ${position.longitude.toString()}');
        });
      }
    });
  }
```

### Version

11.0.0

**Comment by TimHoogstrate** [comment]
Dear @gogommd,

Can you confirm if you added the `ACCESS_BACKGROUND_LOCATION` permission on Android, and added the correct settings to the info.plist?

Kind regards,

**Comment by gogommd** [comment]
Dear @TimHoogstrate ,

Yes, I added the `ACCESS_BACKGROUND_LOCATION` in android.

Best Regards,

**Comment by TimHoogstrate** [comment]
Dear @gogommd,

If the app is terminated then you will not be able to get locations. In the background you should be able. Ar e you testing this outside on a real device?

Kind regards,

**Comment by gogommd** [comment]
Dear @TimHoogstrate,

Yes, I am testing on a real device. The update will be paused when I let the app in the background.

Best Regards,

**Comment by mvanbeusekom** [comment]
Hi @gogommd,

There might be a conflict between the `distanceFilter` and `intervalDuration` properties. For the supplied information the `distanceFilter` is set to 150 meters and the `intervalDuration` is set to 5 minutes. This means that both constraints have to be true for an location to be returned. 

Can you confirm that you have actually moved more then 150 meters during the time the application is in the background? Maybe you can set the intervals to a lower value (e.g. 5 meters and every 3 seconds) and see if that works correctly?
