### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by andreastambazzi** [Baseflow/flutter-geolocator#1467]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [X] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Steps to reproduce

referring to the previous raised issue 

https://github.com/Baseflow/flutter-geolocator/issues/1452

Now I receive the position only one time, but unfortunatly the stream function don't refresh te position after that.
Same code on android platform is working fine.

### Expected results

Expected result is to have a persisting coordinates streaming, even after a listen.onError event rised.

### Actual results

Now I receive the position only one time, but unfortunatly the stream function don't refresh te position after that.
Same code on android platform is working fine.

### Code sample

<details><summary>Code sample</summary>

```
locationAccurancy = LocationAccuracy.high;
distanceFilter    = 5;
intervalDuration  = Duration(seconds: 5);


locationSettings = AppleSettings(
   accuracy: locationAccurancy,        
   activityType: ActivityType.fitness,
   distanceFilter: distanceFilter,
   pauseLocationUpdatesAutomatically: false,
   timeLimit: intervalDuration,
   // Only set to true if our app will be started up in the background.
   showBackgroundLocationIndicator: false,        
 );

positionStream = Geolocator
     .getPositionStream(locationSettings: locationSettings)
     .listen( (Position? position) {

       try {
         if ( position == null ) {
           logger.info("getPositionStream: null");     
         }
         else {
           logger.info("getPositionStream: ${position.latitude.toString()}, ${position.longitude.toString()} ${position.altitude.toStringAsFixed(2)}");
         }
         
         if ( onPositionChange != null ) {
           onPositionChange(position);
         }
       }
       catch(error) {
         logger.error("getPositionStream listen $error");
       }

     },
     onError: (error) {
        logger.error("Geolocator.listen: $error");

        if ( defaultTargetPlatform == TargetPlatform.iOS ) {
          positionStream.pause();
        }

        if ( positionStream.isPaused ) {
          positionStream.resume();
        }
     }
     );
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

11.0.0

### Flutter Doctor output

<details><summary>Doctor output</summary>

```
andreastambazzi@Logos ~/work/Projects/flutter/yourate $ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.2, on macOS 13.6.5 22G621 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Community Edition (version 2023.2.5)
[✓] VS Code (version 1.87.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by mvanbeusekom** [comment]
Hi @andreastambazzi,

Thank you for taking the time raising this separate issue. First thing I want to make sure is that the `timeLimit` field for of the `AppleSettings` class does not act as an interval, but rather as a timeout that will kill the stream if no location is received within the specified duration. The same option also exists in the `AndroidSettings` class and will behave the same way, kill the stream if no location is received within the specified time duration.

Unlike Android, iOS doesn't support fetching locations at a set time interval, therefore the `AppleSettings` class doesn't have a `intervalDuration` property while the `AndroidSettings` class does. 

Does this explain the behavior you are experiencing?

**Comment by andreastambazzi** [comment]
Ok i'm testing it and it seem be working fine now ... 
Crossing the fingers ... 

I hope this is the last communication about this topic :-D  .

Thank you for support

**Comment by mvanbeusekom** [comment]
Thank you for confirming, I will go ahead and close the issue. As always feel free to leave a comment or create a new issue if you have any other questions.
