### ISSUE TITLE
[Bug]: Min API version should not be bumped to 34 until Sept 1

### ISSUE THREAD

**Issue by lukehutch** [Baseflow/flutter-geolocator#1469]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Steps to reproduce

Replicating my comment here:

https://github.com/Baseflow/flutter-geolocator/commit/c8bf9e22cac18c3280b90aa202f7faac4b6be8a6#r140051772

The min API version should not be bumped to API level 34 until Sept 1, 2024:

https://apilevels.com/

Otherwise you get an error like:

```console
Warning: The plugin geolocator_android requires Android SDK version 34.
For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
One or more plugins require a higher Android SDK version.
Fix this issue by adding the following to /home/luke/Work/click/click_flutter/android/app/build.gradle:
android {
  compileSdkVersion 34
  ...
}
```

The users of your library should not be compelled to upgrade their API version until it is required (unless you are prepared to increase the major semantic version of your package when you bump the minimum API version -- otherwise `pub upgrade`ing with the `^` notation on your package version code will cause the above error).

Google is now forcing API upgrades on Sept 1 every year. Until then, the minimum API version should remain at the current minimum level (33).

### Expected results

See above

### Actual results

See above

### Code sample

N/A

### Screenshots or video

N/A

### Version

4.5.4

### Flutter Doctor output

N/A

**Comment by mvanbeusekom** [comment]
Hi @lukehutch,

With the last version only the `compileSdk` has been updated. 

The `targetSdkVersion` and `minSdkVersion` of the plugin has not been changed. 

According to the documentation:
> targetSdk will need to be 34+ for new apps and app updates by August 31, 2024.

That is just to say that I am often confused, when to update which SDK version.

My question to you, did you actually experience an issue in an app? Did this update force you to also update your application to compile against SDK 34?

**Comment by lukehutch** [comment]
I get the nasty warning that I quoted above. Nothing breaks per se, but the warning makes me nervous.

**Comment by mvanbeusekom** [comment]
After doing some additional testing I have come to the following conclusions:

1. Flutter it self has set the `compileSdk` to version 34 (see https://github.com/flutter/flutter/blob/ba393198430278b6595976de84fe170f553cc728/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy#L44).
2. If the `compileSdkVersion` is set to 33 the build process shows the warning below. However this is only a warning and can safely be ignored.

```
Warning: The plugin geolocator_android requires Android SDK version 34.
For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
One or more plugins require a higher Android SDK version.
Fix this issue by adding the following to /home/luke/Work/click/click_flutter/android/app/build.gradle:
android {
  compileSdkVersion 34
  ...
}
```

Although I agree that the warning is not ideal, eventually we'd need to move on and I don't feel this is a breaking change warranting a major version bump.

**Comment by lukehutch** [comment]
> 1. Flutter it self has set the `compileSdk` to version 34 (see https://github.com/flutter/flutter/blob/ba393198430278b6595976de84fe170f553cc728/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy#L44).

Correct, there is the same problem there. I filed a bug about that too:

https://github.com/flutter/flutter/issues/145515

The fundamental problem is that the major semantic version of the Flutter packages was not increased, breaking the semantic version contract when the API changed. This is not OK.

> 2. If the `compileSdkVersion` is set to 33 the build process shows the warning below. However this is only a warning and can safely be ignored.

It's only a warning because you are not yet using API 34 features. But your users don't know that. Therefore, you cannot assume that your users know that they can safely ignore the error.

**Comment by mvanbeusekom** [comment]
Hi @lukehutch,

Thank you for sharing your concerns. I am fully behind Flutters policy "to support the latest versions of things in the latest version of our packages" (see [this](https://github.com/flutter/flutter/issues/145515#issuecomment-2012593619) comment by Stuart Morgan). 

Since the update to the latest compile SDK didn't have any impact on the internals of the permission_handler plugin I didn't feel it warranted a breaking change. And as an extension of that sent the message to developers that it is safe to ignore the warning.

I will keep this discussion in mind for the next update and make sure to evaluate the need for the update. For now however I will not revert the changes and keep it as is.
