### ISSUE TITLE
Privacy manifest file in gelocator_apple 2.3.7 and update status of geolocator plugin

### ISSUE THREAD

**Issue by Ultranmus** [Baseflow/flutter-geolocator#1470]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geolocator/blob/main/geolocator/README.md).

### Please select for which platform(s) you need help

- [ ] Android
- [X] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Your question

I noticed that the geolocator_apple 2.3.7 has a Privacy manifest file. However, the latest version of geolocator still uses  geolocator_apple version 2.3.0. I'm curious about when the geolocator plugin will be updated to include the latest version of geolocator_apple.

### Version

11.0.0

**Comment by mvanbeusekom** [comment]
Hi @Ultranmus,

The geolocator package uses the `^2.3.0` constraint for its dependency on the `geolocator_apple` package, this is short for writing `geolocator_apple: ">=2.3.0 <3.0.0"`. This means that Flutter will automatically download the latest version of the `geolocator_apple` dependency that fits within the contraints.

If you are in doubt which version of the `geolocator_apple` plugin your application is using, checkout the `pubspec.lock` file, it should list all packages and the actual version number being used by your application. If your application is still using an outdated version run `flutter pub upgrade` which will update all dependencies automatically.

More information about version contraints can be found in the [Dart documentation](https://dart.dev/tools/pub/versioning#constraint-solving).

**Comment by Ultranmus** [comment]
@mvanbeusekom Thank you for your response. I'll investigate further for exact version in my application.
