### ISSUE TITLE
[Question]: How to be smoother when i'm displaying my marker in driver mode?

### ISSUE THREAD

**Issue by Naografix** [Baseflow/flutter-geolocator#1492]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geolocator/blob/main/geolocator/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Your question

I'd like to know how to get a more natural version of my marker's movement.

Here are two examples:

Here, my version of flutter map + geolocator + marker
![slow](https://github.com/Baseflow/flutter-geolocator/assets/6979203/a5fd45e8-983d-4066-aec4-e2a4702ae260)

Here a smooth version of OsmAnd app with the same route:
![smooth](https://github.com/Baseflow/flutter-geolocator/assets/6979203/a246dd2f-2cc0-420b-abce-4045ce234c96)

How can I make moving the marker more natural? I'm using the Geolocator stream, but it refreshes every 3-5 seconds.
Thanks

### Version

last

**Comment by MohdSaadi** [comment]
any updates ?
can i manipulate the update interval of Geolocator ?
i have tried to implement a timer to run every second and in each iteration I'm requesting the current location , but every 3 to 5 seconds to get a new location update
