### ISSUE TITLE
[Question]: How to interpret the value of Accuracy?

### ISSUE THREAD

**Issue by Ellynnn** [Baseflow/flutter-geolocator#1503]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geolocator/blob/main/geolocator/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [X] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Your question

Can I know how do I interpret the value of Accuracy that is return in the Position together with latitude and longitude? I only see decimal numbers but is there a way I can understand the meaning of the value? 

### Version

11.0.0

**Comment by ccharp** [comment]
From the code `position.dart`:
```
  /// The estimated horizontal accuracy of the position in meters.
  ///
  /// The accuracy is not available on all devices. In these cases the value is
  /// 0.0.
  final double accuracy;
```

**Comment by TimHoogstrate** [comment]
This issue seems to be resolved. Furthermore, we pass most of the data from the iOS or Android APIs if available. You could always fallback to their documentation for additional context. 

Kind regards,
