### ISSUE TITLE
[Question]: Using IOS background location update but the gps keeps drifting

### ISSUE THREAD

**Issue by Ellynnn** [Baseflow/flutter-geolocator#1523]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geolocator/blob/main/geolocator/README.md).

### Please select for which platform(s) you need help

- [ ] Android
- [X] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Your question

I'm using Geolocator.getPositionStream with AppleSettings that allows background location update. However, I notice that the location data return from the stream tends to drift when the device is stationary. Is there a way that I can filter out the drifted location data?

### Version

11.0.0

**Comment by TimHoogstrate** [comment]
Dear @Ellynnn,

You could write an own implementation filtering out drifted location data. The plugin only passes data that is retrieved bij the OS. Playing around with the settings for your desired situation might improve the data quality.

Kind regards
