### ISSUE TITLE
[Question]: Ios background stop location updates

### ISSUE THREAD

**Issue by tarilo** [Baseflow/flutter-geolocator#1529]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geolocator/blob/main/geolocator/README.md).

### Please select for which platform(s) you need help

- [ ] Android
- [X] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Your question

Hello. We have integrated your location library but when the app is switched to the background on an iOS device, the interception of positioning changes stops within a few seconds. It works in the foreground but when the app is minimized it stops.

We have followed your example with the following code.

final LocationSettings locationSettings = LocationSettings(
  accuracy: LocationAccuracy.high,
  distanceFilter: 100,
);

StreamSubscription<Position> positionStream = Geolocator.getPositionStream(locationSettings: locationSettings).listen(
          (Position? position) {
        print(position == null ? 'Unknown' : 'Geolocator ${position.latitude.toString()}, ${position.longitude.toString()}');
      });

info.plist
<key>UIBackgroundModes</key>
	<array>
		<string>fetch</string>
		<string>location</string>
		<string>processing</string>
		<string>remote-notification</string>
	</array>

How can we use the library so that, when the application is in the background, it does not constantly send position changes to a server?

Thanks

### Version

12.0.0

**Comment by mayank-vinove** [comment]
same issue.

when app killed in IOS , unable to listen location updates.

**Comment by tarilo** [comment]
Hi @mayank-vinove 

With the app. in background you can listen location changes after 5 secs?

**Comment by mayank-vinove** [comment]
As per my understanding minimum interval is 15 min but iam unable to get a callback after every ~15 min.

**Comment by tarilo** [comment]
But there are a multitude of apps with background tracking like Google Maps, Waze, Uber, etc. I think there is a way to be able to track location in the background, for example for interaction with beacons.

**Comment by tarilo** [comment]
No coments?

**Comment by TimHoogstrate** [comment]
Dear @tarilo,

Can you check if it works as expected in the supplied example app? Also check if you requested the correct permissions and added the correct permission to the pod file. Furthermore, check if you used the correct plist entries. 

Kind regards,

**Comment by aanelson** [comment]
@tarilo  This plugin does not have any reference to  https://developer.apple.com/documentation/corelocation/cllocationmanager/startmonitoringsignificantlocationchanges()
which is probably what you are looking for.  This is the api that allows terminated apps to start and receive notification changes when the location has changed.
