### ISSUE TITLE
[Question]: I just install the package but still throw the error showing in the image.

### ISSUE THREAD

**Issue by Arshad-ullah** [Baseflow/flutter-geolocator#1533]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geolocator/blob/main/geolocator/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Your question

![Screenshot (55)](https://github.com/Baseflow/flutter-geolocator/assets/71887229/5f900dec-c39b-48ee-b331-5f638e76a55c)

### Version

4.5.5

**Comment by mvanbeusekom** [comment]
Please carefully read the documentation. 

According to the stack trace you are requesting a location stream using the `getPositionStream` method. Before retrieving location update the application is required to request permission. The geolocator plugin offers `checkPermission` and `requestPermission` methods to accomplish this.

Also note that you need to update the `AndroidManifest.xml` file and declare the necessary permissions the app requires. This is explained in detail in the "Android" section of the README.md file.
