### ISSUE TITLE
[Question]:  [!] Your project requires a newer version of the Kotlin Gradle plugin.                     │ │ Find the latest version on https://kotlinlang.org/docs/releases.html#release-details, then │ │ update D:\my_happy\android\build.gradle:                                                   │ │ ext.kotlin_version = '<latest-version>'                                                    

### ISSUE THREAD

**Issue by ahsi1999** [Baseflow/flutter-geolocator#1535]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geolocator/blob/main/geolocator/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Your question

 [!] Your project requires a newer version of the Kotlin Gradle plugin.                     │
│ Find the latest version on https://kotlinlang.org/docs/releases.html#release-details, then │
│ update D:\my_happy\android\build.gradle:                                                   │
│ ext.kotlin_version = '<latest-version>'                                                    This issue is comming again and again in android but on ios its working fine

### Version

latest   geolocator: ^12.0.0

**Comment by agnoam** [comment]
I have this problem too

**Comment by agnoam** [comment]
I managed to solve this problem by modifying the version number in the `android/settings.gradle` file
from: `id "org.jetbrains.kotlin.android" version "1.7.3" apply false` 
to: `id "org.jetbrains.kotlin.android" version "1.9.0" apply false`

**Comment by ahsi1999** [comment]
Thankyou! It helped a lot.
