### ISSUE TITLE
[Question]: iOS background doesn't work （kCLErrorDomain error 1）

### ISSUE THREAD

**Issue by jupeng123** [Baseflow/flutter-geolocator#1539]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geolocator/blob/main/geolocator/README.md).

### Please select for which platform(s) you need help

- [ ] Android
- [X] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Your question

final locationSettings = AppleSettings(
      activityType: ActivityType.fitness,
      showBackgroundLocationIndicator: true,
      allowBackgroundLocationUpdates: true,
    );

    final sub =
        LocationUtils.getPositionStream(locationSettings: locationSettings).listen((event) {}, onError: (error) {
      print('=======$error');
    });

background is enable

info 
NSLocationAlwaysAndWhenInUseUsageDescription
NSLocationAlwaysUsageDescription
NSLocationWhenInUseUsageDescription

Flutter 3.19.5 
Tools • Dart 3.3.3 • DevTools 2.31.1

### Version

12

**Comment by TimHoogstrate** [comment]
Dear @jupeng123,

What type of permission have you requested? Could it be related to this issue? And can you check if this works in the example app? 

Kind regards,

**Comment by jupeng123** [comment]
> Dear @jupeng123,
> 
> What type of permission have you requested? Could it be related to this issue? And can you check if this works in the example app?
> 
> Kind regards,

static Future<bool> handleLocationPermission({bool checkService = true}) async {
    if (checkService) {
      final serviceFlag = await serviceEnabled();
      if (!serviceFlag) {
        return false;
      }
    }

    LocationPermission permission;
    permission = await Geolocator.checkPermission();
    if (permission == LocationPermission.denied) {
      permission = await Geolocator.requestPermission();
      if (permission == LocationPermission.denied) {
        return false;
      }
    }
    if (permission == LocationPermission.deniedForever) {
      return false;
    }

    return true;
  }

**Comment by jupeng123** [comment]
> Dear @jupeng123,
> 
> I asked another question. Are you able to reproduce it with the example app?
> 
> Kind regards,
![20240805-174458](https://github.com/user-attachments/assets/0f65a66c-f577-44a1-bf17-1b4cae78828a)

**Comment by jupeng123** [comment]
Location permission has been granted

**Comment by TimHoogstrate** [comment]
kCLErrorDomain Code 1 occurs when the user has denied your app access to location services. Please check if you have the correct permissions for background locations on iOS. Also try if it is happening with the example app. Also are you testing this on a real iOS device? Because your screenshot does not look like default iOS.

Kind regards,

**Comment by jupeng123** [comment]
> kCLErrorDomain Code 1 occurs when the user has denied your app access to location services. Please check if you have the correct permissions for background locations on iOS. Also try if it is happening with the example app. Also are you testing this on a real iOS device? Because your screenshot does not look like default iOS.
> 
> Kind regards,

Location permissions are all enabled

**Comment by jupeng123** [comment]
> kCLErrorDomain Code 1 occurs when the user has denied your app access to location services. Please check if you have the correct permissions for background locations on iOS. Also try if it is happening with the example app. Also are you testing this on a real iOS device? Because your screenshot does not look like default iOS.

The device is an iPhone, and location services and permissions are enabled

**Comment by TimHoogstrate** [comment]
Dear @jupeng123,

Did you try to run this in the example app?

Kind regards,
