### ISSUE TITLE
[Feature Request]: Add direct location service request like location flutter plugin method "requestService()"

### ISSUE THREAD

**Issue by ilyasarafathemvigo** [Baseflow/flutter-geolocator#1544]
### Is there already an issue requesting this feature?

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).

### Please select affected platform(s)

- [X] Android
- [X] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Use case

Currently in this plugin provide openLocationSettings() function to enable location service instead of that direct request permission is good for end user. [Location](https://pub.dev/packages/location#:~:text=Future%3Cbool%3E-,requestService,-()%0AShow%20an) Plugin is providing this feature. 

### Proposal

 Direct location service android prompt
[
![Screenshot_1721929800](https://github.com/user-attachments/assets/f59866a3-3b5f-45ed-8a74-1c7a4e7ae763)
](url) 

Direct location service iOS prompt
![screenshot-1721930257590](https://github.com/user-attachments/assets/fd080464-bd3c-4fc4-986d-3b71c8e2f566)

**Comment by ilyasarafathemvigo** [comment]
@TimHoogstrate  
When the user allowed location permission and disabled the service (GPS). 
then there is no direct option available to  turn on the service(GPS).

**Comment by TimHoogstrate** [comment]
Oke, now I understand. It is not default behaviour of iOS or Android to show this alert/dialog. Therefore it has not yet been implemented. I have to discuss this in the team.

Kind regards,

**Comment by sed1ka** [comment]
Why this is closed?
I am one of those who need this feature.

To request to activate the gps we can use [LocationSettingsRequest](https://developers.google.com/android/reference/com/google/android/gms/location/LocationSettingsRequest.Builder)

**Comment by ilyasarafathemvigo** [comment]
Why this closed , Is this released?
