### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by mohamadkenway** [Baseflow/flutter-geolocator#1548]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geolocator/blob/main/geolocator/README.md).

### Please select for which platform(s) you need help

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Your question

Hello
this code working fine in foreground when app not closed
StreamSubscription<Position> positionStream = Geolocator.getPositionStream(locationSettings: locationSettings).listen(
            (Position? position) async{
          print(position);
          if(position != null) {
            print(position.toString());
          }
        }
    );
    
 after closing app, on location changing this function not working and console output is this :
 
 
D/AutofillManager(19510): onActivityFinishing(): calling cancelLocked()
D/FlutterGeolocator(19510): Detaching Geolocator from activity
D/FlutterGeolocator(19510): Flutter engine disconnected. Connected engine count 1
D/FlutterGeolocator(19510): Disposing Geolocator services
E/FlutterGeolocator(19510): Geolocator position updates stopped
E/FlutterGeolocator(19510): There is still another flutter engine connected, not stopping location service
W/WindowOnBackDispatcher(19510): sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@b81b81a
W/FlutterJNI(19510): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: flutter.baseflow.com/geolocator_updates_android. Response ID: 207

### Version

12.0.0

**Comment by TimHoogstrate** [comment]
Dear @mohamadkenway,

Can you add the contents of `flutter doctor -v` and some basic information about the Android version you are currently working with?  Furthermore, have you checked if it works in the Example app?

Kind regards,

**Comment by mohamadkenway** [comment]
Hello again
I detected my problem
I was used trust_fall package in my project without any calling function and it has much load on application and geolocator package
after removing that, everything gone to heaven

**Comment by TimHoogstrate** [comment]
Dear @mohamadkenway,

good to hear, I'll close this issue then.
