### ISSUE TITLE
[Bug]:  Build failed: html_geolocation_manager.dart:2:8: Error: Dart library 'dart:js_interop' is not available on this platform.

### ISSUE THREAD

**Issue by joachimbulow** [Baseflow/flutter-geolocator#1550]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [X] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Steps to reproduce

1. Idk install i guess. We just upgraded from 10.1.0
2. You cannot build on iOS due to:

```
Showing Recent Errors Only
../../../../.pub-cache/hosted/pub.dev/geolocator_web-4.0.0/lib/src/html_geolocation_manager.dart:2:8: Error: Dart library 'dart:js_interop' is not available on this platform.
```

I Tried overriding the dependency like:

```
dependency_overrides:
  geolocator_web: null
```

To no avail

### Expected results

Library should not try to compile js-related files in an iOS build

### Actual results

You get build errors 

### Code sample

Unfortunately i cannot provide this, this is just a headsup something may be wrong. 
Most likely an issue on my end.

### Screenshots or video

<details>
<img width="1033" alt="image" src="https://github.com/user-attachments/assets/19feb31c-df3e-4a00-8de6-c9a2a2a0ec6f">

</details>

### Version

13.0.0

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.3 23D56 darwin-arm64, locale en-DK)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.1)
[✓] VS Code (version 1.92.0)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for Joachim - iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Dev iphone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!
```

</details>

**Comment by mvanbeusekom** [comment]
Hi @joachimbulow, 

Apologies for the inconvenience, by accident a reference to the `dart:js_interop` was referenced through to the non-web platforms causing the error. 

I have just released version 13.0.1 resolving these issues.
