### ISSUE TITLE
Problem with Retrieving Location in Background During --release Compilation[Question]: 

### ISSUE THREAD

**Issue by kamildul** [Baseflow/flutter-geolocator#1551]
Hello,

I am facing an issue with retrieving the location in the background. I am calling the location retrieval in the service using:

`Position position = await Geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.high);`

Everything works perfectly in --debug mode, but when I compile the application in --release mode, I do not receive the location.

Please help.

### Version

12.0.0

**Comment by TimHoogstrate** [comment]
Dear @kamildul,

Thanks for your issue. Please provide the output of `flutter doctor -v` and some example code/minimal steps to reproduce. I don't even know what platform you are testing this on :).

Kind regards,
