### ISSUE TITLE
[Bug]: argument type 'num' can't be assigned to the parameter type 'double'

### ISSUE THREAD

**Issue by blaneyneil** [Baseflow/flutter-geolocator#1552]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [X] Web
- [ ] Windows

### Steps to reproduce

Using geolocator: ^13.0.1, and with that, geolocator_web 4.1.1, the web will not build because of the following type conflicts:

../../../.pub-cache/hosted/pub.dev/geolocator_web-4.1.1/lib/src/utils.dart:12:22: Error: The argument type 'num' can't be assigned to the parameter type 'double'.
    latitude: coords.latitude,
                     ^
../../../.pub-cache/hosted/pub.dev/geolocator_web-4.1.1/lib/src/utils.dart:13:23: Error: The argument type 'num' can't be assigned to the parameter type 'double'.
    longitude: coords.longitude,
                      ^
../../../.pub-cache/hosted/pub.dev/geolocator_web-4.1.1/lib/src/utils.dart:15:31: Error: The argument type 'num' can't be assigned to the parameter type 'double'.
    altitude: coords.altitude ?? 0.0,
                              ^
../../../.pub-cache/hosted/pub.dev/geolocator_web-4.1.1/lib/src/utils.dart:16:47: Error: The argument type 'num' can't be assigned to the parameter type 'double'.
    altitudeAccuracy: coords.altitudeAccuracy ?? 0.0,
                                              ^
../../../.pub-cache/hosted/pub.dev/geolocator_web-4.1.1/lib/src/utils.dart:18:29: Error: The argument type 'num' can't be assigned to the parameter type 'double'.
    heading: coords.heading ?? 0.0,
                            ^
../../../.pub-cache/hosted/pub.dev/geolocator_web-4.1.1/lib/src/utils.dart:21:25: Error: The argument type 'num' can't be assigned to the parameter type 'double'.
    speed: coords.speed ?? 0.0,

### Expected results

'num' should be typed to match 'double'

### Actual results

The web will not build

### Code sample

-

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

geolocator_web 4.1.1

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.23.0-13.0.pre.43, on macOS 14.5 23F79 darwin-arm64, locale en-US)
    • Flutter version 3.23.0-13.0.pre.43 on channel master at /Users/neil/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a1423723ff (10 weeks ago), 2024-05-30 16:37:47 -0700
    • Engine revision bf2e32dfd5
    • Dart version 3.5.0 (build 3.5.0-203.0.dev)
    • DevTools version 2.36.0-dev.10

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/neil/Library/Android/sdk/
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 80.0.2
    • Dart plugin version 241.18808

[✓] Connected device (4 available)
    • iPhone 15 Pro Max (mobile)      • 3899397D-1643-49D5-BDC7-BCE1B8A7DE4F • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 127.0.6533.89

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by blaneyneil** [comment]
Apologies, it was indeed because web was pinned to 0.5.1 (because all the community plus packages depend on that).  Closing this.

**Comment by CryptoSoo** [comment]
Hey guys, got the same issue both on my Linux and Windows machine and changing the web to 1.0.0 didnt solve the problem. and i think it made another problem 
![image](https://github.com/user-attachments/assets/94435b5d-4d25-49b7-9021-49615c11ef93)

**Comment by lcundiff** [comment]
Still getting this error with web 1.0.0 and version 4.1.1. Any other potential fixes?

**Comment by mvanbeusekom** [comment]
Hi @lcundiff, 

Please verify the version of the `web` package used by the application in the `pubspec.lock` file and make sure it is version 1.0.0 or higher.

If the problem persists, remove the `web` package from the pub cache (see this [article](https://dart.dev/tools/pub/environment-variables#:~:text=By%20default%2C%20this%20directory%20is,variable%20to%20specify%20another%20location.) for the location), run `flutter clean` and `flutter pub get`.

As extra reference, this is the source code of the `web` package showing the properties are returning `double` types: https://github.com/dart-lang/web/blob/e89fe49d8a86845e49686b4578c56b67bdd7ba49/lib/src/dom/geolocation.dart#L115

**Comment by lcundiff** [comment]
@mvanbeusekom Thank you for your help! I got it working now :)
