### ISSUE TITLE
[Feature Request]: Huawei location

### ISSUE THREAD

**Issue by giorgio79** [Baseflow/flutter-geolocator#1560]
### Is there already an issue requesting this feature?

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Use case

single package for geolocation

### Proposal

merge with https://pub.dev/packages/huawei_location

**Comment by TimHoogstrate** [comment]
Dear @giorgio79,

Thank you for reaching out! Could you please provide more details on the topic? Specifically, what challenges are you currently facing, and what outcomes are you hoping to achieve? This will help us better understand your feature and assist you better.

Kind regards,

**Comment by giorgio79** [comment]
Hey Tim, much appreciated. I am thinking of releasing my Flutter app in the Huawei app store, but there you cannot use the Google services, but Huawei's own eg https://developer.huawei.com/consumer/en/hms/huawei-locationkit/

So just like this package supports Android and iOS already, it would be nice to support Android Huawei, not just Android Google.

**Comment by TimHoogstrate** [comment]
Hi @giorgio79,

Sounds interesting but unfortunately we are currently not able to include a Huawei platform to the package because we lack the required knowledge to build and maintain such a platform.

Kind regards
