### ISSUE TITLE
[Feature Request]: ITMS-91061: Missing privacy manifest

### ISSUE THREAD

**Issue by xljhd** [Baseflow/flutter-geolocator#1572]
### Is there already an issue requesting this feature?

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).

### Please select affected platform(s)

- [ ] Android
- [X] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Use case

Apple's latest official review requirements mandate that SDKs must include a privacy manifest, otherwise the app will not be allowed on the App Store. Therefore, I kindly request that the author updates the SDK accordingly. My current version is geolocator: 8.0.1.

### Proposal

ITMS-91061: Missing privacy manifest - Your app includes “Frameworks/geolocator_apple.framework/geolocator_apple”, which includes geolocator_apple, an SDK that was identified in the documentation as a privacy-impacting third-party SDK. Starting November 12, 2024, if a new app includes a privacy-impacting SDK, or an app update adds a new privacy-impacting SDK, the SDK must include a privacy manifest file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a privacy manifest. For more details about this policy, including a list of SDKs that are required to include signatures and manifests, visit: https://developer.apple.com/support/third-party-SDK-requirements.

**Comment by mvanbeusekom** [comment]
Hi @xljhd,

The privacy manifest has been added to the geolocator_apple package in version 2.3.7 and is available since March 18th of 2024. 

Version 8.0.1 of the geolocator is heavily outdated, to resolve this issue make sure to update to version 13.0.0 of the geolocator plugin.

**Comment by xljhd** [comment]
thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Maurits van ***@***.***&gt;; 
发送时间: 2024年9月13日(星期五) 下午3:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Baseflow/flutter-geolocator] [Feature Request]: ITMS-91061: Missing privacy manifest (Issue #1572)














 
***@***.***，
 
隐私清单已添加到 2.3.7 版 geolocator_apple 包中，自 2024 年 3 月 18 日起可用。
 
地理定位器 8.0.1 版本已经严重过时，要解决此问题，请确保将地理定位器插件更新至 13.0.0 版本。
 
—
直接回复此电子邮件、在 GitHub 上查看或取消订阅。
您收到此邮件是因为有人提及了您。消息ID ：< ***@***.*** &gt;
