### ISSUE TITLE
[Bug]: [beboro] flutter pub get --no-example Resolving dependencies... Because every version of get from git depends on web >=0.4.0 <0.6.0 and geolocator_web >=4.0.1 depends on web ^1.0.0, get from git is incompatible with geolocator_web >=4.0.1. And because geolocator >=13.0.1 depends on geolocator_web ^4.1.1, get from git is incompatible with geolocator >=13.0.1. So, because beboro depends on both geolocator ^13.0.1 and get from git, version solving failed.

### ISSUE THREAD

**Issue by fisforfaheem** [Baseflow/flutter-geolocator#1592]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [X] iOS
- [ ] Linux
- [ ] macOS
- [X] Web
- [ ] Windows

### Steps to reproduce

[beboro] flutter pub get --no-example
Resolving dependencies...
Because every version of get from git depends on web >=0.4.0 <0.6.0 and geolocator_web >=4.0.1 depends on web ^1.0.0, get from git is incompatible with geolocator_web >=4.0.1.
And because geolocator >=13.0.1 depends on geolocator_web ^4.1.1, get from git is incompatible with geolocator >=13.0.1.
So, because beboro depends on both geolocator ^13.0.1 and get from git, version solving failed.

### Expected results

[beboro] flutter pub get --no-example
Resolving dependencies...
Because every version of get from git depends on web >=0.4.0 <0.6.0 and geolocator_web >=4.0.1 depends on web ^1.0.0, get from git is incompatible with geolocator_web >=4.0.1.
And because geolocator >=13.0.1 depends on geolocator_web ^4.1.1, get from git is incompatible with geolocator >=13.0.1.
So, because beboro depends on both geolocator ^13.0.1 and get from git, version solving failed.

### Actual results

[beboro] flutter pub get --no-example
Resolving dependencies...
Because every version of get from git depends on web >=0.4.0 <0.6.0 and geolocator_web >=4.0.1 depends on web ^1.0.0, get from git is incompatible with geolocator_web >=4.0.1.
And because geolocator >=13.0.1 depends on geolocator_web ^4.1.1, get from git is incompatible with geolocator >=13.0.1.
So, because beboro depends on both geolocator ^13.0.1 and get from git, version solving failed.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

latest

### Flutter Doctor output

[beboro] flutter pub get --no-example
Resolving dependencies...
Because every version of get from git depends on web >=0.4.0 <0.6.0 and geolocator_web >=4.0.1 depends on web ^1.0.0, get from git is incompatible with geolocator_web >=4.0.1.
And because geolocator >=13.0.1 depends on geolocator_web ^4.1.1, get from git is incompatible with geolocator >=13.0.1.
So, because beboro depends on both geolocator ^13.0.1 and get from git, version solving failed.

**Comment by mvanbeusekom** [comment]
The problem here is with the `get` plugin which depends on an outdated version of the `web` package.

Unfortunately there is not much I can do to help, maybe ask the maintainers of `get` to update their plugin dependencies. Version 1.0.0 of `web` is the current standard and we will not deviate from it.

**Comment by fisforfaheem** [comment]
get people say this is a community project etc so they will upgrade only when they need to :(
