### ISSUE TITLE
Taking so long and on some API not returning location on only Android

### ISSUE THREAD

**Issue by ghost** [Baseflow/flutter-geolocator#160]
HI, on iOS there is no problems.
But on Android it takes over 15 seconds to get current location.
Also, API28 not even returning location info.
Any workaround?
Thank you

**Comment by VladimirCourse** [comment]
The same problem, it takes about 30-40 seconds on API 27. In older device  (Android ~5) it works much faster.

**Comment by ibrierley** [comment]
Out of interest if it's slow, and you force it not to use the fusedprovider, is it any better ? Eg

Geolocator geolocator = Geolocator()..forceAndroidLocationManager = true;

**Comment by VladimirCourse** [comment]
> Out of interest if it's slow, and you force it not to use the fusedprovider, is it any better ? Eg
> 
> Geolocator geolocator = Geolocator()..forceAndroidLocationManager = true;

With this it's not working at all, just infinite awaiting of location.

**Comment by kika** [comment]
`.forceAndroidLocationManager = true;` fixed it for me.

**Comment by mulderpf** [comment]
I have had one user who have reported an issue with it never getting a GPS fix.  I've given them the ability to also use forceAndroidLocationManager, but this doesn't resolve the issue.  They are using a Samsung Galaxy Core Prime which even the user admitted was an old phone.  Any ways around this?

**Comment by mvanbeusekom** [comment]
Most issues with locations not being fetched are solved in version 6.0.0. However certain phones did not implement the Android specifications correctly and will keep on returning location information slow. An excellent troubleshooting guide can be found here: #507
