### ISSUE TITLE
[Question]: GPS Coordinates Fluctuation 

### ISSUE THREAD

**Issue by Akkiboy97** [Baseflow/flutter-geolocator#1601]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geolocator/blob/main/geolocator/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Your question

We developing attendance application when employee in office area less than 10 meter of office location employee will able to mark attendance and then application start monitoring his location if he goes more than 10 meter of location show warning popup but the problem is if user not moving then also coordinates change but what we want if user not moving then lat long will not change 

right not happen user not moving then also show 100 meters 10000 meter distance 

void monitorLocationChanges(
      UserModel? userData,
      StreamSubscription<Position>? _positionStreamSubscription,
      bool isOutOfRangeDialogShown,
      Function(bool isOutOffRange, double distance) isOutOffRange) async {
    if (_positionStreamSubscription != null) {
      if (kDebugMode) {
        print('Location monitoring is already running.');
      }
      return;
    }
    _positionStreamSubscription = Geolocator.getPositionStream(
      locationSettings: LocationSettings(
        accuracy: LocationAccuracy.high,
        distanceFilter: int.parse("${userData?.bfrrdus}"),
        timeLimit: const Duration(milliseconds: 10000),
      ),
    ).listen(
      (Position position) {
        if (!isOutOfRangeDialogShown) {
          double distanceFromMarked = Geolocator.distanceBetween(
            double.parse(userData!.latitude!),
            double.parse(userData!.longitude!),
            // lat,
            // long,
            position.latitude,
            position.longitude,
          );

          if (distanceFromMarked >
              (double.parse(userData.bfrrdus ?? "12.0"))) {
            isOutOffRange(true, distanceFromMarked);
          }
        }
      },
    );
  }

### Version

9.0.0

**Comment by TimHoogstrate** [comment]
Dear @Akkiboy97,

It is sometimes difficult to determine an accurate GPS location in an office (concrete) area. The OS often uses WIFI or Celular connections to determine the location of, however, this might not be as accurate as you need. My suggestion is to test out different scenarios while playing with the locationSettings and try to set the `forceLocationManager` in the `LocationSettings()` to `true/false`. But be aware that 10 meters is a very close range...

Kind regards,
