### ISSUE TITLE
Unable to find an address for the supplied coordinates.

### ISSUE THREAD

**Issue by chadidi** [Baseflow/flutter-geolocator#176]
My app stopped at this exception:
`Unable to find an address for the supplied coordinates.`

this is my function
```
Future<void> getAddress(lat, long) async {
    List<Placemark> _placemarks =
        await Geolocator().placemarkFromCoordinates(lat, long);

    if (_placemarks != null && _placemarks.isNotEmpty) {
      final Placemark pos = _placemarks[0];
      setState(() {
        placemark = pos.thoroughfare + ', ' + pos.locality;
      });
    }
  }
```
### Configuration

**Version:** 2.1.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by alexisgc** [comment]
I get the same error in "3.0.1"

**Comment by mvanbeusekom** [comment]
Since version 6.0.0 the geocoding features are no longer part of the geolocator plugin and moved to their own plugin which can be found [here](https://github.com/baseflow/flutter-geocoding).
