### ISSUE TITLE
Speed Units not correct? 

### ISSUE THREAD

**Issue by nkalscheuer** [Baseflow/flutter-geolocator#180]
## 💬 Questions and Help
I'm testing the speed value in an app I am working on and I noticed that when I specify say, 20.0 knots in my Android simulator, the speed value is from my position object is also 20.0. However looking at the comments in the Position class, it seems like the speed should be in meters/second. Is this just a bad comment, or am i maybe doing something wrong?

**Comment by StijnWoerkom** [comment]
Could you provide me with some code from the class and some more details from the problem your facing?

**Comment by nkalscheuer** [comment]
In the position model class:

`/// The speed at which the devices is traveling in meters per second over ground.
  ///
  /// The speed is not available on all devices. In these cases the value is 0.0.
  final double speed;`

**Comment by StijnWoerkom** [comment]
Could you also provide some code from the app you are working on? What do you expect from the code?
