### ISSUE TITLE
 geolocator.getCurrentPosition sometimes take a long time to return position

### ISSUE THREAD

**Issue by aboda1986** [Baseflow/flutter-geolocator#227]
## 🐛 Bug Report

i try to get location using  geolocator.getCurrentPosition in Android 8 - 7 -6 -5, it will take a very long time in real devices, and sometimes not reyurn position and still wait  geolocator.getCurrentPosition forever.

in Android 9 working fine.

can you please check this issue?

**Version:** 3.0.1

**Platform:** 
- [ ] :iphone: iOS
- [X ] :robot: Android

**Comment by sspogra** [comment]
Its also happens with me.

**Comment by billymahmood** [comment]
I am having same issue on Google Pixel 3A

**Comment by lthung1504** [comment]
me too.

**Comment by alexworeku** [comment]
Am having the same issue,anyone knows the solution

**Comment by mvanbeusekom** [comment]
This issue is solved in version 6.0.0
