### ISSUE TITLE
Support flutter-desktop-embedding

### ISSUE THREAD

**Issue by allessandrojs** [Baseflow/flutter-geolocator#241]
Any chance of geolocator support for flutter-desktop-embedding, 
https://github.com/google/flutter-desktop-embedding

**Comment by stuartmorgan** [comment]
Two relevant notes:
- All plugin APIs for desktop have moved into Flutter itself, so this would no longer involve the flutter-desktop-embedding repository, just Flutter.
- The macOS plugin API and tooling have matured to the point where if you added a macOS implementation it would likely not require significant changes (unlike Windows and Linux, which are still in very early stages).

**Comment by mvanbeusekom** [comment]
The geolocator supports macOS starting from version 7.5.0 and Windows from version 8.1.0. And thanks to @pablojimpas and @jpnurmi Linux support is being worked on (see #1008). 

This means this issue has become redundant and as such I will close this issue and track support for Linux in #1008. Thanks to everybody pitching in, it is really much appreciated.
