### ISSUE TITLE
Timeout to stop looking

### ISSUE THREAD

**Issue by mulderpf** [Baseflow/flutter-geolocator#242]
## 🏗 Enhancement Proposal

Currently, the request to get a GPS location is "go off and get me the GPS location to this accuracy" and it takes as long as it takes.  On devices with battery saver mode on, it appears that infinity is also a possibility.

In a previous implementation of my app, I could request a GPS location to a specified accuracy with a time limit included.  So it would go off and find the GPS location and return a value as soon as the desired accuracy was met, but if not, it would continue trying to gain more accuracy until the timeout and then simply return whatever it got to at that point.  I would like to see this behaviour again as it worked well for many years.

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [X ] :robot: Android

**Comment by marcglasberg** [comment]
Do you mean you ask for some location and then you may get no answer at all, not even an error?

**Comment by mulderpf** [comment]
If the signal is bad and a fix cannot be obtained at the desired level (e.g. the device only has to rely on wifi or cell phone triangulation), then it will never resolve and just keep trying and trying.  The referenced PR seems to be helping towards this sort of issue.

**Comment by edihasaj** [comment]
+1
