### ISSUE TITLE
localeIdentifier for arabic not working its translate only some and rest in english.

### ISSUE THREAD

**Issue by kw2019ltd** [Baseflow/flutter-geolocator#262]
localeIdentifier for arabic not working its translate only some and rest in english, while for Hebrew its working fine 

List<Placemark> list = await Geolocator().placemarkFromCoordinates(
        _currentCameraPosition.target.latitude,
        _currentCameraPosition.target.longitude,
        localeIdentifier: "ar_SA");

    print(list.first.country);
    print(list.first.name);
    print(list.first.administrativeArea);
    print(list.first.locality);

-----------------

result:

only country got translated to arabic rest still in english

I/flutter ( 4668): إسرائيل
I/flutter ( 4668): Dar El Sanam Street
I/flutter ( 4668): Haifa District
I/flutter ( 4668): Jatt, Israel

**Comment by mvanbeusekom** [comment]
Hi @kw2019ltd, on which platform do you experience this (Android, iOS or both)?

**Comment by kw2019ltd** [comment]
Hi on android device both emulator and real

**Comment by mvanbeusekom** [comment]
Since version 6.0.0 the geocoding features are no longer part of the geolocator plugin and moved to their own plugin which can be found [here](https://github.com/baseflow/flutter-geocoding).
