### ISSUE TITLE
Listening again on getPositionStream does not immediately trigger retrieval of the location

### ISSUE THREAD

**Issue by agyimr** [Baseflow/flutter-geolocator#279]
## 🐛 Bug Report

After cancelling a subscription on getPositionStream, when I start a listener again, it does not immediately tries to get the location, but waits according to how it is specified on the LocationOptions when the stream was created. 

### Expected behavior

Every time a new listener is attached to the same stream, it should start with immediately getting the location. Just like it does when the first listener subscribes. 

Note: I experience this behaviour on other packages like _cloud_firestore_

### Reproduction steps

1. Listen to the getPositionStream with timeInterval: 60000. Save the stream as a broadcast stream and the subscription into a variable. (getPositionStream(locationOptions).asBroadcastStream())
    a) Observe that as soon as the listener is set up, the location is retrieved. 
2. Cancel the subscription with subscription.cancel();
3. Start listening to the saved stream again. 
    b) Observe that the next update comes when the one minute interval is reached. Not immediately at subscription. 

### Configuration

**Version:** 5.0.0

**Platform:** 
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
I think this is by design, have a look at this article in the Dart repo: https://github.com/dart-lang/sdk/issues/18588
