### ISSUE TITLE
not working when location service is turned off

### ISSUE THREAD

**Issue by Xgamefactory** [Baseflow/flutter-geolocator#315]
unlike other flutter plugins this one not working when location sevice is turned off.

**Comment by aronnelson** [comment]
Doesn't it need location services to work? How would it get the location?

**Comment by mvanbeusekom** [comment]
@Xgamefactory can you clarify what you would expect? @aronnelson is correct that this plugin needs the location services to be running to work correctly, so what do you expect to happen when the services are not running?

**Comment by mikron123** [comment]
1. I'm calling Position position = await Geolocator().getCurrentPosition(desiredAccuracy: LocationAccuracy.high);

At some of the times, when the GPS was off, after I turned it on, it got the location.
Other time.. it didn't do nothing, until I opened google maps. (tested a few times) What is this "cold" condition?

2. When the GPS is off there should be a native dialog to turn it on, and all the user has to do it to press yes (check out what happens in google maps when the gps is off) instead of the user having to slide the bar down, and turn it on by himself.

Thanks

**Comment by jaykobi** [comment]
I have the same problem. When I switch off GPS 
`await Geolocator().getCurrentPosition(desiredAccuracy: LocationAccuracy.low/high);`
just never returns. 

Should it not be possible to  acces the device's location via `locationManager.NETWORK_PROVIDER`?

Also, even though the await never finishes, 
`geolocator.checkGeolocationPermissionStatus();`
return status granted.

**Comment by jaykobi** [comment]
~~Should it not be possible to acces the device's location via locationManager.NETWORK_PROVIDER?~~
Obvious user error: No SIM-Card => no network....

**Comment by Xgamefactory** [comment]
plugin should have a method to trigger location service turn off. it is possible to programmatically on native platforms, at least on android.

**Comment by carlos-labrador** [comment]
I got same problem , I guess the plugin at least should return GeolocationStatus disabled but , it returns  GeolocationStatus granted. 
should you need a better explanation let me know. sorry about it.

**Comment by Hunter3173** [comment]
> I got same problem , I guess the plugin at least should return GeolocationStatus disabled but , it returns GeolocationStatus granted.
> should you need a better explanation let me know. sorry about it.

I got the same issue

**Comment by mvanbeusekom** [comment]
@carlos-labrador, @Hunter3173, if you want to know if the location services are running you can use the `Geolocator().isLocationServiceEnabled()` method. Please also check this issue for more details #414 

We need to have a look if we can make the handling of enabling the location services in a more smooth way (which is what the original issue is about). As suggested by @luis901101 on Android we could use the FusedLocation manager to request service activation.

**Comment by Hunter3173** [comment]
> @carlos-labrador, @Hunter3173, if you want to know if the location services are running you can use the `Geolocator().isLocationServiceEnabled()` method. Please also check this issue for more details #414
> 
> We need to have a look if we can make the handling of enabling the location services in a more smooth way (which is what the original issue is about). As suggested by @luis901101 on Android we could use the FusedLocation manager to request service activation.

Thanks !

**Comment by carlos-labrador** [comment]
> @carlos-labrador, @Hunter3173, if you want to know if the location services are running you can use the `Geolocator().isLocationServiceEnabled()` method. Please also check this issue for more details #414 
> 
> We need to have a look if we can make the handling of enabling the location services in a more smooth way (which is what the original issue is about). As suggested by @luis901101 on Android we could use the FusedLocation manager to request service activation.

Thanks for your help.

**Comment by mvanbeusekom** [comment]
Fixed in version 6.0.0
