### ISSUE TITLE
Permission request and Service toggling on

### ISSUE THREAD

**Issue by luis901101** [Baseflow/flutter-geolocator#319]
It would be great if the plugin allows to request the Location permission directly in order to show a Dialog to the user to easily enables it, in addition it would be useful too if the plugin allows to enable the Location service... the FusedLocations has an option for this...
This way the user doesn't have to abandon the app to grant permissions or enable location service. This would apply most for Android but at least for iOS the plugin could support with something like a dialog get the user directly to Settings

- [ x] :iphone: iOS
- [ x] :robot: Android

**Comment by sh0umik** [comment]
Did you find any solution to this ?

**Comment by luis901101** [comment]
I haven't used the FusedLocation but I have done something to make the process the most user friendly possible:

`void getLocation() async{
    try{
      Geolocator geolocator = Geolocator();
      LocationPermissions locationPermissions = LocationPermissions();

      //checking permissions
      PermissionStatus permissionStatus = await locationPermissions.checkPermissionStatus();

      switch(permissionStatus){
        case PermissionStatus.unknown:
        case PermissionStatus.restricted:
          showDialog(
            context: context,
            barrierDismissible: false,
            builder: (context) =>
              NiceDialog(
                type: NiceDialogType.INFO,
                titleText: R.strings.title_info,
                message: "The app has permanent restricted access to the location service. Do you want grant this access to the app?",
                btnCancelText: R.strings.btn_no,
                btnOkText: R.strings.btn_yes,
                btnOkAction: () async{
                  if(await locationPermissions.checkPermissionStatus() == PermissionStatus.granted){
                    Navigator.of(context).pop();
                    getLocation();
                    return;
                  }
                  AppSettings.openAppSettings().then((value) {
                    Navigator.of(context).pop();
                    getLocation();
                  });
                },
              )
          );
          return;
        case PermissionStatus.denied:
          showDialog(
            context: context,
            barrierDismissible: false,
            builder: (context) =>
              NiceDialog(
                type: NiceDialogType.INFO,
                titleText: R.strings.title_info,
                message: "The app doesn't have access to the device's location. Do you want to grant this access to the app?",
                btnCancelText: R.strings.btn_no,
                btnOkText: R.strings.btn_yes,
                btnOkAction: () async{
                  Navigator.of(context).pop();
                  await locationPermissions.requestPermissions();
                  getLocation();
                },
                btnNeutralText: "Check app permissions".toUpperCase(),
                btnNeutralColor: R.colors.colorWarning,
                btnNeutralAction: () async{
                  if(await locationPermissions.checkPermissionStatus() == PermissionStatus.granted){
                    Navigator.of(context).pop();
                    getLocation();
                    return;
                  }
                  AppSettings.openAppSettings().then((value) {
                    Navigator.of(context).pop();
                    getLocation();
                  });
                },
              )
          );
          return;
        case PermissionStatus.granted:
          default:
          break;
      }

      //checking service availability
      ServiceStatus serviceStatus = await LocationPermissions().checkServiceStatus();

      switch(serviceStatus){
        case ServiceStatus.disabled:
          showDialog(
            context: context,
            barrierDismissible: false,
            builder: (context) =>
              NiceDialog(
                type: NiceDialogType.INFO,
                titleText: R.strings.title_info,
                message: "You must enable location services in order to get the device location".,
                btnCancelText: R.strings.btn_cancel,
                btnOkText: R.strings.btn_ok,
                btnOkAction: () async{
                  if(await geolocator.isLocationServiceEnabled()){
                    Navigator.of(context).pop();
                    getLocation();
                    return;
                  }
                  AppSettings.openLocationSettings().whenComplete(() {
                    Navigator.of(context).pop();
                    getLocation();
                  });
                },
              )
          );
          break;
        case ServiceStatus.enabled:
          Position position = await geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.high);
          notifyControllers(position);
          break;
        case ServiceStatus.unknown:
        case ServiceStatus.notApplicable:
        default:
        showDialog(
          context: context,
          barrierDismissible: false,
          builder: (context) =>
            NiceDialog(
              type: NiceDialogType.WARNING,
              titleText: R.strings.title_warning,
              message: "It seems that your device doesn't support location services.",
              btnCancelText: R.strings.btn_cancel,
              btnOkText: R.strings.btn_ok,
              btnOkAction: (){
                Navigator.of(context).pop();
              },
            )
        );
          break;
      }
    }catch(e){
      Fluttertoast.showToast(msg: e.toString());
    }
  }`
