### ISSUE TITLE
placemarkFromCoordinates doesn't return a locality

### ISSUE THREAD

**Issue by mikron123** [Baseflow/flutter-geolocator#323]
We have an app in beta and some of the users didn't get a locality from their lon/lat... you can sometimes be at the same place and not get a locality, where other time maybe you will (?)

How do we solve it?

**Comment by mikron123** [comment]
coordinates 9.790264,100.035541 have full info in google maps: 
Ko Pha-ngan Sub-district, Ko Pha-ngan District, Surat Thani 84280, Thailand

In geolocator plugin, only the country - Thailand.

**Comment by MichaelM97** [comment]
+1 for this, it seems to be an Android only issue for me. On iOS locality returns something like the City, on Android both locality & sublocality are empty strings.

**Comment by mikron123** [comment]
> +1 for this, it seems to be an Android only issue for me. On iOS locality returns something like the City, on Android both locality & sublocality are empty strings (for the exact same coordinates).

Did you check the exact same coordinate that didn't work in Android, only for iOS?

**Comment by febryituery** [comment]
> +1 for this, it seems to be an Android only issue for me. On iOS locality returns something like the City, on Android both locality & sublocality are empty strings (for the exact same coordinates).

have you try subAdministrativeArea? in my case, when platform android, city is subAdministrativeArea, but when platform iOS, city is locality

**Comment by mikron123** [comment]
I got sometimes also with iOS. I wonder if it's a Google API thing or the Flutter package.

**Comment by mikron123** [comment]
Hi, this is pretty critical, is this going to be taken care of soon?

**Comment by StijnWoerkom** [comment]
We will look at the issue and report back as soon as possible.

**Comment by mikron123** [comment]
> We will look at the issue and report back as soon as possible.

Hi Stijn, any insight about it?

**Comment by davydany** [comment]
I was experiencing this issue too, and decided to do some digging into it. Sadly this is something that is an issue with the Android API. If you look at the code for this repo, you'll notice that the author is just using Android's SDK. From what I was reading on StackOverflow, has limitations.

https://stackoverflow.com/questions/56039308/getting-sub-locality-null-for-some-lat-long

What you'll probably have better luck with is to use the Places API and pass it your Lat/Long. This will return a list of points, and you should be able to get the details that you're interested in.

```
# Replace <API_KEY> with an API Key that you get from Google for your project
https://maps.googleapis.com/maps/api/geocode/json?latlng=39.278431,-76.573979&sensor=true&key=<API_KEY>&callback=initialize
```

I think Google wants you to pay them for more finer data. With Places API, you can get 70k (i think) requests for free, but anymore than that will require you to pay. 

This is just based on my research. I might be wrong, and if I'm wrong, please tell me. I want the best possible data for my app too 😄

**Comment by davydany** [comment]
This looks like a promising way to go forward using the Google Places API: https://pub.dev/packages/google_maps_webservice

**Comment by mvanbeusekom** [comment]
Since version 6.0.0 the geocoding features are no longer part of the geolocator plugin and moved to their own plugin which can be found [here](https://github.com/baseflow/flutter-geocoding).
