### ISSUE TITLE
cannot handle location service is disabled turned off

### ISSUE THREAD

**Issue by Xgamefactory** [Baseflow/flutter-geolocator#328]
there are many ways to trigger location service enable native dialog on android, maybe on ios too. The current plugin has no such feature, there is only isLocationServiceEnabled

**Comment by shreeramk** [comment]
I am also facing similar issue. If this library can't trigger that then how we can use this?

**Comment by mvanbeusekom** [comment]
Fixed in version 6.0.0 (works only on Android)
