### ISSUE TITLE
Geolocator().placemarkFromCoordinates returns non proper English locale name

### ISSUE THREAD

**Issue by mikron123** [Baseflow/flutter-geolocator#342]
I use the latest GeoLocator to get the locale:

await Geolocator().placemarkFromCoordinates(position.latitude, position.longitude,localeIdentifier: "en_US");

When in Moscow, sometimes it returns Moskva instead of Moscow.
It of course created a confusion and then I can't know if it's the same city (since it happens sometimes in other places too like Lisbon and Lisboa)

There is another bug regarding locale I posted before.. is someone attending it or should we just abandon this function using GeoLocator and move it to the server side api?

**Comment by StijnWoerkom** [comment]
@mikron123 Moskva is Russian for Moscow and Lisboa is 
Portuguese for Lisbon. I don't know if it has something to do with the language, but You get the correct location right?

**Comment by mikron123** [comment]
> @mikron123 Moskva is Russian for Moscow and Lisboa is
> Portuguese for Lisbon. I don't know if it has something to do with the language, but You get the correct location right?

I get 2 names for the same location. How am I supposed to know it's the same city?
I can't tell if 2 people are from the same city. It's expected to return Lisbon since I chose 'en', but it does it randomly.

**Comment by StijnWoerkom** [comment]
Maybe you have installed multiple language packages so that a location would provide multiple names for a location for each language package installed.

**Comment by mikron123** [comment]
I didn't. The results I was talking about are for different people using the app. Some of them were located in Lisbon and some Lisboa.
I think the conclusion is not to rely on this function on a client side, so I'll let the server determine the placemarks.. otherwise it won't be unified..

**Comment by StijnWoerkom** [comment]
Lisbon and Lisboa are the same cities? The only difference is that Lisbon is English and Lisboa is Portuguese?

**Comment by mikron123** [comment]
Yes, same city, like Moskva and Moscow.. The thing is that it's written in English letter "Moskva".. and not in Russian - Москва.

**Comment by StijnWoerkom** [comment]
Does this problem occur with more cities? Maybe you could try to install a multilingual package for this problem.

**Comment by Omrankabalan** [comment]
Problem still occuring.
I'm using localeIdentifier "en" and locality is sometimes returning "بيروت" instead of "Beirut"

Any solution ?

**Comment by mikron123** [comment]
I just got a user sending "Spaine" to the DB instead of Spain!! 
It's creating a total mess..

**Comment by Omrankabalan** [comment]
@StijnWoerkom Any updates ?

**Comment by mikron123** [comment]
Also got same location in Thailand - once in English and once in Thai language.. Something with the localization parameter in the code of this package maybe? You need to force it to be English.
(sending the english parameter in the GeoLocator API doesn't make a change) Can you please check it?

**Comment by mikron123** [comment]
Now I got from a user "Melesia" instead of Malaysia (The country) and from another user the name of Thailand in Thai language... please help us(!) :) Thanks!

**Comment by mikron123** [comment]
Update: This might have been due to the localeIdentifier parameter not updated in some of the devices.. checking.

**Comment by sms007** [comment]
I am getting administrativeArea as कर्नाटक instead of Karnataka creating a lot of mess even after.

**Comment by vinnytwice** [comment]
Hi everyone, I'm another one here with same problems.
For now my solution is to use a different API for geocoding.. see my post at https://github.com/Baseflow/flutter-geolocator/issues/240#issuecomment-620458081 hop that helps you.
Cheers.

**Comment by mvanbeusekom** [comment]
Since version 6.0.0 the geocoding features are no longer part of the geolocator plugin and moved to their own plugin which can be found [here](https://github.com/baseflow/flutter-geocoding).
