### ISSUE TITLE
PlatformException error showing ERROR_GEOCODING_ADDRESS

### ISSUE THREAD

**Issue by fazil-augr** [Baseflow/flutter-geolocator#344]
## 🐛 Bug Report

I want to get attitude and longitude from address
When I am using the code 

```

List<Placemark> placemark = await Geolocator().placemarkFromAddress(address);

```

It showing the error for some address. Not showing error for all address.

```

PlatformException(ERROR_GEOCODING_ADDRESS, The operation couldn’t be completed. (kCLErrorDomain error 8.), null)

```

### Configuration

**Version:** ^5.1.4+2

**Platform:** 
- [ ] :iphone: iOS

It ' s working fine in android. But in IOS it showing error.
How to solve this issue?

**Comment by nogicoder** [comment]
I'm having the same issue. It seems like it's happening in many projects. Can you please look into this?

**Comment by lsaudon** [comment]
`PlatformException(ERROR_GEOCODING_COORDINATES, grpc failed, null)`only on android

**Comment by DeCodeR-97** [comment]
I'm having the same issue. It works totally fine on android but not on ios. Was anyone able to find a solution?

**Comment by mvanbeusekom** [comment]
Since version 6.0.0 the geocoding features are no longer part of the geolocator plugin and moved to their own plugin which can be found [here](https://github.com/baseflow/flutter-geocoding).
