### ISSUE TITLE
Futurebuilder doesn't update after user gives permission to use location.

### ISSUE THREAD

**Issue by Nielsns** [Baseflow/flutter-geolocator#347]
### Expected behavior
I want the distance between 2 objects when the user gives permission to use it's location. 
When the page is loaded and geolocator is asking for permission, the futurebuilder returns "error" and when the user gives acces, the futurebuilder doesn't update. The Futurebuilder does update when the page is refreshed but I want the futurebuilder to return the distance when the user authorizes to use it's location.

1. The app first asks the user for permission
![AskLocation](https://user-images.githubusercontent.com/55508570/67907828-93c0a000-fb79-11e9-8bf0-d766bdfac5fe.jpg)

2. The user gives permission but the Futurebuilder returns "error" even the user has allowed the acces to the location
![Error](https://user-images.githubusercontent.com/55508570/67907826-93c0a000-fb79-11e9-8bb0-e5b435e4259c.PNG)

3. IF the user refreshed the page, they get the distance. I want the user to get the distance instantly without refreshing the page.
![AfterReload](https://user-images.githubusercontent.com/55508570/67907827-93c0a000-fb79-11e9-98f9-2a61c848f18a.PNG)

### Reproduction steps
**The main code to run the app**
```
import 'package:flutter/material.dart';
import 'mainlist.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      routes: {
        '/second': (context) => mainlist()
      },
      title: "testapp",
      debugShowCheckedModeBanner: false,
      home: mainlist(),
    );
  }
}`
```

The code where the problem happens - Futurebuilder + getCurrenPosition Future
```
`import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';

import 'package:async/async.dart';
import 'package:geolocator/geolocator.dart';
import 'package:permission/permission.dart';
import 'mainlist.dart';


class mainlist extends StatefulWidget {
  @override
  _mainlistpage createState() => _mainlistpage();
}


class _mainlistpage extends State<mainlist> {


  Future<String> getCurrentPosition(DocumentSnapshot document) async{
    Position position = await Geolocator().getCurrentPosition(desiredAccuracy: LocationAccuracy.high);
    double distanceInMeters = await Geolocator().distanceBetween(position.latitude, position.longitude, document['lat'], document['lat']);
    return distanceInMeters.toString();
  }

  var sortBy = "";

  Widget homePage() {
    return StreamBuilder(
      stream: Firestore.instance.collection("Test").orderBy(sortBy).snapshots(),
      builder: (context, snapshot) {
        if (!snapshot.hasData) return Text("Loading");
        return ListView.builder(
            itemCount: snapshot.data.documents.length,
            itemBuilder: (context, index) =>
                _mainListItem(context, snapshot.data.documents[index]));
      },
    );
  }


  @override
  Widget _mainListItem(BuildContext context, DocumentSnapshot document) {
    return Scaffold(
      body: Container(
        child: Center(
          child: Column(
              children: <Widget>[
                FutureBuilder(
                    future: getCurrentPosition(document),
                    builder: (BuildContext context,AsyncSnapshot snapshot)  {
                      switch (snapshot.connectionState) {
                        case ConnectionState.none:
                          return Text('none');
                        case ConnectionState.active:
                        case ConnectionState.waiting:
                          return Text('waiting');
                        case ConnectionState.done:
                          if (snapshot.hasError)
                            return Text('Error: ${snapshot.error}');
                          return Text(snapshot.data.toString());

                      }
                      return null; // unreachable
                    }
                ),
              ]
          ),
        ),
      ),
    );
  }`
```
### Configuration
Stackoverflow link: https://stackoverflow.com/questions/58613587/flutter-futurebuilder-keeps-returning-null-after-location-permission?noredirect=1#comment103539916_58613587
**Version:** 1.x
5.1.3
**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
The example project uses a`FutureBuilder` to acquire the location and handle permissions if necessary. You might want to have a look

**Comment by giorgio79** [comment]
I am only seeing a ListView builder here https://github.com/Baseflow/flutter-geolocator/blob/master/geolocator/example/lib/main.dart
