### ISSUE TITLE
Turn gps service off without navigating to settings (Android)

### ISSUE THREAD

**Issue by Xgamefactory** [Baseflow/flutter-geolocator#351]
![36700340-6edd18f4-1b60-11e8-8949-ccede05ccad3 1](https://user-images.githubusercontent.com/22529051/68537447-4d3f2280-037d-11ea-8bce-657884d8ab27.png)

it is possible on android here are some examples.

https://stackoverflow.com/questions/33251373/turn-on-location-services-without-navigating-to-settings-page

**Comment by mvanbeusekom** [comment]
Implemented in version 6.0.0
