### ISSUE TITLE
Preventing GPS Spoofing or Location Mocking

### ISSUE THREAD

**Issue by ianjaspersantos** [Baseflow/flutter-geolocator#353]
I implement location tracking to enable the app if you are within the certain proximity however id tried to spoof my location using app spoofing location and yeah the spoofing works. I want to know if theirs a way to prevent it.

**Comment by egorikem** [comment]
There's a `mocked` property of `Position` class

**Comment by fre391** [comment]
Hi, tried to use this attribute, but Im getting an error:

E/flutter (29773): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'mocked' was called on null.
E/flutter (29773): Receiver: null
E/flutter (29773): Tried calling: mocked

Im using the actual version: geolocator: ^5.3.0
