### ISSUE TITLE
When can 'GeolocationStatus.restricted' be set by iOS?

### ISSUE THREAD

**Issue by cielo** [Baseflow/flutter-geolocator#354]
The comment says this status can be set only in iOS.

```
  /// The user granted restricted access to the requested feature (only on iOS).
  static const GeolocationStatus restricted = GeolocationStatus._(3);
```
It must have a different meaning than `disabled` or `denied`, but I could not figure out how I needed to handle this `restricted` case. (how is it different from `granted`?)

**Comment by mvanbeusekom** [comment]
Here is the Apple documentation regarding the restricted permission: 

> The user cannot change this app’s status, possibly due to active restrictions such as parental controls being in place
