### ISSUE TITLE
When Geolocator().placemarkFromAddress()'s address is not right, How can I get null rather than exception

### ISSUE THREAD

**Issue by JunjaK** [Baseflow/flutter-geolocator#356]
Hello! 

It works well when Geolocator().placemarkFromAddress()'s parameter address is right.
But, the address is not right(can't find on google map), this function return " PlatformException (PlatformException(ERROR_GEOCODNG_ADDRESSNOTFOUND, Unable to find coordinates matching the supplied address., null)) " 
like this picture
![2019-12-02](https://user-images.githubusercontent.com/30404630/69948644-58780f00-1533-11ea-9844-bb402e04b612.png)

So, if address is not right, How can I get null rather than exception of 'PlatformException (PlatformException(ERROR_GEOCODNG_ADDRESSNOTFOUND, Unable to find coordinates matching the supplied address., null))'?

**Comment by NaufalHafizi** [comment]
Hi, you solved this ?

**Comment by mvanbeusekom** [comment]
@NaufalHafizi you could simply at a try...catch statement:

```dart
List<Placemark> placemarks = null;
try {
  placemarks = await Geolocator().placemarkFromAddress(query);
} on PlatformException catch (e) {
  if (e.errorCode == 'ERROR_GEOCODING_ADDRESSNOTFOUND') {
    placemarks = null;
  } else {
    // Don't handle this case so rethrow the exception...
    rethrow;
  }
}
```

Note that as part of geolocator version 6.0.0 we have moved the geocoding features into their own [dedicated plugin](https://pub.dev/packages/geocoding) and remove the `placemarkFromAddress` and `placemarkFromCoordinates` from the geolocator plugin.

**Comment by NaufalHafizi** [comment]
> @NaufalHafizi you could simply at a try...catch statement:
> 
> ```dart
> List<Placemark> placemarks = null;
> try {
>   placemarks = await Geolocator().placemarkFromAddress(query);
> } on PlatformException catch (e) {
>   if (e.errorCode == 'ERROR_GEOCODING_ADDRESSNOTFOUND') {
>     placemarks = null;
>   } else {
>     // Don't handle this case so rethrow the exception...
>     rethrow;
>   }
> }
> ```
> 
> Note that as part of geolocator version 6.0.0 we have moved the geocoding features into their own [dedicated plugin](https://pub.dev/packages/geocoding) and remove the `placemarkFromAddress` and `placemarkFromCoordinates` from the geolocator plugin.

thank you

**Comment by Nandkishorkumar** [comment]
> > @NaufalHafizi you could simply at a try...catch statement:
> > ```dart
> > List<Placemark> placemarks = null;
> > try {
> >   placemarks = await Geolocator().placemarkFromAddress(query);
> > } on PlatformException catch (e) {
> >   if (e.errorCode == 'ERROR_GEOCODING_ADDRESSNOTFOUND') {
> >     placemarks = null;
> >   } else {
> >     // Don't handle this case so rethrow the exception...
> >     rethrow;
> >   }
> > }
> > ```
> > 
> > 
> > Note that as part of geolocator version 6.0.0 we have moved the geocoding features into their own [dedicated plugin](https://pub.dev/packages/geocoding) and remove the `placemarkFromAddress` and `placemarkFromCoordinates` from the geolocator plugin.
> 
> thank you

if (e.errorCode == 'ERROR_GEOCODING_ADDRESSNOTFOUND')
here 'e.errorcode' is not working for me
it's showing the getter 'errorcode 'isn't define for the type of 'PlatformException'
will you help see to it .
