### ISSUE TITLE
App Build Failure Dependency Conflict

### ISSUE THREAD

**Issue by petermichaux** [Baseflow/flutter-geolocator#357]
I upgraded the Android part of my Flutter app to use AndroidX. After doing so, my app compiled and ran well.

Then I added `geolocator: ^5.1.5` to my `pubspec.yaml` file. When I tried to build for Android, I see the following build error. (Building works for iOS and I can get the device's current location.)

```
Launching lib/main.dart on SM T380 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'androidx.fragment:fragment' has different version for the compile (1.0.0-rc01) and runtime (1.0.0) classpath. You should manually set the same version via DependencyResolution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

**Comment by mvanbeusekom** [comment]
Hi Peter, 

I have just tried creating a new Flutter application, added the dependency to the Geolocator plugin to the `pubspec.yaml`, downloaded the packages and could compile the app without any problems:

1. Create a new app: `flutter create geolocator_issue_357`
2. Add Geolocator dependency to pubspec.yaml:
```
dependencies:
  flutter:
    sdk: flutter

  geolocator: ^5.1.5
```
3. Download packages: `flutter packages get`
4. Compile the application for Android: `flutter build apk`

Are you adding the Geolocator to an existing app or did you create a fresh App and tried to add the Geolocator?

Why you mention you updated to support AndroidX,  which steps did you take? Could you send the contents of the following files:

- android/build.gradle
- android/gradle.properties
- android/gradle/wrapper/gradle-wrapper.properties
- android/app/build.properties

**Comment by petermichaux** [comment]
Thank you, @mvanbeusekom, for your response.

I can create a fresh Flutter app, add Geolocator, and build for Android!

There seems to be a conflict between the Flutter Google Maps plugin and the Flutter Geolocator plugin.

Create and run a generated Flutter app.

    $ flutter create --org com.example            \
                     --ios-language swift         \
                     --android-language kotlin    \
                     --description 'The ABC app.' \
                     --project-name abc           \
                     --androidx                   \
                     abc

    $ cd abc

    $ flutter run

The app builds and runs on Android as expected.

Now to add a couple dependencies.

    $ code pubspec.yaml
    
Add the following lines in the dependencies section.

    geolocator: ^5.1.5
    google_maps_flutter: ^0.5.21+12

Then

    $ flutter pub get

    $ flutter pub upgrade

    $ flutter run

See the following error message.

```
Launching lib/main.dart on SM T380 in debug mode...
Initializing gradle...                                              0.7s
Resolving dependencies...                                           1.3s

FAILURE: Build failed with an exception.                                

* What went wrong:                                                      
Execution failed for task ':app:preDebugBuild'.                         
> Android dependency 'com.google.android.gms:play-services-basement' has different version for the compile (16.0.1) and runtime (17.0.0) classpath. You should manually set the same version via DependencyResolution

* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org                              

BUILD FAILED in 7s                                                      
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                         7.9s
Gradle task assembleDebug failed with exit code 1
```

-----

To update to AndroidX, I used the Android Studio command to migrate.

What appear to be the key lines in my Android `build.gradle` files, etc seem to match a freshly generated Flutter app. I can provide if the above information about Google Maps and Geolocation not playing well together is not enough.

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G103, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.3)
[✓] IntelliJ IDEA Community Edition (version 2017.1.4)
[✓] VS Code (version 1.40.2)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by petermichaux** [comment]
Using different versions of the Google Maps and Geolocator plugins, I can get the two to coexisit peacefully on Android. (Works for iOS too though iOS hasn't been an issue so far.)

```
google_maps_flutter: 0.5.20+1
geolocator: 5.1.2
```

Based on a screenshot in this article

https://medium.com/flutter-community/google-maps-in-flutter-i-feeb72354392

**Comment by mvanbeusekom** [comment]
@petermichaux thanks to your additional feedback I was able to reproduce the issue. The problem is that the application template that is used by Flutter to create a new Flutter App (using something like `flutter create my_app`). References an outdated version of Gradle in the `android/build.gradle` file (version 3.2.1 to be exact).

Both the "google_maps_flutter" (version 3.3.2) and the "geolocator" (version 3.4.1) plugins reference a newer version which is causing the conflict. 

To solve your problem simply upgrade the version referenced by your App to version 3.3.2 or higher. This can be done by updating the following line (usually line 11) in your `android/build.gradle` file:

```
        classpath 'com.android.tools.build:gradle:3.2.1'
```
to 
```
        classpath 'com.android.tools.build:gradle:3.3.2'
```

> NOTE: if your Android App is using Kotlin you will also have to update Kotlin version from 1.2.71 to 1.3.0 or higher. This is also done in the `android/build.gradle` file (on line 2 update the value for `ext.kotlin_version` to `1.3.0`).

After you have made the necessary changes to the `android/build.gradle` file you should be able to use the latest versions of both plugins together. It might be good to first run a `flutter clean` command before you recompile.
