### ISSUE TITLE
Using XCode archive error, Module 'geolocator' not found

### ISSUE THREAD

**Issue by medz** [Baseflow/flutter-geolocator#362]
![image](https://user-images.githubusercontent.com/5564821/70999197-e0edd680-2113-11ea-88d0-b7a3be64c806.png)

It is normal to use command line packaging, and it is normal to use XCode to debug on the device. But when using XCode for archiving, it always prompts `Module 'geolocator' not found`

![image](https://user-images.githubusercontent.com/5564821/70999362-3f1ab980-2114-11ea-8aee-72e1f17cb25f.png)

**Comment by GLopesRio** [comment]
I have the same problem. Did you manage to solve it? Thank you

**Comment by medz** [comment]
> I have the same problem. Did you manage to solve it?
> My configuration is ok.
> Thanks

@GLopesRio I solved this problem after using `flutter clean`

**Comment by Terterola** [comment]
Hi, there. 

Did you guys solved this error? I'm facing the same problem (Module 'geolocator' not found). 

I've tried "flutter clean" but nothing changed.

:(

**Comment by dsgriffin** [comment]
no amounts of flutter cleans, pod installs and deleting podfile.lock's resolve this for me, anyone?

```
▸ Compiling GeneratedPluginRegistrant.m

❌  /Users/danielgriffin/Documents/projects/fuocos-pizza/consumer_app/ios/Runner/GeneratedPluginRegistrant.m:76:9: module 'geolocator' not found

@import geolocator;
                       ^
▸ Compiling Runner_vers.c
▸ Compiling GeneratedPluginRegistrant.m

❌  /Users/danielgriffin/Documents/projects/fuocos-pizza/consumer_app/ios/Runner/GeneratedPluginRegistrant.m:76:9: module 'geolocator' not found

@import geolocator;
```

**Comment by gustavovisentini** [comment]
Has anyone managed to find the solution?

/Runner/GeneratedPluginRegistrant.m:34:9: Module 'geolocator_apple' not found

geolocator 7.4.0 on pub dev

**Comment by bichoalexis** [comment]
> Has anyone managed to find the solution?
> 
> /Runner/GeneratedPluginRegistrant.m:34:9: Module 'geolocator_apple' not found
> 
> geolocator 7.4.0 on pub dev

Same problem here with geolocator: ^7.3.1

**Comment by shirishkoirala** [comment]
Same problem with geolocator 7.5.0

**Comment by shameemreza** [comment]
Dose anyone got any solution?

**Comment by NgangaWaKahe** [comment]
Try the solutions found on this page - deployment target in xcode - https://issueexplorer.com/issue/Baseflow/flutter-geolocator/829

**Comment by rmahmadkhan** [comment]
I tried everything including clean, pod install, and whatnot.

The build is working on the simulator and device. Only when I try to export the build to AppStore by archiving, this error occurs and the archive is failed. I hope someone can help.

**Comment by rmahmadkhan** [comment]
For me, it was working on the simulator and device. Only when I try to archive the build for sending to Apple, the error occurs.

Thanks to @NgangaWaKahe, I found out that my error was due to the different iOS Deployment Target in `Podfile` and in Xcode's Project Runner.

I made both same, it worked happily after.

Here are screenshots of both now after correction.

#### ios version in my Podfile
[![ios version in my Podfile][1]][1]

#### ios version in Project Runner
[![ios version in Project Runner][2]][2]


  [1]: https://i.stack.imgur.com/1CFQg.png
  [2]: https://i.stack.imgur.com/vTcMq.png
