### ISSUE TITLE
my app does not build after adding geolocator dependency

### ISSUE THREAD

**Issue by AdnanAlshami** [Baseflow/flutter-geolocator#363]
## 🐛 Bug Report

I can't build my app after adding geolocator dependency.
here is what I got when I run `flutter run -v` command:

[+6116 ms] Starting a Gradle Daemon, 6 busy and 3 incompatible and 2 stopped Daemons could not be reused, use --status for details

[+450173 ms] FAILURE: Build failed with an exception.
[   +7 ms] * What went wrong:
[        ] A problem occurred configuring project ':google_api_availability'.
[   +2 ms] > Could not resolve all artifacts for configuration ':google_api_availability:classpath'.
[   +2 ms]    > Could not download builder.jar (com.android.tools.build:builder:3.3.1)
[   +1 ms]       > Could not get resource
'https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.3.1/builder-3.3.1.jar'.
[   +1 ms]          > Premature end of Content-Length delimited message body (expected: 30629071; received: 4456416
[        ] > Could not get unknown property 'android' for project ':google_api_availability' of type org.gradle.api.Project.
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan
to get full insights.
[   +1 ms] * Get more help at https://help.gradle.org
[   +2 ms] BUILD FAILED in 7m 36s
[ +506 ms] Running Gradle task 'assembleDebug'... (completed in 457.0s, longer than expected)
[   +9 ms] "flutter run" took 458,849ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:387:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:74:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:33:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:291:13)
#11     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:74:64)
#13     _rootRunUnary (dart:async/zone.dart:1134:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

**Platform:** 
- [ ] :robot: Android

**Comment by AdnanAlshami** [comment]
any help please

**Comment by divya2399** [comment]
What is the solution to solve this? I am having the exactly same error

**Comment by mvanbeusekom** [comment]
Not sure but try migrating to the latest Android activity: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
