### ISSUE TITLE
Bounding box parameter for placemarkFromAddress() method

### ISSUE THREAD

**Issue by sanisloandras** [Baseflow/flutter-geolocator#366]
## 🚀 Feature Requests

Hello!

What I want to achieve is to geocode addresses into geographic coordinates ONLY within a specific city.
I'm not sure what's the base idea of this library and what does it use internally, but, for example, Android's Geocoder library supports a bounding box for the search results. Read more about this [here](https://developer.android.com/reference/android/location/Geocoder.html#getFromLocationName(java.lang.String,%20int,%20double,%20double,%20double,%20double)).

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by sanisloandras** [comment]
Submitted a PR: https://github.com/Baseflow/flutter-geolocator/pull/367

**Comment by mvanbeusekom** [comment]
Since version 6.0.0 the geocoding features are no longer part of the geolocator plugin and moved to their own plugin which can be found here.
