### ISSUE TITLE
Number of connected satellites

### ISSUE THREAD

**Issue by billymahmood** [Baseflow/flutter-geolocator#368]
### Contextualize the feature
We are building an app that stores the users location when they start filling out a question and also when they finish the question - we need to store their geolocation including the number of satellites the phone was connected to at the time. 

### Describe the feature
Get the number of satellites the phone is connected to when retrieving the geolocation data

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [X] :robot: Android

**Comment by mistercx** [comment]
24/04/2020: This issue is actual still.

**Comment by mvanbeusekom** [comment]
Unfortunately there is no (reliable) way to determine the amount of satellites the phone was connected to when a location is retrieved. 

You do however have the `accuracy` property which the radius of uncertainty for the location, measured in meters. This indicates how accurate the device believes that location fix to be.
