### ISSUE TITLE
How the library got Timestamp?

### ISSUE THREAD

**Issue by pablocunha** [Baseflow/flutter-geolocator#376]
The object Postion has Timestamp property, but how the library got this Timestamp? 

It is based on device's Datetime?

**Comment by mvanbeusekom** [comment]
Hi @pablocunha, 

The timestamp is determined based on the platforms SDK on retrieving geolocation coordinates. In case of Android we are returning the value of the `getTime` method on the [android.location.Location](https://developer.android.com/reference/android/location/Location.html) class. 

In case of iOS the value of the `timestamp` property of the [CLLocation](https://developer.apple.com/documentation/corelocation/cllocation) class is returned.

Hope this answers you question.

**Comment by sszarkadmin** [comment]
Hi @mvanbeusekom. Great plugin.

So just to confirm it is Local DateTime and we need to `.toUtc()` to get grab the UTC DateTime?

Could you kindly confirm?

**Comment by mvanbeusekom** [comment]
Correct, all timestamps are based on the device’s timezone settings

**Comment by sszarkadmin** [comment]
@mvanbeusekom Cheers! ty for the clarification.
