### ISSUE TITLE
Stream to isLocationServiceEnabled does not work

### ISSUE THREAD

**Issue by danielmessi13** [Baseflow/flutter-geolocator#377]
## 🐛 Bug Report

When i try to stream the verification if the user's location is activated my listener cannot hear the state changes in my gps.

I wanted when the user switched on or off I changed my widget signaling that the gps needs to be switched on, giving automatic feedback

### Reproduction steps

```
Stream<bool> streamGPS = Geolocator().isLocationServiceEnabled().asStream();

streamGPS.listen((onData) {
  print("ON DATA $onData");
});
```

**Version:** ^5.2.0

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android

**Comment by mvanbeusekom** [comment]
The `isLocationServiceEnabled` method isn't a stream, it is a one time check (which happens to be asynchronous, but still one time).

So what you are doing now is converting the asynchronous call, which returns one value and then ends, into a stream. This will result in a value being published on the stream, one time only, when the call finishes. 

The operating system (Android and iOS) by my knowledge don't provide an option to subscribe to the state change of the location services, so you will need to manually request it each time you need it.
