### ISSUE TITLE
PlatformException(ERROR_GEOCODING_COORDINATES, grpc failed, null)

### ISSUE THREAD

**Issue by habilgur** [Baseflow/flutter-geolocator#378]
Hello Everyone,

Since yesterday, both on emulator and real decives, i got Unhandled Exception: PlatformException(ERROR_GEOCODING_COORDINATES, grpc failed, null) error from plugin.

I tried all my projects that used geolocation plugins before, unfortunately all of them throws same error.

Does any one have same issue?

**Reproduction** 
When ever call plugin's function 

**Platform** Android.
**Plugin Version:** geolocator 5.2.0
**location**: granted
**internet**: wifi & cellular

**Stack** 
 #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
    #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
    <asynchronous suspension>
    #2      Geolocator.placemarkFromCoordinates (package:geolocator/geolocator.dart:256:59)
    #3      GeoManager.placeMark (package:flutter_app_pray_time/Services/geo_manager.dart:24:10)
    #4      CoreProvider.fetchPositionAndLocation.<anonymous closure> (package:flutter_app_pray_time/Provider/core_provider.dart:29:24)
    #5      _rootRun (dart:async/zone.dart:1122:38)
    #6      _CustomZone.run (dart:async/zone.dart:1023:19)
    #7      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:163:18)
    #8      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:650:39)
    #9      Future._propagateToListeners (dart:async/future_impl.dart:706:37)
    #10     Future._completeWithValue (dart:async/future_impl.dart:524:5)
    #11     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
    #12     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
    #13     GeoManager.getLocation (package:flutter_app_pray_time/Services/geo_manager.dart)
    <asynchronous suspension>
    #14     CoreProvider.fetchPositionAndLocation (package:flutter_app_pray_time/Provider/core_provider.dart:28:22)
    #15     CoreProvider.refreshPositionAndLocation (package:flutter_app_pray_time/Provider/core_provider.dart:38:5)
    #16     _WelcomeScreenState.build.<anonymous closure> (package:flutter_app_pray_time/Views/Screens/welcome_screen.dart:270:71)
    #17     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
    #18     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
    #19     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
    #20     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
    #21     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
    #22     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
    #23     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467:9)
    #24     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
    #25     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
    #26     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
    #27     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
    #28     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
    #29     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
    #30     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
    #31     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
    #32     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
    #33     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
    #34     _rootRunUnary (dart:async/zone.dart:1138:13)
    #35     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
    #36     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
    #37     _invoke1 (dart:ui/hooks.dart:273:10)
    #38     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)

**Comment by mvanbeusekom** [comment]
@habilgur, possible this is an issue related to Google Play Services not being available in the region you are currently in (see also #223 ). 

If you are using the `getPermissionStream` method you could try forcing the use of the Android Location Manager instead of Google Play Services by setting the `forceAndroidLocationManager` property of the `LocationOptions` parameter to `true`.

I will also make an overload to the other methods in the coming release.

**Comment by habilgur** [comment]
@mvanbeusekom , Now service is back and errors gone however it seems unstable.  I think you are right about the region issue because recently there has been some problems about main internet provider of Turkey. Thank you for your reply and  quick support.
