### ISSUE TITLE
Placemark toJson method bug

### ISSUE THREAD

**Issue by efraimrodrigues** [Baseflow/flutter-geolocator#379]
## 🐛 Bug Report

The Placemark.toJson method doesn't return valid json because the position attribute toString method doesn't return a valid json field. This causes an error in the Placemark.fromMap method when using the Placemark.toJson method as parameter.

I'll make a PR to correct this.

### Expected behavior
Placemark.toJson should return the following:
{name: , isoCountryCode: , country: , postalCode: , administrativeArea: , subAdministrativeArea: , locality: , subLocality: , thoroughfare: , subThoroughfare: , position: {longitude: -35.5648988, latitude: -3.7955015, timestamp: null, mocked: false, accuracy: 0.0, altitude: 0.0, heading: 0.0, speed: 0.0, speedAccuracy: 0.0}}

Note the position is a valid json object here.

### Reproduction steps
```
Position currentPosition = await geolocator
    .getCurrentPosition(desiredAccuracy: LocationAccuracy.best);

List<Placemark> p = await geolocator.placemarkFromCoordinates(currentPosition.latitude, currentPosition.longitude);

Placemark newPlacemark = Placemark.fromMap(p[0].toJson());
```

The following error is displayed: type 'Position' is not a subtype of type 'Map<dynamic, dynamic>'
### Configuration

**Version:** 5.2.0

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android

PR [380](https://github.com/Baseflow/flutter-geolocator/pull/380) is a fix for this issue.

**Comment by mvanbeusekom** [comment]
@efraimrodrigues thank you for reporting and fixing this issue. We just released version 5.2.1 containing the fix you supplied.
