### ISSUE TITLE
Move utility methods to Dart side

### ISSUE THREAD

**Issue by mvanbeusekom** [Baseflow/flutter-geolocator#384]
## 🏗 Enhancement Proposal

Currently the implementation of the `distanceBetween` method relies on the implementation on the platform. We can move the implementation to the Dart side which will have the following benefits:

1. Identical implementation between platforms (e.g. you will always get the same results no matter the platform you are on;.
2. No need to send messages between Dart and native code which should increase performance and reduces complexity.

**Comment by RyanRamchandar** [comment]
Anecdotally: I recall trying to do this on the Dart side, but noticed it took an order of magnitude longer to execute than the native utility method. So I opted to stick with the native implementation. Take it with a grain of salt but worth noting.

I agree having this all on the dart side as you proposed is ideal.

**Comment by dougsibley** [comment]
Aah, this makes sense why Issue 311 exists (https://github.com/Baseflow/flutter-geolocator/issues/311). Running in unit test mode doesn't start the simulator (at least in my experience) and so the function doesn't work (it shows as unimplemented).

**Comment by mvanbeusekom** [comment]
Starting from version 6.0.0 the `distanceBetween` method is implemented as a static method in Dart. It can be called like this:

```dart
import 'package:geolocator/geolocator.dart';

double distanceInMeters = GeolocatorPlatform.distanceBetween(52.2165157, 6.9437819, 52.3546274, 4.8285838);
```
