### ISSUE TITLE
GeneratedPluginRegistrant.m:10:9: fatal error: module 'geolocator' not found

### ISSUE THREAD

**Issue by FirdousNath** [Baseflow/flutter-geolocator#387]
Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    Debug.xcconfig line 1: Unable to find included file "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"
    Debug.xcconfig line 1: Unable to find included file "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"
    The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target.
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    /Users/imac/Desktop/untitled folder/Clima/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'geolocator' not found
    @import geolocator;
     ~~~~~~~^~~~~~~~~~
    1 error generated.

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.

**Comment by pedrohenriqueveiga** [comment]
i have same problem,  
put that key <key>NSLocationWhenInUseUsageDescription</key>
<string>This app needs access to location when open.</string> 
but nothing change..

**Comment by Terterola** [comment]
Hi, there. 

Did you guys solved this error? I'm facing the same problem (Module 'geolocator' not found). :(

**Comment by mvanbeusekom** [comment]
This is an issue related to your development environment and caused by differences between Xcode (and the installed Swift version) and the Flutter project. I have solved this multiple time using by opening the folder `ios` with Xcode and build the project. When the build fails simple follow the instructions: 

>The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target.

**Comment by freddycalderonp1990** [comment]
Yo pude solucionarlo..

Generar desde Xcode
Product-Build For-Profiling

Verificar que ele Scheme este en Runner
Luego Generar el Archive

**Comment by yogeshk25** [comment]
@mvanbeusekom  How to fix this in a CI/CD environment. In a console based environment, we can not perform steps you mention by launching xcode.
Is there a permanent fix for this, which does not require manual intervention?
How does other pub packages handle this kind on swift version conflict?
