### ISSUE TITLE
Location in Background Mode 

### ISSUE THREAD

**Issue by thomasnilsson** [Baseflow/flutter-geolocator#390]
## 🚀 Feature Requests

At least on iOS, the app will stop tracking the location after about 30 seconds, after the application goes into the background.

### Contextualize the feature
Continually track the location

### Describe the feature
Add this line after line 38 in `LocationTask.m`
```
 _locationManager.allowsBackgroundLocationUpdates = YES;
```
Not sure what the status is on Android.

### Platforms affected (mark all that apply)
- [ x ] :iphone: iOS
- [ ] :robot: Android

**Comment by hlongngo** [comment]
I am having the same issue.

**Comment by estevez-dev** [comment]
The app can't be launched in the background forever. To save user's battery and memory iOS and Android will close your application been some time on the background. You can try to use [workmanager](https://pub.dev/packages/workmanager) or [foreground_service](https://pub.dev/packages/foreground_service) for this. Nothing to do in geolocator plugin itself.

**Comment by estevez-dev** [comment]
Also see some comments in #389

**Comment by RomanJos** [comment]
Would it be possible to at least have update if we lock the phone ?

**Comment by SetNameHere** [comment]
Does this pull request only address the issue for IOS?
On android I get the same behaviour.
After some time the app will be terminated, preventing the receiption of any stream updates.

**Comment by thomasnilsson** [comment]
> Does this pull request only address the issue for IOS?
> On android I get the same behaviour.
> After some time the app will be terminated, preventing the receiption of any stream updates.

Google has recently changed the behaviour of the location API, read this: https://developer.android.com/about/versions/oreo/background-location-limits

**Comment by SetNameHere** [comment]
So if I get it right, we need in addition to your IOS fix a foreground service, handling the stream functionality on android side, correct?

**Comment by thomasnilsson** [comment]
Yep. This plugin (https://pub.dev/packages/foreground_service) worked for me, although running a foreground service drains the battery quite a lot in my experience, and I had some compilations issues when compiling for iOS, when using the package.

**Comment by SetNameHere** [comment]
I have switched for the moment to the background_locator plugin (https://pub.dev/packages/background_locator#-readme-tab-).
Currently it works realy good.
