### ISSUE TITLE
Getting a PlatformException(ERROR_ALREADY_REQUESTING_PERMISSION) error when I try to grab a location.

### ISSUE THREAD

**Issue by SNELON** [Baseflow/flutter-geolocator#393]
## 🐛 Bug Report

Here is the function that I am using to try and grab a location. When this function is called I get a `PlatformException(ERROR_ALREADY_REQUESTING_PERMISSION, A request for permissions is already running, please wait for it to finish before doing another request., null)` error (It also does not give me a location). Does anyone know a work around for this. 
_getCurrentLocation() {
    final Geolocator geolocator = Geolocator()..forceAndroidLocationManager;

    geolocator
        .getCurrentPosition(desiredAccuracy: LocationAccuracy.best)
        .then((Position position) {
      setState(() {
        _currentPosition = position;
      });
    }).catchError((e) {
      print(e);
    });
  }

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS

**Comment by mvanbeusekom** [comment]
Hi @SNELON, most likely you are executing multiple calls to the `getCurrentLocation` method. The permission handling system used by the Geolocator is sensitive for multiple calls at the same time. So you need to make sure you don't call it a second time before the first time is finished.

The most common case when this happens, is when people call the method directly from their `Widget build(BuildContext context)` method. The build method can be called by the Flutter runtime multiple times in rapid succession. The best way to get around this is to create a statefull widget and get the location in the `initState` method.
