### ISSUE TITLE
permission_handler and geolocator returning different values for the same permission

### ISSUE THREAD

**Issue by fabiomgoncalves** [Baseflow/flutter-geolocator#394]
## 🐛 Bug Report

I'm using the permission_handler package to check different type of permissions, as well the usage the `shouldShowRequestPermissionRationale `method.  

After the application starts, a request to access the user location is made. permission_handler correctly returns the permission as granted, while geolocator is giving denied.

```
await PermissionHandler()
        .checkPermissionStatus(PermissionGroup.locationWhenInUse); // PermissionStatus.granted

await _geolocator.checkGeolocationPermissionStatus(
            locationPermission: GeolocationPermission.locationWhenInUse); // GeolocationStatus.denied
```

### Expected behavior

Both checks should return the same value. In this case, granted.

### Reproduction steps

- Ask for location permission with permission_handler, for example for `locationWhenInUse`
- Allow the request
- Check the the status of the permission with permission_handler and geolocator
- permission_handler returns as allowed, while geolocator as denied

### Configuration

**Version:** 4.2.0+hotfix.3

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android 10 (Samsung S10 and emulator running Android 10)

**Comment by fabiomgoncalves** [comment]
After digging further, [seems to be a bug related to location_permissions](https://github.com/Baseflow/flutter-permission-plugins/issues/29), which is used underneath to check the permissions.

**Comment by mvanbeusekom** [comment]
@fabiomgoncalves this bug occurs when you are targeting SDK 28 and running you app on a device or emulator with Android 10. The solution here would be to update the `targetSdkVersion` and `compileSdkVersion` in your `android/app/build.gradle` file and set them to `29`.

See for more information my [response](https://github.com/Baseflow/flutter-permission-plugins/issues/29#issuecomment-592471168) to the issue in the `location_permissions` plugin.
