### ISSUE TITLE
PlatformException(ERROR_GEOCODING_COORDINATES, grpc failed, null)

### ISSUE THREAD

**Issue by H-Mongo** [Baseflow/flutter-geolocator#398]
## 💬 Questions and Help

For questions or help we recommend checking:

- I use the geolocater 5.3.0 with my project，I get positon like this: 
{longitude: 106.56xxxxxx, latitude: 36.00xxx, timestamp: 1583019382000, mocked: false, accuracy: 1.0, altitude: 0.0, heading: 0.0, speed: 0.0, speedAccuracy: 0.0}. but try to invoke geolocator.placemarkFromCoordinates() method. But the project show a exception to me.
* Exception detials: PlatformException(ERROR_GEOCODING_COORDINATES, grpc failed, null),
who can help me to resolve this question?【I'm in a hurry】

**Comment by mvanbeusekom** [comment]
Hi, this normally happens for people that are in a region that are restricted for accessing Google Play Services.

The plugin doesn’t work with GRPC (a.k.a. Protobuf). This error is generated from the Android API itself and is unfortunately not something we can influence as far as I know (please correct me if I am wrong, I would be happy to make changes when possible).

Please also see other issues with this error: https://github.com/Baseflow/flutter-geolocator/issues/378

**Comment by H-Mongo** [comment]
# 378 I have seen it before, the authorization and positioning status has been detected to be normal, Google Play is also turned on, and this GRPC call occurs in the plugin itself. Is there any other way to solve this problem?

**Comment by H-Mongo** [comment]
#378  I have seen it before, the authorization and positioning status has been detected to be normal, Google Play is also turned on, and this GRPC call occurs in the plugin itself. Is there any other way to solve this problem?

**Comment by mvanbeusekom** [comment]
@H-Mongo the error is generated from the Android SDK (which is wrapper by the "permission_handler" plugin). You can find the official bug reports [here](https://issuetracker.google.com/issues/64418751) and [here](https://issuetracker.google.com/issues/64247769).

I noticed that there are some workarounds (described in this SO answer: https://stackoverflow.com/questions/47331480/geocoder-getfromlocation-grpc-failed-on-android-real-device) but they will require time to implement on our side. If you are really in a hurry we would love to accept a pull-request and move it through quickly.

**Comment by H-Mongo** [comment]
Thanks for your help,i will wait for you close this bug

**Comment by jlubeck** [comment]
On that StackOverflow post it says: "Lol.. Just putting that call in a background thread or Coroutine works "

Is that something that can be done within the library?
