### ISSUE TITLE
Why geolocator.placemarkFromCoordinates() gives different address for same coordinates for Android and iOS.

### ISSUE THREAD

**Issue by muhammadazwa** [Baseflow/flutter-geolocator#404]
## 💬 Questions and Help

For coordinate latitude 3.11097 and longitude 101.63194 the placemarkFromCoordinate gives me:

iOS:
<img width="551" alt="Screenshot 2020-03-11 at 10 49 35 AM" src="https://user-images.githubusercontent.com/6456413/76389486-49acbe00-63a6-11ea-8802-e42e33487153.png">
<img width="341" alt="Screenshot 2020-03-11 at 10 54 30 AM" src="https://user-images.githubusercontent.com/6456413/76389488-4addeb00-63a6-11ea-8cd5-9e0cc84c4241.png">

While Android (this is the correct address):
![Annotation 2020-03-11 105436](https://user-images.githubusercontent.com/6456413/76389503-56311680-63a6-11ea-94de-b2d4090a2d24.jpeg)
![Annotation 2020-03-11 105526](https://user-images.githubusercontent.com/6456413/76389507-57624380-63a6-11ea-82ab-a3d099d66f9b.jpeg)

What causing the differences of placemark between iOS and Android devices albeit having the same coordinates?

**Comment by SharksT** [comment]
I have the same issue

**Comment by mvanbeusekom** [comment]
The reason this happens is that per platform we use the recommended geocoding API's and they return different results.

- On Android we use the [Geocoder](https://developer.android.com/reference/android/location/Geocoder) API provided by Google;
- On iOS we use the [CLGeocoder](https://developer.apple.com/documentation/corelocation/clgeocoder) API provided by Apple.

You would get similar results if you would lookup the coordinates using Google Maps or Apple Maps.

**Comment by KrishnendraPrakash** [comment]
I have same issue, while Reverse geocoding to convert the latitude and longitude coordinates to a readable address.
 **placemarkfromcoordinates**. return different address.
