### ISSUE TITLE
App crashes when revoking location permissions from Android Settings

### ISSUE THREAD

**Issue by ad-on-is** [Baseflow/flutter-geolocator#406]
Steps to reproduce.

1. Grant location permission
2. App works
3. Move app to the background, open app info from Android Settings and revoke location permission
4. App crashes

Any workaround to prevent the crash?

**Comment by estevez-dev** [comment]
As I know this is expected behavior for Android OS. It close application anytime you revoke any permission on it.

**Comment by mvanbeusekom** [comment]
I have trouble finding official documentation regarding this issue. However according to some StackOverflow answers @estevez-dev is correct that the Android OS will terminate your app when permissions are revoked:

- https://stackoverflow.com/questions/32718933/broadcast-action-on-permission-change-in-android-m
- https://stackoverflow.com/questions/56362944/android-revoke-permissions-when-app-is-running-can-i-recover-the-app

I will be closing this issue now. However if you find documentation stating this shouldn't be the correct behavior please feel to post it here and I will reopen the issue.

**Comment by flaviobejkoLH** [comment]
I had the same issue and solved it by adding this on MainActivity.java:

```
 @Override
  protected void onCreate(Bundle savedInstanceState) {
    RNBootSplash.init(this); // ⬅️ initialize the splash screen
    // Check for permissions at app launch
    if (arePermissionsGranted()) {
      super.onCreate(savedInstanceState);
    } else {
      super.onCreate(null);
    }
  }
  
  private boolean arePermissionsGranted() {
    // Check for the required permissions
    if (Build.VERSION.SDK_INT >= 23) {
      int cameraPermission = checkSelfPermission(Manifest.permission.CAMERA);
      int locationPermission = checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION);
      int notificationPermission = checkSelfPermission(Manifest.permission.RECEIVE_BOOT_COMPLETED);

      return cameraPermission == PackageManager.PERMISSION_GRANTED
              && locationPermission == PackageManager.PERMISSION_GRANTED
              && notificationPermission == PackageManager.PERMISSION_GRANTED;
    } else {
      return true;
    }
  }
```

**Comment by ShumailaAshiqHussain** [comment]
hi @mvanbeusekom, i just checked on whatsapp and instagram app, they are working fine when i disable any permission on app settings. so in our flutter app that app kill behavior shouldn't happen.
