### ISSUE TITLE
Update docs for old flutter projects to add flutterEmbedding

### ISSUE THREAD

**Issue by apgapg** [Baseflow/flutter-geolocator#408]
## 🏗 Enhancement Proposal

Recently my permissions were not giving callback on android when i click allow on Location permission dialog ie 
`final permission = await LocationPermissions().requestPermissions();`
It hanged on this line forever until i kill and restart app.

Finally after creating flutter new project i see embedding was missing in manifest ie 
`  <meta-data
            android:name="flutterEmbedding"
            android:value="2" />`
and also this in MainActivity.java
`@Override
    public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
`
### Pitch

After i put the above code the permission callback started working.
Hence please add these embedding docs to make things clear and prevent such untraceable issues for old projects

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [#] :robot: Android

**Comment by mvanbeusekom** [comment]
this has been added since version 5.3.x under the Android section in the readme file
