### ISSUE TITLE
Where Can I find the attributes related to a placemark

### ISSUE THREAD

**Issue by divided7** [Baseflow/flutter-geolocator#410]
I only know 2-3 placemark attributes and wanted to know if I can get more information about a location by some other placemark methods or attributes.

**Comment by divided7** [comment]
Also, if I were to get close matches of an address supplied to the placemarkfrom address function, can i make a custom suggestion widget? Is there any way I can do so?

**Comment by andreystavitsky** [comment]
Look at lib/models/placemark.dart
