### ISSUE TITLE
Can't get location updates or icon, on Emulator (works on real phone)

### ISSUE THREAD

**Issue by ibrierley** [Baseflow/flutter-geolocator#411]
### Expected behavior

Location enabled and get gps position

### Reproduction steps

Try running a stream in an emulator

### Configuration

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_GB.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.6)
[✓] Connected device (2 available)

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

I have a very simple test...

positionStream = Geolocator().getPositionStream(locationOptions).listen((position) {
  print("$position");
}

This does work on my normal mobile phone. The location icon comes on etc.

On the avd emulator, randomly it pops up a dialog, "enable all the time, enable just for this app". 
No matter what I do, the location icon on the emulated phone, never comes on, and it never receives updates from the stream.

It has worked once, but I just can't get the location icon to come on (to give a hint that it will work).

If I check the permission via the gelocator plugin, it shows granted and enabled.

Sometimes I also get another error Unhandled Exception: PlatformException(ERROR_ALREADY_REQUESTING_PERMISSIONS)

Which I've searched the issues on, and it implies as it says, it's already waiting. However, this stream is only added once in an initState, so I don't know why it would be coming up with that error.

I'm trying it on an emulated Pixel 2 API 24, and Nexus 5x 29

**Comment by mvanbeusekom** [comment]
Personally I have no problems simulating position updates using the Android emulator (Nexus 5x API 29). You do however have to playback a KML file to make sure the emulator knows which positions it should emulate (you can find instructions here: https://support.google.com/mymaps/answer/3109452?co=GENIE.Platform%3DDesktop&hl=en). 

Can you confirm you tried this?

**Comment by ibrierley** [comment]
Thanks.
Yes, I've used a downloaded file to test that emulates the route, and updates the position on the emulator. It just doesn't get the location icon going on the emulator (it did work once, but no idea what was different). I don't quite understand why sometimes it shows a permissions dialog screen and othertimes it doesn't as well.

If I turn on google maps, the location icon comes on, and the map updates with the moving location, so I think the emulator location side is working ok.

**Comment by ibrierley** [comment]
Looks related to https://github.com/Baseflow/flutter-permission-plugins/issues/29
Have updated minsdkversion to 29 and looks to be working!

**Comment by ibrierley** [comment]
Re-opening, as it's doing it again. It popped up "Unhandled Exception: PlatformException(ERROR_ALREADY_REQUESTING_PERMISSIONS, A request for permissions is already running" then it won't work again.

As mentioned before, it's just he getPositionStream in the initState() method.

Maybe it doesn't get cancelled/disposed of or something ? I do positionStream.cancel(); it in the dispose method.

**Comment by okayfine** [comment]
This support article will help you understand more.
https://support.google.com/android/answer/3467281?hl=en
If a user has switched off location even on an iPhone, you won't get the location. Usually, we write an alert to persuade the user to switch it on. This is designed to protect the user from malicious threats.

**Comment by mvanbeusekom** [comment]
Should be fixed in version 6.0.0
