### ISSUE TITLE
Location off => GeolocationStatus.granted

### ISSUE THREAD

**Issue by dekadevelop** [Baseflow/flutter-geolocator#414]
### Expected behavior
if I turn off the location on my device I should receive **GeolocationStatus.disabled** with `geoLocator.checkGeolocationPermissionStatus()`

**Version:**  ^5.3.0

**Platform:** 
- [ x ] :robot: Android

**Comment by mvanbeusekom** [comment]
@dekadevelop this actually not correct. According to the Android guidelines you should still be able to request permissions for services even when they are not enabled. So we have updated our plugin to match these guidelines:

https://developer.android.com/distribute/best-practices/develop/runtime-permissions
https://developer.android.com/training/permissions/requesting

You can request the service status using the `Geolocator().isLocationServiceEnabled()` method if you need to check if the location services are enabled or not. The `Geolocator().checkGeolocationPermissionStatus()` will always return the current permission status independent on the service status.

**Comment by dekadevelop** [comment]
Great,
I just didn't find that method in the Readme page,

thank you very much, :)

**Comment by xJon** [comment]
@mvanbeusekom The Readme page states this:
![Screenshot_1](https://user-images.githubusercontent.com/8945347/79910566-9f559b00-8427-11ea-86b0-f2127596f360.png)

**Comment by purutechno** [comment]
The permission being asked at the runtime simple doesn't work even if the user presses allow button when GPS is not turned on. I expect the plugin provide the user option to enable the location service and get the coordinates.
This simply doesn't work!

           Geolocator geolocator = Geolocator()..forceAndroidLocationManager = true;
      Position position = await geolocator.getCurrentPosition(
          desiredAccuracy: LocationAccuracy.high);

**Comment by mvanbeusekom** [comment]
@purutechno I have added support to automatically enable location services in the latest release of the geolocator (version 6.0.0-rc.4). 

However this only works for Android devices using  Google Play Services (so you should not use `forceAndroidLocationManager = true`). The `LocationManager` and iOS SDK’s simply don’t support this feature.
