### ISSUE TITLE
using  geocoder/geolocator some of the addresses does not provide latitude and longitude in IOS only

### ISSUE THREAD

**Issue by navneetkachhadiya77** [Baseflow/flutter-geolocator#417]
Exception has occurred.
PlatformException (PlatformException(ERROR_GEOCODING_ADDRESS, The operation couldn’t be completed. (kCLErrorDomain error 8.), null))

**Comment by masumgandhi** [comment]
The same issue is with me. Does anyone have any solution??

**Comment by DeCodeR-97** [comment]
There are already a few issues covering this problem, however, I think nobody found a solution/fix yet. As a workaround you could use Google‘s Geocoding API (Google Maps Platform).
https://developers.google.com/maps/documentation/geocoding/start

**Comment by christocracy** [comment]
Reverse-geocoding is a task best performed by the server in a queued background job.  Why must it be performed on client?

**Comment by mvanbeusekom** [comment]
As mentioned by @christocracy reverse-geocoding is best performed on the server. However we indeed do provide access to the default implementations provided by the operating systems of the devices you are using (if available). The default implementation do have their limits do. In this case you are most likely running into the rate limit provided by Apple for using their Geocoding features (more information [here](https://developer.apple.com/documentation/corelocation/clgeocoder)). 

If this is an issue for you, you'd probably have to switch to a paid solution (for example Google's Geocoding API as suggested by DeCodeR-97). And preferably you would implement this in your own backend so you can keep things in control. There are however SDKs available to use the API's directly from the device.
