### ISSUE TITLE
Build.gradle not working 

### ISSUE THREAD

**Issue by uzairleo** [Baseflow/flutter-geolocator#428]
## 🐛 Bug Report

Hi there actually i m trying to implement the flutter geolocator with map view but its giving men an error regarding `android build.gradle` file here is the error can u plz fix this.
![Screenshot (949)](https://user-images.githubusercontent.com/52172428/80592858-94a79100-8a39-11ea-84a6-3c11c717550e.png)

### Configuration

**Version:** 1.x

**Platform:** 
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
@uzairleo are you sure this is related to our "geolocat**OR**" plugin? What I can see from your screenshot is that the Gradle is complaining about a project called "geolocat**ION**" which is a different Flutter plugin (which you can find here: https://github.com/loup-v/geolocation).
