### ISSUE TITLE
Module limitations without API key

### ISSUE THREAD

**Issue by lc-heia** [Baseflow/flutter-geolocator#431]
I noticed that I don't have to give an API key to the module to work. According the the google services costs, functionnalities like Geocoding are not free.
Does Geolocator have any limitations on the use of Google's services ? For exemple, if I need to execute 100000 requests of geocoding per month, will it work correctly ?
Thank you.

**Comment by mvanbeusekom** [comment]
Hi @lc-heia, it indeed will not work in all cases. In general we are currently supporting the platform specific geocoding SDKs. This means that on Android devices we use the `Android.Location.Geocoder` API (details [here](https://developer.android.com/reference/android/location/Geocoder)) and on iOS devices we use the `CLGeocoder` API (part of the Core Location framework, details [here](https://developer.apple.com/documentation/corelocation/clgeocoder)).

This means that the API is not available on all Android devices. It is only available on devices that have the Google Play Services installed (which contains the Android Geocoder backend services). When this is available on the device you are good to go and you should have no problems (assuming the device has a internet connection).

On iOS the `CLGeocoder` framework is always available, but is rate limited. This means you could get an exception when the maximum limit (which is unfortunately not documented) is reached.
