### ISSUE TITLE
The plugin geolocator could not be built

### ISSUE THREAD

**Issue by nandalalsun** [Baseflow/flutter-geolocator#432]
## The plugin geolocator failed to build.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'geolocator'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

**Version:** 5.0.*

**Comment by mvanbeusekom** [comment]
@nandalalsun looks like you have a problem with your development environment which doesn't know where to locate the Android SDK. 

This should not be something that is specific to the "geolocator" plugin and my guess is it will also happen with other Flutter or Android projects. Is this something you can test for us? For example by creating a new Flutter app and immediately try to build and run it?
