### ISSUE TITLE
Add assertions to distanceBetween method

### ISSUE THREAD

**Issue by rodriigovieira** [Baseflow/flutter-geolocator#437]
## 🏗 Enhancement Proposal

I believe it would be interesting to add some assertions to the `distanceBetween` method, because when no value is provided (which means, `null` is provided), an unexpected behavior can occur.

 When I provided null for the initial location, the application simply crashed, without providing any other additional debugging details.

### Platforms affected (mark all that apply)
- [X] :iphone: iOS
- [X] :robot: Android

I'm not really sure if this is an issue, a feature request, or just an enhancement proposal. Please correct me if I chose the wrong type.

**Comment by mvanbeusekom** [comment]
Thank you for the feedback. This is a good point and definitely will improve the method. I am open for pull requests or will definitely take is into consideration for the next big release I am working on.

**Comment by mvanbeusekom** [comment]
As of version 6.0.0 the geocoding features have been removed from the geolocator plugin and are now part of their own [geocoding](https://pub.dev/packages/geocoding) plugin.
