### ISSUE TITLE
PlatformException(ERROR_REVERSEGEOCODING_LOCATION, The operation couldn’t be completed. (kCLErrorDomain error 8.), null)

### ISSUE THREAD

**Issue by tongyuling** [Baseflow/flutter-geolocator#442]
in iOS

PlatformException(ERROR_REVERSEGEOCODING_LOCATION, The operation couldn’t be completed. (kCLErrorDomain error 8.), null)

**Comment by mvanbeusekom** [comment]
This error means that Apple does not know about any address on the supplied location. More information can be found [here](https://developer.apple.com/documentation/corelocation/clerror/kclerrorgeocodefoundnoresult) and [here](https://developer.apple.com/documentation/corelocation/clgeocoder?language=objc).

On iOS we rely on Apple to do the translation, unfortunately their services are a bit limited.

**Comment by BasanthVerma** [comment]
It appears that this is now happening on locations that used to work before.

**Comment by mvanbeusekom** [comment]
@BasanthVerma it didn't occur to me earlier but this is very well possible. The iOS backend service is rate limited (the free version) and if you exceed the rate you could also receive this error.

**Comment by BasanthVerma** [comment]
Oh I see. It's sad that there is no mention of what the rate can be on Apple's documentation. I'm also finding other Apple Map services responding very slow or timing out on the Map app, I think some of their services are down right now.

**Comment by maah75** [comment]
I have same issue with both android and IOS

**Comment by Jigneshiosdeveloper** [comment]
I fixed this error below.

https://youtu.be/U_2XMFkZOBc
