### ISSUE TITLE
Geolocator is not supporting in gradle 3.5.0

### ISSUE THREAD

**Issue by krishna9626** [Baseflow/flutter-geolocator#443]
## Geolocator is not supporting on gradle 3.5.0 or any specified version should be used?

getting error as  "The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
The following dependencies do not satisfy the required version:
project ':google_api_availability' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.0"

kotlinversion = '1.3.50'
gradle:3.5.0
geolocator: '^2.1.1'

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
This issue will be solved in version 6.0.0 (version 6.0.0-rc.4 is out now if you want to verify).
