### ISSUE TITLE
PlatformException, ERROR_ALREADY_REQUESTING_PERMISSIONS on flutter location permission

### ISSUE THREAD

**Issue by ahmedminhaj** [Baseflow/flutter-geolocator#450]
For details please check below link:

https://stackoverflow.com/questions/62128258/platformexception-error-already-requesting-permissions-on-flutter-location-permi

occur PlatformException on location permission:
`PlatformException (PlatformException(ERROR_ALREADY_REQUESTING_PERMISSIONS, A request for permissions is already running, please wait for it to finish before doing another request (note that you can request multiple permissions at the same time)., null))
`
The exception occurs on `Geolocator()` call:
 `Position position = await Geolocator().getCurrentPosition(
        desiredAccuracy: LocationAccuracy.high);`

how to solve this exception?

**Comment by mvanbeusekom** [comment]
Can you verify if your application supports the latest version of the Android Activity (detailed migration guide can be found [here](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects)). 

If that doesn't help, please check if your are not requesting the geolocation directly from with in the `build` method if the user didn't grant permissions yet. It is important to make sure the user has provided permissions before you try getting the location inside the build method.

It would also be helpful if you can let us know if this occurs on Android, iOS or both.

**Comment by juanjoserodrigolazaro** [comment]
same problem on ios!

**Comment by poumason** [comment]
I also get the same problem.
But I modify code and work for me, following:

```
var position = await geolocator.getCurrentPosition(
      locationPermissionLevel: GeolocationPermission.locationWhenInUse,
      desiredAccuracy: LocationAccuracy.low);
```

**Comment by alexmazza** [comment]
I think this is related to [https://github.com/Baseflow/flutter-geolocator/issues/430](url) The problem is the Google Maps plugin. I'm not getting a permission dialog with getPositionStream() so I tried to use LocationPermissions().requestPermissions() directly and now I get ERROR_ALREADY_REQUESTING_PERMISSION . I think the request comes from the Google Maps plugin but it doesn't show I dialog until I navigate to the router with the map in it.

**Comment by TylerSchmidtke** [comment]
I noticed this issue when I didn't have my `Info.plist` set up correctly with the app's permissions request descriptions as noted in the [pub.dev](https://pub.dev/packages/geolocation) documentation for the package. Updating the `Info.plist` resolved the issue. Perhaps that was the issue?

**Comment by mvanbeusekom** [comment]
Seems some solutions have been provided. The latest version [6.0.0-rc.3](https://pub.dev/packages/geolocator/versions/6.0.0-rc.3) also has improved permission handling and should work better with other plugins (like Google Maps). Please give it a try.

**Comment by kimgysen** [comment]
Not solved for me on the lastest version. Have you tried it before closing? https://stackoverflow.com/questions/66504726/flutter-geolocator-permissionrequestinprogressexception
