### ISSUE TITLE
please update the dependency location_permissions to use v2 embedding

### ISSUE THREAD

**Issue by lslv1243** [Baseflow/flutter-geolocator#452]
After I updated to Flutter 1.17 I can no longer use this lib with Android, it crashes. I stopped using the pubdev version and started using master cause it has the v2 embedding for Android. But it still crashes because there is a dependency that still uses v1 embedding. Please update this dependency. I made a pull request: https://github.com/Baseflow/flutter-permission-plugins/pull/42

**Comment by mvanbeusekom** [comment]
I have just released Geolocator version 5.3.2 which now uses version 3.0.0 of the `location_permissions` plugin which contains your pull-request.
