### ISSUE TITLE
Can't catch location services disabled exception on iOS

### ISSUE THREAD

**Issue by ErnestoCuesy** [Baseflow/flutter-geolocator#454]
For some reason the condition below is not triggered when location services in iOS are disabled. There's only a quick dialog flashing from iOS saying that location services are disabled but disappears in 1 second and the app crashes. I've tried to catch it with the code below but it just doesn't get to it.
Any ideas?

```
  _determineCurrentLocation() async {
    _geolocator = Geolocator();
    bool locationServiceIsEnabled = await _geolocator.isLocationServiceEnabled(); 
    if (locationServiceIsEnabled) {
      _geolocator.getCurrentPosition(
          desiredAccuracy: LocationAccuracy.best
      ).timeout(
          Duration(
              seconds: 30
          ),
          onTimeout: () {
            print('Geolocator timed out');
            return;
          }).then((position) async {
        if (position != null) {
          _currentLocation = position;
          print(
              'Current location: ${_currentLocation.latitude} : ${_currentLocation
                  .longitude}');
          setState(() {
            _currentLocation = position;
          });
        } else {
          await PlatformExceptionAlertDialog(
            title: 'Could not determine location',
            exception: PlatformException(
              code: 'NO_LOCATION_SERVICE',
              message: 'Please make sure location services are enabled.',
              details: 'Please make sure location services are enabled.',
            ),
          ).show(context);
          exit(0);
        }
      });
    }else {
      await PlatformExceptionAlertDialog(
        title: 'Location services are disabled',
        exception: PlatformException(
          code: 'NO_LOCATION_SERVICE',
          message: 'Please make sure location services are enabled.',
          details: 'Please make sure location services are enabled.',
        ),
      ).show(context);
      exit(0);
    }
  }

```

**Comment by mvanbeusekom** [comment]
Do you have the necessary permissions listed in your `Info.plist` file? iOS does terminate your App (without warning or exception) when trying to access location services if you don't have the required permissions listed in your `Info.plist`. I can imagine this also happens even when the location services are not enabled, although I am not sure it would be worth to quickly give it a try.

**Comment by ErnestoCuesy** [comment]
Hi there! Here's how the relevant permissions in Info.plist look like. If location services are enabled the permissions are asked correctly. Thanks.

    <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
    <string>Your current location will be used to find restaurants advertising on this app.</string>
    <key>NSLocationAlwaysUsageDescription</key>
    <string>Your current location will be used to find restaurants advertising on this app.</string>
    <key>NSLocationWhenInUseUsageDescription</key>
    <string>Your current location will be used to find restaurants advertising on this app.</string>

**Comment by mvanbeusekom** [comment]
Yes sorry, I read the code wrong my apologies. I have updated my earlier question, can you have a look if that helps?

**Comment by ErnestoCuesy** [comment]
Hi Maurits, no problem. Yes, I also tried by commenting out the exit(0) but makes no difference. None of the code in that method is executed if location services are disabled.

**Comment by mvanbeusekom** [comment]
Good to know, but that means I am kinda out of ideas from the top of my head. I will try and see if I can reproduce the issue and see if that will give me more insight into what is happening. This will take some time so please bear with me.

**Comment by ErnestoCuesy** [comment]
Ok great, thanks! And by the way... in Android the method is triggered properly and works fine if location services are disabled. It's only iOS where I have the problem.

**Comment by mvanbeusekom** [comment]
I have been testing a bit with the following simplified version (since I don't have a implementation of `PlatformExceptionAlertDialog`):

```dart
import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Geolocator _geolocator;
  String _currentLocation = 'Not available';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(_currentLocation),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _determineCurrentLocation,
        tooltip: 'Determine current location',
        child: Icon(Icons.location_searching),
      ),
    );
  }

  _determineCurrentLocation() async {
    String message = 'null';
    _geolocator = Geolocator();
    bool locationServiceIsEnabled =
        await _geolocator.isLocationServiceEnabled();
    if (locationServiceIsEnabled) {
      _geolocator
          .getCurrentPosition(desiredAccuracy: LocationAccuracy.best)
          .timeout(
        Duration(seconds: 30),
        onTimeout: () {
          message = 'Geolocator timed out';
          return;
        },
      ).then((position) {
        if (position != null) {
          message =
              'Current location: ${position.latitude} : ${position.longitude}';
        } else {
          message = 'Could not determine location';
        }

        print(message);
          setState(() {
          _currentLocation = message;
        });
      });
    } else {
      message = 'Location services are disabled';
    }

    print(message);
    setState(() {
      _currentLocation = message;
    });
  }
}
```

In the iOS simulator this works without any problems. I correctly displays the `Location services are disables` message if I disable the location services. Otherwise it will fetch the current location and display the coordinates. This lead me to believe it does have something to do with either the `exit(0);` method or the `PlatformExceptionAlertDialog`. Maybe you can use this code as a starting point to try and reproduce the behavior?

**Comment by ErnestoCuesy** [comment]
Maurits - thanks. You're right. It's the exit statement. What makes it confusing is that it works perfectly on Android. But in any case is not very elegant to kill the app like that so I'm refactoring to return some error widgets instead. Thanks a lot for your time and help!

**Comment by mvanbeusekom** [comment]
Glad I could help ;)
