### ISSUE TITLE
getCurrentPosition returns same location in Android even location changes

### ISSUE THREAD

**Issue by yacinegithub** [Baseflow/flutter-geolocator#457]
## 🐛 Bug Report

getCurrentPosition returns same location in Android even location changes

Configuration
compileSdkVersion i tried both 28 and 29
Version: 1.0.0+1
geolocator: ^5.3.2+2
Platform:

 🤖 Android

**Comment by n0tc0ding** [comment]
You should use other plugin (Location was the best for me). This issue have been for a long time, last time i did this.

Apperently this fixed the issue for me but I am not sure about the implications so use it at your own risk.
Go to the folder (your version may be differente for example: 5.1.3):
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\geolocator-5.1.2\android\src\main\java\com\baseflow\geolocator\tasks

open the file:
LocationUpdatesUsingLocationManagerTask.java

and in the line 70 change:
mBestLocation = locationManager.getLastKnownLocation(mActiveProvider);
to
mBestLocation = null;

I hope it helps you

**Comment by mvanbeusekom** [comment]
We have solved this issue in our latest version 6.0.0-rc.3 (final release will be soon).
