### ISSUE TITLE
AdministrativeArea iso code

### ISSUE THREAD

**Issue by krel024** [Baseflow/flutter-geolocator#458]
## 🚀 Feature Requests

Would be very nice to add also `isoAdministrativeArea` to `Placemark`. In order to get the user state base on his current location work with `Strings` can be a dirty way to do it.

**Comment by mvanbeusekom** [comment]
@krel024 unfortunately such a property is not returned by the geocoding services on Android (see [Address](https://developer.android.com/reference/android/location/Address)) or iOS (see [CLPlacemark](https://developer.apple.com/documentation/corelocation/clplacemark)).

Which means we would have to resolve it the same way you do it now and in that case it would be better to leave this to the individual developers.
