### ISSUE TITLE
Namespacing - clash with location plugin

### ISSUE THREAD

**Issue by giorgio79** [Baseflow/flutter-geolocator#460]
Having both geolocator and location plugin gives this error

https://pub.dev/packages/location
https://pub.dev/packages/geolocator

```
Compiler message:
lib/screens/1_GetLocation.dart:17:46: Error: 'LocationAccuracy' is imported from both 'package:geolocator/geolocator.dart' and 'package:location_platform_interface/location_platform_interface.dart'.
        .getCurrentPosition(desiredAccuracy: LocationAccuracy.high)

```

### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
Hello @giorgio79, 

You could solve this issue by specifying a prefix (using the `as` statement) when you import the packages in your code. This will allow you to differentiate between specific implementations in your code. 

```
import 'package:geolocator/geolocator.dart' as geo;

// When you want to use elements from the geolocator you add the prefix
final currentPosition = await geo.Geolocator().getCurrentPosition(desiredAccuracy: geo.LocationAccuracy.high);
```
