### ISSUE TITLE
Get the location updates after each 1 minute? 

### ISSUE THREAD

**Issue by usamamashkoor** [Baseflow/flutter-geolocator#462]
Hi, I want to create an app like Uber, and I want to get the location updates of the user after each 1 minute even if the app is running in the background is there a way to do this using your library?

I want the solution to work for both Android and Ios.

kindly let me know Thanks.

**Comment by mvanbeusekom** [comment]
Hello, unfortunately retrieving location updates in the background is not (yet) supported by this plugin.

**Comment by usamamashkoor** [comment]
@mvanbeusekom can you please suggest, How I can achive this if kind of help will be appreciated greatly?

**Comment by mvanbeusekom** [comment]
There is some documentation on the Flutter website: https://flutter.dev/docs/development/packages-and-plugins/background-processes

I have read through it a few times but haven't been able to translate it yet into a feature that could be applied to the plugin.

**Comment by usamamashkoor** [comment]
@mvanbeusekom Thanks man for sharing it :)
