### ISSUE TITLE
Is it possible re-ask location permission after user denied

### ISSUE THREAD

**Issue by inshaf** [Baseflow/flutter-geolocator#464]
Hi, thanks for this wonderful plugin. 

Let's say first time user denied the permission with "don't show this option again". But later user wanted to allow the app to get the location. 

If there is an option for this, I can place a button so that when user click it, I can show the permission modal again to pick the location

**Comment by mvanbeusekom** [comment]
Hello Inshaf,

No this is not possible unfortunately. Once the user has selected "don't show this option again" the operating system will make sure the permission dialog is not shown anymore for that App. The only way to handle this situation is to manually alert the user and ask them to go into the application settings and allow your app access to the location services.

The geolocator plugin has a helper method called `openAppSettings` which will redirect the user into the app settings page, so you can use this to make it a little bit easier for the user to navigate to the correct settings.
