### ISSUE TITLE
Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference

### ISSUE THREAD

**Issue by uncoded-decimal** [Baseflow/flutter-geolocator#465]
## 🔙 Regression
[log_output.txt](https://github.com/Baseflow/flutter-geolocator/files/4890143/log_output.txt)

### Old (and correct) behavior
Previously it was working fine. Tested it on a physical Android device and I could get the location.

### Current behavior
The app stops working and the log output is as in the file attached. Doesn't work neither on the real device not the emulator.

### Reproduction steps
The only difference I made was update my Android Studio.

### Configuration

**Version:** 5.3.2+2

**Platform:** 
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @uncoded-decimal, I see you are receiving this error while trying to use the geocoding features. Maybe you can try our new `geocoding` plugin which is a completely new plugin specifically designed for handling geocoding features and contains several bug fixes. The next major release of the geolocator will drop the geocoding features and we will forward users to this new plugin.

You can find the plugin at these locations:

- Pub.dev: https://pub.dev/packages/geocoding
- Github: https://github.com/baseflow/flutter-geocoding
