### ISSUE TITLE
locationPermissionLevel not taken into account on Android

### ISSUE THREAD

**Issue by kightsonsanom** [Baseflow/flutter-geolocator#468]
## 🐛 Bug Report

After specifying `locationPermissionLevel` 

![image](https://user-images.githubusercontent.com/24854180/87431969-ab489780-c5e7-11ea-9451-07e3288d1e9c.png)

 The plugin still asks to use permissions all the time on Android.

### Expected behavior

Location permission dialog is not asking to allow permission all the time.

### Reproduction steps

invoke `getCurrentPosition` method and specify `locationPermissionLevel` parameter. 
Permission dialog will ask about allowing location all the time.

### Configuration

**Version:** ^5.3.2+2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @kightsonsanom, 

I am currently working on a major new release which will also solve this problem, hope you have a little bit more patience. Thanks for reporting though.

**Comment by kightsonsanom** [comment]
@mvanbeusekom It works as expected, thank you!
