### ISSUE TITLE
checkGeolocationPermissionStatus is not giving updated status

### ISSUE THREAD

**Issue by azeemgujjar** [Baseflow/flutter-geolocator#470]
## 🐛 Bug Report

To test this package, i create simple example

```
void getLocation() async {
    try {
      final Geolocator geolocator = Geolocator();
      geolocator.forceAndroidLocationManager = true;
      GeolocationStatus geolocationStatus = await geolocator.checkGeolocationPermissionStatus();
      print(geolocationStatus);
    } catch (error) {
      print(error.message);
    }
  };
```

```
@override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: RaisedButton(
          onPressed: () {
            getLocation();
          },
          child: Text('Get Location'),
        ),
      ),
    );
  }
```

### Expected behavior

Every time user turn-on or turn-off location service on mobile this function should return latest status of device instead of last stored behavior.

### Reproduction steps
First time when i run its working fine and shows me response: `GeolocationStatus.granted`
I keep my application in foreground, now i turn off location 
and again i tap button to fetch status, and still it is showing me this response

```
I/flutter (22047): GeolocationStatus.granted

D/LocationManager(22047): removeUpdates listener=com.baseflow.geolocator.tasks
```

**Version:** ^5.3.2+2

**Platform:** 
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @azeemgujjar, 

Seems like you are simple disabling the location services and not retracting permissions to access the device's location. Note that they are two separate things:

1. You can disable the location services which means that the device will no longer provide location updates but doesn't affect the permissions granted to Apps to access the location. Using the Geolocator you can check if the location services are enabled by calling the `Geolocator().isLocationServiceEnabled()` method;
2. To be allowed to access the device's location the App needs explicit permissions from the user of the device. You can request permissions to access the device's location even when the location services are disabled. In case you have permissions but the location services are disabled you would still be able to request the last known location and you can alert the user to turn on the location services so the App will start receiving location updates. In you code example above you only request and check for permissions, you do not check if the location services are enabled or disabled.

Hope this help.

**Comment by mvanbeusekom** [comment]
I noticed that the documentation doesn't mention the `isLocationServiceEnabled()` method as part of the API description. This is something I will fix. 

I am currently working hard (in my spare time) on a new major release and will ensure that the documentation is up to date and complete.
