### ISSUE TITLE
Not working without google services

### ISSUE THREAD

**Issue by Sorunome** [Baseflow/flutter-geolocator#473]
## 🐛 Bug Report
This package seems to be unable to fetch the location if google services are unavailable, even though other apps, such as osmand, have no problem doing so.

### Expected behavior
It should fetch the location

### Reproduction steps
Code like
```dart
    print('=============');
    Geolocator geolocator = Geolocator()..forceAndroidLocationManager = true;
    Position position  = await geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.high);
    print('got location');
    print(position.toString());
```
Will only print the `=============`, and thus never complete the future. if you try without `forceAndroidLocationManager = true` you get the same results.

If you also print the output of `isLocationServiceEnabled` and `checkGeolocationPermissionStatus` you will also see that the location services are enabled *and* the permissions are granted.

### Configuration

**Version:** 5.3.2+2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by lvlira** [comment]
This line "Position position  = await geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.high);" give me that error:
"type 'Future<dynamic>' is not a subtype of type 'LatLng'"

**Comment by mvanbeusekom** [comment]
@Sorunome, please give our new version [6.0.0-rc.3](https://pub.dev/packages/geolocator/versions/6.0.0-rc.3) a try. It fixes a lot of issues with acquiring the location.

**Comment by oguibueno** [comment]
What happen if the device does not have Google Play Services?

**Comment by mvanbeusekom** [comment]
@oguibueno when the device doesn’t have Google Play Services installed and the location services are disabled the geolocator will throw an exception (as mentioned in the earlier comment).

Automatic resolution is only supported on Android  and only with Google Play Services. You will also get the exception if you pass in `true` for the `forceAndroidLocationManager` parameter as it Will bypass the Google Play Services (even if it is installed).

**Comment by Sorunome** [comment]
This issue unfortunately still persists with `7.4.0` and a simple try...catch shows that there is no error thrown at all:

```dart
    print('=============');
    try {
      Position position  = await Geolocator.getCurrentPosition(
        desiredAccuracy: LocationAccuracy.best,
        forceAndroidLocationManager: true,
      );
      print('got location');
      print(position.toString());
    } catch (e, s) {
      print('+++++++++++++++++');
      print(e);
      print(s);
    }
    ```

**Comment by mvanbeusekom** [comment]
Hi @Sorunome, the exception is only thrown when location services are disabled. When the location services are enabled the plugin will wait for a location fix. When using a `LocationAccuracy.high` or higher, the Android `LocationManager` will use the GPS provider to try and get a fix, especially when indoors or not directly in contact with a clear sky this can be difficult and result in longer wait times (or no fix at all). 

More detailed explanation can be found here: https://github.com/Baseflow/flutter-geolocator/issues/773#issuecomment-883311979

**Comment by Sorunome** [comment]
Got it working now, thanks a lot 👍

**Comment by jahnli** [comment]
@Sorunome   No Google services are now supported ？

**Comment by Sorunome** [comment]
> @Sorunome No Google services are now supported ？

yeah, it seems to be working without them here

**Comment by jahnli** [comment]
It will prompt google play is missing before，Has that been solved now @Sorunome

**Comment by jahnli** [comment]
It will prompt google play is missing before，Now whether the problem is solved，Can provide a code reference @Sorunome

**Comment by Sorunome** [comment]
@jahnli sure, over here: https://gitlab.com/famedly/fluffychat/-/blob/main/lib/pages/send_location_dialog.dart#L38-72

**Comment by jahnli** [comment]
![image](https://user-images.githubusercontent.com/20943608/129444677-736ad52d-7f3a-47fa-97e8-5acbcc2ceeaa.png)
It still doesn't seem to work

**Comment by jahnli** [comment]
@Sorunome

**Comment by mvanbeusekom** [comment]
Hi @jahnli, 

This warning is generated by Android it self since the geolocator is automatically checking if Google Play Services are available or not when the `forceAndroidLocationManager` parameter is not set to `true`. This is done using the suggested API from Google (see details [here](https://developers.google.com/android/guides/setup#check-whether-installed) and our implementation [here](https://github.com/Baseflow/flutter-geolocator/blob/06649f48ec061526b779103430b17fd615d3dbf3/geolocator_android/android/src/main/java/com/baseflow/geolocator/location/GeolocationManager.java#L93)).

Unfortunately the `isGooglePlayServicesAvailable()` will generate the warning message that you refer to in the logs. You can safely ignore this (or add it to the exclusion list of warnings that should not be treated as errors if you build system treats warnings as errors). 

Alternatively you can always force the use of the legacy `LocationManager` SDK by providing `true` for the optional `forceAndroidLocationManager` parameter when calling the `getCurrentPosition` or `getPositionStream` methods (this is what @Sorunome is doing and hence doesn't receive the warning in the logs).

**Comment by jahnli** [comment]
@mvanbeusekom  This is a machine from China, when I try to set up forceAndroidLocationManager to true, the problem remains unresolved, still suggest Google play missing

**Comment by mvanbeusekom** [comment]
Unfortunately I don't have access to a Chinese device in China. But like I said, the message is a simple warning which can be safely ignored. 

It is just Google warning you that the Google Play Services are not available and it will fallback on legacy location services which might be not performing as good but still work (see also the links I shared earlier).

**Comment by tabooo** [comment]
Is this still unresolved? I have same error with 10.1.0
