### ISSUE TITLE
I think not working on windows ?

### ISSUE THREAD

**Issue by aTeamSolace** [Baseflow/flutter-geolocator#474]
The plugin `google_api_availability` doesn't have a main class defined in E:\flutter_installation\flutter\.pub-cache\hosted\pub.dartlang.org\google_api_availability-2.0.4\android\src\main\java\com\baseflow\googleapiavailability\GoogleApiAvailabilityPlugin.java or E:\flutter_installation\flutter\.pub-cache\hosted\pub.dartlang.org\google_api_availability-2.0.4\android\src\main\kotlin\com\baseflow\googleapiavailability\GoogleApiAvailabilityPlugin.kt. This is likely to due to an incorrect `androidPackage: com.baseflow.googleapiavailability` or `mainClass` entry in the plugin's pubspec.yaml.
If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above. Otherwise, please contact the author of this plugin and consider using a different plugin in the meanwhile.

**Comment by mvanbeusekom** [comment]
@aTeamSolace this issue should be solved in our latest release [6.0.0-rc.3](https://pub.dev/packages/geolocator/versions/6.0.0-rc.3) which no longer depends on the google_api_availability plugin.
