### ISSUE TITLE
placemarkFromCoordinates not returning complete address

### ISSUE THREAD

**Issue by gautambagla** [Baseflow/flutter-geolocator#476]
## 🐛 Bug Report

The placemark list returned by the function does not contain complete address details as in Street Address. But in the terminal, it does print the whole address (addressLines = [0:" ..."]).

getFromLocation --- return mLocationResults.get(22.6142,88.4013) = [Address[addressLines=[0:" #name, #street address line 1, #street address line 2, #locality, #admin area,#postalcode, #country"],feature=name,admin=admin area,sub-admin=sub-admin,locality=locality,thoroughfare=null,postalCode=code,countryCode=code,countryName=country,hasLatitude=true,latitude=x,hasLongitude=true,longitude=y,phone=null,url=null,extras=null]]

### Reproduction steps
_getAddressFromLatLng() async {
    try {
      List<Placemark> p = await geolocator.placemarkFromCoordinates(
          _position.latitude, _position.longitude);

      Placemark place = p[0];

      setState(() {
        _address =
        "${place.locality}, ${place.postalCode}, ${place.country}";

      });
    } catch (e) {
      print(e);
    }
  }

### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
@gautambagla we are currently rebuilding the Geolocator plugin and as part of that we have moved the geocoding functionality in it's own plugin which you can find [here](https://pub.dev/packages/geocoding).

In this new plugin we have put extra effort in exposing the missing address fields, please give it a try if you like.

**Comment by gautambagla** [comment]
MissingPluginException(No implementation found for method placemarkFromCoordinates on channel flutter.baseflow.com/geocoding)

The plugin has not been implemented, it is showing.
