### ISSUE TITLE
[Bug] getCurrentPosition() waits until GPS is activated

### ISSUE THREAD

**Issue by Ascenio** [Baseflow/flutter-geolocator#477]
### Expected behavior

When `getCurrentPosition()` is called and the GPS is disabled the Geolocator is supposed to at least throw a exception. However, if the dialog was shown before, the permissions were granted but then the GPS got disabled by the user (in the status bar), the request is enqueued. If the GPS is turned on again, then all previous requests (if the location got request more than once) get to finish, which means the requests remain queued until success (if it ever happens).

### Reproduction steps

Run the app for the first time granting GPS permission, then disable GPS in the status bar and just request the user's position.

```dart
final geo = Geolocator();
await geo.getCurrentPosition();
print("Only getting there when GPS is on again");
```

### Configuration

**Version:** 5.2.0

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android - *tested in a Xiaomi Redmi 6*

**Comment by mvanbeusekom** [comment]
@Ascenio I am working on a big new release for the Geolocator which will include this functionality inside the `getCurrentLocation` method. For now however you can manually check if the location services are enabled or not using the `isLocationServiceEnabled` method. You could update your code to:

```dart
final geo = Geolocator();
final isEnabled = await geo.isLocationServiceEnabled();

if (isEnabled) {
  await geo.getCurrentPosition();
  print("Only getting there when GPS is on again");
}
```

Hope this helps.

**Comment by DhavalRKansara** [comment]
I think you guys have provide a functionality that will ask to turn on GPS to get the current location.
