### ISSUE TITLE
Build failed after installing package

### ISSUE THREAD

**Issue by overloadcode** [Baseflow/flutter-geolocator#478]
## 💬 Questions and Help

Hello
I created a new application and I installed geolocator package `geolocator: ^5.3.2+2`
I added required permissions but after flutter run i get an error:
https://imgur.com/vzRhve5

> Execution failed for PlatformAttrTransform ..android-29\android.jar. Can't find specific file.

I have flutter 1.17, AndroidX = true 
Somebody met with this problem and solved it?

I'm working on VS Code with terminal

**Comment by mvanbeusekom** [comment]
@overloadcode this is a new issue to me. I see it is somehow failing on the location_permissions plugin. Maybe give our new [6.0.0-rc.3](https://pub.dev/packages/geolocator/versions/6.0.0-rc.3) a try, this version has no dependency on the location_permissions anymore. All permission logic is now build in.

Would be great to get your feedback.
