### ISSUE TITLE
getPositionStream not working when app paused

### ISSUE THREAD

**Issue by hussenIbrahim** [Baseflow/flutter-geolocator#482]
when app is on the screen it works well
but when app paused ,getPositionStream not triggered even getCurrentPosition getting last known position not the new position

using real device android 10
flutter channel dev, 1.21.0-7.0.pre
 geolocator: ^5.3.2+2

**Comment by mvanbeusekom** [comment]
This is correct the geolocator doesn't support running in the background. We have enhancement issue for this (see #53), but it is hard to implement and I haven't got around to it. 

Feel free to contribute, we are thinking of something similar to what is documented [here](https://flutter.dev/docs/development/packages-and-plugins/background-processes) for the geofencing solution.
