### ISSUE TITLE
400: PlatformException(INVALID_LOCATION_SETTINGS, Location settings are inadequate, check your location settings., null)

### ISSUE THREAD

**Issue by namanawasthi** [Baseflow/flutter-geolocator#483]
## 🐛 Bug Report

Not able to enable location automatically on an android device even when permission status is "GeolocationStatus.granted".

 Expected behavior: Location should get enabled automatically once permissions are allowed.

Below is the code to reproduce error:

 Future<void> getCurrentLocation() async {
    try {
      Geolocator geolocator = Geolocator()..forceAndroidLocationManager = true;
      GeolocationStatus geolocationStatus =
          await geolocator.checkGeolocationPermissionStatus();
      print(geolocationStatus);

      Position position = await geolocator.getCurrentPosition(
        desiredAccuracy: LocationAccuracy.best,
      );

      print(position.longitude);

      latitude = position.latitude;
      longitude = position.longitude;
    } catch (e) {
      print(e);
    }
  } 

Tried on android SDK 30 and on 28 not working on both.

**Geoloactor Version:** Tried 5.2.0 and above all versions

All the permissions are added to AndroidManifest.xml

**Platform:** 
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
@namanawasthi I will address this issue in our next version (6.0.0).

**Comment by thatsenam** [comment]
i am facing same problem

**Comment by mpoirier101** [comment]
getCurrentPosition(forceAndroidLocationManager: true) does not work for me anymore in 6.0.0+3...
