### ISSUE TITLE
What kind of format should the address be in when using the placemarkFromAddress() method?

### ISSUE THREAD

**Issue by yulkin2002** [Baseflow/flutter-geolocator#484]
I see in the example "Gronausestraat 710, Enschede" which I assume is "[street] [house number] [city]"
is this the required format, or can we place the house number first?
can the method take in a country or a province/state?

Thank you!

**Comment by mvanbeusekom** [comment]
Hi @yulkin2002,

Thanks for your question. I am not really sure there is a fixed format you should use. We simply forward the string query to the native geocoding implementation (Geocoder SDK on Android and CLGeocoder on iOS). They will do the parsing and translate it to the coordinates. 

The example uses the address format we use in The Netherlands (b.t.w. you are spot on with your analysis). I am pretty sure both Google and Apple will also support other formats to accommodate people world wide. Maybe you could run some simple tests?

By the way, in our next major release of this plugin we will be removing the Geocoding functionality. We have made a separate plugin which has improved features and a similar API maybe you would be interested in having a look: https://pub.dev/packages/geocoding
