### ISSUE TITLE
[iOS real devices] BackgroundLocationIndicator shows the app is using location service in background forever even when cancelling location stream explicitly when app moves into background

### ISSUE THREAD

**Issue by KrunalRGandhi** [Baseflow/flutter-geolocator#485]
## 🐛 Bug Report

Issue is seen on iOS real device only. 

I am starting location stream when app is started or resumed (In foreground). I am cancelling the stream when app is paused (moved to background). At times when the app is in background, the status bar keeps showing blue bar or pill indicating the app is using location services in background. At times it shows this indicator for couple of seconds and then disappears, which is expected behaviour on iOS as it gives grace period of coupe of seconds to application to complete it work with last location updates.

I am using didChangeAppLifecycleState method in flutter that provides app state changes. The logs show that when app is moved to background, this method is hit with state updated to "paused" and stream is cancelled.

Here is relevant code snippet:
  // User Location Stream
  startCurrentUserLocationStream() {
    currentUserLocationStream = Geolocator()
        .getPositionStream(
      LocationOptions(
        accuracy: LocationAccuracy.best,
        distanceFilter: 100, // 100 meters
        timeInterval: 120000, // 2 minutes
      ),
    ).listen((Position newPosition) {
      Provider.of<UserLocationProvider>(context, listen: false)
          .currentUserLocation = newPosition;
    });
  }

  stopCurrentUserLocationStream() {
    currentUserLocationStream?.cancel();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) async {
    super.didChangeAppLifecycleState(state);
    if (state == AppLifecycleState.resumed) {
      //  Start user location stream.
      startCurrentUserLocationStream();
    } else if (state == AppLifecycleState.paused || state == AppLifecycleState.detached) {
      // Stop location stream
      stopCurrentUserLocationStream();
    }
  }

On simulators this issue never occurs. Most of the phones I used for testing are on iOS 13.5 or higher version.

### Expected behavior
When App moves to background Location stream should be closed and BackgroundLocationIndicator should disappear after couple of seconds.

### Reproduction steps
1. Start location stream using geolocator plugin when app is started or resumed.
2. Cancel location stream when app moves to background.
3. Observe the status bar to check if BackgroundLocationIndicator remains forever or disappears after couple of seconds.

### Configuration
Pranavs-Mac-mini:loffee pranavgandhi$ flutter doctor -v
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.14.6 18G103, locale en-IN)
    • Flutter version 1.20.2 at /Users/pranavgandhi/FlutterDeveloper/flutter
    • Framework revision bbfbf1770c (5 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at ~/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11A1027
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

**Version:** 
geolocator: ^5.3.2+2

**Platform:** 
- :iphone: iOS real devices. iPhone 7, 8, 8plus, 11 and XR

info.plist permissions:
===============
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>This app needs access to location when open.</string>
	<key>UIBackgroundModes</key>
	<array>
		<string>location</string>
	</array>

Also enabled background location capability in xCode project.

**Comment by mvanbeusekom** [comment]
@KrunalRGandhi could you check if this issue also occurs in [version 6.0.0-rc.3](https://pub.dev/packages/geolocator/versions/6.0.0-rc.3)? I am hoping to release this coming Friday as a final version.

**Comment by yacineblr** [comment]
I have exactly the same problem, I get the location event (getPositionStream) even when the app is in the background (AppLifecycleState.paused).
I did add the rules: 
```
<key>NSLocationWhenInUseUsageDescription</key>
<string>This app needs access to location when open.</string>
<key>NSLocationAlwaysUsageDescription</key>
<string>This app always needs access to the device's location.</string>
<key>UIBackgroundModes</key>
<array>
	<string>location</string>
</array>
```
But what bothers me is to have the blue banner/pill at the top on iOS. Is it possible to remove it?
For background location I use "background_locator".

**Comment by mvanbeusekom** [comment]
@yacineblr can you confirm if this problem still occurs in version 6.0.0 of the geolocator plugin?

**Comment by yacineblr** [comment]
I confirm, I do have a background localization with version 6.0.0+4. The blue pill/bar is well displayed at the top of the screen on iOS (iPhone 11, 13.4).

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F96, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.48.2)
[✓] Connected device (1 available)
```

I start the plugin like this:
```
getPositionStream(
    desiredAccuracy: LocationAccuracy.bestForNavigation,
    distanceFilter: 0,
).listen((position) {});
```
![rsz_img_0353](https://user-images.githubusercontent.com/18519670/92582353-26999300-f291-11ea-872c-006bc8f70e90.png)
