### ISSUE TITLE
getCurrentPosition close app [iOS]

### ISSUE THREAD

**Issue by samo92** [Baseflow/flutter-geolocator#486]
## 🐛 Bug Report

When i use getCurrentPosition the app closes, 

**Version:** 5.3.2+2

**Platform:** 
- [X] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
Have you added the required configuration to your `ios/Runner/Info.plist` file (see the [Permission](https://github.com/Baseflow/flutter-geolocator#ios) section in the README.md)?

**Comment by samo92** [comment]
Hello there, my info.plist has:

<key>NSLocationWhenInUseUsageDescription</key>
<string>This app needs access to location when open.</string>
<key>NSLocationAlwaysUsageDescription</key>
<string>This app needs access to location when in the background.</string>
<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
<string>This app needs access to location when open and in the background.</string>

in my app a FAB call a method like this: 

getPos(){   
   try{
    final resp = await mGeolocator.getCurrentPosition();
   } catch (e) {
     print(e.toString);
   }
}

in android works perfectly, but in iOS never appears requestPermission and the app closes, debug console not print any exception.

**Comment by vijayanbits** [comment]
I am facing the same issue as well on my iOS Simulator. The app closes.
Working fine on an Android simulator and able to get the position.

My info.plist has:
    <key>NSLocationWhenInUseUsageDescription</key>
    <string>This app needs access to location when open.</string>
    <key>NSLocationAlwaysUsageDescription</key>
    <string>This app needs access to location when in the background.</string>
    <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
    <string>This app needs access to location when open and in the background.</string>

My Code:

  void getLocation() async {

    Position position = await Geolocator()
        .getCurrentPosition(desiredAccuracy: LocationAccuracy.low);

    print(position);
}

**Comment by ChucNgo** [comment]
In your Targets -> Tab Signing&Capabilites ->  Add Capability -> Select Background Modes
And choose options below.

![image](https://user-images.githubusercontent.com/34784787/90754062-9e644580-e303-11ea-8e93-fad3820869fe.png)

**Comment by KennyChan94** [comment]
make sure your simulator has location enabled.
in your simulator -> Debug -> Location -> Custom Location...
![image](https://user-images.githubusercontent.com/17931649/91200050-395c8580-e731-11ea-94f7-237ed254a836.png)

**Comment by mvanbeusekom** [comment]
@samo92, @vijayanbits during the weekend I published a [release candidate for version 6.0.0](https://pub.dev/packages/geolocator/versions/6.0.0-rc.3) on pub.dev which solves a lot of problems specifically with permissions and reporting if the location services are not enabled.

I would very much appreciate it if you can give it a try and see if it solves this problem. Hope to hear from you.
