### ISSUE TITLE
Blue dot doesn't show on the map right after user grant permissions on Android

### ISSUE THREAD

**Issue by TenPetr** [Baseflow/flutter-geolocator#489]
## 🐛  Bug Report

When I open a map and press button, which calls function that query user's current location for the first time and user grant permissions, blue dot doesn't show on the map. I will get user's location, but the dot is not there. When I open the map again, everything works as expected.

On iOS it works just fine.

### Configuration
Android simulator with Android 10 and real device with Android 9

**Version:** 5.3.2+2

**Platform:** 
- [x] :robot: Android

**Flutter doctor result**

[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.20.2 at /Users/user/development/flutter
    • Framework revision bbfbf1770c (10 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2020.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.48.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

 
[✓] Connected device (1 available)            
    • iPhone 11 Pro (mobile) • 5D097071-2FD7-481A-B5B6-AC5D438FFB15 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

**Comment by mvanbeusekom** [comment]
@TenPetr, to me it looks like this is more a problem with the map plugin then the geolocator. We only fetch the location of the device and not handle any map or other system events that work with the map.

We did however released a new release candidate of the [geolocator plugin](https://pub.dev/packages/geolocator/versions/6.0.0-rc.3) which handles retrieving locations a lot better then the current version, you could give it a try. But otherwise I would look at the map plugin you are using (e.g. the google_maps plugin tries to acquire the device's location all by it self so it by passes the geolocator al together here).
