### ISSUE TITLE
LocationPermission.deniedForever is not "Android only"

### ISSUE THREAD

**Issue by erf** [Baseflow/flutter-geolocator#494]
## 🏗 Enhancement Proposal

The README file says `LocationPermission.deniedForever` status is "Android only", but it also occur on iOS if you **deny** the location request.

### Pitch

Remove the "Android only" from README file and better describe permission status.

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
@erf you are absolutely right. I have updated the documentation to:

``` dart
/// Represent the possible location permissions.
enum LocationPermission {
  /// Permission to access the device's location is denied, but you should
  /// request permission.
  ///
  /// On iOS this is the initial status indicting the App has not requested
  /// permission yet.
  /// On Android this is also the initial status, however the user can still
  /// choose to deny permissions for now, meaning the App can still request
  /// for permission anohter time.
  denied,

  /// Permission to access the device's location is permenantly denied. When
  /// requestiong permissions the permission dialog will not been shown until
  /// the user updates the permission in the App settings.
  deniedForever,

  /// Permission to access the device's location is allowed only while
  /// the App is in use.
  whileInUse,

  /// Permission to access the device's location is allowed even when the
  /// App is running in the background.
  always
}
```

Thank you very much for pointing this out.

**Comment by erf** [comment]
Great!

I see a small typo "anohter time" in "denied".

Maybe improve the sentence in "denied" to something like: "This is the initial state on both Android and iOS, but on Android..."

Thanks!

**Comment by mvanbeusekom** [comment]
Thanks for the suggestion it is indeed a lot better then what I came up with ;). I will update it to and make another release (there are some other documentation changes I was pointed out to):

``` dart
/// Represent the possible location permissions.
enum LocationPermission {
  /// This is the initial state on both Android and iOS, but on Android the
  /// user can still choose to deny permissions for now, meaning the App can 
  /// still request for permission another time.
  denied,

  ...
}
```
