### ISSUE TITLE
[6.0.0+1] Mocked field in Position is deleted

### ISSUE THREAD

**Issue by njovy** [Baseflow/flutter-geolocator#498]
I upgraded geolocator to 6.0.0 from 5.3.1 and the mocked field in ```Position``` is deleted. Is this intended? Unlike iOS, Android users can easily fake their GPS with 3rd party apps so my app checked 'mocked' field to avoid mocked location. I am not sure why this field is deleted in the latest update.

**Comment by mvanbeusekom** [comment]
@njovy can you explain why / how you use the `mocked` field? When I did the rebuild I didn't see any use for it that's why I removed it.

**Comment by njovy** [comment]
@mvanbeusekom My app uses a physical location to match users. We don't allow users to fake their location because of a lot of complaints. Very few android users fake their GPS coordinate and this behavior disrupts "real location only" system.
Android provides a built-in method to check if this coordinate is mocked or fetched from GPS so developers can allow mock data if they want. As far as I know, mocked field was added as developers requested. Deleting this field without any notice doesn't make sense to me.

**Comment by mvanbeusekom** [comment]
@njovy just to give you some background information, this feature was added by someone from the community but never explained what is does. 

I understand it now and will add the feature back in for the next release including proper documentation.

**Comment by njovy** [comment]
@mvanbeusekom Thank you very much for rapid response and adding ```mocked``` field back!

**Comment by mvanbeusekom** [comment]
@njovy I have just released version 6.0.0+2 which now includes a `isMocked` property in the `Position` class. 

On iOS the value will always be `false`, however on Android this will indicate is the position was retrieved from the `Location.MockProvider`. If so the value will be `true` or else it will be `false`.

**Comment by njovy** [comment]
@mvanbeusekom Thank you for this update!
