### ISSUE TITLE
position.mocked is removed from geolocator: ^6.0.0+1

### ISSUE THREAD

**Issue by iampopal** [Baseflow/flutter-geolocator#505]
## 🐛 Bug Report

position.mocked is not found at Positon class, please add position.mocked 

### Expected behavior
the .mocked is not found

### Reproduction steps
Create a Positon object and call position.mocked 

### Configuration

**Version:** ^6.0.0+1

**Platform:** 
- [yes ] :iphone: iOS
- [ yes] :robot: Android

**Comment by mvanbeusekom** [comment]
Duplicate of issue #498 will be fixed in #504 (note that I will be renaming the field to `isMocked`).

**Comment by iampopal** [comment]
I am still not able to get position.isMocked 

When are u planing to add i

**Comment by iampopal** [comment]
Thanks for the quick response 
I am waiting for the fix

**Comment by mvanbeusekom** [comment]
@iampopal  I have just released version 6.0.0+2 which now includes a `isMocked` property in the `Position` class. 

On iOS the value will always be `false`, however on Android this will indicate is the position was retrieved from the `Location.MockProvider`. If so the value will be `true` or else it will be `false`.

**Comment by wahyu-handayani** [comment]
can I use this mock location property for detecting fake gps in ios ?
