### ISSUE TITLE
How to cancel stream updates?

### ISSUE THREAD

**Issue by seanradford** [Baseflow/flutter-geolocator#506]
## 💬 Questions and Help

Hi,

With the latest version (geolocator 6.0.0+1) #getPositionStream(..) returns a Stream<Position> and the documentation states that when it is no longer needed one should call positionStream.cancel(). However this method does not exist. Consequently, how does one cancel location updates to the stream?

Thank you.

**Comment by loooookiezxc** [comment]
I think this is something you want to achieve

```
StreamSubscription<Position> _positionStream;
_positionStream = getPositionStream().listen((event) {
  _currentPos = event;
});
```

You can cancel the stream using ``` _positionStream.cancel();```

**Comment by seanradford** [comment]
Hi @loooookiezxc,

That is what I'm trying to achieve, however as per my post, version 6.0.0+1 `#getPositionStream` returns a `Stream<Position>` and NOT a `StreamSubscription<Position>` (and `Stream` does not have a cancel method)

**Comment by seanradford** [comment]
Right. I got it!!! (thought I must have been being stupid)

```
Stream<Position> positionStream = getPositionStream(desiredAccuracy: LocationAccuracy.best, timeInterval: 0);
StreamSubscription<Position> subStream = positionStream.listen(_onNewPosition);
...
_subStream.cancel();
```

Thank you.
