### ISSUE TITLE
Fetching Location on Different Devices Mainly from Chinese Manufacturers

### ISSUE THREAD

**Issue by loooookiezxc** [Baseflow/flutter-geolocator#507]
## 💬 Questions and Help

Firstly I want to thank @mvanbeusekom for giving me thoughts and ideas regarding my prior issues. I have prepared different Use Cases and Scenarios based on what I've experienced. And yes I need help.

### Use Case No. 1
You have a device that came from Chinese Manufacturers and you want to get the current position of the device. As per @mvanbeusekom says, because of the war between Trump and Chinese Manufacturers, some of the devices doesn't have the full functionality of Google Play Services, so you will resort in using the ```LocationManager```:

#### Solution
```
Position _currentPosition;
_currentPosition = await getCurrentPosition(
  desiredAccuracy: Location.high,
  forceAndroidLocationManager: true
);
```
### Use Case No. 2.
You have a device manufactured by Chinese and have used the first solution, but still, the plugin won't return the current position of the device. Before moving on, there are two scenarios in which I had experienced the capabilities of the first solution; (1) when you are indoors. (2) when you are outdoors.

### Use Case No 2.1 - Indoors 
Upon researching (correct me if I'm wrong) the ```LocationManager``` in ```geolocator``` uses the GPS_PROVIDER by default. But when I did this:
```
Position _currentPosition;
_currentPosition = await getCurrentPosition(
  desiredAccuracy: Location.medium,
  forceAndroidLocationManager: true
);
```
I now have the current position of the device but not that accurate because obviously I have set the accuracy to ```medium```.

### Use Case No. 2.2 - Outdoors
Now, all of the above solutions are working outdoors, either setting the ```desiredAccuracy``` to ```Location.high``` or to ```Location.medium```.

### Use Case No.3
Based on my experiences I have therefore concluded that setting the ```desiredAccuracy``` to ```Location.medium``` and setting the ```forceAndroidLocationManager``` to ```true``` is my best shot. But when I tried this to non-Chinese variant devices it won't return the current position. So, I changed the ```desiredAccuracy``` to ```Location.high```. Now it worked again but not with the Chinese variant devices. I had to wait for almost 10 minutes in order for the app to get the current position.

Before trying these approaches please remember to add the ```<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>``` in your ```AndroidManifest.xml``` file.

### Problem:
I've been testing my app on a Chinese Device because nowadays in our country (Philippines) the number of Chinese device users is increasing because of its affordable price. I cannot find a way to get the current location without relying on ```geolocator``` 

### Disclaimer
The above use cases are based on my experience with the ```geolocator``` and may not be of help to you. But if you have an idea or a solution to this, please share it.

**Comment by loooookiezxc** [comment]
Closing this now because I've figured what's causing this problem. For all of the developers out there who had a Chinese device and testing this plugin on that device, kindly do the following:

1. Check if the device is using a Global ROM
2. If it is using Chinese ROM check if the location permission is allowed in the google play service app.
3. Set it to ```Always Allow``` not ```While App In Use```

**Comment by triluhur** [comment]
hi, I also have the same problem (Geolocator 6.0.0). Some device not working (eg. Xiaomi) even when I change the accuracy to medium. Using the previous version 5.x.x, its working fine (with accuracy medium). But for older android version ( Android 7 or lower) its not working.

**Comment by afxgroup** [comment]
I've the same problem and i've seen that if i use ACCESS_FILE_LOCATION i can get the location while if i use ACCESS_COARSE_LOCATION nothing is returned in the android emulator an it remain stuck in getCurrentPosition(). And if i add a timeLimit property it throws the exception

**Comment by zs-dima** [comment]
> if i use ACCESS_FILE_LOCATION i can get the location while if i use ACCESS_COARSE_LOCATION nothing is returned in the android emulator an it remain stuck in getCurrentPosition().

I have the same issue from 7.0.0 version to 7.0.3 geolocator version

**Comment by rmControls** [comment]
> 
> 
> Closing this now because I've figured what's causing this problem. For all of the developers out there who had a Chinese device and testing this plugin on that device, kindly do the following:
> 
>     1. Check if the device is using a Global ROM
> 
>     2. If it is using Chinese ROM check if the location permission is allowed in the google play service app.
> 
>     3. Set it to `Always Allow` not `While App In Use`

Yes, this solution works but we cannot ask users to make changes to google play service app while using our app.... 

Is there any other way to make it work??

**Comment by zs-dima** [comment]
> Chinese device
I have non-Chinese device and I have this issue on default Android emulator as well.

**Comment by TheOneWithTheBraid** [comment]
For non-Googled devices, you might use the drop-in from [Geolocator FLOSS](https://gitlab.com/free2pass/flutter-geolocator-floss/) too.

It simply removes the Google code from an existing implementation of Geolocator.

**Comment by mvanbeusekom** [comment]
@TheOneWithTheBraid I have been looking at the source code and don't see how this is different from simply enforcing the geolocator to use the `LocationManager` SDK. You can already do this using the `forceAndroidLocationManager` argument on the `getCurrentPosition` and `getPositionStream` methods:

```dart
final position = await Geolocator.getCurrentPosition(forceAndroidLocationManager: true);
```

**Comment by zs-dima** [comment]
> ```dart
> forceAndroidLocationManager
> ```

forceAndroidLocationManager does not solve this issue !

**Comment by TheOneWithTheBraid** [comment]
Yeah, the difference is that the Google code is removed. Scanners from Stores (e.g. F-Droid or Huawei AppGallery) wont't comply the app makes use of prohibited class names hence. That's the major difference. As said, it's nothing but a removal of all the Google specific code.

**Comment by zs-dima** [comment]
> 
> 
> Yeah, the difference is that the Google code is removed. Scanners from Stores (e.g. F-Droid or Huawei AppGallery) wont't comply the app makes use of prohibited class names hence. That's the major difference. As said, it's nothing but a removal of all the Google specific code.

Even Google devices have this issue - including emulator with Google services

**Comment by zmGitHub** [comment]
> > Yeah, the difference is that the Google code is removed. Scanners from Stores (e.g. F-Droid or Huawei AppGallery) wont't comply the app makes use of prohibited class names hence. That's the major difference. As said, it's nothing but a removal of all the Google specific code.
> 
> Even Google devices have this issue - including emulator with Google services

If you use this plug-in in China, you must install Google Service (GMS). You can use TapTap to download the Google suite. If the installation is successful, you must restart your phone, and then remember to put the VPN location and flutter-geolocator on your phone. It’s no problem if you don’t have GMS. The plug-in will always hang without returning

**Comment by zs-dima** [comment]
@zmGitHub I guess you replied to some one other message as I mentioned it is issue for Europe devices as well and even usual Android emulator with Google services installed

**Comment by zmGitHub** [comment]
> @zmGitHub I guess you replied to some one other message as I mentioned it is issue for Europe devices as well and even usual Android emulator with Google services installed

Yes, I replaced it with the location library now, at least I can get GPS information now

**Comment by wapchief** [comment]
delete ``timeLimit``,
set
``
      desiredAccuracy: LocationAccuracy.medium,
      forceAndroidLocationManager: true,
``
