### ISSUE TITLE
Is there the possibility to revoke location permissions?

### ISSUE THREAD

**Issue by enricobenedos** [Baseflow/flutter-geolocator#516]
## 💬 Questions and Help

Good morning,
I start using this package to manage location permissions and get current position.

I want to create a switch button to give user the possibility to grant/discard location permission on my app. 
Investigating on documentation and source code seems that this package can only provide a way to grant permissions but not to revoke them. 
Is it possible to do what I'm looking for? Can be an idea for a future implementation?

Thank you

**Comment by mvanbeusekom** [comment]
Hi @enricobenedos, to my knowledge the Android and iOS SDKs don't over a (public) API to revoke permissions. Meaning it is not possible for us to revoke permissions programmatically.

Please correct me if I am wrong, I did a search through Apple's and Google's documentation but was not able to find such a feature (which from a safety perspective makes sense).

**Comment by enricobenedos** [comment]
Thank you @mvanbeusekom for your explanation and your time.

You are right, at this point I will change my mind due to adapt my app to a new logic about permissions.
