### ISSUE TITLE
LocationServiceDisabledException is not documented

### ISSUE THREAD

**Issue by Ascenio** [Baseflow/flutter-geolocator#519]
## 🐛 Bug Report

The following message is displayed if the user declined to accept the permissions when `getCurrentPosition()` is called.
> LocationServiceDisabledException (The location service on the device is disabled.)

### Expected behavior
This is not really a bug, but I expected it to be documented under the docs of `getCurrentPosition()` 

### Reproduction steps
Call `getCurrentPosition()` but decline the permissions.

### Configuration

**Version:** ^6.0.0+4

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android

**Comment by Ascenio** [comment]
Actually, it really is a bug because it was supposed to throw a `PermissionDeniedException` instead of the `LocationServiceDisabledException`.

**Comment by mvanbeusekom** [comment]
Hi @Ascenio, I am having a hard time reproducing this example. The `getCurrentPosition` will check two things before trying to acquiring the actual position information:

- First it will check if the App has permissions to access the position information. If this is not the case it will throw the `PermissionDeniedException` and exit the function;
- If the App has permissions it will check if the location services are enabled. If not it will throw a `LocationServiceDisabledException` and exit the function;

I have tested these situations using the example App (on version 6.0.0+4 of the geolocator) and came to the conclusion that it is working correctly:

- If I deny permissions and disable the location services and then call `getCurrentPosition` I receive a `PermissionDeniedException`;
- If next I grant the App permissions (doesn't matter if I pick "Allow all the time" or "Allow only while using the app") and refresh the page (by switching tabs), I receive the `LocationServiceDisabledException`;
- If I now enable the location services, the position is retrieved as expected;
- And when I revoke permissions I again receive the `PermissionDeniedException`.

So I am not sure how you are getting the `LocationServiceDisabledException` the way you described it. Maybe I am missing something?

You are right though that the `LocationServiceDisabledException` is not mentioned in the API reference for the `getCurrentPosition` nor the `getPositionStream` method which it should. The documentation should be update in the `geolocator_platform_interface` package: 
- [here](https://github.com/Baseflow/flutter-geolocator/blob/5cf33d70dda447f753dc20dda3e39d0cca61bae6/geolocator_platform_interface/lib/src/geolocator_platform_interface.dart#L98) for the `getCurrentPosition` method;
- and [here](https://github.com/Baseflow/flutter-geolocator/blob/5cf33d70dda447f753dc20dda3e39d0cca61bae6/geolocator_platform_interface/lib/src/geolocator_platform_interface.dart#L138) for the `getPositionStream` method.

And also in de `geolocator` package:
- [here](https://github.com/Baseflow/flutter-geolocator/blob/5cf33d70dda447f753dc20dda3e39d0cca61bae6/geolocator/lib/geolocator.dart#L55) for the `getCurrentPosition` method;
- and [here](https://github.com/Baseflow/flutter-geolocator/blob/5cf33d70dda447f753dc20dda3e39d0cca61bae6/geolocator/lib/geolocator.dart#L98) for the `getPositionStream` method.

**Comment by mvanbeusekom** [comment]
(sorry accidentally closed the issue, didn't mean to)

**Comment by mvanbeusekom** [comment]
Documentation is updated in version 6.1.0
