### ISSUE TITLE
getCurrentLocation does not fetch location on ios (below 13 version)

### ISSUE THREAD

**Issue by razmik-gharibyan** [Baseflow/flutter-geolocator#522]
## 🐛 Bug Report
Geolocator getCurrentLocation() does not return value when i am using (simulator with ios version below 13).
No exceptions , no errors. I've treid adding breakpoint below line getCurrentLocation it seems like it's stuck in there.

### Configuration
For iOS version below 13.

**Version:** 6.0.0+4

**Platform:** 
- [ +] :iphone: iOS
- [ ] :robot: Android

**Comment by SergejDK** [comment]
Do you have set a location on the simulators? One Time I forgot to activate location....

**Comment by mvanbeusekom** [comment]
@razmik-gharibyan did do as @SergejDK mentioned and set a location for the simulator? 

To do so use the following options: Features -> Location -> Custom Location. After that set a latitude and longitude and test getting the location again.

**Comment by razmik-gharibyan** [comment]
Yeah i have done it, but it's way too slow on ios versions below 13.  It may taake from 45 second to 2 minute to update location.

**Comment by mvanbeusekom** [comment]
Which accuracy do you use when getting the location?

**Comment by razmik-gharibyan** [comment]
i've tried all, (low,medium,high,best)

**Comment by SergejDK** [comment]
@razmik-gharibyan did you try to use difference permissions? Sometimes it behaves differently with different permissions - just to narrow down the problem.

**Comment by razmik-gharibyan** [comment]
I've tried all kind of mix and match with allowAlways,allowWhenInUse,allowAlwaysAndWHenInUse. Same behaviour

**Comment by rlueders** [comment]
Im seeing a similar issue, but on IOS 13 and 14. Prior to upgrading to version 6.x.x of the geolocator plugin, I was seeing positions updates every second or so when calling getPositionStream from my iphone 7 (physical device). However, after upgrading the plugin, I see only one or two updates, then  nothing. Sometimes I never get any position updates, but when I do, it is seldom more than two or three.  The couple position updates I do get usually have a position.accuracy of 4,000+.   Not sure if this is different issue, or related to this one, but happy to open a new issue either way.  I tried downgrading back to the old 5.x.x version of the plugin and everything works fine.

**Comment by DonC83** [comment]
getCurrentPosition() doesn't appear to be working, both on Android and iOS, seems to wait indefinitely. If I swap out getCurrentPosition with getLastKnownPosition it returns, however I'm not interested in the last known position.
Version is 6.0.0+4

**Comment by kightsonsanom** [comment]
getCurrentPosition does not work for me as well. I have tried it on Android API30 Emulator and API29 real ONEPLUS 6. It just hangs indefinitely. So far I was using version 5.3.2+2 as a workaround but this version does not work on Android API 30 either

**Comment by racacere** [comment]
Same here on both platforms and multiple devices

**Comment by jimmyszeles** [comment]
I always had the iOS app crashing on me when using the getCurrentPosition function.
Found out that the key _EnableBackgroundLocationUpdates_ in _Info.plist_ made it crash for me.
Removed that key and now everything works fine for me, I had no trouble in Android tho.

**Comment by kightsonsanom** [comment]
@jimmyszeles what android versions did you try? emulator or real device?

**Comment by kightsonsanom** [comment]
@mvanbeusekom  should I create a separate issue for Android ?

**Comment by mvanbeusekom** [comment]
@kightsonsanom yes please it would help to keep things apart.

Also if you have issues with Android I really recommend reading through issue #507. ￼￼

**Comment by hectorAguero** [comment]
> I always had the iOS app crashing on me when using the getCurrentPosition function.
> Found out that the key _EnableBackgroundLocationUpdates_ in _Info.plist_ made it crash for me.
> Removed that key and now everything works fine for me, I had no trouble in Android tho.

Thanks! I have that key and my app crashes on iOS 14 Emulator with current Flutter Stable, Beta and Master,  and using Xcode 12, also the method `getPositionStream` crash the app, and like `getCurrentPosition` both not report the error in console.

That key does the same than enable background capabilities in xcode?

**Comment by nagarwal8** [comment]
I have the same problem as mentioned in this thread - I cannot make it work on either iOS (SE 2nd generation) or Android simulators. I am using "geolocator: ^6.0.0". The command "Position currentPosition =
        await getCurrentPosition(desiredAccuracy: LocationAccuracy.lowest);" hangs.

Any suggestions to make it work are appreciated

**Comment by gabrielgarciagava** [comment]
> I always had the iOS app crashing on me when using the getCurrentPosition function.
> Found out that the key _EnableBackgroundLocationUpdates_ in _Info.plist_ made it crash for me.
> Removed that key and now everything works fine for me, I had no trouble in Android tho.

Do you mind sharing how did you find out that this was the problem?

**Comment by aquilarafa** [comment]
> @razmik-gharibyan did do as @SergejDK mentioned and set a location for the simulator?
> 
> To do so use the following options: Features -> Location -> Custom Location. After that set a latitude and longitude and test getting the location again.

It works for me. 
Simulator ios 14.2

**Comment by mvanbeusekom** [comment]
This issue should have been solved since version 6.1.2.
