### ISSUE TITLE
Support Approximate Location in iOS 14

### ISSUE THREAD

**Issue by RyanRamchandar** [Baseflow/flutter-geolocator#523]
## 🚀 Feature Requests

In iOS 14, users are given an additional authorization control to specify whether an app can have access to precise location. Apps cannot opt-out of this feature.

<img width="243" alt="image" src="https://user-images.githubusercontent.com/3187342/92960496-5aacb980-f433-11ea-8338-2943476e3adb.png">

<img width="246" alt="image" src="https://user-images.githubusercontent.com/3187342/92960445-42d53580-f433-11ea-8bf4-4bb552e8fe6c.png">

Changes are described here: https://developer.apple.com/videos/play/wwdc2020/10660/

To summarize:
- Starting in iOS 14 users can choose to allow precise or reduced accuracy
- Apps that already have allowed location will default to precise location
- Apps can request full or reduced accuracy by default (requests precise if not specified)
- Users can change the precise location setting in the App settings at any time
- Apps can request temporary precise location
- The previous `desiredAccuracy` setting is different than reduced accuracy. The latter enforces it.
- Reduced locations are within 1-10 km accurate and recomputed 4 times per hour.

### Contextualize the feature

iOS 14 has been released and all apps are affected by this.

### Describe the feature

Add support for
- requesting full or reduced accuracy be default
- querying whether the user has authorized full or reduced accuracy (precise location setting)
- requesting temporary precise location accuracy

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by FloLecoeuche** [comment]
This feature is currently present in flutter-geolocator ?

**Comment by RyanRamchandar** [comment]
@FloLecoeuche unfortunately no. See the 'Describe the feature' section for what needs to be added.

**Comment by stepanzalis** [comment]
Any plans to add this feature soon? Unfortunately it's crucial for most apps targeting iOS platform.

**Comment by florissmit1** [comment]
@stepanzalis We're busy implementing the mentioned list of features. See: #760 for the 'querying whether the user has authorized full or reduced accuracy`.

**Comment by mvanbeusekom** [comment]
Support for querying and requesting temporary precise location in iOS 14 has been added in version 7.3.0 which has been released on Jul 16, 2021.
