### ISSUE TITLE
isLocationServiceEnabled() always Returns True for  google message "For a better experience..."

### ISSUE THREAD

**Issue by nicolasjon** [Baseflow/flutter-geolocator#525]
## 🐛 Bug Report

isLocationServiceEnabled() Returns True if the google message "For a better experience, turn on device location, which uses Googles's location service" appears and "No Thanks" is selected. This message only appears on a freshly wiped or new device.
![Screenshot 2020-09-17 at 12 20 39](https://user-images.githubusercontent.com/6538405/93463813-342dc900-f8e0-11ea-9fc4-a72e7f8f45be.png)
 
### Expected behavior
isLocationServiceEnabled()  Returns False 
### Reproduction steps
Close the Android emulator, from AVD select wipe device data, restart emulator
geolocationStatus = await requestPermission();
Select "No Thanks"
isLocationServiceEnabled();
returns true

If use location is toggled in settings isLocationServiceEnabled() then returns the correct results.
It appears to be an issue on a new or wiped emulator device when the "For better experience" message appears

My app works with reduced function if the user switches off app or device location, but needs to handle this additional google message.   
### Configuration
Android emulator 28

**Version:** 6.0.0+4

**Platform:** 
- [ ] :iphone: iOS
- [x ] :robot: Android

**Comment by GrahamDi** [comment]
I am getting the same issue.

Configuration
Android emulator 23

Version: 6.0.0+4

Platform:

 📱 iOS
[x ] 🤖 Android

flutter doctor -v
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.20215.1000], locale en-ZA)
    • Flutter version 1.20.4 at C:\flutter
    • Framework revision fba99f6cf9 (4 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at D:\Android\Sdk
    • Platform android-30, build-tools 29.0.0
    • ANDROID_HOME = D:\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.49.1)
    • VS Code at C:\Users\dicki\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 6.0 (API 23) (emulator)

• No issues found!

**Comment by mvanbeusekom** [comment]
Will look into this, thank for reporting

**Comment by GrahamDi** [comment]
On further investigation, I'm not sure if this is necessarily an issue with geolocator, I tried location_permissions package and permissions package and they both also appear to  report that location services are active. Would appreciate you looking into though.

**Comment by nicolasjon** [comment]
On investigating further. The Google dialog is requesting that the additional location services of wifi/cell etc (and google reporting!) can be used. This is toggled in a buried Android option and is a - device level switch -  
![Screenshot 2020-09-18 at 20 46 04](https://user-images.githubusercontent.com/6538405/93638851-f9b35180-f9ef-11ea-975e-9d50855c7de3.png)
It is an extension of - device level use Location switch -
![Screenshot 2020-09-18 at 20 47 26](https://user-images.githubusercontent.com/6538405/93638979-2a938680-f9f0-11ea-8d0f-f3366dec5f63.png)

On a wiped AVD in settings location and Improve location accuracy are on by default..
It appears that - If the Improve location accuracy option is switched off in settings, then when your app launches if you answer yes to location and then answer "No thanks" to the dialog for additional location services then a location is never returned.

Not quite sure where this leaves us. Google have made this a messy interface.

**Comment by jjosenaldo** [comment]
This is also happening to me. I'm deploying my app to a Redmi 4A device with Android.

**Comment by mvanbeusekom** [comment]
This issue is solved since version 6.1.1 of the geolocator plugin.
