### ISSUE TITLE
undocumented parameters

### ISSUE THREAD

**Issue by mpoirier101** [Baseflow/flutter-geolocator#537]
## 🏗 Enhancement Proposal

_positionStream = getPositionStream(distanceFilter: 50, timeInterval: 60, timeLimit: Duration(minutes: 1)).listen(_onData);

I set timeLimit to 1 minute and hopefully timeInterval to 60 seconds, but I still recevie data at ~15 seconds... without moving!

timeInterval unit and behavior is not documented.
timeLimit precise behavior is not documented.

**Comment by mvanbeusekom** [comment]
Hi @mpoirier101, 

Thank you for raising this issue. I am wondering which documentation you are referring to. In general all public methods and their parameters, return values and possible exceptions are documented in the API reference. For example the `getPositionStream` specific API reference documentation can be found here: https://pub.dev/documentation/geolocator/latest/geolocator/getPositionStream.html (and of course also in the source code, which VS Code, Android Studio and IntelliJ IDEA should be able to display).

**Comment by mvanbeusekom** [comment]
Closing issue as no response is given and documentation is available.
