### ISSUE TITLE
geolocator dependency problem

### ISSUE THREAD

**Issue by leopardquick** [Baseflow/flutter-geolocator#538]
## 💬 Questions and Help

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':geolocator:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':geolocator:debugCompileClasspath'.
   > Could not resolve com.google.android.gms:play-services-location:17.0.0.
     Required by:
         project :geolocator
      > Could not resolve com.google.android.gms:play-services-location:17.0.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-location/17.0.0/play-services-location-17.0.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-location/17.0.0/play-services-location-17.0.0.pom'.
               > Connection reset
      > Could not resolve com.google.android.gms:play-services-location:17.0.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-location/17.0.0/play-services-location-17.0.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-location/17.0.0/play-services-location-17.0.0.pom'.
               > Connection reset

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9m 3s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by renefloor** [comment]
>Could not get resource 'https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-location/17.0.0/play-services-location-17.0.0.pom'.

That file downloads perfectly fine for me. Maybe you or google had a some downtime? Could you try again with a working internet connection?
