### ISSUE TITLE
How to get Location name using this package?

### ISSUE THREAD

**Issue by yashwp** [Baseflow/flutter-geolocator#539]
I have gone through your home page on pub.dev - https://pub.dev/packages/geolocator, I'm not able to find any information around how can I get the location name (like a city, state) of a user using this package.

I did find a lot of articles, which uses your package's older version around `5.x.x`v. Where I can get the location but in your latest version, I could find a single hint around that.

I have seen the `example.dart` file as well...  It is just a random file with 0 information around the implementation.

Here are some of the articles I found out, but none of them are working. Kindly update your documentation as an extreme priority task. Everything in those articles is wrong, Class names, functions, etc.

https://www.digitalocean.com/community/tutorials/flutter-geolocator-plugin
https://medium.com/swlh/working-with-geolocation-and-geocoding-in-flutter-and-integration-with-maps-16fb0bc35ede 
https://medium.com/flutter-community/get-a-users-location-in-flutter-20f488ac8043
https://medium.com/fabcoding/get-current-user-location-in-flutter-57e202bad6db

@mvanbeusekom

**Comment by mvanbeusekom** [comment]
@yashwp as mentioned in the [README.md](https://github.com/Baseflow/flutter-geolocator#usage) and the [CHANGELOG.md](https://github.com/Baseflow/flutter-geolocator/blob/develop/geolocator/CHANGELOG.md#600) the geocoding features have been moved to its own plugin called [geocoding](https://pub.dev/packages/geocoding).
