### ISSUE TITLE
getCurrentPosition does not work on Android with LocationAccuracy.lowest.

### ISSUE THREAD

**Issue by snorreks** [Baseflow/flutter-geolocator#540]
## 🐛 Bug Report

getCurrentPosition does not work on Android with desiredAccuracy = LocationAccuracy.lowest.
It works however on Android with LocationAccuracy.low, and it works with lowest on iOS.

### Expected behavior
Get the currentPoisition on Android.

### Reproduction steps
Call the getCurrentPosition function with LocationAccuracy.lowest on Android on an emulator or a real device (production and debugging).

### Configuration
Code:
```dart
      final Position currentPosition = await getCurrentPosition(
        desiredAccuracy: LocationAccuracy.lowest,
        timeLimit: const Duration(seconds: 10),
      );
```

**Version:** 6.0.0+4, (Channel stable, 1.22.0)

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android

**Comment by hectorAguero** [comment]
Also for the default  `LocationAccuracy.best` I'm test in android 11 device/emulator, and ios 14 emulator

For some reason,  after I'm call `getCurrentPosition`   with `LocationAccuracy.best` the method getPositionStream doesn´t work.

**Comment by mvanbeusekom** [comment]
@snorreks, @hectorAguero, which permissions did you have in your AndroidManifest.xml file? This behavior occurs when you have `ACCESS_COARSE_LOCATION` in your AndroidManifest.xml and should be solved by changing to the `ACCESS_FINE_LOCATION` permission.

This has also recently been updated in the README.md file which now explains:

> **NOTE:** Specifying the `ACCESS_COARSE_LOCATION` permission results in only being allowed to request a location with the `getLastKnownPosition` method. The accuracy can be very precise or could be the equivalent to a city block. If the phone already knows where he is this results in a quick response, but it could also take a long time (minutes) before you will get your first locations fix.

What this says is:

If you are only using the `getLastKnownPosition` in your code the `ACCESS_COARSE_LOCATION` permission is sufficient. If you are using the `getCurrentPosition` or `getPositionStream` methods in your code you must use the `ACCESS_FINE_LOCATION` permission to receive the actual location information.

**Comment by hectorAguero** [comment]
@mvanbeusekom no, I already have `ACCESS_FINE_LOCATION` in manifest, btw the target of the app is 29, and also the bug happens on iOS 14 for me.

**Comment by snorreks** [comment]
@mvanbeusekom I only have ACCESS_COARSE_LOCATION, but it works with LocationAccuracy.low. I will just keep ACCESS_COARSE_LOCATION and use LocationAccuracy.low, just wanted to report that it didn't work with LocationAccuracy.lowest.
