### ISSUE TITLE
Can't stream location after twice getCurrentPosition

### ISSUE THREAD

**Issue by RTrackerDev** [Baseflow/flutter-geolocator#546]
## 🐛 Bug Report

When I called `getCurrentPosition` twice current `positionStream` was stoped.

### Expected behavior
`positionStream` shouldn't stop after twice  `getCurrentPosition`

### Reproduction steps
1. Start listen positionStream
2. Twice call getCurrentPosition
3. positionStream stoped emit any events

### Configuration

**Version:** 6.0.0+4

**Platform:** 
- iOS
- Android

**Comment by fabioginzel** [comment]
that error is back
