### ISSUE TITLE
No indication when user turns off location service via android notification drawer

### ISSUE THREAD

**Issue by JustChris** [Baseflow/flutter-geolocator#548]
## 🐛 Bug Report

No indication when user turns off location service via android notification drawer while app is running. Stream shows last known position.

I caught most scenarios via didChangeAppLifecycleState like: 

1. App is running with location service enabled and granted
2. User goes to settings and turns off location service or denies access
3. User switches back to the app
4. didChangeAppLifecycleState is fired to check if location service is enabled and granted

The last thing I need is to catch is the scenario where the user turns off location service via notification drawer.
But the stream doesn't notice this at all..

According to [#43](https://github.com/Baseflow/flutter-geolocator/issues/43) it is supposed to be fixed, but I can not confirm this.

### Expected behavior

I should get some indication that the position stopped streaming (like null) once the Location is off, and when it turns back on the Position should start streaming again on its own.

### Reproduction steps

1. Build basic app containing a PositionStream using a StreamSubscription or StreamProvider or a Streambuilder
2. Run the app while Location services are on and permitted
3. Turn off Location via Android Notification Drawer

### Configuration

**Version:** 6.0.0+4

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @JustChris, 

thank you for reporting this issue. I managed to reproduce it and have a fix ready which I will try to release tomorrow as part of version 6.1.1 of the geolocator plugin.

**Comment by JustChris** [comment]
Splendid! Thank you.

**Comment by mvanbeusekom** [comment]
@JustChris I just released version 6.1.1 of the Geolocator plugin which should fix the issue above. 

When you are listening to the position stream and you disable the location services the stream will return a `LocationServicesDisabledException` and automatically cancels listening for position updates on the native side (you might need to manually stop listening to your local `StreamSubscription`, since it will not receive any new events anymore).

Let me know if you run into any issues.

**Comment by JustChris** [comment]
@mvanbeusekom Thanks for your effort! It is indeed an improvement!

But unfortunately it is not completely satisfying. 
The optimal solution would be a stream to location service status and to location permission status. So that you can listen to that statuses and get notified when those are changed.

Is something like this possible?

**Comment by mvanbeusekom** [comment]
@JustChris I don't think this is possible unfortunately. On Android we get notified that the location services are disabled through a callback we can supply when we request location updates. Meaning this is directly connected to the stream which is used to receive location updates.

The construct looks something like this:

```java
FusedLocationProviderClient fusedLocationProviderClient = LocationServices.getFusedLocationProviderClient(context);

fusedLocationProviderClient.requestLocationUpdates(
    locationRequest,
    new LocationCallback() {
        @Override
        public void onLocationResult(LocationResult locationResult) {
           // This is called when a new location update is captured.
        }

        @Override
        public void onLocationAvailability(LocationAvailability locationAvailability) {
            if (!locationAvailability.isLocationAvailable()) {
                // This is where we detect that the location services have been disabled.
            }
        }
    },
    Looper.getMainLooper());
```

If you have any other idea's or information, please let me know and I can look into it.

**Comment by JustChris** [comment]
If I am not using distanceFilter, the stream emits the current location every second, even when the device is not moving, i.e. even if there is no new location data.

So when I turn off location service, the stream throws the LocationServicesDisabledException and stops emitting new location data. When I turn location service back on. The stream starts emitting data again. Every second..

When I am using distanceFilter = e.g. 10, the stream does not start emitting data after turning location service back on.

It would be nice, if the stream would emit the current location one time after turning location service back on. Because I do not want the stream to emit data every second.

I hope I explained the situation properly, so you can understand.

Looking forward for your inputs.

**Comment by gkrawiec** [comment]
the same thing happens if location permission is initially denied and then allowed from the settings page. In order to get things running again I have to subscribe to the stream again.
