### ISSUE TITLE
Error while starting the plugin

### ISSUE THREAD

**Issue by nimr77** [Baseflow/flutter-geolocator#551]
## 🐛 Bug Report
# E/flutter ( 4800): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method checkPermission on channel flutter.baseflow.com/geolocator)

Im using flutter 1.23 and I was developing and app that using the plug-in but I got this error 
E/flutter ( 4800): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method checkPermission on channel flutter.baseflow.com/geolocator)

everytime im using the plug-in 

**Version:** 6.0

**Platform:** 
- [ ] :iphone: iOS
- [ *] :robot: Android

**Comment by mvanbeusekom** [comment]
Have you tried running `flutter clean` and after that running `flutter pub get`?

**Comment by nimr77** [comment]
Yes, this is my flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.50.0)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

**Comment by nimr77** [comment]
I was able to fix the problem by using Java 11 and Gradle 5.6.2

**Comment by tayyabmughal676** [comment]
> I was able to fix the problem by using Java 11 and Gradle 5.6.2

I'm facing still?

**Comment by IIIalexmuellerIII** [comment]
I had the same problem with flutter version 2.5.2 and geolocator 8.0.0. **Upgrading flutter** to 3.0.0 fixed the problem for me.
