### ISSUE TITLE
Undefined class 'Geolocator'. Try changing the name to the name of an existing class, or creating a class with the name 'Geolocator'

### ISSUE THREAD

**Issue by Ebadullahamini** [Baseflow/flutter-geolocator#552]
this error happens when I call   final Geolocator geolocator = Geolocator()..forceAndroidLocationManager;
I'm using geolocator version 6.0.0+4.

**Comment by mvanbeusekom** [comment]
Version 6.0.0 of the geolocator plugin has been completely rebuild according to the [Federated plugin architecture](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#federated-plugins).

As part of the rebuild I converted all methods to global methods and removed The `Geolocator` class. Also I removed the `forceAndroidLocationManager` property and included it as an named property of the `getCurrentPosition` and `getPositionUpdates` methods. 

More information can be found in the [README.md](https://pub.dev/packages/geolocator) or the [API reference documentation](https://pub.dev/documentation/geolocator/latest/geolocator/geolocator-library.html).
