### ISSUE TITLE
getCurrentPosition not working on IOS on airplane mode

### ISSUE THREAD

**Issue by abdalmonem** [Baseflow/flutter-geolocator#555]
## 🐛 Bug Report

when i call getCurrentPosition() , its works normal if SIM on the phone and cellular is on

### Expected behavior
get location

**Version:** 1.x
geolocator: 6.1.0
flutter: 1.22

**Platform:** 
- [ not working] :iphone: iOS
- [ works fine] :robot: Android

**Comment by pp2015jp** [comment]
It not work on Android too.
Developers provide 1 line of code. But it seem uncompleted,

e.g.,
MissingPluginException(No implementation found for method listen on channel flutter.baseflow.com/geolocator_updates)

**Comment by ElimuMichael** [comment]
This issue has been pending for years now! I wonder if in any upgrades being made this issue is put into consideration, because, version after version, the same issue is raised.

**Comment by Sempakonka** [comment]
hi @abdalmonem, @ElimuMichael, @pp2015jp 
I have tried to reproduce this issue on the latest version of Geolocator on both IOS and Android on a emulator and a physical device. However I was unable to reproduce it.

Could you try to update to the latest version of Geolocator and see if the issue still persist?
And if that is the case, can you please provide your `flutter doctor -v`?

**Comment by mvanbeusekom** [comment]
Closing this issue due to lack of response. I will reopen it when required information is supplied.

**Comment by omateuscastro** [comment]
I reproduced the error for iOS with version 9.0.0
