### ISSUE TITLE
GeolocationManager.java:18: warning: [deprecation] PluginRegistry in io.flutter.plugin.common has been deprecated

### ISSUE THREAD

**Issue by nicolasjon** [Baseflow/flutter-geolocator#556]
## 🐛 Bug Report

/Users/nicolas/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-6.1.1/android/src/main/java/com/baseflow/geolocator/location/GeolocationManager.java:18: warning: [deprecation] PluginRegistry in io.flutter.plugin.common has been deprecated
import io.flutter.plugin.common.PluginRegistry;

Is this plugin using the old 1.0 embedding/plug in registration? 
Have not tested for iOS
Thanks!

### Expected behaviour
No deprecated warning

### Reproduction steps
Clean build

**Version:** 
6.1.1

**Platform:** 
- [  ] :iphone: iOS
- [ x] :robot: Android

**Comment by mvanbeusekom** [comment]
@nicolasjon no this plugin supports both versions of the plugin registration. Meaning v1 is still supported for backwards compatibility reasons (as in Apps that haven't been migrated to Flutter v1.12.+ yet).

Apparently Flutter recently marked the `PluginRegistry` class deprecated and I will make sure we will correctly handle the warning in future version of the geolocator plugin (for example suppress the warning if the advise is to keep supporting v1 plugin registration as part of backwards compatibility). 

Short answer is, you can safely ignore the warning. If you are on a post Flutter 1.12 app, it will not touch any of the deprecated methods.
