### ISSUE TITLE
Not working on newer devices 

### ISSUE THREAD

**Issue by aTeamSolace** [Baseflow/flutter-geolocator#558]
Hello, I'm using **geolocator: ^6.1.0** this plugin. This is working fine on lower version devices but not working on the above version 9.0 devices. Please let me know the solution.

**Comment by aTeamSolace** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.22.0-12.1.pre, on Microsoft Windows [Version 10.0.18362.1139], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 3.6)
[√] VS Code (version 1.50.1)
[√] Connected device (4 available)

• No issues found!

**Comment by aTeamSolace** [comment]
android {
    compileSdkVersion 30

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.shubham.adam_company_consumer_app"
        minSdkVersion 16
        targetSdkVersion 30
        multiDexEnabled true
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

**Comment by aTeamSolace** [comment]
<uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />

**Comment by aTeamSolace** [comment]
Please let me know the issue

**Comment by aTeamSolace** [comment]
getCurrentLocation() async {
    Position position = await Geolocator.getCurrentPosition(
        desiredAccuracy: LocationAccuracy.high);
    final coordinates = new Coordinates(position.latitude, position.longitude);
    var addresses =
        await Geocoder.local.findAddressesFromCoordinates(coordinates);
    var first = addresses.first;
    if (this.mounted) {
      setState(() {
        latLng = new LatLng(position.latitude, position.longitude);
        currentAddress = first.featureName +
            " " +
            first.subLocality +
            " " +
            first.subAdminArea;
        countryName = first.countryName.toLowerCase();
        getServices();
      });
    }
  }

**Comment by mvanbeusekom** [comment]
@aTeamSolace what do you mean with "but not working on the above version 9.0 devices", can you describe the symptoms you are experiencing? 

Do you receive an exception? Do you get a timeout? Are you testing on real devices? 

Running the example application on the Android Emulator with API 29 and API 30 works just fine for me.

**Comment by aTeamSolace** [comment]
@mvanbeusekom sorry sir my mistake. The plugin is working fine. Geocoder plugin was not working. Sorry and thanks for response.
