### ISSUE TITLE
Getting the number of satellites

### ISSUE THREAD

**Issue by danilonogueirateixeira** [Baseflow/flutter-geolocator#561]
### Contextualize the feature
All external GPS devices have this information using the NMEA protocol.

### Describe the feature
Number of satellites connected to capture location. This information would be most welcome in order to determine the quality of the signal.

### Platforms affected
- [x] :iphone: iOS
- [X] :robot: Android

**Comment by mvanbeusekom** [comment]
@danilonogueirateixeira thank you for submitting this feature request. 

Do you happen to know if there is an official SDK available on iOS to read the NMEA data?

**Comment by danilonogueirateixeira** [comment]
@mvanbeusekom I don't know ... but this solution on android would be of great help

**Comment by venzeo** [comment]
**iOS** has [no API](https://developer.apple.com/documentation/corelocation/cllocation#//apple_ref/occ/instp/CLLocation/horizontalAccuracy) for that. So at least Android...

**Android** implementation (what is possible can be seen in an Android app "GPS Status"):
- [GNSS STATUS in API 24 and higher](https://developer.android.com/reference/android/location/GnssStatus)
- [GPS Satellite in API 23 and lower](https://developer.android.com/reference/android/location/GpsSatellite)

Thank you in advance for implementing this feature.

**Comment by lukepighetti** [comment]
Please correct me if I'm wrong, but isn't the `accuracy` field a predictor for signal quality?

**Comment by venzeo** [comment]
Goog question @lukepighetti . This is not about accuracy. It is about additional "tech related" information attached to a location. We would like to run some analysis on top of those data.

**Comment by TimHoogstrate** [comment]
Resolved by [1364](https://github.com/Baseflow/flutter-geolocator/pull/1364)
