### ISSUE TITLE
getCurrentPosition without timeLimit give error

### ISSUE THREAD

**Issue by hectorAguero** [Baseflow/flutter-geolocator#564]
## 🐛 Bug Report

Hi, I update to 6.1.2 and if I use `Geolocator.getCurrentPosition` without timeLimit a TimeoutException is throw in 0.0 secs

### Expected behavior

The `getCurrentPosition` method need to mark a `warning ` if `timeLimit `is not set, that's possible with the use of `@required ` on the timeLimit parameter on the package method.

Although at the beginning I thought that without timeLimit getCurrentPosition method await without a timeLimit to obtain the location.

### Reproduction steps

Only I test this, In a Android 11 physical device (Pixel 2 XL), and I test all the desiredAccuracy types.

```dart
 try {
      return await Geolocator.getCurrentPosition(
          desiredAccuracy: LocationAccuracy.low);
    } on TimeoutException catch (e) {
      print('catch getCurrentPosition Timeout Error: $e');
      return null;
    } catch (e) {
      print('catch getCurrentPosition: $e');
      return null;
    }
````

### Configuration

**Version:** Geolocator 6.1.2 - Flutter 1.22.2 
**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by bionara** [comment]
Just noticed the exact same thing and had my long/lat data all messed up. Did some digging and set geolocator_platform_interface back to 1.0.5 . Will try adding the timeLimit as mentioned.

**Comment by ViniciusDS** [comment]
I have exact same problem

**Comment by epiphanatic** [comment]
In addition to having the same problem, if I do set a time limit and the user grants permission before the time limit is up (if they don't then it automatically denies), then I get the following error:

`W/ConnectionTracker(19588): Exception thrown while unbinding
W/ConnectionTracker(19588): java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.measurement.internal.zzjf@6571895
W/ConnectionTracker(19588):     at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1751)
W/ConnectionTracker(19588):     at android.app.ContextImpl.unbindService(ContextImpl.java:1776)
W/ConnectionTracker(19588):     at android.content.ContextWrapper.unbindService(ContextWrapper.java:741)
W/ConnectionTracker(19588):     at com.google.android.gms.common.stats.ConnectionTracker.zza(com.google.android.gms:play-services-basement@@17.3.0:55)
W/ConnectionTracker(19588):     at com.google.android.gms.common.stats.ConnectionTracker.unbindService(com.google.android.gms:play-services-basement@@17.3.0:50)
W/ConnectionTracker(19588):     at com.google.android.gms.measurement.internal.zzin.zzah(com.google.android.gms:play-services-measurement-impl@@17.4.1:246)
W/ConnectionTracker(19588):     at com.google.android.gms.measurement.internal.zzin.zzam(com.google.android.gms:play-services-measurement-impl@@17.4.1:263)
W/ConnectionTracker(19588):     at com.google.android.gms.measurement.internal.zzin.zzc(com.google.android.gms:play-services-measurement-impl@@17.4.1:330)
W/ConnectionTracker(19588):     at com.google.android.gms.measurement.internal.zziq.zza(com.google.android.gms:play-services-measurement-impl@@17.4.1:2)
W/ConnectionTracker(19588):     at com.google.android.gms.measurement.internal.zzah.run(com.google.android.gms:play-services-measurement-impl@@17.4.1:7)
W/ConnectionTracker(19588):     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/ConnectionTracker(19588):     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ConnectionTracker(19588):     at com.google.android.gms.measurement.internal.zzfy.run(com.google.android.gms:play-services-measurement-impl@@17.4.1:21)`

**Comment by Tzanker** [comment]
Ive also gotten the same issue

**Comment by mvanbeusekom** [comment]
Thank you for reporting this issue. I have made a small mistake when setting up the timeout on the `getCurrentPosition` method. 

I have released an update of the `geolocator_platform_interface` package (v1.0.6+1) which includes a fix. To fix this you might need to run `flutter pub get` to update your packages. After that this issue should be solved and the timeout settings should be respected:

1. If the `timeLimit` parameter is not supplied, no timeout will occur and the `getCurrentPosition` method will wait until it receives the first location;
2. If a `timeLimit` is supplied the `getCurrentPosition` will throw a `TimeoutException` when the time limit is reached before a location is returned.

Apologies for the inconvenience.

**Comment by Tzanker** [comment]
Awesome it works! Thanks!

**Comment by mvanbeusekom** [comment]
Happy to hear, thank you for confirming @Tzanker

**Comment by bionara** [comment]
Awesome! This is a great package - thank you!
