### ISSUE TITLE
Version 6.1.2 error google services

### ISSUE THREAD

**Issue by EDnny12** [Baseflow/flutter-geolocator#565]
I update to version 6.1.2 :
java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.measurement.internal.zzjf@8abdfe9

**Comment by mvanbeusekom** [comment]
Thank you for reporting this issue. I have made a small mistake when setting up the timeout on the `getCurrentPosition` method. 

I have released an update of the `geolocator_platform_interface` package (v1.0.6+1) which includes a fix. To fix this you might need to run `flutter pub get` to update your packages. After that this issue should be solved and the timeout settings should be respected:

1. If the `timeLimit` parameter is not supplied, no timeout will occur and the `getCurrentPosition` method will wait until it receives the first location;
2. If a `timeLimit` is supplied the `getCurrentPosition` will throw a `TimeoutException` when the time limit is reached before a location is returned.

Apologies for the inconvenience.
