### ISSUE TITLE
geolocator example code is from a different plugin

### ISSUE THREAD

**Issue by explorova** [Baseflow/flutter-geolocator#570]
## 🐛 Bug Report

geolocator example does not reference geolocator functionality

### Expected behavior

geolocator example does reference geolocator functionality

### Reproduction steps

go here -> https://pub.dev/packages/geolocator/example

### Configuration

**Version:** 6.1.3

**Comment by mvanbeusekom** [comment]
Duplicate of issue #547. 

Closing this issue as further progress will be tracked in #547
