### ISSUE TITLE
[iOS] openLocationSettings doesn't redirect to the proper section

### ISSUE THREAD

**Issue by jjboy91** [Baseflow/flutter-geolocator#572]
## 🐛 Bug Report

When openLocationSettings is called the method redirect to the general section of the settings.

### Expected behavior
Expected to redirect to confidentiality > location services
![IMG_BF6829DD7E17-1](https://user-images.githubusercontent.com/19731153/97853861-fc94a800-1cf8-11eb-9812-e217becd288c.jpeg)

### Reproduction steps
Call the method

### Configuration

**Version:** 
geolocator: 6.1.2
flutter: 1.22.2

**Platform:** 
- [X] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @jjboy91, that is correct. Unfortunately Apple doesn't allow you to redirect users to a direct settings pages. 

This is also mentioned in the README.md in the [Settings](https://github.com/Baseflow/flutter-geolocator#settings) section:

>On iOS we are not allowed to open specific setting pages so both methods will redirect the user to the Settings App from where the user can navigate to the correct settings category to update permissions or enable/ disable the location services.

So unfortunately this is not something we can fix.
