### ISSUE TITLE
dart analysis: "Don't import implementation files from another package."

### ISSUE THREAD

**Issue by KopiasCsaba** [Baseflow/flutter-geolocator#582]
## 🐛 Bug Report
Dart analysis gives this warning: 
"info: Don't import implementation files from another package."

But it is not possible from the outside of the library to use e.g. the Position class currently without this warning.
I'm new to dart, maybe I'm missing something that could solve this, but I don't see it yet.

### Expected behavior
No warnings.
### Reproduction steps
Just use this library in a dart code with proper typings, and the import will trigger this event.

```dart
import 'package:geolocator_platform_interface/src/models/position.dart';
```
### Configuration

**Version:** 6.1.1

**Platform:** 
- [x] :iphone: iOS
-  [x] :robot: Android

Thank you for this lib by the way!

**Comment by mvanbeusekom** [comment]
Hi @KopiasCsaba, 

In general you should not import the `package:geolocator_platform_interface/src/models/position.dart` directly. Simply change it to:

```dart
import 'package:geolocator/geolocator.dart`; 
```

This import will export all required public types needed to work with the geolocator library. If you only need the `Position` type (e.g. for a wrapper class, or to communicate position information to other parts of your code) and you don't want to expose the whole library you can selectively import the geolocator library like so:

```dart
import 'package:geolocator/geolocator.dart' show Position;
```

For more information have a look at the official Dart [documentation](https://dart.dev/guides/language/language-tour#using-libraries).

**Comment by KopiasCsaba** [comment]
Oh!

I'm really grateful to you for the clarification!

**Comment by kamleshwebtech** [comment]
> Hi @KopiasCsaba,
> 
> In general you should not import the `package:geolocator_platform_interface/src/models/position.dart` directly. Simply change it to:
> 
> ```dart
> import 'package:geolocator/geolocator.dart`; 
> ```
> 
> This import will export all required public types needed to work with the geolocator library. If you only need the `Position` type (e.g. for a wrapper class, or to communicate position information to other parts of your code) and you don't want to expose the whole library you can selectively import the geolocator library like so:
> 
> ```dart
> import 'package:geolocator/geolocator.dart' show Position;
> ```
> 
> For more information have a look at the official Dart [documentation](https://dart.dev/guides/language/language-tour#using-libraries).

Dear this did not help me /solved my problem. I am using file_picker package and importing it as you suggested:

import 'package:file_picker/file_picker.dart' show FilePicker, FilePickerResult, FileType;

but still getting "Don't import implementation files from another package." error in "generated_plugin_registrant.dart" file.

Kindly suggest what is the issue and how can we fix it. Thanks a lot.

**Comment by mvanbeusekom** [comment]
@kamleshwebtech this seems to be a problem in the `generated_plugin_registrant.dart`. There is nothing in the error message that suggests the problem is related to the `geolocator` or the `file_picker` plugin. It would help if you could give some more details. Things that would be helpful are:

- output of the `flutter doctor -v` command;
- the actual contents of the `generated_plugin_registrant.dart` file.

Also note that this file is generated by flutter and is required to register plugins that support the web platform. Since it is generated you should not be editing it yourself.
