### ISSUE TITLE
Android crash on permission deny for high accuracy

### ISSUE THREAD

**Issue by zubers1128** [Baseflow/flutter-geolocator#587]
Hi,

I am getting crash issue on deny of high accuracy permission popup.
I am using getPositionStream to continuously watch the current position and it gives many popups of allowing high accuracy.
When I click on deny of last popup the app get crashed.

Here's my code.

```dart
StreamSubscription positionStream;
    try {
      print('inside try $gpsErrRun');
        positionStream = Geolocator.getPositionStream()
            .listen((Position position) {
          if (currentState != AppLifecycleState.inactive) {
            if (currentState != AppLifecycleState.paused) {
              if (gpsError == false) {
                Geolocator.getCurrentPosition(
                        desiredAccuracy: LocationAccuracy.high,
                        //timeLimit: Duration(seconds: 3)
                        )
                    .then((value) {
                },onError: (error){
                  print('error 343 $error');
                  positionStream.cancel();
                }).catchError((onError) async {
                });
              }
            }
          }
        });
        positionStream.onError((handleError) {
          setState(() {
            gpsError = false;
          });
        });
    } catch (e) {
         print(e);
    }
```

**Comment by mvanbeusekom** [comment]
@zubers1128 thank you for reporting this issue, however with the current information it is a bit difficult to reproduce the issue. Could you provide the following questions:

1. Are you testing on Android or iOS?
2. Can you include the output of the `flutter doctor -v` command?
3. What is the reason for doing the call to `Geolocator.getCurrentPosition` inside the `listen`?

**Comment by mvanbeusekom** [comment]
Closing due to lack of response, I would be happy to reopen the issue once requested information is provided.
