### ISSUE TITLE
Confidence Feature

### ISSUE THREAD

**Issue by csarigumba** [Baseflow/flutter-geolocator#589]
Hey guys, is there a way we can retrieve the confidence level when retrieving the GPS position?

For instance, I'd want the library to also return the confidence (0-100%) of the longitude and latitude returned? 

Thanks.

**Comment by mvanbeusekom** [comment]
Hi @csarigumba, thank you for your question and interest.

Is the accuracy parameter not what you are looking for?

Otherwise do you know of any Android/iOS API that can provide this information?

**Comment by mvanbeusekom** [comment]
Closing due to lack of response, I would be happy to reopen the issue once requested information is provided.
