### ISSUE TITLE
EnableBackgroundLocationUpdates not set

### ISSUE THREAD

**Issue by markbeij** [Baseflow/flutter-geolocator#592]
According to @mvanbeusekom `EnableBackgroundLocationUpdates` should automatically be set in the Info.plist when following the instructions in the [readme](https://github.com/Baseflow/flutter-geolocator/blob/master/README.md)

> If you would like to receive updates when your App is in the background, you'll also need to add the Background Modes capability to your XCode project (Project > Signing and Capabilities > "+ Capability" button) and select Location Updates. Be careful with this, you will need to explain in detail to Apple why your App needs this when submitting your App to the AppStore. If Apple isn't satisfied with the explanation your App will be rejected.

See: https://github.com/Baseflow/flutter-geolocator/issues/453#issuecomment-725515191

I don't see this happening in Xcode Version 12.1 (12A7403). All it does is setting the UIBackgroundModes:
<img width="291" alt="image" src="https://user-images.githubusercontent.com/20302465/99041715-b575a500-258b-11eb-9aa4-d9532b539dc5.png">

Should the readme be changed?

**Comment by mvanbeusekom** [comment]
Hi @markbeij, the readme is correct, I made a mistake when saying "`EnableBackgroundLocationUpdates` should automatically be set in the Info.plist". What I should have said was that by following the instructions in the readme, Xcode will add the `UIBackgroundModes` key with value `location` to the Info.plist.

If you do so, the geolocator plugin will automatically set the `allowsBackgroundLocationUpdates` property of the `CLLocationManager` class (more info [here](https://developer.apple.com/documentation/corelocation/cllocationmanager/1620568-allowsbackgroundlocationupdates?language=objc)) to `YES`.

Does this make sense?
