### ISSUE TITLE
Can I use this plugin for server-side coding?

### ISSUE THREAD

**Issue by k0302** [Baseflow/flutter-geolocator#599]
I have  GPS coordinates of users' addresses saved in firestore. If a new user registers, I need to search for old users who live within a certain radius from the new user and notify them. And the code might need to be written in server-side(at index.js file). For that, do I have to install this plugin at package.json folder and write code to get users who live nearby at index.js file? I'm new to server-side coding, so any help is appreciated.

**Comment by mvanbeusekom** [comment]
@k0302, no you cannot use this plugin on the server-side. The plugin relies on the Android and iOS SDKs installed on the mobile devices to determine the position of those devices.

Also this plugin is a Flutter plugin (for use with the Flutter framework) not a NodeJS package (which I assume you are using for the server-side implementation). Lastly it looks like you are trying to solve the problem of determining which locations are in a certain radius of a given position, which is not the purpose of this plugin.

I am assuming you are trying to use the `distanceBetween` method from the geolocator plugin. To do something similar on Javascript maybe this will help: https://medium.com/@RichLloydMiles/calculate-the-distance-between-two-points-on-earth-using-javascript-38e12c9a0f52

**Comment by k0302** [comment]
Thanks for your reply. The site asks me to pay at least $5 for this content. Do you think it's worth the money? Does it give actual code?

**Comment by mvanbeusekom** [comment]
Open the link in a private browser (or incognito mode) and you'll bypass the payment.

**Comment by k0302** [comment]
Hi, https://stackoverflow.com/questions/62415394/firebase-cloud-function-sending-push-notifications-with-geo-location
This may be the answer to my question. But I don't know how to create 'geofire.js' that MarkT is referring to. I thought 'geofire.js' is a plugin that needs to be added in 'package.json' file. Since I don't know much about this cloud function, would you check it and give me your opinion?

**Comment by mvanbeusekom** [comment]
This article is discussing Google Cloud Functions that are basically functions (mostly written in JavaScript) that you can host in the Google Cloud.

You can then add configuration which will trigger these functions based on a certain event (e.g. when a request is made to a URL, when a database record is inserted or modified, when a time interval expires and more).

You will need to write these functions yourself and indeed might be a good solution for you. However explaining how this works in detail is way out of scope for this plugin and I suggest you look up some tutorials for developing with Google Cloud Functions (or if you prefer you can do similar solutions for Azure or AWS).
