### ISSUE TITLE
geolocator error in android

### ISSUE THREAD

**Issue by AhmedTahaabdallah** [Baseflow/flutter-geolocator#602]
when i use this version geolocator 6.1.7
in android i get this error when i run my app

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all dependencies for configuration ':app:debugCompileClasspath'.
   > Problems reading data from Binary store in /private/var/folders/_z/3_7d4kw101n9zhsc8rc74st00000gn/T/gradle6893801387785238328.bin offset 540666 exists? true

**Comment by mvanbeusekom** [comment]
@AhmedTahaabdallah this looks to be an issue on your development environment. The provided information is limited but a few things you can try are:

- First think to try is to run `flutter clean` and try to rebuild the app. If the problem persists make sure to check the points below.
- Make sure your project is migrated to AndroidX (https://flutter.dev/docs/development/androidx-migration);
- Make sure your Android project uses gradle version 3.5.0 and gradle-wrapper 5.6.2.

To check the gradle version take the following steps:
 
1. Open the `build.gradle` file located in you `android` folder and look for the following line:
```
        classpath 'com.android.tools.build:gradle:<version>'
```
2. Make sure you update the `<version>` to version number `3.5.0` (or higher) and save the changes;
3. Next make sure to update the gradle-wrapper by opening the file `gradle-wrapper.properties` file in the `android/gradle/wrapper` folder and look for the line:
```
distributionUrl=https\://services.gradle.org/distributions/gradle-<version>-all.zip
```
4. Make sure the `<version>` part is set to `5.6.2` (so the complete line looks like: `distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip`)
5. Save the changes and run the following commands:

```
# Clean the Flutter project cache to ensure a fresh full build
flutter clean
# Build the Android Flutter application
flutter build apk
```

If this still didn't work please try to provide more information:

1. Output of the `flutter doctor -v` command;
2. Small reproducible example.

Another thing you can try is to create a new flutter project and add the geolocator plugin. If that builds correctly (as it should) you can start comparing your Android files with the new project and see if you can find any differences.

**Comment by mvanbeusekom** [comment]
Closing issue due to lack of response. I would gladly reopen the issue once the requested information is supplied.

**Comment by rjtubera** [comment]
I'm also having the same problem, I did the steps above but to no avail

**Comment by mvanbeusekom** [comment]
Hi @rjtubera,

For us to be able to help you please submit a new issue and list the following information:

- Version of the plugin you are using;
- Output of the `flutter doctor -v` command;
- Contents of your `android/app/build.gradle` file;
- Full stack trace log describing the exception;
- Example code on how you are using the geolocator plugin.
