### ISSUE TITLE
why speed is not available to all devices? 

### ISSUE THREAD

**Issue by bhanuka96** [Baseflow/flutter-geolocator#603]
**The speed is not available on all devices. In these cases the value is  /// 0.0.**

Why speed is unavailable to some devices? How does speed work? 

I am using speed to calculate waiting time on my app. 

```
 if (userLocation.speed <= 2){
    // waiting time calculation
}
```

Is there any way to calculate waiting time using `geolocator`?

**Comment by mvanbeusekom** [comment]
Hi @bhanuka96, 

The geolocator uses the native Android and iOS SDKs to acquire the current position of the device. As per there documentation (specifically on Android) in some cases the speed parameter is not available (unfortunately they don't explain why). See for instance:

- Android: https://developer.android.com/reference/android/location/Location#getSpeed()
- iOS: https://developer.apple.com/documentation/corelocation/cllocation/1423798-speed?language=objc

If you are listening to the position stream you could calculate the speed by comparing the timestamps and calculating the distance between two subsequent positions as an alternative.

Hope this helps.
