### ISSUE TITLE
iOS speed is always returned -1

### ISSUE THREAD

**Issue by web75018** [Baseflow/flutter-geolocator#607]
### Expected behavior
${position.speed.toInt()} => Always returns -1.

### Reproduction steps

```dart
Widget build(_) {
    Size size = MediaQuery.of(context).size;
    return StreamProvider<Position>.value(
      value: getPositionStream(),
      builder: (c, wd) {
        return Consumer<Position>(
          builder: (_, position, __) {
            if (position == null) return SizedBox();

.....
.....

  Row buildRow(Position position) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Icon(FontAwesome.arrow_left,
            size: 44, color: Colors.grey.withOpacity(0.3)),
        **buildRichText(label: "${position.speed.toInt()}"),**
        Icon(FontAwesome.arrow_right,
            size: 44, color: Colors.grey.withOpacity(0.3)),
      ],
    );
  }
```
### Configuration

**Version:**  geolocator: ^6.1.7

**Platform:** 
- [ x] :iphone: iOS

**Comment by daniloapr** [comment]
Hi! This is something from the iOS location library, when the provided location is not from the GPS itself, but it is calculated using the Wi-Fi, the internet signal (3G, 4G...) or the phone reception. Something like the Fused Location API does in the Android.

I suggest you to try it in a physical device under the open sky and make sure you are using the accuracy High. After a while, you should see the real speed.

**Comment by mvanbeusekom** [comment]
@daniloapr thank you for explaining the issue to the OP. I will close the issue for now if there are any questions or other concerns place post them here and I would be glad to reopen the issue.
