### ISSUE TITLE
Please provide complete example with exception handling and permission requests

### ISSUE THREAD

**Issue by giorgio79** [Baseflow/flutter-geolocator#615]
## 💬 Questions and Help
I notice the example does not provide a try catch for handling exceptions when requesting location.

Also, a complete example would be nice:
1. checking if location service enabled
2. checking if permission is granted
3. try getting location and handle exceptions

I am also noticing this package https://pub.dev/packages/location_permissions wonder if it is needed given this package also handled perms

**Comment by mvanbeusekom** [comment]
The geolocator plugin will handle permissions internally, no need for other packages. Also if you try to acquire a location using the `getCurrentPosition` and `getPositionStream` methods, the plugin will automatically request permissions if permissions are not granted and the plugin is allowed to ask. So in general you don't need to worry about checking or requesting permissions yourself. The `checkPermission` and `requestPermission` methods are provided for developers who want to manually check or request permission on a different time and do not really need location information yet. For example during on boarding of users in the app. Although not illegal, this is not recommended by Apple's and Google's guidelines.

Regarding the other points, I will update the example App to do some basic exception handling. Note however that use cases on how to handle exceptions can be very different per application. The `try..catch` is trivial, but how to respond to the exception can be very different per application.

**Comment by giorgio79** [comment]
Thank you! 
Response for most apps will most likely be similar to top apps, like Tinder, that have a "Try again" or sg similar button, when an exception is met. 
I was using the getCurrentPosition, but the iOS App team review rejected it, because they tested with denying the location, and the app crased :)

**Comment by giorgio79** [comment]
Location seems to be providing a nice basic flow https://pub.dev/packages/location
Although I think location permission should be a stream wrapping the entire MaterialApp in case the user decided to deny permission during use.

> In order to request location, you should always check manually Location Service status and Permission status.


```
Location location = new Location();

bool _serviceEnabled;
PermissionStatus _permissionGranted;
LocationData _locationData;

_serviceEnabled = await location.serviceEnabled();
if (!_serviceEnabled) {
  _serviceEnabled = await location.requestService();
  if (!_serviceEnabled) {
    return;
  }
}

_permissionGranted = await location.hasPermission();
if (_permissionGranted == PermissionStatus.denied) {
  _permissionGranted = await location.requestPermission();
  if (_permissionGranted != PermissionStatus.granted) {
    return;
  }
}

_locationData = await location.getLocation();
```

**Comment by giorgio79** [comment]
The full example here is pretty complete https://github.com/Lyokone/flutterlocation/tree/master/location/example/lib

no exceptions when denying location :) For now I switched to Location

**Comment by mvanbeusekom** [comment]
@giorgio79 if that suits you then sure, Location is also an excellent plugin.

Of course you can also use the Geolocator without exception handling in a similar way as Location, but unfortunately that was not obvious enough for you from the documentation. I will still improve the example and documentation to have a more complete flow. 

Just to prove my point, the Location example can be updated to use the Geolocator like this:

```dart
bool _serviceEnabled;
LocationPermission _permission;
Position _position;

_serviceEnabled = await Geolocator.isLocationServiceEnabled();
if (!_serviceEnabled) {
  return;
}

_permission = await Geolocator.checkPermission();
if (_permission == LocationPermission.deniedForever) {
  return;
}

if (_permission == LocationPermission.denied) {
  _permission = await Geolocator.requestPermission();
  if (_permission  != LocationPermission.whileInUse || _permission != LocationPermission.always) {
    return;
  }
}

_position = await Geolocator.getCurrentPosition();
```

**Comment by mvanbeusekom** [comment]
Hi @giorgio79, today I got around updating the README.md and adding an example on how to acquire the device's location while checking if location services and permissions are available. See version 6.1.12 on pub.dev: https://pub.dev/packages/geolocator#example

Might be a bit late for you but I hope other users will appreciate it. Thank you for making me aware of this problem and raising the issue.

**Comment by cedvdb** [comment]
> Just to prove my point, the Location example can be updated to use the Geolocator like this:
> 
> ```dart
>  // ...
> _serviceEnabled = await Geolocator.isLocationServiceEnabled();
> if (!_serviceEnabled) {
>   return;
> }
> ```

That is not the same as the location package, is it ? Here you are not requestingTheService to be enabled

**Comment by mvanbeusekom** [comment]
@cedvdb no it does not. The `Geolocator` will try to enable the location services when calling the `Geolocator.getCurrentPosition()` or `Geolocator.getPositionStream()` methods. If this doesn't work you will receive a `LocationServicesDisabledException`. 

The `Geolocator.isLocationServiceEnabled()` will only return the current status (if the location services are enabled or not). Which is the same behaviour as the `location.serviceEnabled()` of the location package (they provide an extra `location.requestService()` method that we don't offer at the moment).
