### ISSUE TITLE
getCurrentPosition crashes if user denies access to location

### ISSUE THREAD

**Issue by giorgio79** [Baseflow/flutter-geolocator#616]
## 🐛 Bug Report

If the user denies location access, Geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.high) will crash the app
At the moment this bug is preventing my app submission to the Apple store. They are testing what happens if the user denies access...

```

[   +1 ms] I/flutter ( 2765): [2020-12-01 18:19:12.999245 | ConsoleHandler | INFO] Crash occured on 2020-12-01 18:19:12.927568
[        ] I/flutter ( 2765): [2020-12-01 18:19:12.999441 | ConsoleHandler | INFO] 
[   +5 ms] I/flutter ( 2765): [2020-12-01 18:19:13.002494 | ConsoleHandler | INFO] ---------- ERROR ----------
[        ] I/flutter ( 2765): [2020-12-01 18:19:13.002845 | ConsoleHandler | INFO] User denied permissions to access the device's location.
[        ] I/flutter ( 2765): [2020-12-01 18:19:13.003005 | ConsoleHandler | INFO] 
[  +12 ms] I/flutter ( 2765): [2020-12-01 18:19:13.015963 | ConsoleHandler | INFO] ------- STACK TRACE -------
[   +8 ms] I/flutter ( 2765): [2020-12-01 18:19:13.027411 | ConsoleHandler | INFO] #0      MethodChannelGeolocator._handlePlatformException (package:geolocator_platform_interface/src/implementations/method_channel_geolocator.dart:198:9)
[   +1 ms] I/flutter ( 2765): [2020-12-01 18:19:13.029490 | ConsoleHandler | INFO] #1      MethodChannelGeolocator.getCurrentPosition (package:geolocator_platform_interface/src/implementations/method_channel_geolocator.dart:121:7)
[   +1 ms] I/flutter ( 2765): [2020-12-01 18:19:13.030678 | ConsoleHandler | INFO] <asynchronous suspension>
[  +14 ms] I/flutter ( 2765): [2020-12-01 18:19:13.030869 | ConsoleHandler | INFO] #2      Geolocator.getCurrentPosition (package:geolocator/geolocator.dart:258:35)
```

### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @giorgio79,

This is expected behaviour and documented [here](https://pub.dev/documentation/geolocator/latest/geolocator/Geolocator/getCurrentPosition.html) (this should also pop-up in you IDE when you select the `getCurrentPosition` method from the intelli sense menu):

> Throws a PermissionDeniedException when trying to request the device's location when the user denied access. Throws a LocationServiceDisabledException when the user allowed access, but the location services of the device are disabled.

You should simple add a try..catch and handle the error anyway you see fit.
