### ISSUE TITLE
Can get location in background mode or foreground mode?

### ISSUE THREAD

**Issue by bhanuka96** [Baseflow/flutter-geolocator#617]
Is it possible to get data or listen on background / forground?

**Comment by mvanbeusekom** [comment]
no this is not supported (yet). 

There is an open feature request (#53) but I haven't had the time to implement it as of yet. We are very much open for contributions from the community but this seems to be a though nut to crack and we have had not contributions as of yet.

I will be closing this issue in favor of tracking progress in issue #53

**Comment by bhanuka96** [comment]
@mvanbeusekom Thanks for your time
