### ISSUE TITLE
getInitialLocation issue

### ISSUE THREAD

**Issue by Qussdz** [Baseflow/flutter-geolocator#618]
Hello everyone ! 

i'm a begginner in flutter and i'm working on an application. I'm following some tutorials, but lot of geolocator functiuns that i find are depreciated, and i have a problem with one of em.

**The file : Map** 
```dart
class Map extends StatefulWidget {
  final Position initialPosition;

  Map(this.initialPosition);

  @override
  State<StatefulWidget> createState() => _MapState();
}

class _MapState extends State<Map> {
  final GeolocatorService geoService = GeolocatorService();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: GoogleMap(
          initialCameraPosition: CameraPosition(
              target: LatLng(widget.initialPosition.longitude,
                  widget.initialPosition.latitude),
              zoom: 18.0),
          mapType: MapType.normal,
        ),
      ),
    );
  }
}
```

**The file: Main**
```dart
void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  final geoService = GeolocatorService();
  @override
  Widget build(BuildContext context) {
    return FutureProvider(
      create: (context) => geoService.getInitialLocation(),
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        title: 'Metz Trip',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: Map(),
        // home: MyHomePage(title: 'Metz Trip'),
      ),
    );
  }
}
```

**the error i get:** 
`The method 'getInitialLocation' isn't defined for the type 'GeolocatorService'.
Try correcting the name to the name of an existing method, or defining a method named 'getInitialLocation'.`

i think that the getInitialLocation function is deprecated but i dont find with what i can replace it, i wish if someone could help me.

Thank you

**Comment by mvanbeusekom** [comment]
@MehdiSoulimane welcome to Flutter, I hope you are enjoying your experience so far.

Unfortunately the class and method you mention, are not (and never have been) part of the Geolocator plugin. This leads me to think you are mixing up plugins at the moment. 

Are you sure you are using the Geolocator plugin? You can check this in your `pubspec.yaml` file. If you are using the Geolocator plugin you should be able to find a line like below (version number might be different): 

```yaml
  geolocator: 6.1.9
```

If you were using the Geolocator, your code should look something like this:

**The file: Map**
```dart
class Map extends StatelessWidget {
  final Position initialPosition;

  Map(this.initialPosition);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: GoogleMap(
          initialCameraPosition: CameraPosition(
              target: LatLng(widget.initialPosition.longitude,
                  widget.initialPosition.latitude),
              zoom: 18.0),
          mapType: MapType.normal,
        ),
      ),
    );
  }
}
```

**The file: Main**
```dart
void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return FutureBuilder<Position>(
      future: Geolocator.getCurrentPosition,
      builder: (context, snapshot) {
        if (snapshot.hasData) {
          return MaterialApp(
            debugShowCheckedModeBanner: false,
            title: 'Metz Trip',
            theme: ThemeData(
              primarySwatch: Colors.blue,
            ),
            home: Map(snapshot.data),
        // home: MyHomePage(title: 'Metz Trip'),
          );
        } else if (snapshot.hasError) {
          // TODO: handle the error (i.e. show a widget or try again)...
        } else { 
          // TODO: No result yet, show an indication we are waiting for location to be fetched...
        }
     }
  }
}
```

**Comment by Qussdz** [comment]
Thank you for your answer,
yes in the code i linked to my  first message i'm using Geolocator plugin (and provider)

`  geolocator: ^6.1.8
  provider: ^4.3.2+2`

**Comment by mvanbeusekom** [comment]
ok that makes sense. 

First you receive the error because your `GeolocatorService` class doesn't have a method called `getInitialLocation`. Which is correct if I look at the `GeolocatorService` class you submitted.

Second I see you have simply copied the implementation of the `getPositionStream` method and added it to your `GeolocatorService`. Of course you are allowed to do this (meaning our licenses are not forbidding you to do so) but it is not the easiest way to do it and you would potentially miss out on improvements we make in the implementation. Since you are using the `Provider` plugin (note I am not really familiar with it) I think your goal is to wrap the static class in a class you can instantiate. If that is the case your would probable do something like this:

```dart
class GeolocatorService {

  Future<Position> getLastKnownPosition(
          {bool forceAndroidLocationManager = false,
  }) => Geolocator.getLastKnownPosition(
        forceAndroidLocationManager: forceAndroidLocationManager);

  Future<Position> getCurrentPosition({
    LocationAccuracy desiredAccuracy = LocationAccuracy.best,
    bool forceAndroidLocationManager = false,
    Duration timeLimit,
  }) => Geolocator.getCurrentPosition((
        desiredAccuracy: desiredAccuracy,
        forceAndroidLocationManager: forceAndroidLocationManager,
        timeLimit: timeLimit,
      );

  Stream<Position> getPositionStream({
    LocationAccuracy desiredAccuracy = LocationAccuracy.best,
    int distanceFilter = 10,
    bool forceAndroidLocationManager = false,
    int timeInterval = 0,
    Duration timeLimit,
  }) => Geolocator.getPositionStream(
        desiredAccuracy: desiredAccuracy,
        distanceFilter: distanceFilter,
        forceAndroidLocationManager: forceAndroidLocationManager,
        timeInterval: timeInterval,
        timeLimit: timeLimit,
      );
}
```

**Comment by Qussdz** [comment]
Perfect, you've made things clear for me.

Thank you for your help.

**Comment by mvanbeusekom** [comment]
Cool, glad I could help. I will close this issue for now but don't hesitate to leave another comment if you run into something else.
