### ISSUE TITLE
Geolocator Plugin is showing deprecated during build

### ISSUE THREAD

**Issue by BankySam** [Baseflow/flutter-geolocator#623]
I tried building my app and boom, error occurs during build. But the apk builds successfully but doesn't load on smartphone. I need help
``
Note: C:\Users\Banky\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\geolocator-6.1.12\android\src\mai
n\java\com\baseflow\geolocator\GeolocatorPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by mvanbeusekom** [comment]
@BankySam I have just released version 6.1.13 of the geolocator which resolves all the deprecation warnings. They were not problematic and was part of code that is only used when compiling your App with older Flutter versions, so I don't think this is what makes your App crash.

Do you have any additional logs showing the actual error? Something you could try is running the App from the Java/ Kotlin side. You can do this by using Android Studio (or IntelliJ IDEA):

1. Start Android Studio;
2. Select the option "Open an Existing Project";
3. Browse to the "android" folder in your App;
4. Click the "Open" button.

This will load the App from the Android (Java/ Kotlin) perspective. Now if you start debugging your App you will get all the log information from the Java/ Kotlin side in the "Debug" pane. This might give some additional information (i.e. exception or error messages) on why your App is crashing. 

For us to be able to help you it would be nice if we can receive this additional information. Also please include the output of the `flutter doctor -v` command.

**Comment by BankySam** [comment]
hello Baseflow/flutter-geolocator.
Thanks for the clarity and the speedy response.
You save me a lot of hassle. I love you guys

I have an issue:
I am trying to get my current location using the geolocator.
My code works perfectly, but When I run my app on the android emulator, it
shows the googolplex location .
I also added my permission to the android manifest file. But still couldn’t
show my current location.

**Comment by mvanbeusekom** [comment]
Hi @BankySam, thank you for these compliments. That is really awesome.

Regarding the location in the emulator. The Android location is emulated and can be set (or configured) to any location you like using the emulator settings (in the "Location" tab). A detailed description can be found here: https://stackoverflow.com/a/61573119/5167831

**Comment by BankySam** [comment]
Ohh 😲
Awesome thanks so much, checking it out right now
