### ISSUE TITLE
Getting location permission status as 'denied' but actually it is 'denied forever' on android 9.

### ISSUE THREAD

**Issue by dhanrajVerma** [Baseflow/flutter-geolocator#626]
## 🐛 Bug Report

On requesting for location permission I got system pop-up with two choice
1. allow
2. deny
when I choose 'deny' and handle my app accordingly. But when I request permission again then system pop-up have three options,**allow**, **deny**, and a  checkbox  saying 'don't ask again'. I choose deny with "don't ask again" checked.
Then I am getting permission status as "denied" in Geolocator.checkpermission() api but it should be denied forever.

**Version:** 6.1.1

**Platform:** 
- [ ] :robot: Android 9

**Comment by mvanbeusekom** [comment]
@dhanrajVerma this was indeed a problem but has been solved in version 6.1.5 of the geolocator (released on the 5th of November).

**Comment by yoseptara** [comment]
Hello this issue occurs again in Geolocator 7.0.1

**Comment by mvanbeusekom** [comment]
@yoseptara yes starting from version 7.0.0 we updated the permission flow. The change is documented [here](https://github.com/Baseflow/flutter-geolocator/wiki/Breaking-changes-in-7.0.0#android-permission-update).
