### ISSUE TITLE
Get Current Position Method Is Always Seems Returning last Known Location

### ISSUE THREAD

**Issue by ixsans** [Baseflow/flutter-geolocator#629]
## 🐛 Bug Report

I'm using iOS simulator (iPhone 11) with custom location. I set it from simulator menu `Features > Location > Custom Location`. 
![Screenshot 2020-12-16 at 5 58 44 PM](https://user-images.githubusercontent.com/7322066/102339850-5a8aff80-3fc8-11eb-86ab-0e29e523a568.png)

I tried to fetch current location and it returning a correct location value.

But I want to simulate when i lost location by switch it from custom location to no location using simulator menu.
`Features > Location > None`

![Screenshot 2020-12-16 at 5 58 07 PM](https://user-images.githubusercontent.com/7322066/102339786-434c1200-3fc8-11eb-941e-c0d82e97373e.png)

The issue was: When i fetch current location with `None` location, it still returning the same location value as i fetched before. 

My assumption was: `getCurrentPosition` method Is always returning last known location. Because when i don't have last known location and no current location it will finding current location until timeout

### Expected behavior

 When i fetch current location with `None` location, it should returning `null` value or catched as an exception.

### Reproduction steps

1. Run code in iOS Simulator
2. Set custom location from simulator menu `Features > Location > Custom Location`
3. Fetch current location by invoking `Geolocator.getCurrentPosition()`
4. Set no location from simulator menu `Features > Location > None`
5. Fetch current location by invoking `Geolocator.getCurrentPosition()`

### Configuration

**Version:** 1.22.3

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H15, locale en-SG)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Android Studio (version 4.0)
[✓] Connected device (1 available)
• No issues found!
```

**Platform:** 
- [*] :iphone: iOS
- [ ] :robot: Android

**Comment by mislavlukach** [comment]
+1
Experiencing this as well.

**Comment by wanggang-cnkj** [comment]
+1, Same here
Version:
  geolocator:
    dependency: "direct main"
    description:
      name: geolocator
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "5.3.2+2"

**Comment by A-Azizi79** [comment]
same...

**Comment by florissmit1** [comment]
I can reproduce the same issue on an iPhone 11 Simulator and on a physical iPad Air. I'm looking into the issue.

**Comment by A-Azizi79** [comment]
> I can reproduce the same issue on an iPhone 11 Simulator and on a physical iPad Air. I'm looking into the issue.

did you solve the problem?

**Comment by bdairy** [comment]
Same here
