### ISSUE TITLE
Using bearingBetween as a compass?

### ISSUE THREAD

**Issue by giorgio79** [Baseflow/flutter-geolocator#635]
I am trying to use the bearingBetween result as a compass direction to a point. Is the output sufficient?

Looking at stackoverflow there seem to be a lot of additional stuff going into the calc:

- https://stackoverflow.com/questions/4308262/calculate-compass-bearing-heading-to-location-in-android
- https://github.com/Lyokone/flutterlocation/issues/114

**Comment by diegogarciar** [comment]
I have this:

```
double didUpdateHeading(double newHeading) {
    if (lastLocation != null && targetLocation != null) {
      final angle = Geolocator.bearingBetween(
              lastLocation.latitude,
              lastLocation.longitude,
              targetLocation.latitude,
              targetLocation.longitude)
          .bounded;

      return -newHeading.bounded + angle;
    }
    return null;
  }
  
  extension on double {
  double get bounded {
    if (this > 180) {
      return this - 360;
    }
    return this;
  }
}
  
```

I use bounded to shift the angle into the "-180" - "180" range

**Comment by mvanbeusekom** [comment]
Solution provided by @diegogarciar look solid, will close this issue for now. Happy to reopen it when follow up is required.

**Comment by giorgio79** [comment]
Hi @diegogarciar  thanks for the snipprt. Could you post a full working example? :)
