### ISSUE TITLE
Filter GPS coordinates

### ISSUE THREAD

**Issue by jjboy91** [Baseflow/flutter-geolocator#637]
## 💬 Questions and Help

Hi,
I'm using the plugin to track my daily movements coordinate by coordinate just for learning purposes.
I'm wondering if there is a way to filter the coordinates that are too far from the main track (cell towers as an example) before dispatching the new location event ?

**Comment by Sempakonka** [comment]
Is the `distanceFilter` what you are looking for? _from documentation:_  `the minimum distance (measured in meters) a device must move horizontally before an update event is generated`

**Comment by hordeariibarley** [comment]
@jjboy91 I believe that you are looking for it:
https://github.com/rekab-app/background_locator/issues/74
You can use a Kalman Filter on these cases
