### ISSUE TITLE
forceAndroidLocationManager:true  application hang

### ISSUE THREAD

**Issue by KrishnendraPrakash** [Baseflow/flutter-geolocator#644]
## 🐛 Bug Report

application hang

### Reproduction steps
 await Geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.best, forceAndroidLocationManager:true);

### Configuration

**Version:** 6.1.13

**Platform:** 
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
Check your permissions in AndroidManifest file. See also issue #641

**Comment by KrishnendraPrakash** [comment]
I have follow all conditions and checks mentioned :   

<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
