### ISSUE TITLE
getCurrentPosition is not working really fine on Android, &  IOS it took so much time to execute. 

### ISSUE THREAD

**Issue by ashishoffice** [Baseflow/flutter-geolocator#648]
### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
Please help us help you and fill out the complete issue template.

Provide a clear description of your issue, supply reproduction steps, version information and output of the `flutter doctor -v` command.

Issues missing this information will not be taken seriously and will be closed.

If the requested information is supplied I will reopen the issue.
