### ISSUE TITLE
pub get failed (1; Because sgim depends on geolocator ^6.1.14 which doesn't match any versions, version solving failed.)

### ISSUE THREAD

**Issue by 594904020** [Baseflow/flutter-geolocator#651]
flutter pub get error :

pub get failed (1; Because projectName depends on geolocator ^6.1.14 which doesn't match any versions, version solving failed.)

**Comment by mvanbeusekom** [comment]
You are not really providing a lot of information for me to go on.

Version 6.1.14 does exists and is available in pub.dev: https://pub.dev/packages/geolocator

**Comment by 594904020** [comment]
谢谢，已解决。我降低了版本为6.1.13

**Comment by Basher7** [comment]
When I want to upgrade my geolocator version to latest but flutter pub get failed to download geolocator v6.1.14. 
**Exact error throw in log** 

> Because myapp depends on geolocator ^6.1.14 which doesn't match any versions, version solving failed.
> pub get failed (1; Because myapp depends on geolocator ^6.1.14 which doesn't match any versions, version solving failed.)
> exit code 1

this also happen if for newly created app.

**Comment by 594904020** [comment]
> 当我想将我的geolocator版本升级到最新版本，但是flutter pub却无法下载geolocator v6.1.14。
> **日志中准确抛出错误**
> 
> > 由于myapp依赖于与任何版本都不匹配的geolocator ^ 6.1.14，因此版本解析失败。
> > pub get failed（1；因为myapp依赖于与任何版本都不匹配的geolocator ^ 6.1.14，所以版本解析失败。）
> > 退出代码1
> 
> 新创建的应用程序也会发生这种情况。
Use 6.1.13 can solve the problem
