### ISSUE TITLE
getCurrentPosition does not work when mock location is enabled

### ISSUE THREAD

**Issue by edwinmacalopu** [Baseflow/flutter-geolocator#660]
## 🐛 Bug Report

getCurrentPosition doesn't work when the mock location is activated using an application like FakeGPS, but if I don't use the mock location getCurrentPosition if it returns the coordinates correctly. the problem is when I use the simulated location it does not catch any coordinates nor do I catch the error with the try catch.

```
try {
      position = await Geolocator.getCurrentPosition(
          desiredAccuracy: LocationAccuracy.high);
    } catch (e) {
      print(e.toString());
    }

```
### Expected behavior
 Capture false coordinates and true ismocked
### Configuration
Channel beta, 1.26.0-17.3.pre
Samsung A30 , android 10

**Version:** 6.2.0

**Platform:** 
- [ ] :iphone: iOS
- [ x] :robot: Android

**Comment by JDDV** [comment]
Mock location only works for GPS, it will not fake any other provider. Specifically it will not fake the NETWORK location provider. By using LocationAccuracy.high the Android implementation will use GPS and network to determine the current position. By using LocationAccuracy.lowest the implementation will only listen to GPS positions. Hope this will help!

**Comment by mvanbeusekom** [comment]
@JDDV this is incorrect, starting from `LocationAccuracy.high` and above the Geolocator is more likely to use the GPS system then on lower accuracies (according to the Android [documentation](https://developers.google.com/android/reference/com/google/android/gms/location/LocationRequest)):

>The priority of the request is a strong hint to the LocationClient for which location sources to use. For example, PRIORITY_HIGH_ACCURACY is more likely to use GPS, and PRIORITY_BALANCED_POWER_ACCURACY is more likely to use WIFI & Cell tower positioning, but it also depends on many other factors (such as which sources are available) and is implementation dependent.

This means your explanation is not correct, when using the `LocationAccuracy.lowest` the Android location services are very likely NOT to use the GPS provider.

**Comment by danielroek** [comment]
When testing this it did look like setting `LocationAccuracy.lowest` solved the issue. But @mvanbeusekom is right. 

The LocationRequest documentation states: 

> Applications cannot specify the exact location sources, such as GPS, that are used by the LocationClient. In fact, the system may have multiple location sources (providers) running and may fuse the results from several sources into a single Location object.

I'm not sure about how Android handles this exactly, but it might help to try and turn off WiFi AND turn off "Scanning always available" in the WiFi-preferences. That would prevent the app from using WiFi networks to determine the location of the device.

**Comment by danielroek** [comment]
I'm going to close this issue. We are not able to solve this with a new feature, as Android does not allow to define the source of the location client. @edwinmacalopu I hope the answer above helps.
