### ISSUE TITLE
Add "provider" property (aka "source", aka "origin") to Position object

### ISSUE THREAD

**Issue by Tomucha** [Baseflow/flutter-geolocator#671]
## 🚀 Feature Requests

Please add "provider" property to the Position class. Property should contain the source of the location update: gps, network, wifi, ...

**Comment by mvanbeusekom** [comment]
Hi @Tomucha, I have been looking into this earlier as well. However I don't think it is possible to get this information in a reliable way on iOS and Android using the `FusedLocationProviderClient` implementation (I think only with the old `LocationManager` implementation you could probably be certain which provider was used).

If you could point me to some documentation on how to accomplish this I would be happy to have a look.

**Comment by Tomucha** [comment]
@mvanbeusekom Unfortunately that's above my expertise, I'm just a humble user of your package. Nevermind.

**Comment by mvanbeusekom** [comment]
I closed the issue for now. If you do happen to stumble onto something please let me know and maybe we can figure something out.
