### ISSUE TITLE
How to detect Mock location using isMocked property

### ISSUE THREAD

**Issue by FaizanMubasher** [Baseflow/flutter-geolocator#675]
This is what I am trying to do:
```
Future<Position> _determinePosition() async {
bool serviceEnabled;
LocationPermission permission;

serviceEnabled = await Geolocator.isLocationServiceEnabled();
if (!serviceEnabled) {
  return Future.error('Location services are disabled.');
}

permission = await Geolocator.checkPermission();
if (permission == LocationPermission.deniedForever) {
  return Future.error(
      'Location permissions are permanently denied, we cannot request permissions.');
}

if (permission == LocationPermission.denied) {
  permission = await Geolocator.requestPermission();
  if (permission != LocationPermission.whileInUse &&
      permission != LocationPermission.always) {
    return Future.error(
        'Location permissions are denied (actual value: $permission).');
  }
}
return await Geolocator.getCurrentPosition(
    desiredAccuracy: LocationAccuracy.high);
}
```

And call it like:

`_determinePosition().then((position) {
  if (position.isMocked) {
    //.. Show error message
    return;
  }`

But this if is never executed. Please guide how to detect Mock location correctly. I have FAKE GPS App and Mock Location turned on as well.

[SO Post](https://stackoverflow.com/questions/66347602/how-to-detect-mock-location-in-flutter-using-geolocator-plugin)

**Comment by siva999999999** [comment]
i am trying to make a fake Gps app but i am not getting how can i change location to google maps location and how can i get moack permission to my app? is it possible to do Fake gps app with flutter if not i will leave flutter and go to native development? please help me
