### ISSUE TITLE
Is this plugin also using wifi siginal or phone siginal to speed up the location

### ISSUE THREAD

**Issue by function2000** [Baseflow/flutter-geolocator#677]
Is this plugin also using wifi siginal or phone siginal to speed up the location?

For example, if I am in the building, it is very slow to get the location updated.  If outside, it is no problem.  Therefore I ask if possible to use wifi or cell phone siginal to speed it up.

Thanks!

**Comment by mvanbeusekom** [comment]
Yes it does for both iOS and Android. The later only if the target device has Google Play Services installed and you are not explicitly forcing the use of the LocationManager SDK (e.g. by setting the `forceAndroidLocationManager` parameter of the `getCurrentPosition` or `getPositionStream` methods to `true`).

For one of the Baseflow App we are the plugin in combination with WiFi location services to handle indoor navigation in large buildings which works extremely well.
