### ISSUE TITLE
isLocationServiceEnabled = true but error "The location service on the device is disabled"

### ISSUE THREAD

**Issue by minhdanhsc** [Baseflow/flutter-geolocator#679]
## 🐛 Bug Report
I check my positioning is turned on and i have it on too.  isLocationServiceEnabled  return true.
However, when using `Geolocator.getCurrentPosition`, it throws an error "The location service on the device is disabled".
I use xiaomi note 8pro and geolocator: 6.1.13.

**Comment by yuanjinsongquyi** [comment]
same

**Comment by florissmit1** [comment]
Can you provide your: 
```
flutter doctor -v
```
I reproduced the issue on my Oppo Reno 2Z using the example application:
- Granted location permission
- Turned location on
- Method shows expected behaviour

**Comment by bajajsahil** [comment]
#631

**Comment by sooxt98** [comment]
isLocationServiceEnabled still returns true on iOS when i set gps access to "never"

**Comment by it-one-mm** [comment]
@sooxt98 please show me your work around example.

**Comment by it-one-mm** [comment]
@sooxt98  Please show me the workaround example.

**Comment by ShohidulProgrammer** [comment]
bool serviceEnabled = await Geolocator.isLocationServiceEnabled(); always returns true. even, when it's in denaied forever mode.

**Comment by carlossilvaf** [comment]
same here, any workarounds?

**Comment by storm265** [comment]
Same, but in my case this error appears only on tablet emulators. If use android emulator, real device or genimotion - all fine.

**Comment by TimHoogstrate** [comment]
It seems to us that this issue is no longer valid, or is solved in the meantime. Therefore, we will close this issue. Feel free to reopen the issue if it is still relevant or reappears. If so, in order to be able to reproduce this issue, please add the output of `flutter doctor -v` below.
