### ISSUE TITLE
Troubles on xiaomi Mi devices

### ISSUE THREAD

**Issue by angelschnider** [Baseflow/flutter-geolocator#681]
## 🐛 Bug Report

Hi, 
I have a strange bug on some samsung (s8) and Xiaomi (mi a2) devices. 
In my app I use an external lib that handle the camera. When I try to call the camera and if I have geolocation activated my camera freeze randomly... When I kill the app and relaunch it and try again to launch the camera, again, it freeze...but when I deactivate in the system the gps and relaunch it and try again my app, that's work, my camera not freezing anymore until I take the shot and recall again the camera...then it's freeze....have you got any idea about what's the problem?   

### Expected behavior

I expected that in any case the camera with geolocation not freezing anymore. Or maybe have any response about how to solve this kind of problem.

### Reproduction steps

Explained in Bug Report section

### Configuration
My Xiaomi is with androidone not with MIUI.

[✓] Flutter (Channel beta, 1.26.0-17.8.pre, on macOS 11.2.1 20D74 darwin-x64, locale en-CH)
    • Flutter version 1.26.0-17.8.pre at /Users/angelus/Downloads/flutter
    • Framework revision 044f2cf560 (8 days ago), 2021-02-24 13:02:05 -0800
    • Engine revision 042c82b02c
    • Dart version 2.12.0 (build 2.12.0-259.16.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/angelus/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • Mi A2 (mobile) • 13ce2c6 • android-arm64  • Android 10 (API 29)
    • Chrome (web)   • chrome  • web-javascript • Google Chrome 89.0.4389.72

**Version:** 1.x
Same issue with stable channel. 
Flutter 1.26.0-17.8.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 044f2cf560 (8 days ago) • 2021-02-24 13:02:05 -0800
Engine • revision 042c82b02c
Tools • Dart 2.12.0 (build 2.12.0-259.16.beta)

**Platform:** 
- [ ] :iphone: iOS
- [ x ] :robot: Android

Thank you.

**Comment by mvanbeusekom** [comment]
Hi @angelschnider, 

This is an interesting issue, the geolocator plugin is really not involved with accessing the camera so it's hard for me to believe the geolocator is the reason for this issue. The only thing I can imagine is that the camera (or the camera library) also wants to access the location services to add the location meta data with the photo but is blocked because the geolocator is already accessing them (which is still strange because GPS data is ofter requested by multiple services at the same time).

Could you tell me the version of the geolocator plugin you are using and which camera library (including version)?

Without this information it would be nearly impossible to reproduce the issue.

**Comment by kinchanprajapati** [comment]
@mvanbeusekom and @angelschnider i have same issue when i try with samsung M 20 then Camera will work fine and API had respond but when i try with Redmi phone camera is open but API haven't respond.

[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.13.6 17G14033 darwin-x64, locale en-IN)
    • Flutter version 2.0.3 at /Users/appleto/Desktop/Work/flutter
    • Framework revision 4d7946a68d (2 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/appleto/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • Redmi 4A (mobile) • 17f064397ce4 • android-arm64  • Android 7.1.2 (API 25)
    • Chrome (web)      • chrome       • web-javascript • Google Chrome 89.0.4389.114

**Comment by arunavsikdershuvo** [comment]
Anyone solve this problem? I'm testing on Poco M2(MIUI 12.0.4) 

`await Geolocator.getCurrentPosition(forceAndroidLocationManager: true, desiredAccuracy: LocationAccuracy.low)`

is not working. Stuck on this line forever.
But `desiredAccuracy: LocationAccuracy.best` works instantly.
Anyone help me on this problem?
