### ISSUE TITLE
How to get user's location accuracy in meters ?

### ISSUE THREAD

**Issue by kadirfayzi** [Baseflow/flutter-geolocator#690]

**Comment by renefloor** [comment]
When you call [getCurrentPosition](https://pub.dev/documentation/geolocator/latest/geolocator/Geolocator/getCurrentPosition.html) you'll get a Future<[Position](https://pub.dev/documentation/geolocator_platform_interface/latest/geolocator_platform_interface/Position-class.html)> which has an [accuracy in meters](https://pub.dev/documentation/geolocator_platform_interface/latest/geolocator_platform_interface/Position/accuracy.html). Do you have any problems with that?
