### ISSUE TITLE
Checkpermission doesnt return deniedforever (Using Geolocator 7.0.1)

### ISSUE THREAD

**Issue by yoseptara** [Baseflow/flutter-geolocator#691]
## 🐛 Bug Report

It's exactly the same issue as #626 #571

**Comment by mvanbeusekom** [comment]
This is by design, detailed explanation can be found on our Wiki: https://github.com/Baseflow/flutter-geolocator/wiki/Breaking-changes-in-7.0.0#android-permission-update
