### ISSUE TITLE
Web: Geolocator.isLocationServiceEnabled() not supported: UnimplementedError

### ISSUE THREAD

**Issue by eggnstone** [Baseflow/flutter-geolocator#694]
## 🐛 Bug Report

Using Flutter for Web:
Using `Geolocator.isLocationServiceEnabled()` throws `UnimplementedError`.
This should either be implemented or documented.
In the docs there is only a mention of other methods and with different expected errors.

### Configuration
Flutter for Web, beta channel, latest version.

**Version:** 7.01

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [x] Web

**Comment by mvanbeusekom** [comment]
This issue is fixed with the release of `geolocator_web` version 2.0.3.
