### ISSUE TITLE
line 19 pos 16: 'latitude != null': is not true.

### ISSUE THREAD

**Issue by vmarinovich** [Baseflow/flutter-geolocator#698]
## 🐛 Bug Report
line 19 pos 16: 'latitude != null': is not true. 

I have some problems when I try to get the endPosition latitude and longitude. The problem is that return Null and show is **line 19 pos 16: 'latitude != null': is not true.**

### Expected behavior

I Expected that when I select a option of the Prediction List, get the coordinates from address as endPosition. but I found this issues

### Configuration
```
// Var to callback method 
`GestureDetector(
       onTap: () async {
           var response = await Navigator.push(context, MaterialPageRoute(
           builder: (context) => SearchPage()));
           if(response == 'getDirection') {
           await getDirection();}
              else{
              CircularProgressIndicator();}`
```

`// Method
Future<void> getDirection() async {

    var pickup = Provider.of<AppData>(context, listen: false).pickupAddress;
    var destination = Provider.of<AppData>(context, listen: false).destinationAddress;
    var pickLatLng = LatLng(pickup.latitude, pickup.longitude);
    var destinationLatLng = LatLng  (destination.latitude, destination.longitude);
        showDialog(
          barrierDismissible: false,
          context: context,
          builder: (BuildContext context) => ProgressDialog(status: 'Por favor espera...',));
    var thisDetails = await HelperMethods.getDirectionDetails(pickLatLng, destinationLatLng);
    Navigator.pop(context);`

**Version:** 1.x

**Platform:** 
- [X ] :iphone: iOS
- [ X] :robot: Android

**Comment by florissmit1** [comment]
In what context are u using Geolocator? F.e. how do u fetch the location of the device? Be more specific in describing your issue and provide more information such as flutter doctor -v.
