### ISSUE TITLE
MI camera haven't respond

### ISSUE THREAD

**Issue by kinchanprajapati** [Baseflow/flutter-geolocator#700]
i have same issue when i try with samsung M 20 then Camera will work fine and API had respond but when i try with Redmi phone camera is open but API haven't respond.

[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.13.6 17G14033 darwin-x64, locale en-IN)
• Flutter version 2.0.3 at /Users/appleto/Desktop/Work/flutter
• Framework revision 4d7946a68d (2 weeks ago), 2021-03-18 17:24:33 -0700
• Engine revision 3459eb2436
• Dart version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
• Android SDK at /Users/appleto/Library/Android/sdk
• Platform android-30, build-tools 30.0.3
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✗] Xcode - develop for iOS and macOS
✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
Download at: https://developer.apple.com/xcode/download/
Or install Xcode via the App Store.
Once installed, run:
sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
sudo xcodebuild -runFirstLaunch
✗ CocoaPods not installed.
CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
Without CocoaPods, plugins will not work on iOS or macOS.
For more info, see https://flutter.dev/platform-plugins
To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
• Redmi 4A (mobile) • 17f064397ce4 • android-arm64 • Android 7.1.2 (API 25)
• Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114

**Comment by florissmit1** [comment]
I think the issue u mention is not related to Geolocator, so for now I'll close the issue.
