### ISSUE TITLE
Forcing to set ACCESS_BACKGROUND_LOCATION

### ISSUE THREAD

**Issue by sajanyamaha** [Baseflow/flutter-geolocator#701]
### Expected behavior
I am using version ^6.2.1 , My app needs location in foreground , and NOT in background ,but app run in android studio errors like this ,

/Users/sajansj/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-6.2.1/android/src/main/java/com/baseflow/geolocator/permission/PermissionManager.java:48: error: cannot find symbol
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q) {
                                                   ^
  symbol:   variable Q
  location: class VERSION_CODES
/Users/sajansj/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-6.2.1/android/src/main/java/com/baseflow/geolocator/permission/PermissionManager.java:54: error: cannot find symbol
            context, Manifest.permission.ACCESS_BACKGROUND_LOCATION);
                                        ^
  symbol:   variable ACCESS_BACKGROUND_LOCATION
  location: class permission
/Users/sajansj/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-6.2.1/android/src/main/java/com/baseflow/geolocator/permission/PermissionManager.java:60: error: cannot find symbol
        ContextCompat.checkSelfPermission(context, Manifest.permission.ACCESS_BACKGROUND_LOCATION);

### Configuration
Already set foreground settings in manifest
    uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" 
    uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" 

### Flutter doctor
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale en-IN)
    • Flutter version 2.0.3 at /Users/sajansj/Developer/flutter
    • Framework revision 4d7946a68d (2 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/sajansj/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/sajansj/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/sajansj/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 89.0.4389.114

• No issues found!

**Version:** 6.2.1

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by sajanyamaha** [comment]
I have found a workaround for this , I had to edit the PermissionManager.java located at 
ios/.symlinks/plugins/geolocator/android/src/main/java/com/baseflow/geolocator/permission/PermissionManager.java

Since I never used background location I had to edit the file for commenting out the logics on ACCESS_BACKGROUND_LOCATION in the above file

This link gave me the idea
https://github.com/permissions-dispatcher/PermissionsDispatcher/pull/679#issue-456238328

**Comment by mvanbeusekom** [comment]
@sajanyamaha this issue probably occurs because your App targets Android API 28 or below.

You can resolve this issue by setting the `targetSdkVersion` in you `android/build.gradle` file to 29 or higher.

The `Build.VERSION_CODES.Q` and `Manifest.permission.ACCESS_BACKGROUND_LOCATION` enum values are only available from Android Q (API 29). There is no need to remove any code.
