### ISSUE TITLE
update distanceFilter and intervalDuration not work

### ISSUE THREAD

**Issue by tranice** [Baseflow/flutter-geolocator#703]
## 🐛 Bug Report

First:
StreamSubscription<Position> _positionStream = Geolocator.getPositionStream(
        forceAndroidLocationManager: true,
        desiredAccuracy: LocationAccuracy .best,
        distanceFilter:100,
        intervalDuration: Duration(seconds: 2),
      ).listen((Position position) {
       ......
      });

then:
await _positionStream .cancel();
_positionStream =null;

and:
_positionStream = Geolocator.getPositionStream(
        forceAndroidLocationManager: true,
        desiredAccuracy: LocationAccuracy .best,
        distanceFilter:10,  /*change*/
        intervalDuration:  Duration(seconds: 3),  /*change*/
      ).listen((Position position) {
       ......
      });

 /*  new distanceFilter and intervalDuration not working, still use last ones  , if restart app ,everything  return to normal*/

**Version:**    geolocator: ^7.0.1

**Platform:** 
- Android 

both locations are in background and occur in real phone.

**Comment by florissmit1** [comment]
I was able to reproduce this issue. The positionParameters are cached , thus the initial parameters are always used. 

I mark the issue as a 'bug' since I think the parameters should be changeable after initializing a positionStream for the second time.

**Comment by florissmit1** [comment]
The bug u mentioned is fixed, see #723. Thanks for the feedback!
