### ISSUE TITLE
**didChangeAppLifecycleState** goes into a loop when starting the Position Stream 

### ISSUE THREAD

**Issue by Dhaval2404** [Baseflow/flutter-geolocator#717]
## 🐛 Bug Report

**didChangeAppLifecycleState** goes into a loop when starting the Position Stream 

### Expected behavior
**didChangeAppLifecycleState** should not go into a loop when listening on getPositionStream method

### Reproduction steps
1. Checkout the source code: https://gist.github.com/Dhaval2404/5279181bb7999aa1ad35d0d80786279b
2. Add below permission in manifest
```
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
```
3. Build and Run the app
4. Click "Request Permission" and grant the permission
5. Click **"Start Stream"** and observe that didChangeAppLifecycleState call continuously with the below logs:
  
  ```
    I/flutter (30769): _didChangeAppLifecycleState: AppLifecycleState.inactive
    I/flutter (30769): _didChangeAppLifecycleState: AppLifecycleState.resumed
    I/flutter (30769): _didChangeAppLifecycleState: AppLifecycleState.inactive
    I/flutter (30769): _didChangeAppLifecycleState: AppLifecycleState.resumed
    I/flutter (30769): _didChangeAppLifecycleState: AppLifecycleState.inactive
    I/flutter (30769): _didChangeAppLifecycleState: AppLifecycleState.paused
```

### Configuration

**Version: **7.0.3**

**Platform:** 
- [✔] :robot: Android

**Comment by Dhaval2404** [comment]
After much debugging, I found that the below code was executed repeatedly.

![image](https://user-images.githubusercontent.com/7314181/115279616-9267a680-a164-11eb-91f5-16996e4facfe.png)

It was starting the resolution activity and immediately return with Activity.RESUTL_OK (It should have open the resolution dialog). On success, it starts the stream again and the cycle continues.

This scenario seems a bit suspicious to me, and I tried to restart the device and to my surprise, things started to work normally.

Putting this description, In case anyone facing a similar situation.

**Comment by asbah007** [comment]
I have the same issue.. Dont know why this occurs.
I am getting this output

```
I/flutter (14504): AppLifecycleState.inactive
I/Counters(14504): exceeded sample count in FrameTime
I/flutter (14504): AppLifecycleState.resumed
I/flutter (14504): AppLifecycleState.inactive
I/Counters(14504): exceeded sample count in FrameTime
I/flutter (14504): AppLifecycleState.resumed
I/flutter (14504): AppLifecycleState.inactive
I/flutter (14504): AppLifecycleState.resumed
I/flutter (14504): AppLifecycleState.inactive
```

Anybody know about the issue in detail.???
