### ISSUE TITLE
I n

### ISSUE THREAD

**Issue by jbiddulph** [Baseflow/flutter-geolocator#718]
### Configuration

**Version:** 1.x

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by jbiddulph** [comment]
using geolocator 7.0.3 

I get null null for lat/lng

Please help

**Comment by florissmit1** [comment]
Can you provide  your `flutter doctor -v`? Also, can you provide your code which is returning the null exception?
