### ISSUE TITLE
Wait for user to enable location

### ISSUE THREAD

**Issue by FRANIAZA** [Baseflow/flutter-geolocator#719]
Hello,
When I redirect the user to the location settings page using 
```dart
await Geolocator.openLocationSettings();
```
the future resolves as soon as the settings page is opened. This results in my code executing even though the location service might not be enabled yet.

How can I wait for the user to finish editing his settings and return to the app, and only then run the rest of my code?

Thank you

**Comment by florissmit1** [comment]
At the moment it's not possible to wait for the user to finish editing his/her locationSettings and then resolve the Future.

What you can do is use:
```
await Geolocator.isLocationServiceEnabled();
```
To check whether the user has the LocationService enabled or not.
