### ISSUE TITLE
Geolocator plugin is not working in android release mode

### ISSUE THREAD

**Issue by saqismile** [Baseflow/flutter-geolocator#720]
## 🐛 Bug Report

I am using geolocator plugin version 5.3.2+2 in my flutter application. It works fine in android debug mode by does not work in release mode. What am I missing while configuring this plugin because earlier it was working fine.

### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
This is a difficult question to answer. You are not providing a lot of information to go with, also the current release is version 7.0.3 which is far away from version 5.3.2+2 you mentioned.

A few things I can suggest are:

1. Make sure you have the permissions listed correctly in you `AndroidManifest.xml` file (you probably want to make sure you use the `android.permission.ACCESS_FINE_LOCATION"` permission). Make sure you list all permissions in the `AndroidManifest.xml` file that is located in your `android/app/src/main` folder (and not in the `android/app/src/debug` or `android/app/src/profile` folders);
2. Make sure Google Play Services are enabled (or ensure the `forceAndroidLocationManager` is set to `true`);
