### ISSUE TITLE
Fluctuate 

### ISSUE THREAD

**Issue by ibrar-web** [Baseflow/flutter-geolocator#726]
Initially points flutute highly even if I am wakking and record track. It shows variation in points Plus minus in lat lng

**Comment by florissmit1** [comment]
Can you provide more information about your issue? Maybe some code snippets, `flutter doctor -v` or a deeper explanation about your issue. Depending on different factors, GPS accuracy can differ from a few meters to hundreds of meters. See the below table for for information:

lowest | 500m | 3000m
-- | -- | --
low | 500m | 1000m
medium | 100 - 500m | 100m
high | 0 - 100m | 10m
best | 0 - 100m | ~0m
bestForNavigation | 0 - 100m | Optimized for navigation

See: https://pub.dev/packages/geolocator
