### ISSUE TITLE
getCurrentPosition not Working when Moving fast

### ISSUE THREAD

**Issue by AliEasy** [Baseflow/flutter-geolocator#727]
Hi
`getCurrentPosition` method is not working when moving fast eg. when you are inside a car

```
Position position = await Geolocator.getCurrentPosition(
                  desiredAccuracy: LocationAccuracy.best);
```

geolocator: ^6.1.8+1
My device: Android 11

**Comment by florissmit1** [comment]
Thanks for reporting your issue. At the moment there is a new version of geolocator available, version ^7.0.3, try using this version of geolocator.
