### ISSUE TITLE
Not working with Flutter Web in release mode geolocator: ^7.0.2

### ISSUE THREAD

**Issue by MySwastik** [Baseflow/flutter-geolocator#728]
## 🐛 Bug Report
**Help me .**.

Tried all efforts but didn't the result . Current version of geolocator is not working with fluter web in release mode..
### Expected behavior
After allowing the location permision nothing happen still getting null in user location..But the same code work in debug mode.
### Configuration
Position? userlocation;
  Future<Position?> _getLocation() async {
    var currentLocation;
    try {
      currentLocation = await Geolocator.getCurrentPosition(
          desiredAccuracy: LocationAccuracy.high);
    } catch (e) {
      currentLocation = null;
      print(e);
    }
    setState(() {
      userlocation=currentLocation;
    });
  }
  @override
  void initState() {
    _getLocation();
    super.initState();
  }
**Version:** 1.x
   geolocator: ^7.0.2
**Platform:** 
- [ ] :Web: Chrome

**Comment by florissmit1** [comment]
@MySwastik There is a known bug in Dart causing the issue you mentioned. Building your Flutter web application **without** null safety will solve the problem for now. `flutter build web --no-sound-null-safety`.

**Comment by MySwastik** [comment]
Ok fine its working..  after using  this " flutter build web --no-sound-null-safety ". Thanks for support
