### ISSUE TITLE
Geolocator.getCurrentPosition() not working in verion 7.0.3

### ISSUE THREAD

**Issue by ngoluuduythai** [Baseflow/flutter-geolocator#729]
## 🐛 Bug Report

Geolocator.getCurrentPosition() not return value when all permissions are allowed. I run the example of geolocator, get last position work, but getCurrentPosition does not return value.

### Expected behavior
Geolocator.getCurrentPosition()  return current position
### Reproduction steps
 I run the example of geolocator, get last position work, but getCurrentPosition does not return value.

**Version:** 7.0.3

**Platform:** 
- [ ] :iphone: iOS
- [* ] :robot: Android

**Comment by mvanbeusekom** [comment]
@ngoluuduythai depending on what device and where you run the example it can take up to several minutes for the devices to acquire and return a location fix.

If you are running on the emulator, make sure you have set a location in the emulator settings. If you are running on a real device make sure you have a good cellular connection (e.g. make sure you have inserted a sim card) and/or make sure you have a clear view to the sky so you get a solid GPS connection. 

You could also have a look at this issue which describes a lot of things regarding working with GPS on Android: #507

When the above information doesn't help, please supply the following information so we can help you better:

- [ ] Output of the `flutter doctor -v` command;
- [ ] The Android API level (or version) you are testing with;
- [ ] If testing on a real device, please provide its make and model;
- [ ] If testing on the emulator, please provide the settings;
- [ ] Code snippet or example app reproducing the error.

**Comment by guccisekspir** [comment]
Same error. Android works perfectly but iOS doesnt return anything also doesnt throw any error.

**Comment by mvanbeusekom** [comment]
@guccisekspir please provide the requested information if you want us to help out.

Also the original author is experiencing issues on Android, while you mention an issue on iOS so I suggest to create a separate issue.

**Comment by guccisekspir** [comment]
Oh sorry. The selection style confused my mind. 
Actually I used 7.0.1 version when commenting and android side works perfectly but in iOS side didnt work. 
After upgrade to 7.0.3 both sides fixed for me.

**Comment by jopmiddelkamp** [comment]
@mvanbeusekom Same here.

Example project;
https://github.com/jopmiddelkamp/geolocator-issue

 Output of the flutter doctor -v command;
```[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.5 at /Users/jopmiddelkamp/Development/flutter
    • Framework revision adc687823a (4 weeks ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jopmiddelkamp/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Users/jopmiddelkamp/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7199119/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/jopmiddelkamp/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7199119/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11
      (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • macOS
      11.2.3 20D91 darwin-x64
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 90.0.4430.212

• No issues found!```

Physical device info;
![image](https://user-images.githubusercontent.com/1774351/118134195-3aa31f00-b434-11eb-807d-0c2dfc42e3ce.png)

**Comment by zs-dima** [comment]
> if i use ACCESS_FILE_LOCATION i can get the location while if i use ACCESS_COARSE_LOCATION nothing is returned in the android emulator an it remain stuck in getCurrentPosition().

I have the same issue from 7.0.0 version to 7.0.3 geolocator version

https://github.com/Baseflow/flutter-geolocator/issues/507
