### ISSUE TITLE
Error launching application on xxxyyyzzz’s iPhone

### ISSUE THREAD

**Issue by sboicu** [Baseflow/flutter-geolocator#730]
I try to run the example of this and I cannot make it work.
The app starts but only a white screen is prezent, I would expect something like allow using location services or something. Then it takes a bit and the app closes and following message I get:

Running Xcode build...
Xcode build done.                                            6.3s
Installing and launching...
Error launching application on xxxyyyzzz’s iPhone.

any ideea what I do wrong?
I have added in info plist all the necessary actions.

**Comment by florissmit1** [comment]
Can u be more specific about the issue, for example: Your `flutter doctor -v` and the version of XCode you're using.  Are you trying to run the example app on a physical device or on a iPhone Simulator? Which iOS version are you using e.d.
