### ISSUE TITLE
Web wrong location

### ISSUE THREAD

**Issue by FRANIAZA** [Baseflow/flutter-geolocator#732]
I'm using this package both on mobile and on web.
On mobile it works like a charm, and the retrieved location is accurate.
On web, from my PC the position obtained is waaay off: 
on mobile -> 45.xxx, 6.xxx ; on web -> 44.xxx, 8.xxx.

I'm using the package like this:
```dart
Future _getUserPosition() async{
    LocationPermission permission;

    if(homePageFirstLoad){
      homePageFirstLoad = false;
      permission = await Geolocator.checkPermission();

      if (permission == LocationPermission.denied) {
        permission = await Geolocator.requestPermission();
        if (permission == LocationPermission.denied) {
          // Permissions are denied, next time you could try
          // requesting permissions again (this is also where
          // Android's shouldShowRequestPermissionRationale
          // returned true. According to Android guidelines
          // your App should show an explanatory UI now.
          bool? requestAgain = await generateAlertDialog(
            context,
            S.of(context).locationAccessDeniedTitle,
            S.of(context).locationAccessDeniedMsg,
            S.of(context).enableText,
                () => Navigator.pop(context, true),
            leftBtnText: S.of(context).disableText,
            leftBtnOnPressed: () => Navigator.pop(context, false),
          );
          if(requestAgain!) permission = await Geolocator.requestPermission();

          if(permission == LocationPermission.denied) return false;
        }
      }

      if (permission == LocationPermission.deniedForever) {
        // Permissions are denied forever, handle appropriately.
        await generateAlertDialog(
            context,
            S.of(context).locationAccessDeniedForeverTitle,
            S.of(context).locationAccessDeniedForeverMsg,
            S.of(context).okText,
                () => Navigator.pop(context, false)
        );
        return false;
      }
    }

    // When we reach here, permissions are granted and we can
    // continue accessing the position of the device.
    setState(() {
      _gettingPosition = true;
    });

    try{
      getUserInfo.position = await Geolocator.getCurrentPosition();
    } on LocationServiceDisabledException catch(_){

    }

    print(getUserInfo.position);
    _getNearYouRestaurants = _getRestaurantsNearYou();

    setState(() {
      _gettingPosition = false;
    });
    return getUserInfo.position;
  }
```

Is this a bug or am I doing something wrong?

**Comment by florissmit1** [comment]
Can you try using the example application of the geolocater plugin and check if it's working or not, because for me the correct location is fetched using the example application on web. Also, because Desktop pc's / laptops often don't have a GPS receiver, the location is based on several factors such as IP-address, so that can be the explanation of your issue.

**Comment by FRANIAZA** [comment]
So I ran the example app and got the the wrong location. Then I ran my app and it worked! I restarted the PC just to be sure and it still worked. Magic

**Comment by FRANIAZA** [comment]
I ran the example application and I still get the same wrong location, about 6.5 Km away from the correct location. Could it be an inaccuracy due to the fact that I'm running it on a desktop?
However google maps on web manages to get the exact location.

**Comment by FRANIAZA** [comment]
[√] Flutter (Channel beta, 2.1.0-12.2.pre, on Microsoft Windows [Version 10.0.19042.1052], locale en-US)
    • Flutter version 2.1.0-12.2.pre at D:\Android\Flutter\flutter
    • Framework revision 5bedb7b1d5 (3 months ago), 2021-03-17 17:06:30 -0700
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\FRANZ\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Connected device (3 available)
    • SM G975F (mobile) • R58M54WPNAD • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 91.0.4472.101
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 91.0.864.41

**Comment by FRANIAZA** [comment]
I ran the app from my girlfriend's house and it got the location spot on. It must be just some sort of inaccuracy

**Comment by mvanbeusekom** [comment]
Hi @FRANIAZA, 

The location results might indeed very based on the capabilities of your desktop machine. For devices that contain a GPS chip determining the permission is a lot more detailed. Desktop devices usually don't have a GPS chip and often rely on information from the Internet Service Provider (location of network nodes or data centers). The reason that Google Maps is a lot closer (or even exact) is that they use advanced algorithms and information related to your Google Account to help determine the your location. For example when you own an Android device it will and you are signed in on both your desktop and Android device with the same Google account it will link the position information from your mobile device with your search on Google Maps using the desktop.

We obviously don't have access to this information and rely solely on the information the browser supplies using the default Geolocation API (detailed information can be found [here](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API)).

I am going to close this issue, feel free however to supply additional information in a comment if you feel there is a better way to access the geolocation using the browser and default (free) APIs.
