### ISSUE TITLE
placemarkFromCoordinates:Is this API cancelled? Can it be added? It's easy to directly convert geographic location information

### ISSUE THREAD

**Issue by Etermally** [Baseflow/flutter-geolocator#733]
## 🚀 Feature Requests

placemarkFromCoordinates:
Is there no alternative to this old version of the API geolocation decompilation method? Abandon it directly? Great God, can you add it? It's more convenient to use~ thanks!!!

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
@Etermally yes it has been cancelled since version 6.0.0 (see also release notes). 

The geocoding features have been moved to their own package called [geocoding](https://pub.dev/packages/geocoding).
