### ISSUE TITLE
iOS approximate location (iOS 14+)

### ISSUE THREAD

**Issue by stepanzalis** [Baseflow/flutter-geolocator#736]
## 🚀 Feature Requests

From iOS 14.x, user can decide if wants to grant approximate location (eg. city) or current precise location.  

### Describe the feature
It is necessary to know which type of location user has given. There are some use cases, where approximate location is not enough and application must react to this type (food deliver, etc). 

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
Support for querying and requesting approximate and precise location for iOS 14+ has been added in version 7.3.0 which was released on Jul 16, 2021.

Closing this issue, thank you for reporting.
