### ISSUE TITLE
getPositionStream hangs on Android 12 Beta

### ISSUE THREAD

**Issue by rlueders** [Baseflow/flutter-geolocator#737]
## 🐛 Bug Report

The latest version of the plugin (7.0.3) hangs when calling getPositionStream on apps running under the first Android 12 beta that was released yesterday (05/18). I am seeing the same hang on emulators and a physical devices running Android 12 Beta.  Also, no exception are getting logged.

**Comment by Anullos** [comment]
same error :(

**Comment by florissmit1** [comment]
I am able to reproduce the issue on the emulator as well, with and without Google Play Services enabled.

**Comment by florissmit1** [comment]
@rlueders @Anullos I fixed the issue for now by changing the properties below in the `build.gradle`:
`targetSdkVersion 28 to -> targetSdkVersion "S"`
`compileSdkVersion 28 to -> compileSdkVersion "android-S"`
And by adding the following property to the `<activity>` tag:
`android:exported="true"`

For me the solution mentioned above works (for now), I'm not sure if this is the correct way.

'If your app targets Android 12 and contains activities, services, or broadcast receivers that use intent filters, you must explicitly declare the android:exported attribute for these app components.`

More info: https://developer.android.com/about/versions/12/behavior-changes-12

**Comment by rlueders** [comment]
Thanks @florissmit1 . After making these three changes, the app no longer hung on the call to getPositionStream. However, my accuracy never dropped below 30 m. Was getting as low as 4 before.   I realized that I had forceAndroidLocationManager set to true, but after setting it to false (in addition to the three changes suggested by  @florissmit1 ) My accuracy was back to normal.

**Comment by florissmit1** [comment]
Nice to hear that it's working. I'm closing the issue fow now.
