### ISSUE TITLE
All parameters of the "Position" object are marked as required

### ISSUE THREAD

**Issue by sbis04** [Baseflow/flutter-geolocator#739]
### Expected behavior

In previous versions, the `Position` object could be created just by passing the `latitude` and `longitude` like this:

```dart
Position(
    latitude: _currentPosition.latitude,
    longitude: _currentPosition.longitude
)
```

### Reproduction steps

In the latest version, the `Position` object has marked all parameters as **required**. I think this shouldn't be the case as they are optional.

![Screenshot 2021-05-27 at 9 21 35 PM](https://user-images.githubusercontent.com/43280874/119857895-92ac4c00-bf31-11eb-8ec9-c680c4af76fd.png)

### Configuration

**Version:** ^7.0.3

**Comment by mvanbeusekom** [comment]
This is correct, the position object is not ment to be created from outside the `geolocator` plugin. The plugin creates this particular object based on the output of the Android, iOS of Web location services and returns this to you as a developer. We require that platforms always supply all fields for this object.

Why do you want to create a new position manually?

**Comment by sbis04** [comment]
I am creating `Position` objects to store the **latitudes** and **longitudes** of a certain position easily. And then using them to generate markers and calculated distance between two locations, you can check the code [here](https://github.com/sbis04/flutter_maps/blob/master/lib/main.dart#L147-L275). 

A part of the code is below:

```dart
        Position startCoordinates = _startAddress == _currentAddress
            ? Position(
                latitude: _currentPosition.latitude,
                longitude: _currentPosition.longitude)
            : Position(
                latitude: startPlacemark[0].latitude,
                longitude: startPlacemark[0].longitude);

        // Start Location Marker
        Marker startMarker = Marker(
          markerId: MarkerId('$startCoordinates'),
          position: LatLng(
            startCoordinates.latitude,
            startCoordinates.longitude,
          ),
          infoWindow: InfoWindow(
            title: 'Start',
            snippet: _startAddress,
          ),
          icon: BitmapDescriptor.defaultMarker,
        );
```

**Comment by florissmit1** [comment]
@sbis04 Since the Position class has some required properties that are irrelevant for your use case, maybe you can try making a separate dart class which exists of the properties latitude and longitude, something like this:
**In your app**
```
LatLongPosition position = LatLongPosition(1.0, 1.0);
  LatLongPosition position2 = LatLongPosition(1.0, 1.0);

  void calculateDistance(){
      Geolocator.distanceBetween(position.latitude, position.longitude, position2.latitude, position2.longitude);
  }
```
**In a separate class named latlongposition.dart or something like that**
```
class LatLongPosition {

  double latitude;
  double longitude;

  LatLongPosition(this.latitude, this.longitude) : super();

}
```

**Comment by sbis04** [comment]
Yes @florissmit1, I have done a similar thing in my implementation. 

Closing this issue because I think the `Position` class was created for internal use.
