### ISSUE TITLE
NSLocationAlwaysUsageDescription is this really essential ?

### ISSUE THREAD

**Issue by sajanyamaha** [Baseflow/flutter-geolocator#740]
The Readme says both the below are needed , for apps which need only `whileInUse` is the `AlwaysInUse` mandatory as apple review asks specifically for the real use of tracking ? will the plugin work if only `whileInUse` is used ?
```
1. whileInUse
2. AlwaysInUse
```

**Comment by florissmit1** [comment]
The app will work when you add the following to the info.plist (But it will only work when running the app in the foreground): 
```
<key>NSLocationWhenInUseUsageDescription</key>
<string>This app needs access to location when open.</string>
```
So it won't track the location of the device when the application is running in the background.

Let me know if it's still not working, you can re-open the issue if not.
