### ISSUE TITLE
Error when get location simulator android pixel4, iOs work fine.

### ISSUE THREAD

**Issue by tuemaytinh1981** [Baseflow/flutter-geolocator#744]
## 🐛 Bug Report
iOS works fine, android seems to have problem with Pixel 4 simulator when get location current.

E/flutter (18466): [ERROR:flutter/lib/ui/ui_dart_state.cc(213)] Unhandled Exception: NoSuchMethodError: Class 'PermissionDefinitionsNotFoundException' has no instance getter 'error'.
E/flutter (18466): Receiver: Instance of 'PermissionDefinitionsNotFoundException'
E/flutter (18466): Tried calling: error
E/flutter (18466): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:63:5)
E/flutter (18466): #1      LocationForm.build.<anonymous closure>.<anonymous closure> (package:innhunting/screens/location/components/location_form.dart:73:83)
E/flutter (18466): #2      _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter (18466): #3      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (18466): #4      _FutureListener.handleError (dart:async/future_impl.dart:172:20)
E/flutter (18466): #5      Future._propagateToListeners.handleError (dart:async/future_impl.dart:719:47)
E/flutter (18466): #6      Future._propagateToListeners (dart:async/future_impl.dart:740:13)
E/flutter (18466): #7      Future._completeError (dart:async/future_impl.dart:550:5)
E/flutter (18466): #8      _completeOnAsyncError (dart:async-patch/async_patch.dart:274:13)
E/flutter (18466): #9      determinePosition (package:innhunting/google_map/location.dart)
E/flutter (18466): <asynchronous suspension>
E/flutter (18466): 
E/flutter (18466): [ERROR:flutter/lib/ui/ui_dart_state.cc(213)] Unhandled Exception: NoSuchMethodError: Class 'PermissionDefinitionsNotFoundException' has no instance getter 'error'.
E/flutter (18466): Receiver: Instance of 'PermissionDefinitionsNotFoundException'
E/flutter (18466): Tried calling: error
E/flutter (18466): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:63:5)
E/flutter (18466): #1      LocationForm.build.<anonymous closure>.<anonymous closure> (package:innhunting/screens/location/components/location_form.dart:73:83)
E/flutter (18466): #2      _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter (18466): #3      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (18466): #4      _FutureListener.handleError (dart:async/future_impl.dart:172:20)
E/flutter (18466): #5      Future._propagateToListeners.handleError (dart:async/future_impl.dart:719:47)
E/flutter (18466): #6      Future._propagateToListeners (dart:async/future_impl.dart:740:13)
E/flutter (18466): #7      Future._completeError (dart:async/future_impl.dart:550:5)
E/flutter (18466): #8      _completeOnAsyncError (dart:async-patch/async_patch.dart:274:13)
E/flutter (18466): #9      determinePosition (package:innhunting/google_map/location.dart)
E/flutter (18466): <asynchronous suspension>
E/flutter (18466): 

### Configuration
AndroidManifest.xml

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.extech.innhunting">
    
    <uses-permission android:name="android.permission.INTERNET"/>
    
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    
</manifest>

**Version: geolocator: ^7.0.3

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @tuemaytinh1981,

Can you confirm that you added the required permissions to your `android/app/src/main/AndroidManifest.xml` file? 

You should have added at least the `android.permission.ACCESS_FINE_LOCATION` or `android.permission.ACCESS_COARSE_LOCATION` permission as direct child of the `<manifest>` element in you `AndroidManifest.xml` file (see also the Android section of the [README.md](https://github.com/Baseflow/flutter-geolocator/blob/master/geolocator/README.md)). 

The error is not as it is supposed to be, so we will look into that but we are interested if you added this to your AndroidManifest.xml file.

**Comment by tuemaytinh1981** [comment]
* I added required permissions to my android/app/src/main/AndroidManifest.xml.
* I change setting android simulator "allow" get location when used app.
* and I have solved it. Thanks very much.

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.extech.innhunting">
    
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
    
   <application
        .........
        ........

I understood the problem of app getting "location denied". I change the setting in simulator android, I got the location. App work fine. Thanks very much.
