### ISSUE TITLE
old problem  "Unhandled Exception: MissingPluginException"

### ISSUE THREAD

**Issue by izzabellerina** [Baseflow/flutter-geolocator#745]
## 🐛 Bug Report
Hi, I am so sorry that I face the old problem. "Unhandled Exception: MissingPluginException(No implementation found for method getCurrentPosition on channel flutter.baseflow.com/geolocator)"
I have tried "flutter clean and" "flutter pub get" and restart much time and the results were the same TT.
I don't know what to do, please anyone helps me. 
Thank you in advance

[✓] Flutter (Channel master, 2.3.0-17.0.pre.274, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-TH)
    • Flutter version 2.3.0-17.0.pre.274 at /Users/armotesomboonkaew/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 56e0908cc3 (2 hours ago), 2021-06-08 22:44:03 -0400
    • Engine revision 837438f6cd
    • Dart version 2.14.0 (build 2.14.0-189.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio
    • Android Studio at /Users/armotesomboonkaew/Documents/2Day/2day_lotties/Android Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] Connected device (2 available)
    • iPad (mobile) • 901c84eb24dec037c5a13a6db774a7dcf7481c01 • ios            • iOS 14.4
    • Chrome (web)  • chrome                                   • web-javascript • Google Chrome 91.0.4472.77

! Doctor found issues in 1 category.
Process finished with exit code 0

  geolocator: ^7.0.3

**Platform:** 
- [x] :iphone: iOS

**Comment by mvanbeusekom** [comment]
Hi @izzabellerina, 

Could you try the following steps:

1. Make sure you exit your IDE and exit your App if it is running;
2. Remove the generated `ios/Runner/GeneratedPluginRegistrant.h` and `ios/Runner/GeneratedPluginRegistrant.m` files;
3. Remove all Geolocator version from the pub.dev cache on your machine. The cache is usually located in the `~/.pub-cache/hosted/pub.dartlang.org` folder, so the following command should do the trick: `rm -rf ~/.pub-cache/hosted/pub.dartlang.org/geolocator*`;
4. Run `flutter clean` in the root of you App folder;
5. Run `flutter pub get` to download a fresh copy of the `geolocator` plugin;
6. Now try to build / run the App again using `flutter run` (this will re-generate the files removed in step 2).

If this still doesn't work please have a look at this [Flutter issue](https://github.com/flutter/flutter/issues/10912#issuecomment-310499594) which describes additional steps you can take to resolve your problem.  

I am going to close this issue as this doesn't seem related to the plugin itself but more the user environment. However if you have any follow up questions don't hesitate to leave another comment.

**Comment by pinguluk** [comment]
https://github.com/Baseflow/flutter-geolocator/issues/930#issuecomment-1019639841

**Comment by dukenebur** [comment]
This don't work for me
