### ISSUE TITLE
How to get coordinates from postal code

### ISSUE THREAD

**Issue by hautran90** [Baseflow/flutter-geolocator#747]
I am involved in a project, I need to open a Google Map in the application of a postal code. Is there a way for me to switch from the postal code to coordinates?

Ex: postal code: 500000

**Comment by mvanbeusekom** [comment]
Hi @hautran90, converting address information into coordinates is called (reversed) geocoding. Geocoding services are provided by several companies (e.g. Google, Apple and Here). 

If you want this functionality on an Android or iOS platform there are (limit) free SDKs available. We made a Flutter plugin called [geocoding](https://pub.dev/packages/geocoding) that provide access to these native SDK via Dart. But note that there are restrictions (mostly rate limits) on the use of this API. 

There are also other plugins available if you want to make use of some of the paid services which are not restricted to the limitations that come with the free services.

Hope this helps. Feel free to leave another comment if you have more questions.
