### ISSUE TITLE
Should not request permission on checking GPS is on/off

### ISSUE THREAD

**Issue by ShohidulProgrammer** [Baseflow/flutter-geolocator#752]
The isLocationServiceEnabled method should only check GPS enabled or not. but, it does request permission for enabling location service. Also, it always returns true; even it's in denied forever mode

**Comment by mvanbeusekom** [comment]
@ShohidulProgrammer the `isLocationServiceEnabled` method will check if the user has the system wide location services enabled. This is not related to the permissions indicating if the end-user allows your App to access the current devices location (this is checked with `checkPermission`). This means that even when the user doesn't allow your App to access the device's location as a developer you can still check if the system wide location services are enabled or not.
