### ISSUE TITLE
AndroidX dependency migration URL is wrongly formatted.

### ISSUE THREAD

**Issue by i-ampraveen** [Baseflow/flutter-geolocator#754]
### In Readme > Usage section, Android, in Point 3 states "Make sure you replace all the android. dependencies to their AndroidX counterparts (a full list can be found here: https://developer.android.com/jetpack/androidx/migrate). "
here when we click on the URL  it is displaying a 404 error. Attached Image. Need to remove the ')' in the URL. Please rectify it.
![404_error](https://user-images.githubusercontent.com/51072726/122077027-00ed7b80-ce19-11eb-8328-34f295fd87a1.png)

**Comment by florissmit1** [comment]
Thanks for mentioning this issue, I opened a pull request and it will be fixed as soon as possible!
