### ISSUE TITLE
onStatusChanged Deprecated

### ISSUE THREAD

**Issue by zerosADnn** [Baseflow/flutter-geolocator#757]
## 🐛 Bug Report

Every time I attempt to build and run a debug version of an app in Android, I receive the following error:

flutter\.pub-cache\hosted\pub.dartlang.org\geolocator-7.1.0\android\src\main\java\com\baseflow\geolocator\location\LocationManagerClient.java:137: warning: [deprecation] onStatusChanged(String,int,Bundle) in LocationListener has been deprecated
  public void onStatusChanged(String provider, int status, Bundle extras) {
              ^
error: warnings found and -Werror specified
1 error
1 warning

FAILURE: Build failed with an exception.

### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android

**Comment by mvanbeusekom** [comment]
@zerosADnn not really sure what causes this issue. The `onStatusChanged` method is indeed deprecated and we marked it with the `@SuppressWarnings("deprecation")` attribute (see [here](https://github.com/Baseflow/flutter-geolocator/blob/0bb522785331c35298c112e5aea7acd597b3c9c8/geolocator/android/src/main/java/com/baseflow/geolocator/location/LocationManagerClient.java#L135).

The method is there for backwards compatibility reasons only. We also included the the `-Werror` [argument](https://github.com/Baseflow/flutter-geolocator/blob/0bb522785331c35298c112e5aea7acd597b3c9c8/geolocator/android/build.gradle#L3) as part of our build configuration and locally as well on the CI environment this is not causing any issues (only if we remove the `@SuppressWarnings("deprecation")` attribute the build will fail).

Could you run a `flutter clean` or maybe the cached version of the geolocator plugin is corrupted (try removing it from the location reported in the error message: `flutter.pub-cache\hosted\pub.dartlang.org\`).

**Comment by zerosADnn** [comment]
@mvanbeusekom Thanks the prompt reply! I'll dig at this with your guidance later. As of last night I marked it @Deprecated for it to build. I know that's dangerous so I have faith your guidance will work. I'm a newb with geolocation usage. Will report later!

**Comment by zerosADnn** [comment]
@mvanbeusekom The issue was a JDK version. I had JDK 1.8.25, not the most recent one (291, been a long while). I found a forum that spoke on this and tested it out. The suppression put in place works like a charm. Much better than trying to force it to build (before, I placed @Deprecated above the method in question which I knew was not good). Thanks again!
