### ISSUE TITLE
Geolocator does not work on flutter web in release mode

### ISSUE THREAD

**Issue by tainanfochesatto** [Baseflow/flutter-geolocator#759]
## 🐛 Bug Report

When prompted for location in flutter web in release mode, the following exception is thrown on the console: 
**Uncaught TypeError: i.gQE is not a function**

In debug mode they work normally.

### Configuration
Flutter version: 2.2.2
Dart version 2.13.3

**Comment by rodgav** [comment]
I run into the same problem after running flutter build web in production. it just doesn't bring me the location.

**Comment by rodgav** [comment]
https://github.com/Baseflow/flutter-geolocator/issues/728#issue-874469817

acabo de encontrar esto. sería probarlo, yo lo probare mañana.

**Comment by mvanbeusekom** [comment]
Unfortunately there is a bug in the dart2js that is causing this problem. More information can be found [here](https://github.com/Baseflow/flutter-geolocator/issues/693#issuecomment-812453075). 

The dart2js team already provided a fix but we have to wait for it to land in stable. Workaround is to not build with sound null safety.

I will close this issue as it is not related to the geolocator plugin.
