### ISSUE TITLE
getCurrentPosition doesn't work with ACCESS_COARSE_LOCATION

### ISSUE THREAD

**Issue by AmjadKhan2k18** [Baseflow/flutter-geolocator#761]
i have been using ACCESS_COARSE_LOCATION and it was working fine in older version i was using but after updating i tried to get user currentPosition but it doesn't work. i updated FINE LOCATION and then it worked

i tested on virtual device and physical device 

``` 
     final position = await Geolocator.getCurrentPosition(
      desiredAccuracy: LocationAccuracy.high,
    );
```

flutter version 2.2.2
latest version of geolocator and tried previous 2 versions

[✓] Flutter (Channel stable, 2.2.2, on macOS 11.3 20E232 darwin-arm, locale
    en-GB)
    • Flutter version 2.2.2 at /users/khan/dev/flutter
    • Framework revision d79295af24 (12 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/khan/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11
      (API 30) (emulator)
    • Chrome (web)              • chrome        • web-javascript • Google Chrome
      91.0.4472.114

• No issues found!

**Comment by hasan-dorian** [comment]
For my case
It didn't work on emulator, but worked on real device !

**Comment by JeroenWeener** [comment]
Closing this issue as there has not been any activity for almost 2 years. If you are experiencing this issue on the latest version of the plugin, please let us know by opening a [new issue](https://github.com/Baseflow/flutter-geolocator/issues/new/choose).
