### ISSUE TITLE
Is Geolocator.getServiceStatusStream() removed from the package?

### ISSUE THREAD

**Issue by joeloudjinz** [Baseflow/flutter-geolocator#764]
## 💬 Questions and Help
**Is `Geolocator.getServiceStatusStream()` removed from the package?** in the package's readme on pup.dev, there is a mention on how to use this method
> To listen for service status changes you can call the getServiceStatusStream. This will return a Stream<ServiceStatus> which can be listened to, to receive location service status updates.
```
import 'package:geolocator/geolocator.dart';

StreamSubscription<ServiceStatus> serviceStatusStream = Geolocator.getServiceStatusStream().listen(
    (ServiceStatus status) {
        print(status);
    });
```
but it is missing from the implementation because when it is called, an error is displayed saying:
> The method 'getServiceStatusStream' isn't defined for the type 'Geolocator'. Try correcting the name to the name of an existing method, or defining a method named 'getServiceStatusStream'.

**Comment by mvanbeusekom** [comment]
@joeloudjinz no it is not removed from the package. Please make sure you are on the latest version of the plugin. The `getServiceStatusStream` method is available from version 7.1.0. Als make sure you are not overriding the `geolocator_platform_interface` package in your pubspec.yaml.
