### ISSUE TITLE
Channel Method for getLocationAccuracy not implemented

### ISSUE THREAD

**Issue by helixbooks** [Baseflow/flutter-geolocator#767]
## 🐛 Bug Report

**Geolocator.getLocationAccuracy()** does not have a channel method implemented on Android and is throwing a **MissingPluginException**.

E/flutter (26906): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method getLocationAccuracy on channel flutter.baseflow.com/geolocator)

### Expected behavior

A default value of **LocationAccuracyStatus.precise** to be returned. I think this is currently the behavior for iOS?

### Reproduction steps

1. Call Geolocator.getLocationAccuracy() on Android device

### Configuration

**Version:** 7.20+1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
@helixbooks the `getLocationAccuracy()` method is only supported on iOS and is indeed not implemented on Android, hence the error.

I noticed the documentation doesn't mention this, so I will leave this issue open so we can track the documentation update.

**Comment by florissmit1** [comment]
@helixbooks I changed the documentation, so that it is clear the method only supports iOS devices. Also, when executing the method on Android devices `LocationAccuracyStatus.unknown` will now be returned. See: https://github.com/Baseflow/flutter-geolocator/pull/769
