### ISSUE TITLE
Geolocator.getCurrentPosition(); throws an unexpected error in release web application

### ISSUE THREAD

**Issue by ncdm-stldr** [Baseflow/flutter-geolocator#772]
## 🐛 Bug Report

I use Geolocator.getCurrentPosition(); to determine the web application position.
In debug version I don't get any error, and a position is returned. However, with the release version, I get the following error in the browser console:
`js_helper.dart:1130 Uncaught TypeError: h.gBO is not a function
    at utils.dart:17
    at ZF.a (async_patch.dart:316)
    at ZF.$2 (async_patch.dart:341)
    at YK.$1 (async_patch.dart:292)
    at XF.TH (zone.dart:1613)
    at XF.uy (zone.dart:1612)
    at Wc.$0 (future_impl.dart:119)
    at Object.nu (future_impl.dart:736)
    at Z.iq (future_impl.dart:542)
    at W4.$0 (future_impl.dart:580)`

The corresponding code of utils.dart:17 ( flutter-geolocator/geolocator_web/lib/src/utils.dart ) is the following:
`final coords = webPosition.coords;`
If I replace this line by:
`final coords = getProperty(webPosition, 'coords');`
and add the following import: `import 'dart:js_util';`
Their is no error anymore at this line.
If I do the same type of replacement for the remaining of the function, I do not got any error and the position is returned.

I tried to use getProperty because I saw a very similar error in the following issue: https://github.com/flutter/flutter/issues/68052

### Expected behavior

No error should be thrown and the position should be returned.

### Reproduction steps

Here's an simple example for reproducing the error.

pubspec.yaml:
`
...
  geolocator: ^7.2.0
...
flutter:
  uses-material-design: true
`

main.dart: (taken from the issue link I mentionned earlier with a small modification)
```
import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool _loading = false;
  Position? position;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          Center(
            child: ElevatedButton(
              child: Text('Get location'),
              onPressed: _loading ? null : _getLocation,
            ),
          ),
          Center(
            child: Text('Loading: $_loading'),
          ),
          Center(child: Text('Long: ${position?.longitude} : Lat: ${position?.latitude}')),
        ],
      ),
    );
  }

  Future<void> _getLocation() async {
    setState(() {
      _loading = true;
    });
    Position location = await Geolocator.getCurrentPosition();;
    setState(() {
      position = location;
      _loading = false;
    });
  }
}
```

### Configuration

I use flutter sdk version 2.2.2 with Dart 2.13.3
The released application is for the web plateform

**Comment by mvanbeusekom** [comment]
Hi @ncdm-stldr, this error is caused by a bug in the Dart2JS implementation when compiling with sound null safety turned on. I have already reported this as an issue (see [here](https://github.com/dart-lang/sdk/issues/45562)) which has already been fixed but we are waiting for it to be released.

See also issue #693 for more information, it also contains a workaround.
