### ISSUE TITLE
[Proposal] Remove implicit request for permissions when getting a position.

### ISSUE THREAD

**Issue by mvanbeusekom** [Baseflow/flutter-geolocator#775]
## Context

The current version of the geolocator plugin implicitly requests permissions when the `Geolocator.getCurrentPosition()` or `Geolocator.getPositionStream()` methods are executed and permissions have not been granted.

This has always worked nicely but now becomes a bit of a pain to manage. This is mainly because the proces of requesting permissions is asynchronous since the user needs to respond to a dialog allow or denying permissions. At the moment this results in two issues:

1. When adding new functionality (e.g. accessing location services from the background) we need to add additional logic to manage permissions. This means adding complexity which makes the plugin harder to maintain;
2. It is currently causing a problem with the timeout feature that is part of the `Geolocator.getCurrentPosition()` and `Geolocator.getPositionStream()` methods, since the requesting of permissions is considered part of the execution. Meaning if the user doesn't respond fast enough to the permission dialog the timeout triggers and throws a timeout exception. The current work around is to handle requesting permissions manually.

## Proposal

The idea is to remove the implicit handling of permissions when calling the `Geolocator.getCurrentPosition()` and `Geolocator.getPositionStream()` methods. This would solve the issues mentioned above but of course has the downside that developers now need to manually handle permissions using the `Geolocator.checkPermission()` and `Geolocator.requestPermission()` methods. The recommended workflow is demonstrated in the code snippet below:

```dart
bool serviceEnabled;
LocationPermission permission;

// Test if location services are enabled.
serviceEnabled = await Geolocator.isLocationServiceEnabled();
if (!serviceEnabled) {
  // Location services are not enabled don't continue
  // accessing the position and request users of the 
  // App to enable the location services.
  return;
}

permission = await Geolocator.checkPermission();
if (permission == LocationPermission.denied) {
  // Only request permission when permission are denied.
  permission = await Geolocator.requestPermission();
  if (permission == LocationPermission.deniedForever) {
    // Permissions are denied forever, handle appropriately. 
    return;
  } 

  if (permission == LocationPermission.denied) {
    // Permissions are denied, next time you could try
    // requesting permissions again (this is also where
    // Android's shouldShowRequestPermissionRationale 
    // returned true. According to Android guidelines
    // your App should show an explanatory UI now.
    return;
  }
}

// When we reach here, permissions are granted and we can
// continue accessing the position of the device.
_position = await Geolocator.getCurrentPosition();
```

I am very interested in how the community feel about this and if this will cause some serious problems that I am currently not able to see. Please give a 👍 if you agree with this change or give your 👎 if you are against it. When you are against it, it would be great if you could leave a comment explaining what it is that would be blocking you.

**Comment by grahamsmith** [comment]
To be honest when I integrated this, I was surprised it asked for permission for me. Seems sensible enough a move. 👍

**Comment by aytunch** [comment]
We never relied on the permission functionality of geolocator package because of the lack of freedom it causes. We used the permission package for those needs. And i think we should show how to use permission&geolocator together in the example amd readme files and it will all be fine.

**Comment by mvanbeusekom** [comment]
@aytunch thank you for your feedback, it is much appreciated. I was just wondering if you could explain which freedom you are missing in the geolocator package in relation to managing permissions?

**Comment by matasb-google** [comment]
Proposal makes sense, especially for use cases when location should be requested "silently" and fail otherwise.

**Comment by aytunch** [comment]
@mvanbeusekom hi,
What I meant by "lack of freedom" was `geolocator` handling the permission internally without my explicit consent.
We feel that handling permission manually is better because we have UI elements (showing exclamation mark icons etc) which guide user. Also we like showing the user our own dialogs stating why the permission is needed before displaying the OS permission dialog. And if permission is permanently denied, we show them a dialog asking them to go to the app settings. So basically we want to have more control.

**Comment by mvanbeusekom** [comment]
Thanks for this feedback @aytunch, however what I am mostly interested in is which features are you missing in the geolocator to handle permissions manually?

The geolocator currently provides a `checkPermission` and `requestPermission` to handle permissions manually with the idea you don't need a third party package (at least for handling the location related permissions). I am wondering if you are missing something there that we could add to improve handling permissions manually.

**Comment by aytunch** [comment]
Right now we are using these to manage the above scenario. So we are not missing anything in the `geolocator` package in terms of permission functionality. We use `AppLifecycleState` in conjunction with 'checkPermission'

```
Geolocator.getServiceStatusStream();
Geolocator.checkPermission();
Geolocator.isLocationServiceEnabled();
Geolocator.openAppSettings();
Geolocator.openLocationSettings();
```

**Comment by mvanbeusekom** [comment]
> Right now we are using these to manage the above scenario. So we are not missing anything in the `geolocator` package in terms of permission functionality. Our app is very robust in terms of Location thanks to Geolocator.

Awesome that is great to hear, thank you very much for the feedback and please let us know when there is something we can improve on.

**Comment by aytunch** [comment]
@mvanbeusekom I thank you for these greatly maintained plugins.

The only improvement I would ask for is the issue with Android permissions not being able to distinguish between denied and permanently denied. We need to check the return value of `checkPermission` to understand the state of the permission.

However I am not sure if this is related to the plugins or Android OS.
