### ISSUE TITLE
is it working with Wear OS ?

### ISSUE THREAD

**Issue by weissloic** [Baseflow/flutter-geolocator#785]
When I try to get my location on my watch, I always get this error message : "The location service on the device is disabled.", however it's enabled.

Thx

**Comment by AlirezaEiji191379** [comment]
Are you sure that you set the correct permissions in the manifest file for wear os?

if you forget it just add this line to the android manifest file

`<uses-permission android:name="android.hardware.location" />`

**Comment by weissloic** [comment]
Yes, it's already done, i've tested the same code on my Oneplus 6t and it works...

**Comment by mvanbeusekom** [comment]
Hi @weissloic, 

This is hard to say, I personally don't have access to a WearOS device and therefore haven't tested. The plugin is developed (and tested) for Android phone/ tablets, iOS phones and tablets and the web. I have not done anything specific to make sure WearOS is also supported. 

If you could help out and maybe debug on you WearOS device and give feedback on where things might go wrong, I am more then willing to make changes to make sure WearOS is also supported correctly.

**Comment by jahnli** [comment]
@mvanbeusekom  For Chinese devices, Google Play Store is missing
![1627374990(1)](https://user-images.githubusercontent.com/20943608/127123494-cb55c103-843d-4c1a-bcdf-eb657c945b83.jpg)

**Comment by mvanbeusekom** [comment]
@jahnli thank you for your reply, but how does this apply to running the plugin on WearOS? I am not quite sure how your comment is relevant to this issue, could you explain this?

**Comment by jahnli** [comment]
@mvanbeusekom   https://github.com/Baseflow/flutter-geolocator/issues/794   
This is the question I want to ask,
I have a Chinese device, but when I use it, I am prompted that oogle Play Store is missing. May I ask if it can be solved

**Comment by mvanbeusekom** [comment]
@jahnli you may of course but that is a separate issue and not related to WearOS. Posting your problem here will distract from the original issue and may lead to wrong assumptions / conclusions.

**Comment by jahnli** [comment]
@mvanbeusekom  ok， I will delete the answer under this question, please help me https://github.com/Baseflow/flutter-geolocator/issues/794

**Comment by masus04** [comment]
Can confirm, speed api works perfectly well on android phone but throws an error about the service being disabled on any wearOS device.

Any updates or plans on this?

**Comment by masus04** [comment]
I would be motivated to add wearOS support to the android plugin, if you can point me in the right direction.

**Comment by masus04** [comment]
Hi @mvanbeusekom

I just realized now that you offered to help implement it :)

I only develop on Android Studio, using the provided WearOS emulator. It is quite simple to use and the error seems to be identical to the one @weissloic describes.

I can post the stacktrace I receive below:
```
D/FlutterGeolocator( 6377): Attaching Geolocator to activity
D/FlutterGeolocator( 6377): Creating service.
D/FlutterGeolocator( 6377): Binding to location service.
D/FlutterGeolocator( 6377): Geolocator foreground service connected
D/FlutterGeolocator( 6377): Initializing Geolocator services
D/FlutterGeolocator( 6377): Flutter engine connected. Connected engine count 1
...
E/FlutterGeolocator( 6377): Geolocator position updates started
...
I/flutter ( 6377): The location service on the device is disabled.
I/flutter ( 6377): #0      GeolocatorAndroid.getPositionStream.<anonymous closure> (package:geolocator_android/src/geolocator_android.dart:187:9)
I/flutter ( 6377): (elided 26 frames from dart:async)
```
There's not really anything useful in there as far as I can tell. I assume there's a different API that must be used for wearOS compared to regular android?

Does this help? Otherwise let me know what I can do in order to help.

**Comment by talhazengin** [comment]
So, no updates?

**Comment by Deme94** [comment]
so you cannot get the Wear OS device's location in flutter??? because the location library is outdated too

**Comment by JeroenWeener** [comment]
Closing this issue as discussion pointed out that WearOS is indeed not supported at this time.

Please refer to #1197 for tracking WearOS support.
