### ISSUE TITLE
Geolocator not working when deployed to web server.

### ISSUE THREAD

**Issue by hevf** [Baseflow/flutter-geolocator#793]
## 🐛 Bug Report

Geolocator is not giving back coordinates when deploying to web server. I uploaded the example you provided here https://github.com/Baseflow/flutter-geolocator/tree/master/geolocator_web and when I press the "play" button nothing is returned, also when pressing the "get permissions button" i get this error in the console:

main.dart.js:3758 Uncaught TypeError: m.gFz is not a function
    at Object.ae8 (main.dart.js:14922)
    at main.dart.js:55100
    at a4e.a (main.dart.js:5325)
    at a4e.$2 (main.dart.js:28990)
    at a3g.$1 (main.dart.js:28982)
    at J5.iK (main.dart.js:30032)
    at a_Z.$0 (main.dart.js:29437)
    at Object.p9 (main.dart.js:5445)
    at V.iY (main.dart.js:29345)
    at a_R.$0 (main.dart.js:29398)

You can see the behaviour here:  https://purebaskkc.web.app/#/

Cheers!

**Comment by mvanbeusekom** [comment]
Hi @hevf,

This is an known issue and is caused in the null-safe version of dartjs. The code will work fine if you build using the `--no-sound-null-safety` switch.

More information can be found in issue #693.

The bug has been fixed but we are waiting for it to be released.

**Comment by hevf** [comment]
@mvanbeusekom Thanks a lot for the info!

Cheers!
