### ISSUE TITLE
Execution failed for task ':geolocator:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by fauzipadlaw** [Baseflow/flutter-geolocator#795]
## 🐛 Bug Report

Error when running on Android.

```
Note: Recompile with -Xlint:deprecation for details.
3 warnings
/Users/efzet/.pub-cache/hosted/pub.dartlang.org/geolocator-7.3.1/android/src/main/java/com/baseflow/geolocator/location/LocationManagerClient.java:10: warning: [deprecation] LocationProvider in android.location has been deprecated
import android.location.LocationProvider;
                       ^
error: warnings found and -Werror specified
/Users/efzet/.pub-cache/hosted/pub.dartlang.org/geolocator-7.3.1/android/src/main/java/com/baseflow/geolocator/location/LocationMapper.java:29: warning: [deprecation] isFromMockProvider() in Location has been deprecated
      position.put("is_mocked", location.isFromMockProvider());
                                        ^
1 error
2 warnings

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':geolocator:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 47s
Exception: Gradle task assembleStagingDebug failed with exit code 1
```
### Expected behavior
Success running
### Reproduction steps
flutter run
### Configuration

**Version:** 7.3.1

```
[✓] Flutter (Channel unknown, 2.0.5, on macOS 11.5 20G71 darwin-arm, locale en)
    • Flutter version 2.0.5 at /Users/efzet/SDKs/flutold
    • Framework revision adc687823a (3 months ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/efzet/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/efzet/Library/Android/sdk
    • Java binary at: /Users/efzet/.sdkman/candidates/java/current/bin/java
    • Java version OpenJDK Runtime Environment Zulu15.28+13-CA (build 15.0.1+8)
    • All Android licenses accepted.

```

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @fauzipadlaw, 

We have no such issues when building the example app on our CI environment (you can find the latest build run for Android [here](https://github.com/Baseflow/flutter-geolocator/runs/3143584528?check_suite_focus=true)). 

Could you please list the your copy of the `android/build.gradle` and `android/app/build.gradle` files? Possibly you are using are using a newer gradle version or compiling against the latest Android SDK which is causing this problem.

**Comment by fauzipadlaw** [comment]
I found out this issue is because I used SDK version 31 for the compilation. I changed to 31 and it worked again. Anyway, we will be facing this issue eventually.

**Comment by Alqasim77** [comment]
> I found out this issue is because I used SDK version 31 for the compilation. I changed to 30 and it worked again. Anyway, we will be facing this issue eventually. Some APIs are removed in SDK 31 (Deprecated).

THANKS MAN A LOT..I HAVE THIS ISSUE FOR A WEEK AND THIS SOLUTION WORK FOR ME...THAAAAAAAANKSS

**Comment by ajilijihad** [comment]
please help if i change to 31 this error disappear but this another error show

C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\geolocator-7.1.1\android\src\main\java\com\baseflow\geolocator\location\LocationMapper.java:29: warning: [deprecation] isFromMockProvider() in Location has been deprecated
      position.put("is_mocked", location.isFromMockProvider());

**Comment by vikramsinghrajpoot** [comment]
Facing same issue with FLutter 3.7.0 and (geolocator: ^9.0.2)

**Comment by vikramsinghrajpoot** [comment]
* What went wrong:
Execution failed for task ':geolocator_android:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by jb3rndt** [comment]
The issue sill occurs for compileSdkTarget 33 (which is the current default by flutter) after geolocator_android upgraded from 4.2.0 to 4.2.2. If you dont want to hard-code your compileSdkTarget, you can also lock the geolocator_android version by adding this to your pubspec.yaml:

```
dependency_overrides:
  geolocator_android: 4.2.0
```

This worked for me, I guess the geolocator_android dependency will be updated in the future so this is not necessary anymore. Until then, I suggest to reopen this issue...

**Comment by mvanbeusekom** [comment]
Hi @jb3rndt,

Unfortunately I cannot reproduce the above deprecation error with the latest code base using the example app. At the moment there is a specific warning regarding requesting `POST_NOTIFICATION` permission which is addressed separately. 

However the deprecation warning regarding the `isFromMockProvider` has been suppressed (since it is placed inside a check on API level).

**Comment by jb3rndt** [comment]
Thanks for your fast response, it turns out that the underlying issue is a completely different one :)
