### ISSUE TITLE
Geolocator Apple not found. Release build on iOS

### ISSUE THREAD

**Issue by bichoalexis** [Baseflow/flutter-geolocator#805]
## 🐛 Bug Report

When I try to run as release mode I get the error @import **geolocator_apple not found**.
I did flutter clean, delete pods and change version and nothing works.
### Expected behavior
Compile my app 

### Configuration

**Version:** geolocator: ^7.4.0 and ^7.3.1

**Platform:** 
- [ x ] :iphone: iOS
- [ ] :robot: Android

**Comment by jigarfumakiya** [comment]
Any update here
I have the same issue

**Comment by bichoalexis** [comment]
> Any update here
> I have the same issue

Not yet :( still waiting

**Comment by mbagozpel** [comment]
I have the same issue

**Comment by jigarfumakiya** [comment]
Please try below might work.

1. Switch to flutter master.
2. flutter clean
3. Run in the real device.

**Comment by bichoalexis** [comment]
> @mabels
> Please try below might work.
> 
> 1. Switch to flutter master.
> 2. flutter clean
> 3. Run in the real device.

Not working :/

**Comment by jigarfumakiya** [comment]
> > @mabels
> > Please try below might work.
> > 
> > 1. Switch to flutter master.
> > 2. flutter clean
> > 3. Run in the real device.
> 
> Not working :/

@bichoalexis  Yes, that fix is random sometimes it's work sometimes it's not.

**Comment by bichoalexis** [comment]
Hey there I found finally the solution of this topic. Just ensure that your iOS Deployment version is above 12.0.
<img width="866" alt="Captura de Pantalla 2021-09-08 a la(s) 12 43 25" src="https://user-images.githubusercontent.com/78701419/132558721-564ecaa6-ae8d-4df5-9635-fcea693cff90.png">

Here is another person who was the same problem [https://githubmemory.com/repo/Baseflow/flutter-geolocator/issues/829](url) 
Hope This help.
