### ISSUE TITLE
A problem occurred evaluating project ':mobile' ( please help me1

### ISSUE THREAD

**Issue by digitalgriho** [Baseflow/flutter-geolocator#811]
## 💬 Questions and Help

A problem occurred evaluating project ': mobile' 

 Could not get unknown property 'release' for SigningConfig container of type org.gradle.api.internal.FactoryNamedDomainObjectContainer.

this is a problem on the android studio when i going to gradle build. please help me, team, please... 
there has show,  

Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'release' for SigningConfig container of type org.gradle.api.internal.FactoryNamedDomainObjectContainer

**Comment by mvanbeusekom** [comment]
Hi @digitalgriho,

This seems to be related to the configuration in your `android/app/build.gradle` file which according to the error you shared is missing the `release` section under the `buildTypes` section. 

If you need an example please have a look at the `build.gradle` file of our example app: https://github.com/Baseflow/flutter-geolocator/blob/master/geolocator/example/android/app/build.gradle

Note, I don't see any relation to the geolocator plugin so I will close this issue. If you have any (geolocator related) questions don't hesitate to leave another comment or open a new issue.
