### ISSUE TITLE
didChangeAppLifecycleState loop

### ISSUE THREAD

**Issue by p-shapovalov** [Baseflow/flutter-geolocator#816]
## 🐛 Bug Report

**didChangeAppLifecycleState** goes into a loop after location request. Only on some devices, but definitely reproduced on any xiaomi redmi note 9
It can be avoided by **forceAndroidLocationManager: true**

### Configuration

**Version:** 7.4.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by p-shapovalov** [comment]
Please check https://github.com/Baseflow/flutter-geolocator/issues/717#issuecomment-822654900, same behavior here with activity result cycle

**Comment by hoanglm4** [comment]
same issue for me on Xiaomi device

**Comment by mvanbeusekom** [comment]
Thanks to @hoanglm4 this issue should now be fixed. I will close the issue but feel free to leave a comment when you run into the issue again.

**Comment by sed1ka** [comment]
this issue is exactly what happened to me. This issue also happen on Xiaomi Redmi 9T #1056
