### ISSUE TITLE
[iOS] Not receiving location updates if location services are turned off and then back on

### ISSUE THREAD

**Issue by mikebryant71** [Baseflow/flutter-geolocator#821]
### Expected behavior
After subscribing to location updates (onLocationChanged stream) if the user turns off the location services, then back on, it should resume yielding new location updates.

### Reproduction steps

- Tap on "Play button" to start listening for position updates
- Go to native Settings/Privacy/Location Services 
- Turn off Location Services
- Turn on Location Services
- Return to Example app
- Change user's location via Simulator menu -> Features/Location
- The new position is not received. (onLocationChanged not receiving new data)

Video: https://streamable.com/cc1p5l

### Configuration
Use iOS baseflow example app provided. (Also reproducible in the app I'm developing)
Using iOS Simulator, reproducible on iOS 13.2 & 14.4. (likely on other versions of iOS too).

**Version:** 7.4.0

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by mikebryant71** [comment]
I did some testing and did not find there to be any memory leaks, nor with energy usage. It seems like the CLLocationManager does a good job of that.

An exception, although an improvement, I think the current behaviour is a bit unexpected from the flutter side. If you're start listening to a stream, you expect it to be "active" until you call `cancel()`. Calling `cancel()` also stops listening to location updates so that means any memory concerns flutter side are manageable.
This also makes it easier for the flutter dev who wants to monitor location updates. They don't need to keep re subscribing to a stream based off the events of the service enabled stream which would also makes them independant.

**Comment by florissmit1** [comment]
@JustChris This issue is solved, the PR is mentioned just above this comment. I will close this issue, if it's still not working like you would expect, please re-open this issue.
