### ISSUE TITLE
Deprecation warnings when compiling against Android API 31

### ISSUE THREAD

**Issue by mvanbeusekom** [Baseflow/flutter-geolocator#828]
## 🐛 Bug Report

Using the geolocator plugin on Android API 31 generates the following error:

```
Note: Recompile with -Xlint:deprecation for details.
3 warnings
/Users/efzet/.pub-cache/hosted/pub.dartlang.org/geolocator-7.3.1/android/src/main/java/com/baseflow/geolocator/location/LocationManagerClient.java:10: warning: [deprecation] LocationProvider in android.location has been deprecated
import android.location.LocationProvider;
                       ^
error: warnings found and -Werror specified
/Users/efzet/.pub-cache/hosted/pub.dartlang.org/geolocator-7.3.1/android/src/main/java/com/baseflow/geolocator/location/LocationMapper.java:29: warning: [deprecation] isFromMockProvider() in Location has been deprecated
      position.put("is_mocked", location.isFromMockProvider());
                                        ^
1 error
2 warnings

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':geolocator:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 47s
Exception: Gradle task assembleStagingDebug failed with exit code 1
```

Starting from Android API 31 the `LocationProvider` class and `isFromMockProvider` method are deprecated. More information can be found in the official documentation:

- https://developer.android.com/reference/android/location/LocationProvider
- https://developer.android.com/reference/android/location/Location#isFromMockProvider()

### Expected behavior

Compiling an App depending on the geolocator plugin should work fine on Android 31.

### Reproduction steps

To reproduce this on the example App take the following steps:
1. Open `example/android/app/build.gradle` file;
2. Change the `compileSdkVersion` to value `31`;
3. Build the example app using `flutter build appbundle`

### Configuration

**Version:** 7.6.0

**Platform:** 
- [x] :robot: Android

**Comment by babihutan** [comment]
I'd like to help out by working on this, but not really sure how to get started.

**Comment by mvanbeusekom** [comment]
Hi @babihutan, thank you very much for this generous offer. However @florissmit1 just this morning created PR #830 which should resolve this issue. 

The PR is currently marked as draft since it would require everyone to compile against API 31 if it were merged. Since API 31 is still in a beta state we figured it would be better not to merge it yet to master and release it to the public.

**Comment by babihutan** [comment]
I reviewed at the fixes for PR #830, and I can see that I wasn't going to figure that out!  I tried using the fix directly (many ways) to get my project to work using dependency_overrides, but kept getting an error that pubspec.yaml couldn't be found and other errors.  The fundamental problem I've had is that somehow I started picking up a dependency to 1.7.0-alpha02 on 1 Sept which necessitates API 31. At last, I fixed it by adding this to android/app/build.gradle:

    configurations.all {
        resolutionStrategy {
            force 'androidx.core:core-ktx:1.6.0'
        }
    }

If others have this issue, maybe this will provide relief.

**Comment by hpoul** [comment]
fwiw, I had the exact same problem because a plugin depended on `androidx.core:core-ktx:+` so i guess it would be better to search for that broken dependency (eg by building with gradle `--scan` and check which plugin requires that latest version). This way other users won't run into this at all 🤔

**Comment by ajilijihad** [comment]
> ## 🐛 Bug Report
> Using the geolocator plugin on Android API 31 generates the following error:
> 
> ```
> Note: Recompile with -Xlint:deprecation for details.
> 3 warnings
> /Users/efzet/.pub-cache/hosted/pub.dartlang.org/geolocator-7.3.1/android/src/main/java/com/baseflow/geolocator/location/LocationManagerClient.java:10: warning: [deprecation] LocationProvider in android.location has been deprecated
> import android.location.LocationProvider;
>                        ^
> error: warnings found and -Werror specified
> /Users/efzet/.pub-cache/hosted/pub.dartlang.org/geolocator-7.3.1/android/src/main/java/com/baseflow/geolocator/location/LocationMapper.java:29: warning: [deprecation] isFromMockProvider() in Location has been deprecated
>       position.put("is_mocked", location.isFromMockProvider());
>                                         ^
> 1 error
> 2 warnings
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':geolocator:compileDebugJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 47s
> Exception: Gradle task assembleStagingDebug failed with exit code 1
> ```
> 
> Starting from Android API 31 the `LocationProvider` class and `isFromMockProvider` method are deprecated. More information can be found in the official documentation:
> 
> * https://developer.android.com/reference/android/location/LocationProvider
> * https://developer.android.com/reference/android/location/Location#isFromMockProvider()
> 
> ### Expected behavior
> Compiling an App depending on the geolocator plugin should work fine on Android 31.
> 
> ### Reproduction steps
> To reproduce this on the example App take the following steps:
> 
> 1. Open `example/android/app/build.gradle` file;
> 2. Change the `compileSdkVersion` to value `31`;
> 3. Build the example app using `flutter build appbundle`
> 
> ### Configuration
> **Version:** 7.6.0
> 
> **Platform:**
> 
> * [x]  🤖 Android

if i change it to 30 

same erro lik this 

 Flutter Fix ─────────────────────────────────────────────────┐
│ [!] Your project requires a higher compileSdkVersion.         │
│ Fix this issue by bumping the compileSdkVersion in            │
│ C:\Users\jihad\OneDrive\Bureau\uber\android\app\build.gradle: │
│ android {                                                     │
│   compileSdkVersion 31                                        │
│ }
