### ISSUE TITLE
Using Geolocator 7.6.0 packages produces following errors

### ISSUE THREAD

**Issue by christhapa9** [Baseflow/flutter-geolocator#832]
## 🐛 Bug Report
![Capture](https://user-images.githubusercontent.com/46759369/132653977-4da46ab5-e4ab-4f77-beba-076f44316616.PNG)

```
../../../../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/geolocator_platform_interface-2.3.4/lib/src/implementations/method_channel_geolocator.dart:249:9: Error: The getter 'appthrow' isn't defined for the class 'MethodChannelGeolocator'.
 - 'MethodChannelGeolocator' is from 'package:geolocator_platform_interface/src/implementations/method_channel_geolocator.dart' ('../../../../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/geolocator_platform_interface-2.3.4/lib/src/implementations/method_channel_geolocator.dart').

Try correcting the name to the name of an existing getter, or defining a getter or field named 'appthrow'.
        appthrow const LocationServiceDisabledException();
        ^^^^^^^^
../../../../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/geolocator_platform_interface-2.3.4/lib/src/implementations/method_channel_geolocator.dart:248:7: Error: Switch case may fall through to the next case.
      case 'LOCATION_SERVICES_DISABLED':

      ^
../../../../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/geolocator_platform_interface-2.3.4/lib/src/implementations/method_channel_geolocator.dart:249:9: Error: Expected ';' after this.
        appthrow const LocationServiceDisabledException();
        ^^^^^^^^
../../../../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/geolocator_platform_interface-2.3.4/lib/src/implementations/method_channel_geolocator.dart:249:9: Error: The getter 'appthrow' isn't defined for the class 'MethodChannelGeolocator'.

 - 'MethodChannelGeolocator' is from 'package:geolocator_platform_interface/src/implementations/method_channel_geolocator.dart' ('../../../../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/geolocator_platform_interface-2.3.4/lib/src/implementations/method_channel_geolocator.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'appthrow'.
        appthrow const LocationServiceDisabledException();

        ^^^^^^^^
../../../../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/geolocator_platform_interface-2.3.4/lib/src/implementations/method_channel_geolocator.dart:248:7: Error: Switch case may fall through to the next case.
      case 'LOCATION_SERVICES_DISABLED':
```

### [√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1165], locale en-US)
-Terminate batch job (Y/N)? y
PS C:\Users\nitro\Dropbox\My PC (LAPTOP-894T55CI)\Desktop\projects\native\flutter\flutterapp> flutter doctor -v
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1165], locale en-US)
    • Flutter version 2.2.3 at C:\src\flutter
    • Framework revision f4abaa0735 (2 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3) 
    • Android SDK at C:\Users\nitro\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\nitro\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.60.0)
    • VS Code at C:\Users\nitro\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 93.0.4577.63
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 93.0.961.38

• No issues found!

**Version:** 7.6.0

**Platform:** 
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @christhapa9,

It looks like you have accidentally edited the `method_channel_geolocator.dart` file in the pub-cache folder. Keep in mind that source code of packages downloaded from pub.dev is downloaded to your `C:\Users\nitro\AppData\Local\Pub\cache\hosted\pub.dartlang.org` folder. When debugging your App this source code is opened and can easily be edited/ altered. 

If you look at the [source code on GitHub](https://github.com/Baseflow/flutter-geolocator/blob/ef10960f3ada99347e0ab7ec10d3db0f3736163c/geolocator_platform_interface/lib/src/implementations/method_channel_geolocator.dart#L249) for version 7.6.0, you will notice that this line is a valid `throw` statement. From the error message you listed I understand that your local version is trying to call `appthrow` on this line which is not valid obviously.

The best way to solve this issue would be to remove the `geolocator_platform_interface-2.3.4` folder from the `C:\Users\nitro\AppData\Local\Pub\cache\hosted\pub.dartlang.org` location. Once you have removed this folder run `flutter pub get` to download a fresh copy of the dependencies your app requires.

Please let me know if this resolves your problem.

**Comment by nicolasjon** [comment]
I would also suggest this is followed by
Flutter Clean
and
Android Studio invalidate caches and restart
