### ISSUE TITLE
[deprecation] LocationProvider in android.location has been deprecated.  flutter 2.5, for android

### ISSUE THREAD

**Issue by jeffreyliu8** [Baseflow/flutter-geolocator#844]
android:

1.0.2/android/src/main/java/com/baseflow/geolocator/location/LocationManagerClient.java:10: warning: [deprecation] LocationProvider in android.location has been deprecated
import android.location.LocationProvider;
                       ^
error: warnings found and -Werror specified
/Users/JeffreyLiu/development/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_android-1.0.2/android/src/main/java/com/baseflow/geolocator/location/LocationMapper.java:29: warning: [deprecation] isFromMockProvider() in Location has been deprecated
      position.put("is_mocked", location.isFromMockProvider());
                                        ^
1 error
2 warnings

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':geolocator_android:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by mvanbeusekom** [comment]
@jeffreyliu8 we have a PR ready with a fix. However this is not related to Flutter 2.5 but to the upcoming release of Android 12 (API 31). 

For now the workaround would be to not target Android API 31 in your `android/app/build.gradle` file. Make sure the values for `targetSdkVersion` and `compileSdkVersion` are set to `30`.

I will close this issue as it is a duplicated of existing issue.

**Comment by ajilijihad** [comment]
> @jeffreyliu8 we have a PR ready with a fix. However this is not related to Flutter 2.5 but to the upcoming release of Android 12 (API 31).
> 
> For now the workaround would be to not target Android API 31 in your `android/app/build.gradle` file. Make sure the values for `targetSdkVersion` and `compileSdkVersion` are set to `30`.
> 
> I will close this issue as it is a duplicated of existing issue.


if i change in 30 same error show like this :

 [!] Your project requires a higher compileSdkVersion.         │
│ Fix this issue by bumping the compileSdkVersion in            │
│ C:\Users\jihad\OneDrive\Bureau\uber\android\app\build.gradle: │
│ android {                                                     │
│   compileSdkVersion 31                                        │
│ }
