### ISSUE TITLE
requestPermission() should not return LocationPermission.deniedForever when dialog is dismissed (Chrome)

### ISSUE THREAD

**Issue by minhqdao** [Baseflow/flutter-geolocator#848]
## 🐛 Bug Report

When `requestPermission()` is executed in Chrome, a dialog is shown asking for permissions to access user location. The return value is `LocationPermission.whileInUse` if the user agrees and `LocationPermission.deniedForever` if the user denies. That's fine. But when the user dismisses the dialog, `LocationPermission.deniedForever` is also returned, although I think that `LocationPermission.denied` (or even rename it to `LocationPermission.dismissed`) would be a much better choice.

To differentiate whether the user has denied permissions or dismissed the dialog, we now call `checkPermission()` afterwards because that is able to differentiate between `LocationPermission.denied` and `LocationPermission.deniedForever` in Chrome. However, that is problematic in Firefox because `checkPermission()` always returns `LocationPermission.denied` if you haven't checked the "remember" checkbox. If possible, I think we should change that, too.

### Expected behavior

- `LocationPermission.denied` should be returned instead of `LocationPermission.deniedForever` when the user dismisses the dialog in Chrome.
- `getLocation()` should throw different exceptions if the user dismisses the dialog vs. rejects permission.
- `checkPermission()` should return the correct `LocationPermission` of the session in Firefox.

### Reproduction steps

- Call `requestPermission()` on Chrome and print out the result after awaiting user input.
- Then call `checkPermission()` and print out to compare.
- Deploy somewhere and repeat the same steps in Firefox.

### Configuration

**Version:**
- Flutter (Channel dev, 2.5.0-5.0.pre, on macOS 11.6 20G165 darwin-arm, locale de-DE)
- geolocator: ^7.6.2

**Platform:** 
- [x] Web (Chrome, Firefox)

**Comment by mvanbeusekom** [comment]
Hi @minhqdao,

Thank you for submitting this issue and the clear explanation. Unfortunately there is no way to distinguish between a user blocking permissions or dismissing the dialog window. In both cases a `PermissionDeniedException` is thrown which is translated by the geolocator_web plugin to a `LocationPermission.deniedForever` status. 

Actually Firefox has the only correct implementation where it distinguishes between "don't ask me again" (when checking the remember box) and simply blocking permissions once but Apps are allowed to ask again (when you don't check the remember button). 

When calling the Firefox implementation of the `navigator.permissions.query()` method Firefox will return:

- `granted` when the user selected "Allow";
- `prompt` when the user selected "Block" without checking the "Remember" checkbox;
- `denied` when the user selected "Block" and checking the "Remember" checkbox.

Chrome doesn't make this differentiation and only returns the status `granted` or `denied` which means the geolocator plugin can also not differentiate between `denied` or `deniedForever`. 

I can look into a solution where we detect the browser (Chrome, Firefox, Safari, etc..) and return permissions based on that, however I feel this can easily become very messy and maybe even more confusing to developers.

**Comment by minhqdao** [comment]
Thanks for the detailed answer!

It's indeed unfortunate that Chrome doesn't distinguish between dismissing and blocking permissions and in both cases throws the same exception when `navigator.geolocation.getCurrentPosition()` is invoked by `requestPermission()`.

However, I think that `navigator.permissions.query()` (invoked by `checkPermission()`) also returns the correct info in Chrome (`granted`, `prompt` and `denied`), just as in Firefox. But that still means that `checkPermission()` needs to be called after `requestPermission()` if we want to know whether permissions were blocked or dismissed by the user before. 😮‍💨

What then makes it bit difficult is that `checkPermission()` is only of limited use in Firefox as it always returns `LocationPermission.denied` after the user granted or blocked permissions with "remember" not being checked. I guess the entire point behind the deselected checkbox is that permission state is not maintained (in Chrome it is), but it also makes handling different browsers via the same code difficult if each one handles state so differently.

So yeah, it's a bit tricky.

And then we haven't talked about the fact that Safari is not supported at all. 😅
