### ISSUE TITLE
Android build failing on Geolocator.  Worked yesterday, failing today

### ISSUE THREAD

**Issue by abbadabbatech** [Baseflow/flutter-geolocator#857]
## 🐛 Bug Report

/Users/dnetman99/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_android-2.0.0/android/src/main/java/com/baseflow/geolocator/location/LocationMapper.java:29: error: cannot find symbol
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
                                                    ^
  symbol:   variable S
  location: class VERSION_CODES
/Users/dnetman99/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_android-2.0.0/android/src/main/java/com/baseflow/geolocator/location/LocationMapper.java:30: error: cannot find symbol
      position.put("is_mocked", location.isMock());
                                        ^
  symbol:   method isMock()
  location: variable location of type Location
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':geolocator_android:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
Exception: Gradle task assembleDebug failed with exit code 1

### Reproduction steps
Once I remove the plugin all works fine

### Configuration

**Platform:** 
- [ ] :iphone: iOS have not tried yet
- [X ] :robot: Android

**Comment by mvanbeusekom** [comment]
You have probably upgraded to use Geolocator version 7.7.0, which means you will also need to update your `android/app/build.gradle` file and set the `compileSdkVersion` to `31` (see also the [CHANGELOG](https://pub.dev/packages/geolocator/changelog#770)).

**Comment by EinatK** [comment]
@mvanbeusekom I'm on version 7.6.2, with compileSdkVersion and targetSdkVersion set to 30 not not working. 

flutter doctor -v 

`[✓] Flutter (Channel master, 2.6.0-12.0.pre.186, on macOS 11.6 20G165 darwin-arm,
    locale en-US)
    • Flutter version 2.6.0-12.0.pre.186 at /Users/einatkidron/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 905ac63e34 (6 days ago), 2021-10-04 23:13:04 +0800
    • Engine revision 6f4143e800
    • Dart version 2.15.0 (build 2.15.0-172.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/einatkidron/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/einatkidron/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (3 available)
    • Redmi Note 7 (mobile)      • ab9cb65                              •
      android-arm64  • Android 10 (API 29)
    • iPhone 11 Pro Max (mobile) • 7E65B9B7-74A2-40BC-8B92-D54C5FDB1ABF • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 94.0.4606.71

• No issues found!`

**Comment by mvanbeusekom** [comment]
@EinatK,

Make sure you run a `flutter clean` followed with `flutter pub get`. If that doesn't work, could you provide more information?

- What is the error you receive?
- Provide the contents of the `pubspec.yaml`;
- Provide the contents of the `android/app/build.gradle`;

**Comment by mvanbeusekom** [comment]
@EinatK, you should pin the geolocator to version 7.6.2 (without using the caret `^` character) like so:

```yaml
  geolocator: 7.6.2
```

If you don't Flutter will still upgrade the geolocator plugin to version 7.7.0. More information can be found here: https://dart.dev/tools/pub/dependencies#caret-syntax

**Comment by EinatK** [comment]
@mvanbeusekom it is pinned

**Comment by mvanbeusekom** [comment]
Not in the version of the `pubspec.yaml` you attached in your previous comment.

**Comment by EinatK** [comment]
So sorry, my bad ... i was sure i did that :/
I pinned and now it's working
Thanks so much
