### ISSUE TITLE
when run flutter 

### ISSUE THREAD

**Issue by GeNeRal070** [Baseflow/flutter-geolocator#858]
## 🐛 Bug Report

* Try:
Launching lib\main.dart on AOSP on IA Emulator in debug mode...
lib\main.dart:1
2
Invalid depfile: D:\projects_flutter\app\.dart_tool\flutter_build\863a1c3735d759309bede64556b1f917\kernel_snapshot.d
C:\flutter_2\.pub-cache\hosted\pub.dartlang.org\geolocator_android-2.0.0\android\src\main\java\com\baseflow\geolocator\location\LocationMapper.java:29: error: cannot find symbol
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
                                                    ^
  symbol:   variable S
  location: class VERSION_CODES
C:\flutter_2\.pub-cache\hosted\pub.dartlang.org\geolocator_android-2.0.0\android\src\main\java\com\baseflow\geolocator\location\LocationMapper.java:30: error: cannot find symbol
      position.put("is_mocked", location.isMock());
                                        ^

  symbol:   method isMock()
  location: variable location of type Location
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':geolocator_android:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @GeNeRal070, 

Please make sure you update the `compileSdkVersion` in your `android/app/build.gradle` file to `31` (see also the [CHANGELOG.md](https://pub.dev/packages/geolocator/changelog) entry for version 7.7.0).

If you don't want or can't upgrade the Android compile SDK version you can pin the geolocator to version 7.6.2 in your pubspec.yaml file.

**Comment by mvanbeusekom** [comment]
@Puspharaj do you have the Android SDK Platform 31 installed (see screenshot below)?

<img width="983" alt="Screenshot 2021-10-08 at 15 06 36" src="https://user-images.githubusercontent.com/13098888/136562733-fb409166-e7f6-4643-b80f-54d587fb3267.png">

If all is installed please include the contents of your `android/app/build.gradle` file and the output of the `flutter doctor -v` command.
