### ISSUE TITLE
compilation error version 7.7.0

### ISSUE THREAD

**Issue by Shveetsov** [Baseflow/flutter-geolocator#861]
/Users/shvetsov/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_android-2.1.0/android/src/main/java/com/baseflow/geolocator/location/LocationMapper.java:29: error: cannot find symbol
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
                                                    ^
  symbol:   variable S
  location: class VERSION_CODES
/Users/shvetsov/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_android-2.1.0/android/src/main/java/com/baseflow/geolocator/location/LocationMapper.java:30: error: cannot find symbol
      position.put("is_mocked", location.isMock());
                                        ^
  symbol:   method isMock()
  location: variable location of type Location
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':geolocator_android:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

----------------
After updating flutter 61.2.2. there was this thing before that everything was fine

**Comment by mvanbeusekom** [comment]
Hi, please make sure you set `compileSdkVersion` in your `android/app/build.gradle` file to `31` when using geolocator version 7.7.0. If you cannot support Android 12 yet make sure to pin the dependency on geolocator to version 7.6.2.
