### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by omrid594** [Baseflow/flutter-geolocator#862]
## 🐛 Bug Report

SDK 31 installed
![image](https://user-images.githubusercontent.com/19475206/136647772-77aa6c56-f7cf-4b4e-b3f4-cce182ce3c54.png)

`compileSdkVersion` set to `31` at `android\app\build.gradle`

`* What went wrong:
Execution failed for task ':permission_handler:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
`

**Version:** 7.7.0

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android

**Comment by mvanbeusekom** [comment]
@omrid594 which version of the permission_handler are you using? The compile error seems to be related to the permission_handler. Make sure you are using 8.2.0 or higher of the permission_handler as that version is also compatible with Android 12.

If that doesn't work please provide the following information:

- the complete error message;
- the contents of your `android/app/build.gradle` file.

**Comment by omrid594** [comment]
@mvanbeusekom Thank you, updating permission make it worked!
