### ISSUE TITLE
LocationMapper.java:29: error: cannot find symbol

### ISSUE THREAD

**Issue by alexmro** [Baseflow/flutter-geolocator#863]
## 🐛 Bug Report

All of a sudden I get this error when trying to build in debug mode for Android:

```
C:\Users\user\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\geolocator_android-2.1.0\android\src\main\java\com\baseflow\geolocator\location\LocationMapper.java:29: error: cannot find symbol
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
                                                    ^
  symbol:   variable S
  location: class VERSION_CODES
C:\Users\user\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\geolocator_android-2.1.0\android\src\main\java\com\baseflow\geolocator\location\LocationMapper.java:30: error: cannot find symbol
      position.put("is_mocked", location.isMock());
                                        ^
  symbol:   method isMock()
  location: variable location of type Location
2 errors

FAILURE: Build failed with an exception.
```

This happened with version _7.6.2_ and also with _7.7.0_. I am using flutter _2.6.0-11.0.pre_. I tried cleaning up the pub cache, deleted _pubspeck.lock_. This just started happening after closing a gitflow feature and merging back to develop. Very strange how it started showing like this out of nowhere.

### Configuration

**Version:** 7.x

**Platform:** 
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi, please make sure you set `compileSdkVersion` in your `android/app/build.gradle` file to `31` when using geolocator version 7.7.0. If you cannot support Android 12 yet make sure to pin the dependency on geolocator to version 7.6.2 (make sure you pin it and not use the caret `^` symbol).
