### ISSUE TITLE
Geolocator not retrieving coordinates quickly on certain android devices (minutes) but working fine on iOS

### ISSUE THREAD

**Issue by jgolding94** [Baseflow/flutter-geolocator#877]
I have recently upgraded the plugin to version 7.0.0 and I have noticed that I am having issues getting the user's location coordinates, but only on the Android platform. Essentially, this is the logic flow:

1. User clicks on the button to get coordinates
2. If they haven't already been granted permission, they are presented with the popup which asks for their permission, with the three options
3. Once they grant permission, the popup disappears
4. The location icon in the top toolbar appears (not on the emulator though, only physical devices) indicating the location is being retrieved

The problem is on my Android device, which is a Samsung Galaxy A21s, running API 11.0, it takes 58 second plus to actually retrieve the coordinates. On the emulator, it just doesn't get the coordinates. On iOS devices, it comes within a few seconds. The slow speed at which the coordinates are retrieved makes it feel as though it hasn't worked and users certainly aren't going to be happy with that.

There's obviously no error with the code, as coordinates are retrieved, even when taking ages, except for the Android 12.0 emulator. In addition, there is no stack trace or error log output in the console, so I have nothing to show you in that sense.

In addition, the coordinates are retrieved in certain situations:

- iOS simulator
- iOS physical device
- Android emulator running API 11.0
- Android A21s physical device with API 11.0 (taking 58 seconds though)

Coordinates are not retrieved in the following situations:

- Android emulator running API 12.0
- Android physical device, running API 12.0

Is there a possible reason as to why the Geolocator isn't working with Android API 12.0 at all, and why it takes so long with the 11.0 API? Is there perhaps a setting I am not aware of, or a setting that I have configured incorrectly? These are the bits of code that might be of use.

```
  _determineCurrentPositionStarting() async {
    bool serviceEnabled;
    LocationPermission permission;

    // Test if location services are enabled.
    serviceEnabled = await Geolocator.isLocationServiceEnabled();
    if (!serviceEnabled) {
      // Location services are not enabled don't continue
      // accessing the position and request users of the
      // App to enable the location services.
      return;
    }

    permission = await Geolocator.checkPermission();
    if (permission == LocationPermission.denied) {
      permission = await Geolocator.requestPermission();
      if (permission == LocationPermission.deniedForever) {
        // Permissions are denied forever, handle appropriately.
        return;
      }
    }

    if (permission == LocationPermission.denied) {
      // Permissions are denied, next time you could try
      // requesting permissions again (this is also where
      // Android's shouldShowRequestPermissionRationale
      // returned true. According to Android guidelines
      // your App should show an explanatory UI now.
      return;
    }

    // When we reach here, permissions are granted and we can
    // continue accessing the position of the device.

    return await Geolocator.getCurrentPosition(
      desiredAccuracy: LocationAccuracy.best,
      forceAndroidLocationManager: true,
      timeLimit: null,
    ).then((Position position) {
      setState(() {
        gcStartingLatitudeGEODEG.text = position.latitude.toStringAsFixed(6);
        gcStartingLongitudeGEODEG.text = position.longitude.toStringAsFixed(6);
      });
    }).catchError((e) {
      print(e);
    });
  }
```

The asynchronous onPressed that calls the above function is:

```
            onPressed: () async {
              _determineCurrentPositionFinishing();
            },
```

The permissions granted within the androidmanifest.xml file are:

```
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
```

I am using gradle version 7.0.0 in my build.gradle file (android > app > build.gradle) my SDK versions are:

- compileSdkVersion: 31
- minSdkVersion: 23
- targetSdkVersion: 31

The Flutter Doctor comes back completely clean:

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Connected device (2 available)
```

I'm looking forward to hearing your thoughts, thanks.

**Comment by sxtfv** [comment]
+1, @jgolding94 did you found a workaround?

**Comment by jgolding94** [comment]
@sxtfv Not as such. I did a bit more 'testing' on various devices and simulators/emulators. What I found was quite interesting. Basically, the coordinates were retrieved in all cases. However, for the cases I described in my first post, it just took a long time.

As an example, on the iOS simulator I have, coordinates were retrieved within a few seconds, maximum. On both my own Android phone (an A21s, running 11.0) and 2 different emulators, the coordinates retrieval took anywhere between 60 seconds to 3 or 4 minutes. However, it did happen and did not fail, hence why no error message was shown in the console. 

I did notice that I had set the location accuracy to the highest possible setting and thought that might be slowing it down. That turned out not to be the case though, since even with the lowest accuracy, it still took the same amount of time.

To cut a long story short, I haven't been able to work out why it takes so long to get the coordinates on Android devices and therefore I have no way of speeding it up. However, I have added a little bit of warning text that shows up for users, explaining that it could take a while, depending on their device, location, connectivity etc.

I would still love to find a way of improving the speed on Android devices though!

**Comment by Shahmirzali-Huseynov** [comment]
any progress :( ?

**Comment by florissmit1** [comment]
@jgolding94 Thanks for reporting your issue, and indeed it's expected behaviour. What you can try, is making use of the FusedLocationProviderClient instead of the Android Location Manager. You can make use of it by not passing the `forceAndroidLocationManager` parameter to the `getCurrentPosition` method.  FusedLocationClient is by far faster then Android Location Manager. You can search the internet for a comparison between the two.

Let me know if it resolves your problem.

**Comment by jgolding94** [comment]
@florissmit1 Thanks so much for your feedback. That's interesting, as I wasn't aware of that. I have commented out the `forceAndroidLocationManager` parameter now and my gosh, the coordinates came within seconds, not minutes. Thanks! Can I ask though, why is that the case? Why is `forceAndroidLocationManager` so much slower? :)

**Comment by florissmit1** [comment]
@jgolding94 As you can see in the code snippet below, when passing the `forceAndroidLocationManager = true` paramater, you force your users to make us of the Android Location Manager instead of the Android Fused Location Provider. When not passing `forceAndroidLocationManager = true, the Fused Location Provider is used IF it's available on your device, else the Android Location Manager is used. The main difference between the two, is that Fused Location Provider relies on the Google Play Service API's, where Location Manager doesn't.

There are a lot of comparisons to be found on the internet which compare the two.

```
 public LocationClient createLocationClient(
      Context context,
      boolean forceAndroidLocationManager,
      @Nullable LocationOptions locationOptions) {
    if (forceAndroidLocationManager) {
      return new LocationManagerClient(context, locationOptions);
    }

    return isGooglePlayServicesAvailable(context)
        ? new FusedLocationClient(context, locationOptions)
        : new LocationManagerClient(context, locationOptions);
  }
  ```

**Comment by a1111198** [comment]
Thanks, everyone for this clarification But there is one situation when the user doesn't have Google play services properly installed in such cases it calls using forcedAndroidLocationManager so t would take 3-4 minutes so is there any alternative for such cases.
I know such users are limited but this issue is affecting my production version.

**Comment by Pgrammerybj** [comment]
中国大陆用户，一言难尽
