### ISSUE TITLE
Flutter/Flutter.h not found

### ISSUE THREAD

**Issue by BalrajArpit** [Baseflow/flutter-geolocator#885]
### Old (and correct) behavior

Everything was working fine.

### Current behavior

In file included from /Users/balrajarpit/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_apple-1.2.2/ios/Classes/Handlers/LocationServiceStreamHandler.m:10:
    /Users/balrajarpit/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_apple-1.2.2/ios/Classes/Handlers/LocationServiceStreamHandler.h:14:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>

### Reproduction steps

Tried every steps from internet.

### Configuration
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.5.2 20G95 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.61.2)
[✓] Connected device (1 available)

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by lazicah** [comment]
Any solution?

**Comment by mvanbeusekom** [comment]
Hi @BalrajArpit, @lazicah,

Personally I cannot reproduce this issue. I have created a new Flutter App and added a dependency on `geolocator: ^7.7.1` and was able you build for iOS just fine.

Some things you might be able to try:

- Remove ios/Flutter/Flutter.podspec file: `rm -rf ios/Flutter/Flutter.podspec`;
- Run `flutter clean`;
- Build you app: `flutter build ios --no-codesign`

If that doesn't work have a look at this solution: https://stackoverflow.com/a/64993852/5167831

Let me know how it goes.

**Comment by BalrajArpit** [comment]
Solution: Downgraded Flutter to 2.2.3 Stable.
