### ISSUE TITLE
Geolocator.getCurrentPosition is very slow on ios 14

### ISSUE THREAD

**Issue by ibra-iad** [Baseflow/flutter-geolocator#888]
## 🔙 Regression

After updating our sdk flutter to version 2, we encounter a slow geolocation problem on iOs 14 only, no problem on iOs 15

### Old (and correct) behavior
On flutter 1 and geolocator 6.2.1 the location fixed quickly

### Current behavior
After switching to flutter 2 and geolocator 7.7.0 the location became slow, about 10 to 15 sec

### Reproduction steps
```dart
Position position = await Geolocator.getCurrentPosition();
```

### Configuration

**Version:** 7.7.0

**Platform:** 
- [X] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @ibra-iad,

This is expected behaviour and explained in more detail in issue #887. Older versions (pre-7.6.0) of the geolocator actually contained a bug when fetching the current position (see issue #629) which is fixed in [version 7.6.0](https://pub.dev/packages/geolocator/changelog#760).

**Comment by ibra-iad** [comment]
Thank you @mvanbeusekom
