### ISSUE TITLE
Can't get background location on Android-Device

### ISSUE THREAD

**Issue by Babwenbiber** [Baseflow/flutter-geolocator#891]
## 🐛 Bug Report

The geo locator `Geolocator.getPositionStream` doesn't work as expected, when the app is in the background.

### Expected behavior

For that I build a simple app. It counts the measured positions and shows it on a map.
When the app is in the foreground, the counter increases rapidly over time.

However, when the app is in the background, the counter does not increase. Furthermore, you can verify that by looking at the map. There is no marker created when the app is in the background (nor does the app print).

This problem occurs to me on android only (tested on Android 12 -> Pixel 6 and Android 11 -> Huawei P30lite).

### Reproduction steps

I built a simple App verifying this.
Here is [my repo.](https://github.com/Babwenbiber/location_tracking.git)

### Configuration

**Version:** 7.7.1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android: (Android 12) -> Pixel 6 and (Android 11) -> Huawei P30lite

<details>
 <summary>flutter doctor -v  </summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale de-DE)
    • Flutter version 2.5.3 at /Users/frederikfroling/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/frederikfroling/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Users/frederikfroling/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • Lauras iPhone (mobile) • 00008030-001A4046020B802E • ios            • iOS 14.8.1 18H107
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```

</details>

**Comment by mvanbeusekom** [comment]
@Babwenbiber that is correct, fetching locations in the background is not supported. There is an open feature request (see #53) which is used to track progress off the implementation. However due to other commitments I don't expect it to be implemented on the short term.
