### ISSUE TITLE
How to access   ServiceStatus ?

### ISSUE THREAD

**Issue by CMingTseng** [Baseflow/flutter-geolocator#892]
Dear sir

i flow this

https://pub.dev/packages/geolocator/install

add  geolocator: ^7.7.1

and  use this demo code 

i can not get ServiceStatus 

THX

https://github.com/Baseflow/flutter-geolocator/blob/131a1e3341e24a8c9bf8306513eccb67634e1877/geolocator/example/lib/main.dart#L43

**Comment by mvanbeusekom** [comment]
@CMingTseng note that on Web this functionality is not implemented as the web doesn't have a separate backend service like the other platforms do. Trying to get the service stream on web will result in a `UnimplementedError`.

If you are trying to access the service stream on any other platform (Android, iOS or macOS) please provide some more information:

1. Output of the `flutter doctor -v` command;
2. Complete stack trace of the error you receive;
3. List of platforms you are testing on (preferably with version numbers, i.e. iOS 13 or Android 8.0).
