### ISSUE TITLE
Location service not working on iOS Safari

### ISSUE THREAD

**Issue by Limvunhoy** [Baseflow/flutter-geolocator#894]
## 🐛 Bug Report

I have embedded Flutter Web App as a WebView in iOS App (Swift), and I got js error when try to ask for user Location Service and Permission.

<img width="779" alt="Screen Shot 2021-11-15 at 3 17 10 PM" src="https://user-images.githubusercontent.com/39089099/141746472-2c54d4fb-d75b-4eb6-9581-64642bb930a2.png">

### Expected behavior
- I want to get user current location from Flutter Web App in WebView iOS App. 
- Must show dialog when Location Service / Permission are turned off 
- Able to get current location when Location Services / Permission are turned on

### Reproduction steps
- Create flutter web app
- Embedded it as WebView in Native App
- Got an error when try to ask for User Location Service and Permission from Native App

### Configuration
- I have run these below command line: 
-  flutter build web --no-sound-null-safety --release
- firebase deploy

**Version:** 1.x
- Flutter SDK version: 2.5.3

**Platform:** 
- [ ] :iphone: iOS
- [ ] :web: Safari

**Comment by florissmit1** [comment]
We're aware of this issue and are currently working on a fix in this PR: https://github.com/Baseflow/flutter-geolocator/pull/897. Thanks for reporting your issue and I will keep you up to date.
