### ISSUE TITLE
Two widgets calling Current location but getting error on second widget

### ISSUE THREAD

**Issue by mohammednabil95** [Baseflow/flutter-geolocator#895]
I have two widgets which displays current location latitude and longitude, when user first time install the app and once it accept the user current location permission then first widget gets the current location latitude and longitude but on second widget it gets an error "A Request for location permissions is already running, please wait for it to complete before doing another request."

**Comment by mvanbeusekom** [comment]
@mohammednabil95 as the error mentions it is not possible to request location details more than once simultaneously. This is a physical limitation on some of the platforms.

**Comment by mohammednabil95** [comment]
> @mohammednabil95 as the error mentions it is not possible to request location details more than once simultaneously. This is a physical limitation on some of the platforms.

So how to prevent this issue?

**Comment by mvanbeusekom** [comment]
Make sure you don't call it twice. Personally I like to make a small service class which provides the location and wraps it in a completer. But there are a lot of other solutions.

Something like this should work (note this is out if my head and is just to point you into a direction):

```
Completer<Position> _positionCompleter = Completer();

Future<Position> getCurrentPosition() {
  if (!_positionCompleter.isCompleted) {
    return _positionCompleter.future;
  }
  
  Geolocator.getCurrentPosition().then((Position position) => _positionCompleter.complete(position));

  return _positionCompleter.future;
}
```
