### ISSUE TITLE
cannot find symbol in LocationMapper.java

### ISSUE THREAD

**Issue by Pranav108** [Baseflow/flutter-geolocator#901]
## 🐛 Bug Report

![Screenshot (454)](https://user-images.githubusercontent.com/56934594/143084549-f33581f6-384c-41dd-99c0-1a5cc4b43695.png)

cannot find symbol in LocationMapper.java .
### Expected behavior
Should work fine, sdk version and other dependencies are fine.
### Reproduction steps
not applicable
### Configuration
Android SDK 31
**Version:** 1.x
7.7.0
**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
Can you include the contents of the `android/app/build.gradle` file?

The error indicates it is unable to find `Build.VERSION_CODES.S` which means it is not compiling against Android SDK 31. Most likely you have a mistake in the above mentioned `build.gradle` file.

**Comment by Pranav108** [comment]
Thanks @mvanbeusekom , I set Android SDK 31 but in build.gradle file it was still 30 .Now improved it and it's working fine.
I was barking up the wrong tree🤦‍♂️😅. Thanks again✨.
