### ISSUE TITLE
Using example code always returns: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long

### ISSUE THREAD

**Issue by ashored-aross** [Baseflow/flutter-geolocator#911]
## 🐛 Bug Report

When calling the example code the position is never return and an error is thrown. Here is my output:

E/MethodChannel#flutter.baseflow.com/geolocator( 3803): Failed to handle method call
E/MethodChannel#flutter.baseflow.com/geolocator( 3803): java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
E/MethodChannel#flutter.baseflow.com/geolocator( 3803): 	at com.baseflow.geolocator.location.LocationOptions.parseArguments(LocationOptions.java:17)
E/MethodChannel#flutter.baseflow.com/geolocator( 3803): 	at com.baseflow.geolocator.MethodCallHandlerImpl.onGetCurrentPosition(MethodCallHandlerImpl.java:205)
E/MethodChannel#flutter.baseflow.com/geolocator( 3803): 	at com.baseflow.geolocator.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:74)
E/MethodChannel#flutter.baseflow.com/geolocator( 3803): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter.baseflow.com/geolocator( 3803): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/MethodChannel#flutter.baseflow.com/geolocator( 3803): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/MethodChannel#flutter.baseflow.com/geolocator( 3803): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter.baseflow.com/geolocator( 3803): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#flutter.baseflow.com/geolocator( 3803): 	at android.os.Looper.loop(Looper.java:183)
E/MethodChannel#flutter.baseflow.com/geolocator( 3803): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/MethodChannel#flutter.baseflow.com/geolocator( 3803): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter.baseflow.com/geolocator( 3803): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#flutter.baseflow.com/geolocator( 3803): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

### Expected behavior

Actual positions
### Reproduction steps

My main.dart (note _getPosition was the original function, not _determinePosition, observed while in debug mode. Neither work):
```
import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Position? _position;
  bool _isLoading = false;

  Future<void> _getPosition() async {
    Geolocator.getCurrentPosition(
      desiredAccuracy: LocationAccuracy.best,
      forceAndroidLocationManager: true,
      timeLimit: Duration(seconds: 10),
    ).then((Position position) {
      print('Acquired position: $position');
      setState(() {
        _position = position;
        _isLoading = false;
      });
    });

    setState(() {
      _isLoading = true;
    });
  }

  /// Determine the current position of the device.
  ///
  /// When the location services are not enabled or permissions
  /// are denied the `Future` will return an error.
  Future<Position> _determinePosition() async {
    bool serviceEnabled;
    LocationPermission permission;

    // Test if location services are enabled.
    serviceEnabled = await Geolocator.isLocationServiceEnabled();
    if (!serviceEnabled) {
      // Location services are not enabled don't continue
      // accessing the position and request users of the
      // App to enable the location services.
      return Future.error('Location services are disabled.');
    }

    permission = await Geolocator.checkPermission();
    if (permission == LocationPermission.denied) {
      permission = await Geolocator.requestPermission();
      if (permission == LocationPermission.denied) {
        // Permissions are denied, next time you could try
        // requesting permissions again (this is also where
        // Android's shouldShowRequestPermissionRationale
        // returned true. According to Android guidelines
        // your App should show an explanatory UI now.
        return Future.error('Location permissions are denied');
      }
    }

    if (permission == LocationPermission.deniedForever) {
      // Permissions are denied forever, handle appropriately.
      return Future.error(
          'Location permissions are permanently denied, we cannot request permissions.');
    }

    // When we reach here, permissions are granted and we can
    // continue accessing the position of the device.
    return await Geolocator.getCurrentPosition();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: (_isLoading)
            ? CircularProgressIndicator()
            : Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  Text(
                    'The following position was acquired:',
                  ),
                  Text(
                    '$_position',
                    style: Theme.of(context).textTheme.headline4,
                  ),
                ],
              ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _determinePosition,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

```

pubspec.yaml:

```
name: geo_issue_773
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.5.3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  geolocator: 8.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```

build.gradle

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 31

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.geo_issue_773"
        minSdkVersion 16
        targetSdkVersion 31
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
```

### Configuration
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.1348], locale en-CA)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.3)  
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.62.3)      
[√] Connected device (4 available)

• No issues found!
**Version:** 1.x

This seems to be java related:

java --version
java 17.0.1 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)

**Platform:** 
- [ ] :iphone: iOS
- [x ] :robot: Android -- emulated

**Comment by ashored-aross** [comment]
<img width="580" alt="Capture" src="https://user-images.githubusercontent.com/65681320/144643626-49814d26-c3ee-409d-8ae9-ef38bf3005e6.PNG">

This is weird... It looks like git commits got stuck into the file somehow.

How could this have happened? 

C:\flutter\.pub-cache\hosted\pub.dartlang.org\geolocator_android-3.0.0+3\android\src\main\java\com\baseflow\geolocator\location

**Comment by ashored-aross** [comment]
Issue was in C:\flutter\.pub-cache\hosted\pub.dartlang.org\geolocator_android-3.0.0+3\android\src\main\java\com\baseflow\geolocator\location\LocationOptions.java

Redownloading the package cleared this error

**Comment by yuriboeira11tx** [comment]
@ashored-aross I just had this same problem. I'm on MAC OS, do you have any suggestions?
