### ISSUE TITLE
Activity type on Apple Settings

### ISSUE THREAD

**Issue by Wackymax** [Baseflow/flutter-geolocator#916]
## 🐛 Bug Report

The activity type enum is not exported and cannot be used to change the activity type on Apple Settings.

### Expected behavior

Being able to change the activity type for Apple settings.

### Reproduction steps

Import the library from an external project and try to set the activity type on Apple Settings.

### Configuration

**Version:** 8.0.0

**Platform:** 
- [X] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
This is on purpose not to pollute the app facing package with a lot of platform specific information. It should be possible to add an import to the geolocator_apple.dart in the source file which references the `ActivityType` to resolve to problem:

```dart
import 'package:geoloator_apple/geolocator_apple.dart';
``` 

Let me know if this works.

**Comment by Wackymax** [comment]
That worked perfectly. Thanks! Sorry, the IDE didn't give that as in option automatically. Maybe something add to the documentation?

**Comment by florissmit1** [comment]
@Wackymax PR with the updated documentation is open, see: #924.
