### ISSUE TITLE
Switching accuracy

### ISSUE THREAD

**Issue by MrWj** [Baseflow/flutter-geolocator#923]
💬 Questions and Help

I have an Android-9 device here.  always time out when I use LocationAccuracy.high precision to get stream, but it work when I 

use LocationAccuracy.medium, so when I get a timeout error, I switch the LocationAccuracy.medium and try to get stream again, 

this time, although I switch the precision to LocationAccuracy.medium, I still get a timeout error.

**Comment by florissmit1** [comment]
Thanks for your question @MrWj. Can you provide me with some code, especially on how you change the `LocationAccuracy`?  

When you want to change the `LocationAccuracy` of a `PositionStream`, you should cancel and nullify the stream and finally initialize  a new `PositionStream` with the changed `LocationAccuracy` value.
