### ISSUE TITLE
Error - MethodChannelGeolocator.getCurrentPosition

### ISSUE THREAD

**Issue by yuriboeira11tx** [Baseflow/flutter-geolocator#925]
## 🐛 Bug Report

After implementing the example code available in pub.dev, as soon as I test the get current position function, a platform exception is thrown.

### Expected behavior

Return current position.

### Reproduction steps
1 - Implement functions
2 - Run function getCurrentPosition()
3 - Returns:

![Captura de Tela 2021-12-16 às 2 32 41 PM](https://user-images.githubusercontent.com/26651347/146420665-bce6c810-a379-41b7-ab20-b73d051f6881.png)

### Configuration

**Version:** 8.0.1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android 11

**Comment by florissmit1** [comment]
d

**Comment by yuriboeira11tx** [comment]
I managed to solve the problem by clearing the pub cache and downgrading the project packages. Thanks!
