### ISSUE TITLE
PositionStream does not work properly if location service is initially disabled then enabled 

### ISSUE THREAD

**Issue by CDevFlttr** [Baseflow/flutter-geolocator#926]
i am trying to get the position stream after the location permission has been granted and the location service has also been enabled, but i got:
'Unhandled Exception: User denied permissions to access the device's location.'

**Comment by florissmit1** [comment]
Thanks for reporting your issue @CDevFlttr. Can you provide more information, f.e. your `flutter doctor -v`, a code snippet and the device you're using?

**Comment by CDevFlttr** [comment]
The device used is Huawei Y5.


My flutter doctor -v:


[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Versione 10.0.19042.1237], locale it-IT)
    • Flutter version 2.5.3 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (10 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc3)
    • Android SDK at C:\Users\marra\AppData\Local\Android\Sdk
    • Platform android-31, build-tools 31.0.0-rc3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.62.3)
    • VS Code at C:\Users\marra\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (3 available)
    • AMN LX9 (mobile) • WNPNU19704230175 • android-arm    • Android 9 (API 28)
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 96.0.4664.110
    • Edge (web)       • edge             • web-javascript • Microsoft Edge 93.0.961.52

• No issues found!

Code snippet:


StreamSubscription<Position>? _positionStream;
  Position? _positionCurrent;

  double? _longitudeCurrent;
  double? _latitudeCurrent;

  double? _longitudeStream;
  double? _latitudeStream;

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    getPositionStream();
  }

  Future<void> getPositionStream() async {
    late LocationSettings locationSettings;

    if (defaultTargetPlatform == TargetPlatform.android) {
      locationSettings = AndroidSettings(
        accuracy: LocationAccuracy.high,
        distanceFilter: 10,
        forceLocationManager: true,
        intervalDuration: const Duration(seconds: 1),
      );
    } else if (defaultTargetPlatform == TargetPlatform.iOS ||
        defaultTargetPlatform == TargetPlatform.macOS) {
      locationSettings = AppleSettings(
        accuracy: LocationAccuracy.high,
        distanceFilter: 10,
        pauseLocationUpdatesAutomatically: true,
      );
    } else {
      locationSettings = LocationSettings(
        accuracy: LocationAccuracy.high,
        distanceFilter: 10,
      );
    }

    _positionStream =
        Geolocator.getPositionStream(locationSettings: locationSettings)
            .listen((Position position) async {
      setState(() {
        _longitudeStream = position.longitude;
        _latitudeStream = position.latitude;
      });
    });
  }

  Future<void> getLocationCurrent() async {
    _positionCurrent = await _determinePosition();
    setState(() {
      _longitudeCurrent = _positionCurrent!.longitude;
      _latitudeCurrent = _positionCurrent!.latitude;
    });
  }

  Future<Position> _determinePosition() async {
    bool serviceEnabled;
    LocationPermission permission;

    // Test if location services are enabled.
    serviceEnabled = await Geolocator.isLocationServiceEnabled();
    if (!serviceEnabled) {
      // Location services are not enabled don't continue
      // accessing the position and request users of the
      // App to enable the location services.
      return Future.error('Location services are disabled.');
    }

    permission = await Geolocator.checkPermission();
    if (permission == LocationPermission.denied) {
      permission = await Geolocator.requestPermission();
      if (permission == LocationPermission.denied) {
        // Permissions are denied, next time you could try
        // requesting permissions again (this is also where
        // Android's shouldShowRequestPermissionRationale
        // returned true. According to Android guidelines
        // your App should show an explanatory UI now.
        return Future.error('Location permissions are denied');
      }
    }

    if (permission == LocationPermission.deniedForever) {
      // Permissions are denied forever, handle appropriately.
      return Future.error(
          'Location permissions are permanently denied, we cannot request permissions.');
    }

    // When we reach here, permissions are granted and we can
    // continue accessing the position of the device.
    return await Geolocator.getCurrentPosition(
      desiredAccuracy: LocationAccuracy.best,
      forceAndroidLocationManager: true,
    );
  }

  @override
  void dispose() {
    _positionStream!.cancel();
    super.dispose();
  }

**Comment by mvanbeusekom** [comment]
Hi @CDevFlttr, 

Analysing the code it seems like it starts listening to the position stream before permissions are being requested which might result in the exception mentioned. 

Since the snippet doesn't include the full widget I am making some assumptions here. However the code is subscribing (starts listening) to the position stream from the `initState()` method. Permissions are only requested in the `_determinePosition()` method which is only called from the `getLocationCurrent()` method. The code snippet doesn't indicate when the `getLocationCurrent()` is called however it is likely the the `initState()` method is called (and thus the code tries to start listening to the position stream) before any other code can call the `getLocationCurrent()` method and trigger the logic to request permissions.

One solution might be too refactor the code and make sure to request permissions before listening to the position stream and requesting the current location. This could look something like this:

```dart
StreamSubscription<Position>? _positionStream;
  Position? _positionCurrent;

  double? _longitudeCurrent;
  double? _latitudeCurrent;

  double? _longitudeStream;
  double? _latitudeStream;

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    
    _requestPermission()
      .then(() => getPositionString())
      .catchError((error) => print(error.toString()));
  }

  Future<void> getPositionStream() async {
    late LocationSettings locationSettings;

    if (defaultTargetPlatform == TargetPlatform.android) {
      locationSettings = AndroidSettings(
        accuracy: LocationAccuracy.high,
        distanceFilter: 10,
        forceLocationManager: true,
        intervalDuration: const Duration(seconds: 1),
      );
    } else if (defaultTargetPlatform == TargetPlatform.iOS ||
        defaultTargetPlatform == TargetPlatform.macOS) {
      locationSettings = AppleSettings(
        accuracy: LocationAccuracy.high,
        distanceFilter: 10,
        pauseLocationUpdatesAutomatically: true,
      );
    } else {
      locationSettings = LocationSettings(
        accuracy: LocationAccuracy.high,
        distanceFilter: 10,
      );
    }

    _positionStream =
        Geolocator.getPositionStream(locationSettings: locationSettings)
            .listen((Position position) async {
      setState(() {
        _longitudeStream = position.longitude;
        _latitudeStream = position.latitude;
      });
    });
  }

  Future<void> getLocationCurrent() async {
    try {
      await _requestPermission();
      // When we reach here, permissions are granted and we can
      // continue accessing the position of the device.
      _positionCurrent = await Geolocator.getCurrentPosition(
        desiredAccuracy: LocationAccuracy.best,
        forceAndroidLocationManager: true,
      );

      setState(() {
        _longitudeCurrent = _positionCurrent!.longitude;
        _latitudeCurrent = _positionCurrent!.latitude;
      });
    } catch (Exception ex) { 
      print(ex.toString());
    }
  }

  Future<void> _requestPermission() async {
    bool serviceEnabled;
    LocationPermission permission;

    // Test if location services are enabled.
    serviceEnabled = await Geolocator.isLocationServiceEnabled();
    if (!serviceEnabled) {
      // Location services are not enabled don't continue
      // accessing the position and request users of the
      // App to enable the location services.
      return Future.error('Location services are disabled.');
    }

    permission = await Geolocator.checkPermission();
    if (permission == LocationPermission.denied) {
      permission = await Geolocator.requestPermission();
      if (permission == LocationPermission.denied) {
        // Permissions are denied, next time you could try
        // requesting permissions again (this is also where
        // Android's shouldShowRequestPermissionRationale
        // returned true. According to Android guidelines
        // your App should show an explanatory UI now.
        return Future.error('Location permissions are denied');
      }
    }

    if (permission == LocationPermission.deniedForever) {
      // Permissions are denied forever, handle appropriately.
      return Future.error(
          'Location permissions are permanently denied, we cannot request permissions.');
    }
  }

  @override
  void dispose() {
    _positionStream!.cancel();
    super.dispose();
  }
```

Please let me know if this makes sense and resolves the problem.

**Comment by tlserver** [comment]
Using geolocator v9.0.2, I still have this problem on API 33 Android Enulator, when Location Service is on before calling `getPositionStream()`, it work fine:
[device-2023-04-01-175537.webm](https://user-images.githubusercontent.com/8895426/229279379-d24d03e5-5947-494a-b987-3e0381aa93b7.webm)
But if the services is disabled before, it never receive update even I enabled it again later. Calling `getCurrentPosition()` is not help.
[device-2023-04-01-175611.webm](https://user-images.githubusercontent.com/8895426/229279470-ac96cbe6-276b-430b-80df-d51ed615e2f6.webm)

```
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';

class MinimumExample extends StatefulWidget {
  @override
  State<MinimumExample> createState() => _MinimumExampleState();
}

class _MinimumExampleState extends State<MinimumExample> {
  int _positionUpdateCount = 0;
  late final StreamSubscription _subscription;
  bool getCurrent = false;
  Position? current;

  @override
  void initState() {
    super.initState();
    _subscription = Geolocator.getPositionStream().listen((p) {
      print(p);
      setState(() {
        _positionUpdateCount++;
      });
    });
    Future.delayed(const Duration(seconds: 12)).then((_) async {
      if (mounted) {
        setState(() {
          getCurrent = true;
        });
        print("getCurrent");
        Geolocator.getCurrentPosition().then((value) {
          if (mounted) {
            setState(() {
              getCurrent = false;
              current = value;
            });
          }
          print("getCurrent:$value");
        });
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Minimum Example'),
      ),
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text("Update: $_positionUpdateCount"),
            if (getCurrent) const Text("Calling getCurrentPosition"),
            if (current != null) Text("Current : $current"),
          ],
        ),
      ),
    );
  }

  @override
  void dispose() {
    _subscription.cancel();
    super.dispose();
  }
}
```
