### ISSUE TITLE
LocationAccuracy enum comments in location_accuracy.dart may be misleading 

### ISSUE THREAD

**Issue by jocelyngriselle** [Baseflow/flutter-geolocator#928]
## 🏗 Enhancement Proposal

Comments in location_accuracy.dart do not reflect Android docs on accuracy with FusedLocationProviderClient.

### Pitch

I'm working with your plugin and digging with accuracy and power consumption. It occured to me that  comments in `LocationAccuracy` enum are misleading. According to official docs ( https://developers.google.com/android/reference/com/google/android/gms/location/LocationRequest#constants )  `LocationAccuracy.medium` = PRIORITY_BALANCED_POWER_ACCURACY = ~ 100m accuracy

In `enum LocationAccuracy` comments it says :
```
/// Location is accurate within a distance of 100m on iOS and between 100m and
/// 500m on Android
```
  
I am missing something or could i propose a Pull Request to address this ?  

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by florissmit1** [comment]
Hey @jocelyngriselle, thanks for reporting your issue. As you can in the code snippet, we're using the `setHorizontalAccuracy` method to set the accuracy. This method is making use of the `android.location.Criteria` class. More info about the `Criteria` class can be found here: https://developer.android.com/reference/android/location/Criteria.

For instance, when using the `LocationAccuracy.medium`, the `Criteria` documentation states the following: 
`public static final int ACCURACY_MEDIUM`
A constant indicating a medium accuracy requirement - currently used only for horizontal accuracy. For horizontal position this corresponds roughly to to an accuracy of between 100 and 500 meters.

```
case medium:
        criteria.setAccuracy(Criteria.ACCURACY_COARSE);
        criteria.setHorizontalAccuracy(Criteria.ACCURACY_MEDIUM);
        criteria.setPowerRequirement(Criteria.POWER_MEDIUM);
        break;
```

For now I will close this issue, if something is unclear, please re-open this issue.
