### ISSUE TITLE
GeoLocator Not Working in my simulator or device android

### ISSUE THREAD

**Issue by NassimCodeDev** [Baseflow/flutter-geolocator#930]
## 💬 Questions and Help
Hi Gues How Are You ?
i Have A big Problem: when run my code in android studio to my phone with using geolocator package i against this problem:
```
E/flutter (12560): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getCurrentPosition on channel flutter.baseflow.com/geolocator)
E/flutter (12560): #0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (12560): <asynchronous suspension>
E/flutter (12560): #1 MethodChannelGeolocator.getCurrentPosition (package:geolocator_platform_interface/src/implementations/method_channel_geolocator.dart:122:27)
E/flutter (12560): <asynchronous suspension>
E/flutter (12560): #2 MyApp.getLocation (package:geolocation_app/main.dart:10:25)
E/flutter (12560): <asynchronous suspension>
```
Please Help Me 🙂

**Comment by mvanbeusekom** [comment]
Hi @NassimCodeDev,

This error seems the same as issue #745. Please have a look if the instructions in this [comment](https://github.com/Baseflow/flutter-geolocator/issues/745#issuecomment-857477258) solve your problem. This seems to be related to something getting corrupted on your local environment.

If this doesn't work please provide additional information to this issue:

1. The version of the geolocator plugin that is used;
2. Include the output of the `flutter doctor -v` command;
3. The platform on which the error occurs (Android, iOS or macOs);
4. Include the contents of the `android/app/src/main/AndroidManifest.xml` and/or the `ios/Runner/Info.plist` file to the issue.

**Comment by pinguluk** [comment]
You'll have to rebuild the app once

**Comment by arjun2020-py** [comment]
MissingPluginException(No implementation found for method getCurrentPosition on channel flutter.baseflow.com/geolocator_android)
