### ISSUE TITLE
Upgrading from v7 to v8, how to properly use `Geolocator.getPositionStream` without `intervalDuration`?

### ISSUE THREAD

**Issue by comatory** [Baseflow/flutter-geolocator#934]
## 💬 Questions and Help

I want to move away from one of my dependencies relying on v7. I have a code in app that depends on this older version and my question is how come `Geolocator.getPositionStream` no longer accepts `intervalDuration`? Is there some other mechanism where updates are pushed to stream?

I don't mind that the polling is gone, I just want to make sure that this change does not have any consequences to my app. Thank you.

**Comment by florissmit1** [comment]
Hey @comatory, thanks for reporting your issue. In the documentation on [pub.dev](https://pub.dev/packages/geolocator), there is an example on how to use the new `LocationOptions` class. I posted the example below, I hope this will help you migrating your dependencies. If something is unclear or not working, feel free to re-open this issue again.

```
import 'package:geolocator/geolocator.dart';

late LocationSettings locationSettings

if (defaultTargetPlatform == TargetPlatform.android) {
  locationSettings = AndroidSettings(
    accuracy: LocationAccuracy.high,
    distanceFilter: 100,
    forceLocationManager: true,
    intervalDuration: const Duration(seconds: 10),
  );
} else if (defaultTargetPlatform == TargetPlatform.iOS || defaultTargetPlatform == TargetPlatform.macOS) {
  locationSettings = AppleSettings(
    accuracy: LocationAccuracy.high,
    activityType: ActivityType.fitness,
    distanceFilter: 100,
    pauseLocationUpdatesAutomatically: true,
  );
} else {
    locationSettings = LocationSettings(
    accuracy: LocationAccuracy.high,
    distanceFilter: 100,
  );
}

StreamSubscription<Position> positionStream = Geolocator.getPositionStream(locationSettings: locationSettings).listen(
    (Position position) {
        print(position == null ? 'Unknown' : position.latitude.toString() + ', ' + position.longitude.toString());
    });
    ```

**Comment by comatory** [comment]
On Wed Jan 12, 2022 at 11:09 AM CET, florissmit1 wrote:
> Hey @comatory, thanks for reporting your issue. In the documentation on
> [pub.dev](https://pub.dev/packages/geolocator), there is an example on
> how to use the new `LocationOptions` class. I posted the example below,
> I hope this will help you migrating your dependencies.

Hey, thanks for helping me out. For me the problem is not with the
changed API per-se but how it affects the behaviour.

I assume changing from time polling to detecting distance is more
friendly to battery etc so I understand the motivation.

It would help if in `CHANGELOG` it was mentioned somewhere that this
change has been made and explained why (or with a link to GH issue).
Maybe it was there and I missed it? Anyway, I understand it now thanks.
