### ISSUE TITLE
Example code doesn't work for Pixel C API 30 Emulator

### ISSUE THREAD

**Issue by ashored-aross** [Baseflow/flutter-geolocator#935]
## 🐛 Bug Report

In reference to: #912 (Sorry for re-opening/ the delay, I was on holiday)

Running the example code in the emulator never gets position. 

Break point after get position never gets hit, but permission appears to be granted.

Forced a position to be set as well with the emulator tools. 

No map appears to be loaded either as shown below:

https://i.imgur.com/2VBc9S8.png

Note: I modified the ini file to have the Google Play Store added. https://stackoverflow.com/questions/38593738/is-google-play-store-supported-in-avd-emulators

### Expected behavior

Should return position. Map should load.

### Reproduction steps

Run in Pixel C tablet 

### Configuration
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19042.1415], locale en-CA)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.3)  
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.63.2)
[√] Connected device (4 available)
```

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [x ] :robot: Android

**Comment by florissmit1** [comment]
Hey @ashored-aross, I can reproduce your issue on the device you mentioned above. Although it's frustrating that the location is not fetched, I think it's not a `geolocator` related issue. Google Maps and other applications that require positioning don't function either on my Pixel C Emulator. Can you check for me if that's the case on your side as well?

**Comment by ashored-aross** [comment]
> Hey @ashored-aross, I can reproduce your issue on the device you mentioned above. Although it's frustrating that the location is not fetched, I think it's not a `geolocator` related issue. Google Maps and other applications that require positioning don't function either on my Pixel C Emulator. Can you check for me if that's the case on your side as well?

So it sort  of works...Sort of doesn't. Mostly doesn't. Using the find my location it points me towards the Googleplex in California. I tried to override the location to Canada and it didn't change. (I am nowhere near California). 

<img width="1842" alt="google_maps_fail" src="https://user-images.githubusercontent.com/65681320/149528004-76f8381d-58af-424a-8e2b-c7339e8be565.PNG">

What I do find interesting is the example app doesn't register the Googleplex location either. 

I have a Samsung Tab Lite S6 tablet that I can test the example app on. Could you send me the exact build command you'd like me to test with? 

Thanks

**Comment by mvanbeusekom** [comment]
Hi @ashored-aross, 

To test the example App on a real device take the following steps:

1. Connect the device to your development machine using a USB cable;
2. Open a terminal window and navigate to the folder which contains the example application;
3. Now run the `flutter run` command;
4. The `flutter run` command should print a list of possible devices it can run the app on, choose the number associated with your Samsung device. 

Of course it is also possible to run the example App on your device from an IDE (Android Studio or Visual Studio Code). To do so:

1. Connect the device to your development machine using the USB cable;
2. Open the example project in your favorite IDE;
  a. If using Android Studio select your device from the "available devices" listbox in the top of the window;
  b. If using Visual Studio code select your device by clicking the device button in the bottom taskbar (this might already show your device by default);
3. Hit the run button to start a debugging session.

**Comment by ashored-aross** [comment]
Hi @mvanbeusekom ,

I was able to run the example app on my tablet so I can confirm that this is an issue with the Android emulator. 

Hopefully Google fixes this?

**Comment by mvanbeusekom** [comment]
Happy to hear. I will close this issue now and keep an eye on potential fixes from Google (fingers crossed).
