### ISSUE TITLE
Geolocator.isLocationServiceEnabled() isn't working well

### ISSUE THREAD

**Issue by DennisJu007** [Baseflow/flutter-geolocator#936]
## 🐛 Bug Report
bool isLocationServiceOn = await Geolocator.isLocationServiceEnabled();
 i got [isLocationServiceOn = false] when my gps switch was openned.
### Expected behavior
this only happend on my Lenovo Pad, while other android phone worded well.
### Configuration
![image](https://user-images.githubusercontent.com/42829167/148526742-53b6fe48-8ff6-4554-81a0-66a6ce238635.png)

**Version:** 

**Platform:** 
- [ ] :robot: Android 11

**Comment by JeroenWeener** [comment]
Hi @DennisJu007, thank you for taking the time to create this issue!

It would be helpful if you provided some additional information, so people that want to look into this issue have an easier time tracking down the bug.

For example:
- Which device (model) experiences this issue exactly?
- Can you provide us with some reproduction steps? ie
  - Create a new Flutter project supporting Android
  - Add a dependency to `geolocator` version `9.0.2`
  - In `main.dart`, add
```dart
bool isLocationServiceOn = await Geolocator.isLocationServiceEnabled();
print(isLocationServiceOn);
```
- Make sure the GPS is on
- Build the app and run on the device
