### ISSUE TITLE
[Bug] Geolocator does not return coordinate

### ISSUE THREAD

**Issue by wanoghoco** [Baseflow/flutter-geolocator#949]
Geolocator does not return coordinate sometimes in android 11, it just returns error after a while.

And sometimes it returns wrong coordinate if I don't forceAndroidLocationManager and sometimes, the location icon does not come up on my Device, sometimes it comes 

**Version: 8.0.3

**Platform:**

**Comment by mvanbeusekom** [comment]
> And sometimes it returns wrong coordinate if I don't forceAndroidLocationManager

This is possible, the Android [FusedLocationProviderClient]() makes use of several sensors and API's to try and acquire a location. If it cannot acquire a GPS fix it will might try to triangulate your location using the cellular network which is often not precise. In other cases it might use information from a WiFi network or Bluetooth connections, which all might not be accurate. 

Of course there is also the possibility that the GPS chip off the device is malfunctioning, if you have the opportunity try testing on an other device as well.

**Comment by jocelyngriselle** [comment]
Hello,

i'm facing the same issue with the "example" project from the lib. I works fine on android emulators but with several physical devices ( including OnePlus 6T Android 10 and a Galaxy A25S Android 11 )  `getCurrentPosition` just never returns.

When tapping on the "location" icon it display "Permission granted" and stops here, no logs are displayed ( event with -v option )

Tell me if you need any other information, and thanks for the plugin !

Here is my flutter doctor -v
```
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6.2 20G314 darwin-x64, locale fr-FR)
    • Flutter version 2.8.1 at /Users/jocelyn_griselle/fvm/versions/2.8.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/jocelyn_griselle/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/jocelyn_griselle/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Community Edition (version 2021.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 212.5486

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • ONEPLUS A6010 (mobile)  • 667a9449      • android-arm64  • Android 10 (API 29)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 97.0.4692.99

• No issues found!
```

**Comment by JeroenWeener** [comment]
I am closing this issue as no new information has surfaced since the reopening.
