### ISSUE TITLE
not able to setting timeInterval in 8.0.3 version

### ISSUE THREAD

**Issue by jin-develop** [Baseflow/flutter-geolocator#952]
### Expected behavior
when I use 7.6.2 version, I could set time Interval setting.
but after update 8.0.3 version, I can't set time interval setting in LocationSettings

### Configuration
class LocationSettings {
  /// Initializes a new [LocationSettings] instance with default values.
  ///
  /// The following default values are used:
  /// - accuracy: best
  /// - distanceFilter: 0
  /// - timeInterval: 0
  /// - timeLimit: 0
  const LocationSettings({
    this.accuracy = LocationAccuracy.best,
    this.distanceFilter = 0,
    this.timeLimit,
  });

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @jin-develop,

The structure changes a little bit to more clearly make developers aware that the `intervalDuration` property is an Android only feature. 

To be able to set this property you should use the derived `AndroidSettings` class. A more detailed explanation can be found in our [README.md](https://github.com/Baseflow/flutter-geolocator/blob/master/geolocator/README.md#listen-to-location-updates).

**Comment by shefeekae** [comment]
Is there a work around for setting the `intervalDuration`property for iOS ?
