### ISSUE TITLE
'openURL:' is deprecated: first deprecated in iOS 10.0

### ISSUE THREAD

**Issue by MrBananaPants** [Baseflow/flutter-geolocator#955]
Hi, I'm not sure if this is a bug or not so that's why I'm posting it in the questions and help section.

I have a Flutter application that uses Geolocator but when I build it in Xcode, I get an `'openURL:' is deprecated: first deprecated in iOS 10.0` message every time. The package works as expected and it builds successfully but I'm not sure if it's normal that I get that message every time.
Is it a bug or an issue on my side?
This is what I mean:
![image](https://user-images.githubusercontent.com/41532982/150578560-5f44ef60-abab-4524-a65b-531b42286ff0.png)
![image](https://user-images.githubusercontent.com/41532982/150578614-f3d53d81-5fef-4abe-b92c-098a495e1433.png)

**Comment by developer002-interactive** [comment]
where i can find this file and edited some code for change error version?
