### ISSUE TITLE
[macOS] Missing functionality when calling `placemarkFromCoordinates` in a flutter macOS app.

### ISSUE THREAD

**Issue by efraespada** [Baseflow/flutter-geolocator#961]
## 🐛 Bug Report

```
MissingPluginException(No implementation found for method placemarkFromCoordinates
on channel flutter.baseflow.com/geocoding)
```
Missing functionality when calling `placemarkFromCoordinates` in a flutter macOS app.

### Expected behavior

Same behavior as in iOS and Android

### Reproduction steps

**Version:** 8.0.5

**Platform:** 
- macOS

**Comment by mvanbeusekom** [comment]
Hi @efraespada,

The geocoding plugin indeed doesn't support the macOS platform yet. I have created a new [issue](https://github.com/Baseflow/flutter-geocoding/issues/81) in the geocoding repo (you posted this issue in the geolocator repo which is one of our other plugins).

**Comment by AhmadullahSaikat** [comment]
Why geoCoding library doesnt support macos?
When I install a App from Appstore via Macos, then The location services of IOS app works perfectly on Macos.
