### ISSUE TITLE
DesiredAccuracy not used for iOS9+?

### ISSUE THREAD

**Issue by BaechlerM-Liip** [Baseflow/flutter-geolocator#972]
So, for iOS 9 and more, the desiredAccuracy specified in getCurrentPosition() is never used? Is it really the behavior wanted?

> @erf if you have another look at the `requestPosition` method you will see that on iOS 9.0 and higher it will in fact call the `requestLocation` method and return (never reaching the `startUpdatingLocationWithDesiredAccuracy` call):
> 
> ```objc
> - (void)requestPosition:(GeolocatorResult _Nonnull)resultHandler
>            errorHandler:(GeolocatorError _Nonnull)errorHandler {
>   self.errorHandler = errorHandler;
>   self.resultHandler = resultHandler;
>   
>   if (@available(iOS 9.0, macOS 10.14, *)) {
>     [self.locationManager requestLocation];
>     return;
>   }
>   
>   [self startUpdatingLocationWithDesiredAccuracy:kCLLocationAccuracyBest
>                                   distanceFilter:kCLDistanceFilterNone
>                pauseLocationUpdatesAutomatically:NO
>                                     activityType:CLActivityTypeOther];
> }
> ```
> Unfortunately this method can be slow and is explained more detailed in this [comment](https://github.com/Baseflow/flutter-geolocator/issues/887#issuecomment-958123890). As explained in that comment you can listen to the `getPositionStream()` method which under the hood uses `locationManager.startUpdatingLocation()`, this however has the problem that the first result is the last known location (which often is not very precise)  and the second result might be a less accurate location as well.
> 
> Back to the original problem, can you verify if other apps also experience location problems on this device? I strongly suspect there is a hardware problem.
> 
> _Originally posted by @mvanbeusekom in https://github.com/Baseflow/flutter-geolocator/issues/962#issuecomment-1023532195_

**Comment by BaechlerM-Liip** [comment]
I could fix the problem myself and create a pull request. I just want to know before hand if it's really an issue or not

**Comment by mvanbeusekom** [comment]
Hi @BaechlerM-Liip, 

Sorry for not responding, reason is that I am working on a PR myself to solve this. It takes a little bit longer since I am also adding native unit tests to ensure all is working correctly (and not only test the new functionality but also some of the existing code). 

I really would like to finalise the PR today, so please hang tight.
