### ISSUE TITLE
Geolocator example does not work

### ISSUE THREAD

**Issue by Henk-Keijzer** [Baseflow/flutter-geolocator#976]
The Geolocator example depends on a package that is not generally available in pub.dev (baseflow_plugin_template). Please only use officially published packages, otherwise it is very time-consuming for beginners to find out how to install the package. Once I found out how to install the package, it appeared that the parameter "appBarActions" is used in the example, but not available in the BaseFlowPluginExample widget. A lot of time wasted.....

**Comment by mvanbeusekom** [comment]
@Henk-Keijzer, the package is generally available as open-source software on GitHub. The `pubspec.yaml` clearly specifies the location and branch being used. Also the `flutter pub get` command will automatically download and cache the package on your local machine. 

We do not intent to publish this package to pub.dev as this is a package we use only to give a common look to our example apps for our plugins and has no other value for developers outside Baseflow, which means it will just pollute the pub.dev repository.

That said, we can of course mention the use of this package in the README.md of the example App and elaborate a bit on how and why it is used. 

Also I would not consider this "A lot of time wasted", you learned how to load packages from a Git repository (b.t.w. detailed information about this topic can be found [here](https://dart.dev/tools/pub/dependencies)), which in our experience is very useful when developing enterprise grade apps.

I will keep this issue open as a reminder to improve the documentation. Thanks for reporting it.

**Comment by Henk-Keijzer** [comment]
Hi Martin, Thanks for your answer. The remark on "time wasted" was indeed a bit rude. Sorry for that.
Thanks to you and Baseflow for providing us with the geolocator package. Best regards, Henk

**Comment by JeroenWeener** [comment]
Talked with @mvanbeusekom and decided that this issue can be closed, as the template is available on pub.dev.
