### ISSUE TITLE
Kilometric point when driving in a road?

### ISSUE THREAD

**Issue by blopez** [Baseflow/flutter-geolocator#977]
## 💬 Questions and Help

Hi,

I've been analyzing the output data of the placemarkFromCoordinates function (returns the province, city, address, etc) but I cannot find any information regarding the current kilometer (or mile) in case of driving on a road/highway. Is there any way to get that info?

**Comment by florissmit1** [comment]
Hey @blopez, at the moment this is not possible using the `placemarkFromCoordinates` method or an other method within the `geocoding` package. Also, this repository is for the `geolocator` package, next time please pay attention to posting your issue in the correct repository.

For now I will close this issue. Feel free to open any other issues.
