### ISSUE TITLE
GeoLocation cannot retrieve Location info without internet.

### ISSUE THREAD

**Issue by GowthamF** [Baseflow/flutter-geolocator#981]
Using Geolocator package I tried retrieving Location when No Internet is connected, It does not work on most of the devices even though I tried using forceAndroidLocationManager. That is the main feature of our app. Appreciate if someone could help us.

**Comment by GowthamF** [comment]
> I'm facing the same problem, can you help ? @GowthamF

I reduced the accuracy from best to high and forceAndroidLocationManager true. It works we need to be outside. Accuracy is little less.

**Comment by AliEasy** [comment]
your solution is not working for me.....
you have any other idea?
could you please share the permissions given inside your app manifest?!
