### ISSUE TITLE
Errors building iOS version

### ISSUE THREAD

**Issue by pamir72** [Baseflow/flutter-geolocator#983]
**After upgrade got errors when building iOS version**

Lexical or Preprocessor Issue (Xcode): Expected module declaration
/Users/pavelmiheev/Library/Developer/Xcode/DerivedData/Runner-esqjnnsykqugiaakbsvxyndhzeor/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/geolocator_apple.build/module.modulemap:0:0

Lexical or Preprocessor Issue (Xcode): Expected module declaration
/Users/pavelmiheev/Library/Developer/Xcode/DerivedData/Runner-esqjnnsykqugiaakbsvxyndhzeor/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/geolocator_apple.build/module.modulemap:0:1

Lexical or Preprocessor Issue (Xcode): Skipping stray token
/Users/pavelmiheev/Library/Developer/Xcode/DerivedData/Runner-esqjnnsykqugiaakbsvxyndhzeor/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/geolocator_apple.build/module.modulemap:0:2

Lexical or Preprocessor Issue (Xcode): Expected module declaration
/Users/pavelmiheev/Library/Developer/Xcode/DerivedData/Runner-esqjnnsykqugiaakbsvxyndhzeor/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/geolocator_apple.build/module.modulemap:0:3

Lexical or Preprocessor Issue (Xcode): Expected module declaration
/Users/pavelmiheev/Library/Developer/Xcode/DerivedData/Runner-esqjnnsykqugiaakbsvxyndhzeor/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/geolocator_apple.build/module.modulemap:0:4

Lexical or Preprocessor Issue (Xcode): Skipping stray token
/Users/pavelmiheev/Library/Developer/Xcode/DerivedData/Runner-esqjnnsykqugiaakbsvxyndhzeor/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/geolocator_apple.build/module.modulemap:0:5

Lexical or Preprocessor Issue (Xcode): Expected module declaration
/Users/pavelmiheev/Library/Developer/Xcode/DerivedData/Runner-esqjnnsykqugiaakbsvxyndhzeor/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/geolocator_apple.build/module.modulemap:0:6

Lexical or Preprocessor Issue (Xcode): Skipping stray token
/Users/pavelmiheev/Library/Developer/Xcode/DerivedData/Runner-esqjnnsykqugiaakbsvxyndhzeor/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/geolocator_apple.build/module.modulemap:0:11

Lexical or Preprocessor Issue (Xcode): Expected module declaration
/Users/pavelmiheev/Library/Developer/Xcode/DerivedData/Runner-esqjnnsykqugiaakbsvxyndhzeor/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/geolocator_apple.build/module.modulemap:0:12

Lexical or Preprocessor Issue (Xcode): Skipping stray token
/Users/pavelmiheev/Library/Developer/Xcode/DerivedData/Runner-esqjnnsykqugiaakbsvxyndhzeor/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/geolocator_apple.build/module.modulemap:0:19

Lexical or Preprocessor Issue (Xcode): Expected module declaration
/Users/pavelmiheev/Library/Developer/Xcode/DerivedData/Runner-esqjnnsykqugiaakbsvxyndhzeor/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/geolocator_apple.build/module.modulemap:0:20

Lexical or Preprocessor Issue (Xcode): Expected module declaration
/Users/pavelmiheev/Library/Developer/Xcode/DerivedData/Runner-esqjnnsykqugiaakbsvxyndhzeor/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/geolocator_apple.build/module.modulemap:0:36

Lexical or Preprocessor Issue (Xcode): Expected module declaration
/Users/pavelmiheev/Library/Developer/Xcode/DerivedData/Runner-esqjnnsykqugiaakbsvxyndhzeor/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/geolocator_apple.build/module.modulemap:0:37

Parse Issue (Xcode): Expected identifier or '('
/Users/pavelmiheev/Flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_apple-2.1.1/ios/Classes/Handlers/PositionStreamHandler.m:0:0

Could not build the application for the simulator.
Error launching application on iPhone 13.

------

[✓] Flutter (Channel stable, 2.10.1, on macOS 12.1 21C52 darwin-x64, locale ru-RU)
    • Flutter version 2.10.1 at ...
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (4 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at ...
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • D9A95925-CF50-47EE-8B74-14D3795990FE • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by Wian-TMC** [comment]
I was just about to post this issue as well. Have not found a fix yet

**Comment by AbeiOS** [comment]
the same issue

**Comment by ZhuBoao** [comment]
Exact same issue here

**Comment by Wian-TMC** [comment]
Downgrading Flutter to 2.8.1 for now

**Comment by ZhuBoao** [comment]
> Downgrading Flutter to 2.8.1 for now.
> 
> Scratch that... Downgrading revealed the same error

LOL, I tried as well. Same error. I can't figure out why this suddenly happened today except I upgrade flutter yesterday.

**Comment by Wian-TMC** [comment]
> > Downgrading Flutter to 2.8.1 for now.
> > Scratch that... Downgrading revealed the same error
> 
> LOL, I tried as well. Same error. I can't figure out why this suddenly happened today except I upgrade flutter yesterday.

So strange.. I really thought downgrading would work. At least the ```Parse Issue (Xcode): Expected identifier or '('``` is absent after the downgrade.

**Comment by mvanbeusekom** [comment]
We are investigating this issue, something is wrong with the symbolic links in the objective-c code. 

Normally all source files in the `geolocator_apple/ios` and `geolocator_apple/macos` folders are symbolic links to the matching source files int the `geolocator_apple/apple` folder. For some reason the symbolic link attribute is removed and the source files now only contain a string representing the path the the matching file in the `geolocator_apple/apple` folder. For example:

```
../../../apple/Classes/Handlers/PermissionHandler.m
```

Xcode is trying to compile this as Objective-C code which obviously is generating a compile error. We are currently investigating what could be the reason of this bug.

**Comment by mvanbeusekom** [comment]
The problem seems to be related to version 2.1.1 of the geolocator_apple package. A workaround would be to pin your app to version 2.1.0 of the geolocator_apple package using a dependency override like this:

```yaml
dependency_overrides:
  geolocator_apple: 2.1.0

dependencies:
  ...
```

**Comment by FarhanSajid1** [comment]
Same issue

**Comment by FarhanSajid1** [comment]
> The problem seems to be related to version 2.1.1 of the geolocator_apple package. A workaround would be to pin your app to version 2.1.0 of the geolocator_apple package using a dependency override like this:
> 
> ```yaml
> dependency_overrides:
>   geolocator_apple: 2.1.0
> 
> dependencies:
>   ...
> ```

Seems like I get a different C compilation error when trying to use the version override
```
.pub-cache/hosted/pub.dartlang.org/geolocator_apple-2.1.0/ios/Classes/Handlers/PositionStreamHandler.h:14:9: fatal error: 'Flutter/Flutter.h' file not found
```

**Comment by mvanbeusekom** [comment]
@FarhanSajid1, try cleaning your Flutter cache using the `flutter clean` command and try again.

**Comment by FarhanSajid1** [comment]
@mvanbeusekom I've tried the following, but still see the same error

```
$ flutter clean
Cleaning Xcode workspace...                                      1,359ms
Cleaning Xcode workspace...                                      1,973ms
Deleting build...                                                    3ms
Deleting .dart_tool...                                               0ms
Deleting .packages...                                                0ms
Deleting Generated.xcconfig...                                       0ms
Deleting flutter_export_environment.sh...                            0ms
Deleting Flutter.podspec...                                          0ms
Deleting ephemeral...                                                0ms
Deleting .flutter-plugins-dependencies...                            0ms
Deleting .flutter-plugins...                                         0ms

$ flutter pub get
Warning: You are using these overridden dependencies:
! geolocator_apple 2.1.0 (2.1.1 available)
Running "flutter pub get" in mapbox_mapping...                     769ms
 
$ flutter run
Launching lib/main.dart on iPhone 13 in debug mode...
Running pod install...                                           1,482ms
Running Xcode build...                                                  
Xcode build done.                                            1.6s
Failed to build iOS app
Error output from Xcode build:
↳
    objc[15969]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x204302b90) and
    /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1041382c8). One of the two will be used.
    Which one is undefined.
    objc[15969]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x204302be0) and
    /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x104138318). One of the two will be used.
    Which one is undefined.
    ** BUILD FAILED **


Xcode's output:
↳
    Writing result bundle at path:
        /var/folders/9j/696hv2v54s15kjrj1qn1yjx40000gn/T/flutter_tools.L76EQ7/flutter_ios_build_temp_dirUeQiOA/temporary_xcresult_bundle

    In file included from
   ~/.pub-cache/hosted/pub.dartlang.org/geolocator_apple-2.1.0/ios/Classes/Handlers/PositionStreamHandler.m:9:
    ~/.pub-cache/hosted/pub.dartlang.org/geolocator_apple-2.1.0/ios/Classes/Handlers/PositionStreamHandler.h:14:9: fatal
    error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve
    this, select a development team in the Runner editor. (in target 'Runner' from project 'Runner')

    Result bundle written to path:
        /var/folders/9j/696hv2v54s15kjrj1qn1yjx40000gn/T/flutter_tools.L76EQ7/flutter_ios_build_temp_dirUeQiOA/temporary_xcresult_bundle


Lexical or Preprocessor Issue (Xcode): 'Flutter/Flutter.h' file not found
~/.pub-cache/hosted/pub.dartlang.org/geolocator_apple-2.1.0/ios/Classes/Handlers/PositionStreamHandler.h:13:8


Could not build the application for the simulator.
Error launching application on iPhone 13.
```

**Comment by mvanbeusekom** [comment]
@FarhanSajid1, I think something is wrong with the cached Pods, could you try the following:

1. Delete the `ios/Pods` folder (using the following command in the root of your project): `rm -rf ios/Pods`;
2. Delete the `ios/Podfile.lock` file: `rm ios/Podfile.lock`; 
3. Delete the `ios/Flutter/Flutter.podspec` file: `rm ios/Flutter/Flutter.podspec`;
4. Run `flutter clean`
5. Try to build again.

**Comment by timbrueckner** [comment]
Same issue here. Downgrading helped. Cleaning caches did not.

**Comment by Wian-TMC** [comment]
> @FarhanSajid1, I think something is wrong with the cached Pods, could you try the following:
> 
> 1. Delete the `ios/Pods` folder (using the following command in the root of your project): `rm -rf ios/Pods`;
> 2. Delete the `ios/Podfile.lock` file: `rm ios/Podfile.lock`;
> 3. Delete the `ios/Flutter/Flutter.podspec` file: `rm ios/Flutter/Flutter.podspec`;
> 4. Run `flutter clean`
> 5. Try to build again.


Can confirm that 

```
dependency_overrides:
  geolocator_apple: 2.1.0

dependencies:
  ...
```
works like a charm.


Remember to:
1. run `flutter clean`
2. run `flutter pub get`
3. Delete the ios/Podfile.lock file: rm ios/Podfile.lock;
4. run `pod install --repo-update` inside the iOS directory

**Comment by mvanbeusekom** [comment]
Update, version 2.1.1 of the geolocator_apple plugin was accidentally published from a Windows machine which removed all symbolic links from the project resulting in the above behaviour.

I will release a hotfix (version 2.1.1+1) within the next 10 minutes which should resolve the issue. Apologies for all inconvenience.

**Comment by mvanbeusekom** [comment]
Version 2.1.1+1 of the geolocator_apple package has just been released and I can confirm this resolves the issue. Please make sure to remove the `dependency_overrides` if you added it. 

Also ensure you do a `flutter pub upgrade` (or manually update the `geolocator_apple` version in your `pubspec.lock` file if you don't want to update other packages).

If you run into issues please follow the instructions provided by @Wian-TMC above:

1. run `flutter clean`
2. run `flutter pub get`
3. Delete the `ios/Podfile.lock` file: `rm ios/Podfile.lock`
4. run `pod install --repo-update` inside the `ios` directory
