### ISSUE TITLE
[Android] Altitude strange behavior

### ISSUE THREAD

**Issue by CMiguelRB** [Baseflow/flutter-geolocator#987]
## 💬 Questions and Help

Hi all. I don't want to fill a bug issue, as I'm not entirely sure if I'm doing something wrong. I'm developing a GPS tracking app with an altitude chart. I've been testing both, location and geolocator (both really good!) for listening to the location updates as an on screen 
 app/foreground service. While using flutter location library, the altitude readings seem to be more natural, but when I switch to geolocator the altitude values have quite a big jumps. I'm not sure which could be the problem. 

### Expected behavior

Stable and accurate altitude readings.

### Reproduction steps

Those are chart examples from both libraries. It's not the same path, but I've tested both in several occasions and the outcome is similar. Also, the track on the map is precise and it follows the path correctly, there are no jumps in lat and lon coordinates.

location library:
![Screenshot_20220221-233851](https://user-images.githubusercontent.com/17690736/155044791-cac1ab9f-2e4f-4911-b89f-e4d5c3e2e523.png)

geolocator library:
![Screenshot_20220221-212617](https://user-images.githubusercontent.com/17690736/155044842-6b24c677-fe44-447f-a684-4f28e0c56c31.png)

### Configuration
The configuration regarding `distanceFilter` and `intervalDuration` is the same for both libraries.
```
final LocationSettings _locationSettings = AndroidSettings(
      accuracy: LocationAccuracy.best,
      distanceFilter: 10,
      intervalDuration: const Duration(seconds: 5),
      foregroundNotificationConfig: ForegroundNotificationConfig(
        notificationText: I18n.translate('map_notification_desc'),
        notificationTitle: I18n.translate('map_notification_title'),
        enableWakeLock: true,
      ));
```

**Version:** 8.2.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

Pixel 6. Android 12.

**Comment by florissmit1** [comment]
Hey @CMiguelRB, thanks for reporting your issue. I've looked into it and it's expected behaviour. Since the `Location` package is making use of NMEA data to get the altitude, the readings are often more accurate. The `geolocator` plugin is using the GPS data to fetch the altitude, which is less accurate most of the time.

We're planning to implement NMEA soon in the future. We'll keep you up to date!

**Comment by CMiguelRB** [comment]
Hi @florissmit1,

Thanks for the information! I'll keep track, you are doing a great work!

**Comment by Wackymax** [comment]
https://github.com/Baseflow/flutter-geolocator/pull/1057 has been created to allow Geolocator to have the same behaviour as the location package by requesting that altitude be reported as MSL.

**Comment by Wackymax** [comment]
@mvanbeusekom this can probably be closed?
