### ISSUE TITLE
Unable to fetch location when app is in background

### ISSUE THREAD

**Issue by Harjinderbains01** [Baseflow/flutter-geolocator#988]
Unable to fetch location when app is in background

**Comment by mvanbeusekom** [comment]
You don't give us a lot to work with, please provide more details:

1. On which platform do you experience the problem?
2. Which version of the geolocator do you use (background support is only available from version 8.2.0)?
2. Include the output of `flutter doctor -v`

**Comment by somitBond** [comment]
> You don't give us a lot to work with, please provide more details:
> 
> 1. What is the problem you are trying to solve? The geolocator plugin (when configured correctly) will keep the location service alive in the background but won't call any Dart code). Locations are sent to Dart when the App moves back into the foreground.
> 2. On which platform do you experience the problem?
> 3. Which version of the geolocator do you use (background support is only available from version 8.2.0)?
> 4. Include the output of `flutter doctor -v`
---------------------

I am looking for continues user location position update while app is in background; but It is not working like so. 
When app is in foreground and switch into background for first time it does return location.
I have update package to 8.2.0 but not working for continues background update.
