### ISSUE TITLE
IOS Geolocator.getPositionStream called only once 

### ISSUE THREAD

**Issue by heshesh2010** [Baseflow/flutter-geolocator#989]
geolocator: ^8.2.0
 tested on iphone 13 emulator and real device  iphone 15

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.2.1 21D62 darwin-x64, locale en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)

my code :

```dart
    _determinePosition();
    LocationSettings locationSettings;

    if (defaultTargetPlatform == TargetPlatform.android) {
      locationSettings = AndroidSettings(
          accuracy: LocationAccuracy.medium,
          distanceFilter: 100,
          forceLocationManager: true,
          intervalDuration: const Duration(seconds: 10),
          //(Optional) Set foreground notification config to keep the app alive
          //when going to the background
          foregroundNotificationConfig: const ForegroundNotificationConfig(
            notificationText:
            "Example app will continue to receive your location even when you aren't using it",
            notificationTitle: "Running in Background",
            enableWifiLock: true,
            enableWakeLock: true,
          )
      );
    } else if (defaultTargetPlatform == TargetPlatform.iOS || defaultTargetPlatform == TargetPlatform.macOS) {
      locationSettings = AppleSettings(
        accuracy: LocationAccuracy.medium,
        activityType: ActivityType.automotiveNavigation,
        distanceFilter: 100,
        pauseLocationUpdatesAutomatically: true,
        // Only set to true if our app will be started up in the background.
        showBackgroundLocationIndicator: true,
      );
    } else {
      locationSettings = LocationSettings(
        accuracy: LocationAccuracy.high,
        distanceFilter: 100,
      );
    }

      // this method not called even i turn on freeway drive via emulator 
     Geolocator.getPositionStream(locationSettings: locationSettings).listen(
            (Position position) {
          print(position == null ? 'Unknown' : '${position.latitude.toString()}, ${position.longitude.toString()}');
          Helper().showSuccessToast(position.latitude.toString());
        });
```

**Comment by mvanbeusekom** [comment]
@heshesh2010 unfortunately I cannot reproduce your example. I have created a simple test application incorporating your code (see full code below) and ran it on the simulator (iPhone 11 - iOS 15.2) and received multiple position updates:

```
flutter: Received position: Latitude: 37.62706302, Longitude: -122.43053069
flutter: Received position: Latitude: 37.62773583, Longitude: -122.43132588
flutter: Received position: Latitude: 37.62836385, Longitude: -122.4321489
flutter: Received position: Latitude: 37.62919127, Longitude: -122.43325339
flutter: Received position: Latitude: 37.62981274, Longitude: -122.43408294
flutter: Received position: Latitude: 37.63064217, Longitude: -122.43516698
flutter: Received position: Latitude: 37.63128427, Longitude: -122.43601061
flutter: Received position: Latitude: 37.63195905, Longitude: -122.43678066
flutter: Received position: Latitude: 37.63269591, Longitude: -122.43746404
```

**Important:** since you set the `distanceFilter` to `100`  position updates are only send every 100 meters. So I configured the simulator to simulate a Freeway drive. To do so make sure the simulator has the focus and select `Features -> Location -> Freeway Drive`.

Here is the code I used (based on the default Flutter template):

<details>
<summary>pubspec.yaml</summary>

```yaml
name: geo_issue_989
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  geolocator: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
```

</details>

<details>
<summary>ios/Runner/Info.plist</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>Geo Issue 989</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>geo_issue_989</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>The example App requires access to the device&apos;s location.</string>
</dict>
</plist>
```

</details>

<details>
<summary>main.dart</summary>

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  LocationSettings _createLocationSettings() {
    LocationSettings locationSettings;

    if (defaultTargetPlatform == TargetPlatform.android) {
      locationSettings = AndroidSettings(
          accuracy: LocationAccuracy.medium,
          distanceFilter: 100,
          forceLocationManager: true,
          intervalDuration: const Duration(seconds: 10),
          //(Optional) Set foreground notification config to keep the app alive
          //when going to the background
          foregroundNotificationConfig: const ForegroundNotificationConfig(
            notificationText:
                "Example app will continue to receive your location even when you aren't using it",
            notificationTitle: "Running in Background",
            enableWifiLock: true,
            enableWakeLock: true,
          ));
    } else if (defaultTargetPlatform == TargetPlatform.iOS ||
        defaultTargetPlatform == TargetPlatform.macOS) {
      locationSettings = AppleSettings(
        accuracy: LocationAccuracy.medium,
        activityType: ActivityType.automotiveNavigation,
        distanceFilter: 100,
        pauseLocationUpdatesAutomatically: true,
        // Only set to true if our app will be started up in the background.
        showBackgroundLocationIndicator: true,
      );
    } else {
      locationSettings = const LocationSettings(
        accuracy: LocationAccuracy.high,
        distanceFilter: 100,
      );
    }

    return locationSettings;
  }

  Future<void> _printPositionUpdates() async {
    await Geolocator.requestPermission();

    final LocationSettings settings = _createLocationSettings();
    Geolocator.getPositionStream(locationSettings: settings)
        .listen((Position position) {
      print('Received position: $position');
    });

    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _printPositionUpdates,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```
</details>

**Comment by salahkamal** [comment]
I have same issue after 8.2.0 upgrade

**Comment by mvanbeusekom** [comment]
@salahkamal Have you tried the example code I provided?

Can you give more information?

**Comment by salahkamal** [comment]
Yes, I tried your example and it doesn’t work

**Comment by salahkamal** [comment]
[✓] Flutter (Channel stable, 2.10.1, on macOS 11.6 20G165 darwin-x64, locale en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.64.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by mvanbeusekom** [comment]
@salahkamal, I am sorry but the provided information is not really helpful. 

For us to be able to help please provide exact steps you do when the problem occurs:

1. Are you testing on a real device or the simulator?
    a. When on simulator, did you change the location settings to "Freeway Drive" (to simulate a moving device)?
    b. When on a real device did you move enough to satisfy the configured distance filter?
2. Please provide the full `flutter doctor -v` output?

As mentioned we can not reproduce the problem (both on real device and simulator) and the provided demo code in previous comment works as expected (as proven by the output).

If you only test on a real device it is possible you don't have a connection to GPS satellites and you have to wait before connection is made (note this can take up to 30 seconds).

**Comment by salahkamal** [comment]
Sorry for not mention that .. I Used freeway Drive to test your code and it’s not working btw it’s working fine on Android and i tested on real device with mocked route.

**Thats a full flutter doctor  output**

[✓] Flutter (Channel stable, 2.10.1, on macOS 11.6 20G165 darwin-x64, locale en-EG)
    • Flutter version 2.10.1 at /Users/macstoreegypt/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (2 weeks ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/macstoreegypt/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/macstoreegypt/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (4 available)
    • SM G781B (mobile)          • RFCNA0NTM3P                          • android-arm64  • Android 12 (API 31)
    • Salah’s iPhone (mobile)    • 00008030-001E30DC3E2B402E            • ios            • iOS 15.2.1 19C63
    • iPhone 11 Pro Max (mobile) • 0FF91A7E-1F54-4C9C-B28B-6D608171385D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0
      (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by heshesh2010** [comment]
> @heshesh2010 unfortunately I cannot reproduce your example. I have created a simple test application incorporating your code (see full code below) and ran it on the simulator (iPhone 11 - iOS 15.2) and received multiple position updates:
> 
> ```
> flutter: Received position: Latitude: 37.62706302, Longitude: -122.43053069
> flutter: Received position: Latitude: 37.62773583, Longitude: -122.43132588
> flutter: Received position: Latitude: 37.62836385, Longitude: -122.4321489
> flutter: Received position: Latitude: 37.62919127, Longitude: -122.43325339
> flutter: Received position: Latitude: 37.62981274, Longitude: -122.43408294
> flutter: Received position: Latitude: 37.63064217, Longitude: -122.43516698
> flutter: Received position: Latitude: 37.63128427, Longitude: -122.43601061
> flutter: Received position: Latitude: 37.63195905, Longitude: -122.43678066
> flutter: Received position: Latitude: 37.63269591, Longitude: -122.43746404
> ```
> 
> **Important:** since you set the `distanceFilter` to `100` position updates are only send every 100 meters. So I configured the simulator to simulate a Freeway drive. To do so make sure the simulator has the focus and select `Features -> Location -> Freeway Drive`.
> 
> Here is the code I used (based on the default Flutter template):
> 
> pubspec.yaml
> ios/Runner/Info.plist
> main.dart

Thanks for your response , 

I used your code with new project and it works , but in  my current project it called only once , I'm sure I using your code as u mentioned , but i think the geolocator plugin is conflict with one other plugins .

pubspec.yaml
`name: deliveryboy
description: deliveryboy

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"
module:
  androidX: true
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  google_maps_flutter: ^2.1.1
  mvc_pattern: ^8.7.0
  global_configuration: 2.0.0-nullsafety.1
  http: ^0.13.4
  intl: ^0.17.0
  html: ^0.15.0
  shared_preferences: ^2.0.13
  flutter_html: ^2.2.1
  url_launcher: ^6.0.20
  firebase_messaging: ^11.2.6
  cached_network_image: ^3.2.0
  rounded_loading_button: ^2.0.8
  flare_flutter: ^3.0.2
  fluttertoast: ^8.0.8
  overlay_support: ^1.2.1
  image_picker: ^0.8.4+8
  path_provider: ^2.0.9
  audioplayers: ^0.20.1
  geolocator: ^8.2.0
  flutter_local_notifications: ^9.3.2
  awesome_dialog: ^2.1.2
  flare_splash_screen: ^4.0.0
  permission_handler: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/cfg/
    - assets/img/brazil.png
    - assets/img/canada.png
    - assets/img/china.png
    - assets/img/france.png
    - assets/img/germany.png
    - assets/img/italy.png
    - assets/img/netherlands.png
    - assets/img/spain.png
    - assets/img/splash.jpg
    - assets/img/united-arab-emirates.png
    - assets/img/united-states-of-america.png
    - assets/img/marker.png
    - assets/img/my_marker.png
    - assets/img/logo.png
    - assets/img/loading.gif
    - assets/flare/
    - assets/sound.mp3
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 600
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: assets/fonts/TrajanPro.ttf
  #       - asset: assets/fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-assets/fonts/#from-packages
`

**Comment by mvanbeusekom** [comment]
@heshesh2010 the problem here is that you don't keep a hold of the `StreamSubscription` returned be listening to the `Geolocator.getPositionUpdates()` stream. 

As soon as you navigate away the `_MyAppState` object is disposed and therefore also the handle to the stream which means your stream is cancelled and the position updates stop coming in. In the movie you supplied, you can see that the position updates are coming in while the splash screen is show and stop as soon as the page containing the `ListView` is loaded.

One solution would be to make a singleton service that wraps the Geolocator plugin and keeps the stream alive while your App is running. 

Another solution would be (not as nice though) to keep the `StreamSubscription` instance in a global field. Something like:

```dart
StreamSubscription? positionSubscription = null;

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends StateMVC<MyApp> {
  final RouteObserver<PageRoute> routeObserver = RouteObserver<PageRoute>();
  UserController con;

  _MyAppState() : super(UserController()) {
    con = controller;
  }

  @override
  void initState() {
    settingRepo.initSettings();
    userRepo.getCurrentUser();

    if (positionSubscription == null) {
        final LocationSettings settings = _createLocationSettings();
        positionSubscription = Geolocator.getPositionStream(locationSettings: settings).listen(
                (Position position) {
              print(position == null ? 'Unknown' : '${position.latitude
                  .toString()}, ${position.longitude.toString()}');
              Helper().showSuccessToast(position.latitude.toString());
        });
    }
    super.initState();
  }
  
  // The rest of your code goes here...
}
```

Hopefully you get the idea that you will have to keep the `StreamSubscription`.

**Comment by mvanbeusekom** [comment]
@heshesh2010 the supplied code isn't a singleton, it is just a class that gets constructed and destroyed when it leaves the `init` method.

Maybe convert it to something like this:

```dart
import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:geolocator/geolocator.dart';

import 'helper.dart';

class GeolocationService {
  static GeolocationService? _geolocationService;

  static GeolocationService get instance {
    return _geolocationService ??= GeolocationService._();
  }

  /// Private constructor which hides the public constructor
  GeolocationService._() {}

  void getLocationUpdates() {
    final LocationSettings settings = _createLocationSettings();
    Geolocator.getPositionStream(locationSettings: settings)
        .listen((Position position) {
      print(position == null
          ? 'Unknown'
          : '${position.latitude.toString()}, ${position.longitude.toString()}');
      Helper().showSuccessToast(position.latitude.toString());
    });
  }

  Future<LocationPermission> requestPermission() {
    return Geolocator.requestPermission();
  }

  LocationSettings _createLocationSettings() {
    LocationSettings locationSettings;

    if (defaultTargetPlatform == TargetPlatform.android) {
      locationSettings = AndroidSettings(
          accuracy: LocationAccuracy.medium,
          distanceFilter: 100,
          forceLocationManager: true,
          intervalDuration: const Duration(seconds: 10),
          //(Optional) Set foreground notification config to keep the app alive
          //when going to the background
          foregroundNotificationConfig: const ForegroundNotificationConfig(
            notificationText:
                "Example app will continue to receive your location even when you aren't using it",
            notificationTitle: "Running in Background",
            enableWifiLock: true,
            enableWakeLock: true,
          ));
    } else if (defaultTargetPlatform == TargetPlatform.iOS ||
        defaultTargetPlatform == TargetPlatform.macOS) {
      locationSettings = AppleSettings(
        accuracy: LocationAccuracy.best,
        //activityType: ActivityType.automotiveNavigation,]
        distanceFilter: 1,
        pauseLocationUpdatesAutomatically: true,
        // Only set to true if our app will be started up in the background.
        showBackgroundLocationIndicator: true,
      );
    } else {
      locationSettings = const LocationSettings(
        accuracy: LocationAccuracy.high,
        distanceFilter: 1,
      );
    }

    return locationSettings;
  }
}

```

The usage would then be something like this:
```dart
final LocationPermission permission =
    await GeolocationService.instance.requestPermission();

if (permission == LocationPermission.always ||
  permission == LocationPermission.whileInUse) {
  GeolocationService.instance.getLocationUpdates();
}
```

**Comment by heshesh2010** [comment]
``> ```dart
> final LocationPermission permission =
>     await GeolocationService.instance.requestPermission();
> 
> if (permission == LocationPermission.always ||
>   permission == LocationPermission.whileInUse) {
>   GeolocationService.instance.getLocationUpdates();
> }
> ```

Still didn't work , I called this code in main fun 


```
final LocationPermission permission =
  await GeolocationService.instance.requestPermission();

  if (permission == LocationPermission.always ||
      permission == LocationPermission.whileInUse) {
    GeolocationService.instance.getLocationUpdates();
  }
```

**Comment by mvanbeusekom** [comment]
This is hard for me to reproduce as in my examples it is all working. Can you make an example that reproduces the problem and you can share with me? 

Because of the fact that I cannot reproduce it and you mentioning the example I posted worked fine, I'm not convinced this is a problem within the geolocator (that would also mean a lot more people would have been reporting problems). Therefore I'm inclined to say that there is either a small bug in your code or as you mentioned before there is another plugin interfering. 

Something you could try is to try disabling plugins one by one and see if everything starts working out of the sudden. If in the end you excluded all plugins and it still doesn't work, please try to make a working sample reproducing the error which you feel comfortable sharing with us, hopefully we can then help you locate the issue.
