### ISSUE TITLE
Include a mock in the library

### ISSUE THREAD

**Issue by GabrielBB** [Baseflow/flutter-geolocator#990]
## 🚀 Feature Requests

Include a mock in the library just like the `http` package does.

### Contextualize the feature
I want to easily unit test the following function:

```dart
import 'package:geolocator/geolocator.dart';

const _settings = LocationSettings(accuracy: LocationAccuracy.low);

Future<Position> getPosition(GeolocatorPlatform geolocator) async {
  if (!await geolocator.isLocationServiceEnabled()) {
    throw 'Location services are disabled.';
  }

  if (await geolocator.checkPermission() == LocationPermission.denied) {
    if (await geolocator.requestPermission() == LocationPermission.denied) {
      // According to guidelines our App should show an explanatory UI now.
      throw 'Location permissions are denied';
    }
  }

  return await geolocator.getCurrentPosition(locationSettings: _settings);
}
```

### Describe the feature
Would be nice if the library included a mock for `GeolocatorPlatform.instance` similar to  https://pub.dev/documentation/http/latest/http.testing/MockClient-class.html . The problem about using [Mockito](https://pub.dev/packages/mockito) is that we have to introduce code generation to our project, which just... sucks. (until [this](https://github.com/dart-lang/language/issues/1482))

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by cedvdb** [comment]
In my opinion every library that access the device should have an helper method to override the method channel results. Or better a `FakeX` (here `FakeGeolocator`) that does just that (mock method channels and use the real Geolocator under the hood).
