### ISSUE TITLE
 Unhandled Exception: NoSuchMethodError: Class '_InternalLinkedHashMap<String, dynamic>' has no instance method 'castMap'

### ISSUE THREAD

**Issue by hodakl099** [Baseflow/flutter-geolocator#991]
tried to cast it but it didn't work for me. 
```dart
  Future getData() async {
    http.Response response = await http.get(Uri.parse(url));

    if (response.statusCode == 200) {
      String data = json.decode(response.body).castMap<String, dynamic>();

      Map decodedData = jsonDecode(data);
      return decodedData;
    } else {
      print(response.statusCode);
    }
  }
}
```

- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
Hello @hodakl099,

How does this relate to the geolocator plugin? Seems like you are doing a HTTP request and try to convert the resulting body into instance  of a `Map<String, dynamic>` class. I don't see how this is related to the geolocator plugin.

From my point of view you are using an invalid method `castMap` which doesn't exists. Maybe try to handle it like this:

```dart
  Future<Map<String, dynamic>> getData() async {
    http.Response response = await http.get(Uri.parse(url));

    if (response.statusCode == 200) {
      final Map<String, dynamic> decodedData = jsonDecode(response.body).cast<Map<String, dynamic>>();
      return decodedData;
    } else {
      print(response.statusCode);
    }
  }
}
```

I am closing this issue now as I don't see the relevance to the geolocator plugin. There are several really good articles that explain parsing HTTP response data into Dart objects. One of the better ones would be: https://docs.flutter.dev/cookbook/networking/fetch-data

**Comment by hodakl099** [comment]
@mvanbeusekom  
**after reading the docs https://docs.flutter.dev/cookbook/networking/fetch-data I've found that I have to  JsonDecoder objecr, I've handled it this way: 
 `final JsonDecoder _decoder = new JsonDecoder();
 
Future getData() async {
http.Response response = await http.get(Uri.parse(url));

if (response.statusCode == 200) {
  String data = response.body;
  Map<String, dynamic> decodedData  = _decoder.convert(data);
 
  return decodedData;
} else {
  print(response.statusCode);
}
}`

**Comment by hodakl099** [comment]
@mvanbeusekom  
**after reading the docs https://docs.flutter.dev/cookbook/networking/fetch-data I've found that I have to JsonDecoder objecr, I've handled it this way:
```
final JsonDecoder _decoder = new JsonDecoder();

Future getData() async {
http.Response response = await http.get(Uri.parse(url));

if (response.statusCode == 200) {
String data = response.body;
Map<String, dynamic> decodedData = _decoder.convert(data);

return decodedData;
} else {
print(response.statusCode);
}
}
```
