### ISSUE TITLE
Unable to use geolocator in with mock location apps 'error location service on this device is disabled'

### ISSUE THREAD

**Issue by jesussmile** [Baseflow/flutter-geolocator#992]
## 🐛 Bug Report

The background location service stops working when a mock location app is in use. I get the error `Unhandled Exception: The location service on the device is disabled.`

### Expected behavior
Like all other location plugin I expect it to work using mock location apps on emulator for testing.

## Reproduction steps
create a project with this lines of codes
```
void getLocationLiveUpdates() async {

    await Geolocator.isLocationServiceEnabled();
    locationSettings = AndroidSettings(
        accuracy: LocationAccuracy.best,
        distanceFilter: 100,
        forceLocationManager: true,
        intervalDuration: const Duration(seconds: 1),

        //(Optional) Set foreground notification config to keep the app alive
        //when going to the background
        foregroundNotificationConfig: const ForegroundNotificationConfig(
          notificationText:
              "Example app will continue to receive your location even when you aren't using it",
          notificationTitle: "Running in Background",
          enableWakeLock: true,
        ));

    StreamSubscription<Position> positionStream =
        Geolocator.getPositionStream(locationSettings: locationSettings)
            .listen((Position? position) {
      print(position == null
          ? 'Unknown'
          : '${position.latitude.toString()}, ${position.longitude.toString()}');
    });
    
```

I am using an app called `mock location` 
[https://play.google.com/store/apps/details?id=ru.gavrikov.mocklocations&hl=en&gl=US#:~:text=Mock%20Locations%20allows%20you%20to,fake%20information%20about%20the%20location.](URL)
when I create a path on the app and run I get the following error as mentioned above . without mock location I am unable to work on my  project. My main objective for now with `geolocation` is to have it run on the background.

### Configuration
As per the documentation

**Version:** 1.x
geolocator: ^8.1.1
**Platform:** 
- [ ]no :iphone: iOS
- [yes ] :robot: Android

**Comment by florissmit1** [comment]
Hey @jesussmile, does your issue still exist? If so, I would recommend using the Extended Controls of the Android Emulator itself to mock a Location. Thus the use of a third-party mock application is not needed. 

When using the Extended Controls of the Android Emulator, the `geolocator` plugin will work as expected. I will close this issue for now, if your issue also exists when using the official Extended Controls, feel free to re-open this issue.

**Comment by RahamanZirak** [comment]
hello ,
I have this issue too . but in real devices .
I set the permissions and even turn on the gps but it still show this error
