### ISSUE TITLE
Problem getting user speed

### ISSUE THREAD

**Issue by SwiftyFlow** [Baseflow/flutter-geolocator#993]
## 💬 Questions and Help

I'm struggling to get the user speed.

```dart
double velocity = 0;

  @override
  void initState() {

    _determinePosition(); //just for authorisations

    Geolocator.getPositionStream(
        locationSettings: const LocationSettings(
      accuracy: LocationAccuracy.bestForNavigation,
      //distanceFilter: 0,
    )).listen((Position position) {
      _onAccelerate(position);
    });

    super.initState();
  }

void _onAccelerate(Position position) {
    setState(() {
      velocity = position.speed;
    });
  }

Future<Position> _determinePosition() async {
    bool serviceEnabled;
    LocationPermission permission;

    serviceEnabled = await Geolocator.isLocationServiceEnabled();
    if (!serviceEnabled) {
      // not enabled
      return Future.error('Location services are disabled.');
    }

    permission = await Geolocator.checkPermission();
    if (permission == LocationPermission.denied) {
      permission = await Geolocator.requestPermission();
      if (permission == LocationPermission.denied) {
        // denied
        return Future.error('Location permissions are denied');
      }
    }

    if (permission == LocationPermission.deniedForever) {
      // Permissions are denied forever, handle appropriately.
      return Future.error(
          'Location permissions are permanently denied, we cannot request permissions.');
    }

    return await Geolocator.getCurrentPosition(
        desiredAccuracy: LocationAccuracy.bestForNavigation);
  }
```

-1 km/h is not fast...

**Comment by mvanbeusekom** [comment]
Hi @SwiftyFlow,

On which platform (Android, iOS, macOS, web or Windows) are you experiencing this problem?

**Comment by SwiftyFlow** [comment]
I managed to go at 4.50km/h!

Future<void> _getSpeed() async {
    await Geolocator.requestPermission();

    final LocationSettings settings = _createLocationSettings();

    while (_running) {
      await Future<void>.delayed(const Duration(milliseconds: 1000));
      Geolocator.getPositionStream(locationSettings: settings).listen(
        (Position position) {
          print('Received position: $position');

          if (position.speed.isNegative) return;

          setState(() {
            velocity = position.speed;

            context.read<MaxSpeedProvider>().setCurrentSpeedTo(position.speed);

            if (velocity > context.read<MaxSpeedProvider>().maxSpeed) {
              context.read<MaxSpeedProvider>().setMaxSpeedTo(velocity);
            }
          });
        },
      );
    }
  }

Still not happy with the result... I have tried a stream builder but I cannot yield the result because of async issues. I'm stuck...

**Comment by JeroenWeener** [comment]
Hi @SwiftyFlow, the geolocator plugin calls the native APIs to get position information. We do not have control over the accuracy of the readings.

We do expose the accuracy values, however. You can get them from a `Position` by calling `position.speedAccuracy`. Documentation about what this accuracy means can be found [here for Android](https://developer.android.com/reference/android/location/Location#getSpeedAccuracyMetersPerSecond()) and [here for iOS](https://developer.apple.com/documentation/corelocation/cllocation/3524340-speedaccuracy?language=objc). These values can tell you how accurate the speed readings are.
