### ISSUE TITLE
`checkPermission()` & `requestPermission()` will return different method while they shouldn't

### ISSUE THREAD

**Issue by easazade** [Baseflow/flutter-geolocator#995]
## 🐛 Bug Report

the problems is when we ask for permission using `requestPermission()` method and result is `LocationPermission.deniedForever`  and then we call `checkPermission` method we will get a different result which is `LocationPermission.denied`. 

### Expected behavior
`checkPermission()` & `requestPermission()` methods should return the same result in above scenario
### Configuration

**Version:** ^2.8.0

**Platform:** 
- [ ] :iphone: iOS (did not test it on iOS)
- [ x] :robot: Android

**Comment by mvanbeusekom** [comment]
This is expected behaviour, more details in my earlier comment: https://github.com/Baseflow/flutter-geolocator/issues/994#issuecomment-1055430478
